// GENERATED by scripts/atlas/generate.mjs - do not edit by hand.
export interface AtlasPlateLabel { structureId: string; x: number; y: number; radius: number; en: string; es: string }
export interface AtlasPlate { id: string; key: string; svgPath: string; pngPath: string; title: [string, string]; description: [string, string]; orientation: string; labels: AtlasPlateLabel[] }
export const atlasPlates: AtlasPlate[] = [
  {
    "id": "asset-atlas-anterior-position",
    "key": "anterior-position",
    "svgPath": "assets/images/anatomy/atlas/atlas-01-anterior-position.svg",
    "pngPath": "assets/images/anatomy/atlas/atlas-01-anterior-position.png",
    "title": [
      "Anterior anatomical position",
      "Posición anatómica anterior"
    ],
    "description": [
      "Standing figure seen from the front, palms forward and thumbs lateral. Patient right is on the viewer's left.",
      "Figura de pie vista de frente, con las palmas hacia delante y los pulgares laterales. La derecha del paciente queda a la izquierda del observador."
    ],
    "orientation": "anterior view; patient right = viewer left; palms forward; thumbs lateral",
    "labels": [
      {
        "structureId": "cephalic-region",
        "x": 0.5,
        "y": 0.1,
        "radius": 0.022,
        "en": "Head (cephalic) region",
        "es": "Región cefálica (cabeza)"
      },
      {
        "structureId": "cervical-region",
        "x": 0.5,
        "y": 0.186,
        "radius": 0.022,
        "en": "Neck (cervical) region",
        "es": "Región cervical (cuello)"
      },
      {
        "structureId": "thoracic-region",
        "x": 0.4793,
        "y": 0.265,
        "radius": 0.022,
        "en": "Chest (thoracic) region",
        "es": "Región torácica (tórax)"
      },
      {
        "structureId": "axillary-region",
        "x": 0.4338,
        "y": 0.226,
        "radius": 0.022,
        "en": "Armpit (axillary) region",
        "es": "Región axilar"
      },
      {
        "structureId": "brachial-region",
        "x": 0.4159,
        "y": 0.31,
        "radius": 0.022,
        "en": "Upper arm (brachial) region",
        "es": "Región braquial (brazo)"
      },
      {
        "structureId": "antebrachial-region",
        "x": 0.391,
        "y": 0.448,
        "radius": 0.022,
        "en": "Forearm (antebrachial) region",
        "es": "Región antebraquial (antebrazo)"
      },
      {
        "structureId": "abdominal-region",
        "x": 0.5193,
        "y": 0.39,
        "radius": 0.022,
        "en": "Abdominal region",
        "es": "Región abdominal"
      },
      {
        "structureId": "femoral-region",
        "x": 0.4641,
        "y": 0.58,
        "radius": 0.022,
        "en": "Thigh (femoral) region",
        "es": "Región femoral (muslo)"
      },
      {
        "structureId": "patellar-region",
        "x": 0.4697,
        "y": 0.678,
        "radius": 0.022,
        "en": "Front of knee (patellar) region",
        "es": "Región patelar (rodilla anterior)"
      },
      {
        "structureId": "crural-region",
        "x": 0.4683,
        "y": 0.78,
        "radius": 0.022,
        "en": "Leg (crural) region",
        "es": "Región crural (pierna)"
      }
    ]
  },
  {
    "id": "asset-atlas-posterior-position",
    "key": "posterior-position",
    "svgPath": "assets/images/anatomy/atlas/atlas-02-posterior-position.svg",
    "pngPath": "assets/images/anatomy/atlas/atlas-02-posterior-position.png",
    "title": [
      "Posterior anatomical position",
      "Posición anatómica posterior"
    ],
    "description": [
      "Standing figure seen from behind with the same limb position. Patient right is on the viewer's right.",
      "Figura vista desde atrás con la misma posición de las extremidades. La derecha del paciente queda a la derecha del observador."
    ],
    "orientation": "posterior view; patient right = viewer right; palms forward; thumbs lateral",
    "labels": [
      {
        "structureId": "cephalic-region",
        "x": 0.5,
        "y": 0.09,
        "radius": 0.022,
        "en": "Head (cephalic) region",
        "es": "Región cefálica (cabeza)"
      },
      {
        "structureId": "cervical-region",
        "x": 0.5,
        "y": 0.186,
        "radius": 0.022,
        "en": "Neck (cervical) region",
        "es": "Región cervical (cuello)"
      },
      {
        "structureId": "posterior",
        "x": 0.5,
        "y": 0.295,
        "radius": 0.022,
        "en": "Posterior (back)",
        "es": "Posterior (dorso)"
      },
      {
        "structureId": "brachial-region",
        "x": 0.5841,
        "y": 0.31,
        "radius": 0.022,
        "en": "Upper arm (brachial) region",
        "es": "Región braquial (brazo)"
      },
      {
        "structureId": "antebrachial-region",
        "x": 0.609,
        "y": 0.448,
        "radius": 0.022,
        "en": "Forearm (antebrachial) region",
        "es": "Región antebraquial (antebrazo)"
      },
      {
        "structureId": "femoral-region",
        "x": 0.5359,
        "y": 0.58,
        "radius": 0.022,
        "en": "Thigh (femoral) region",
        "es": "Región femoral (muslo)"
      },
      {
        "structureId": "popliteal-region",
        "x": 0.529,
        "y": 0.658,
        "radius": 0.022,
        "en": "Back of knee (popliteal) region",
        "es": "Región poplítea (hueco de la rodilla)"
      },
      {
        "structureId": "crural-region",
        "x": 0.5317,
        "y": 0.78,
        "radius": 0.022,
        "en": "Leg (crural) region",
        "es": "Región crural (pierna)"
      }
    ]
  },
  {
    "id": "asset-atlas-body-planes",
    "key": "body-planes",
    "svgPath": "assets/images/anatomy/atlas/atlas-03-body-planes.svg",
    "pngPath": "assets/images/anatomy/atlas/atlas-03-body-planes.png",
    "title": [
      "Three body planes compared",
      "Comparación de los tres planos corporales"
    ],
    "description": [
      "Three panels, left to right: sagittal plane (left and right parts), coronal plane (front and back parts) and transverse plane (upper and lower parts).",
      "Tres paneles, de izquierda a derecha: plano sagital (partes izquierda y derecha), plano coronal (partes anterior y posterior) y plano transversal (partes superior e inferior)."
    ],
    "orientation": "anterior views; panels ordered sagittal, coronal, transverse",
    "labels": [
      {
        "structureId": "sagittal-plane",
        "x": 0.2138,
        "y": 0.1485,
        "radius": 0.03,
        "en": "Sagittal plane",
        "es": "Plano sagital"
      },
      {
        "structureId": "coronal-plane",
        "x": 0.6046,
        "y": 0.2388,
        "radius": 0.035,
        "en": "Coronal plane",
        "es": "Plano coronal"
      },
      {
        "structureId": "transverse-plane",
        "x": 0.9016,
        "y": 0.3912,
        "radius": 0.03,
        "en": "Transverse plane",
        "es": "Plano transversal"
      }
    ]
  },
  {
    "id": "asset-atlas-body-cavities",
    "key": "body-cavities",
    "svgPath": "assets/images/anatomy/atlas/atlas-04-body-cavities.svg",
    "pngPath": "assets/images/anatomy/atlas/atlas-04-body-cavities.png",
    "title": [
      "Major body cavities with serous-space inset",
      "Cavidades corporales principales con detalle del espacio seroso"
    ],
    "description": [
      "Lateral section facing viewer-left: cranial, vertebral, thoracic, abdominal and pelvic cavities, the diaphragm and a retroperitoneal kidney. The circular inset enlarges the pleural layers: lung, visceral pleura, thin pleural cavity, parietal pleura and chest wall. Spaces are tinted regions; organs are separate shapes.",
      "Corte lateral orientado hacia la izquierda: cavidades craneal, vertebral, torácica, abdominal y pélvica, diafragma y un riñón retroperitoneal. El recuadro circular amplía las capas pleurales: pulmón, pleura visceral, delgada cavidad pleural, pleura parietal y pared torácica. Los espacios son regiones teñidas; los órganos son formas distintas."
    ],
    "orientation": "lateral section; anterior toward viewer-left; inset shows lung at left and chest wall at right",
    "labels": [
      {
        "structureId": "cranial-cavity",
        "x": 0.3241,
        "y": 0.104,
        "radius": 0.022,
        "en": "Cranial cavity",
        "es": "Cavidad craneal"
      },
      {
        "structureId": "thoracic-cavity",
        "x": 0.2883,
        "y": 0.336,
        "radius": 0.022,
        "en": "Thoracic cavity",
        "es": "Cavidad torácica"
      },
      {
        "structureId": "diaphragm",
        "x": 0.331,
        "y": 0.47,
        "radius": 0.022,
        "en": "Diaphragm",
        "es": "Diafragma"
      },
      {
        "structureId": "abdominal-cavity",
        "x": 0.2855,
        "y": 0.59,
        "radius": 0.022,
        "en": "Abdominal cavity",
        "es": "Cavidad abdominal"
      },
      {
        "structureId": "pelvic-cavity",
        "x": 0.3407,
        "y": 0.776,
        "radius": 0.022,
        "en": "Pelvic cavity",
        "es": "Cavidad pélvica"
      },
      {
        "structureId": "kidneys",
        "x": 0.3655,
        "y": 0.566,
        "radius": 0.016,
        "en": "Kidney (retroperitoneal)",
        "es": "Riñón (retroperitoneal)"
      },
      {
        "structureId": "vertebral-cavity",
        "x": 0.3966,
        "y": 0.48,
        "radius": 0.012,
        "en": "Vertebral cavity",
        "es": "Cavidad vertebral"
      },
      {
        "structureId": "visceral-pleura",
        "x": 0.6993,
        "y": 0.41,
        "radius": 0.012,
        "en": "Visceral pleura",
        "es": "Pleura visceral"
      },
      {
        "structureId": "pleural-cavity",
        "x": 0.7117,
        "y": 0.5,
        "radius": 0.012,
        "en": "Pleural cavity (thin space)",
        "es": "Cavidad pleural (espacio delgado)"
      },
      {
        "structureId": "parietal-pleura",
        "x": 0.7241,
        "y": 0.59,
        "radius": 0.012,
        "en": "Parietal pleura",
        "es": "Pleura parietal"
      }
    ]
  },
  {
    "id": "asset-atlas-abdominal-quadrants",
    "key": "abdominal-quadrants",
    "svgPath": "assets/images/anatomy/atlas/atlas-05-abdominal-quadrants.svg",
    "pngPath": "assets/images/anatomy/atlas/atlas-05-abdominal-quadrants.png",
    "title": [
      "Four abdominal quadrants",
      "Los cuatro cuadrantes abdominales"
    ],
    "description": [
      "Anterior torso divided by a vertical midline and a horizontal line through the navel. Right and left are the patient's: patient right is on the viewer's left.",
      "Torso anterior dividido por una línea media vertical y una línea horizontal a través del ombligo. Derecha e izquierda son las del paciente: la derecha del paciente queda a la izquierda del observador."
    ],
    "orientation": "anterior torso; patient right = viewer left; split at the navel",
    "labels": [
      {
        "structureId": "right-upper-quadrant",
        "x": 0.4241,
        "y": 0.4936,
        "radius": 0.06,
        "en": "Right upper quadrant",
        "es": "Cuadrante superior derecho"
      },
      {
        "structureId": "left-upper-quadrant",
        "x": 0.5759,
        "y": 0.4936,
        "radius": 0.06,
        "en": "Left upper quadrant",
        "es": "Cuadrante superior izquierdo"
      },
      {
        "structureId": "right-lower-quadrant",
        "x": 0.4241,
        "y": 0.7312,
        "radius": 0.06,
        "en": "Right lower quadrant",
        "es": "Cuadrante inferior derecho"
      },
      {
        "structureId": "left-lower-quadrant",
        "x": 0.5759,
        "y": 0.7312,
        "radius": 0.06,
        "en": "Left lower quadrant",
        "es": "Cuadrante inferior izquierdo"
      }
    ]
  },
  {
    "id": "asset-atlas-abdominal-regions",
    "key": "abdominal-regions",
    "svgPath": "assets/images/anatomy/atlas/atlas-06-abdominal-regions.svg",
    "pngPath": "assets/images/anatomy/atlas/atlas-06-abdominal-regions.png",
    "title": [
      "Nine abdominal regions",
      "Las nueve regiones abdominales"
    ],
    "description": [
      "Anterior torso divided by two vertical and two horizontal lines into a three-by-three grid; the umbilical region is the central square. Patient right is on the viewer's left.",
      "Torso anterior dividido por dos líneas verticales y dos horizontales en una cuadrícula de tres por tres; la región umbilical es el cuadro central. La derecha del paciente queda a la izquierda del observador."
    ],
    "orientation": "anterior torso; patient right = viewer left; 3 x 3 grid",
    "labels": [
      {
        "structureId": "right-hypochondriac-region",
        "x": 0.4029,
        "y": 0.4408,
        "radius": 0.04,
        "en": "Right hypochondriac region",
        "es": "Región hipocondríaca derecha"
      },
      {
        "structureId": "epigastric-region",
        "x": 0.5,
        "y": 0.4408,
        "radius": 0.04,
        "en": "Epigastric region",
        "es": "Región epigástrica"
      },
      {
        "structureId": "left-hypochondriac-region",
        "x": 0.5971,
        "y": 0.4408,
        "radius": 0.04,
        "en": "Left hypochondriac region",
        "es": "Región hipocondríaca izquierda"
      },
      {
        "structureId": "right-lumbar-region",
        "x": 0.4029,
        "y": 0.597,
        "radius": 0.04,
        "en": "Right lumbar region",
        "es": "Región lumbar derecha"
      },
      {
        "structureId": "umbilical-region",
        "x": 0.5,
        "y": 0.6476,
        "radius": 0.04,
        "en": "Umbilical region",
        "es": "Región umbilical"
      },
      {
        "structureId": "left-lumbar-region",
        "x": 0.5971,
        "y": 0.597,
        "radius": 0.04,
        "en": "Left lumbar region",
        "es": "Región lumbar izquierda"
      },
      {
        "structureId": "right-iliac-region",
        "x": 0.4029,
        "y": 0.7928,
        "radius": 0.04,
        "en": "Right iliac region",
        "es": "Región ilíaca derecha"
      },
      {
        "structureId": "hypogastric-region",
        "x": 0.5,
        "y": 0.7928,
        "radius": 0.04,
        "en": "Hypogastric region",
        "es": "Región hipogástrica"
      },
      {
        "structureId": "left-iliac-region",
        "x": 0.5971,
        "y": 0.7928,
        "radius": 0.04,
        "en": "Left iliac region",
        "es": "Región ilíaca izquierda"
      }
    ]
  },
  {
    "id": "asset-atlas-organ-locations",
    "key": "organ-locations",
    "svgPath": "assets/images/anatomy/atlas/atlas-07-organ-locations.svg",
    "pngPath": "assets/images/anatomy/atlas/atlas-07-organ-locations.png",
    "title": [
      "Whole-body organ locations",
      "Ubicación de los órganos en todo el cuerpo"
    ],
    "description": [
      "Anterior view of the major organs in place. Liver on the patient's right (viewer left); stomach and spleen on the patient's left; heart left of midline with its apex to the viewer's right; kidneys lie behind the abdominal organs (dashed).",
      "Vista anterior de los órganos principales en su lugar. Hígado a la derecha del paciente (izquierda del observador); estómago y bazo a la izquierda del paciente; corazón a la izquierda de la línea media con el vértice hacia la derecha del observador; los riñones están detrás de los órganos abdominales (línea discontinua)."
    ],
    "orientation": "anterior view; patient right = viewer left",
    "labels": [
      {
        "structureId": "brain",
        "x": 0.5,
        "y": 0.1,
        "radius": 0.025,
        "en": "Brain",
        "es": "Encéfalo"
      },
      {
        "structureId": "lungs",
        "x": 0.4669,
        "y": 0.29,
        "radius": 0.03,
        "en": "Lungs",
        "es": "Pulmones"
      },
      {
        "structureId": "heart",
        "x": 0.5152,
        "y": 0.3,
        "radius": 0.022,
        "en": "Heart",
        "es": "Corazón"
      },
      {
        "structureId": "liver",
        "x": 0.4641,
        "y": 0.378,
        "radius": 0.026,
        "en": "Liver",
        "es": "Hígado"
      },
      {
        "structureId": "stomach",
        "x": 0.5248,
        "y": 0.4,
        "radius": 0.016,
        "en": "Stomach",
        "es": "Estómago"
      },
      {
        "structureId": "spleen",
        "x": 0.5497,
        "y": 0.378,
        "radius": 0.012,
        "en": "Spleen",
        "es": "Bazo"
      },
      {
        "structureId": "pancreas",
        "x": 0.5138,
        "y": 0.43,
        "radius": 0.012,
        "en": "Pancreas",
        "es": "Páncreas"
      },
      {
        "structureId": "kidneys",
        "x": 0.4766,
        "y": 0.42,
        "radius": 0.012,
        "en": "Kidney (retroperitoneal)",
        "es": "Riñón (retroperitoneal)"
      },
      {
        "structureId": "urinary-system-urinary-bladder",
        "x": 0.5,
        "y": 0.5,
        "radius": 0.016,
        "en": "Urinary bladder",
        "es": "Vejiga urinaria"
      }
    ]
  },
  {
    "id": "asset-atlas-skeleton-anterior",
    "key": "skeleton-anterior",
    "svgPath": "assets/images/anatomy/atlas/atlas-08-skeleton-anterior.svg",
    "pngPath": "assets/images/anatomy/atlas/atlas-08-skeleton-anterior.png",
    "title": [
      "Anterior skeleton",
      "Esqueleto anterior"
    ],
    "description": [
      "Skeleton in anatomical position seen from the front: skull, clavicles, sternum, 12 rib pairs with costal cartilage, vertebral column, pelvis, long bones, hands and feet. Patient right is on the viewer's left.",
      "Esqueleto en posición anatómica visto de frente: cráneo, clavículas, esternón, 12 pares de costillas con cartílago costal, columna vertebral, pelvis, huesos largos, manos y pies. La derecha del paciente queda a la izquierda del observador."
    ],
    "orientation": "anterior view; patient right = viewer left",
    "labels": [
      {
        "structureId": "skull",
        "x": 0.5,
        "y": 0.086,
        "radius": 0.02,
        "en": "Skull",
        "es": "Cráneo"
      },
      {
        "structureId": "mandible",
        "x": 0.5,
        "y": 0.172,
        "radius": 0.012,
        "en": "Mandible",
        "es": "Mandíbula"
      },
      {
        "structureId": "clavicle",
        "x": 0.5428,
        "y": 0.197,
        "radius": 0.014,
        "en": "Clavicle",
        "es": "Clavícula"
      },
      {
        "structureId": "sternum",
        "x": 0.5,
        "y": 0.265,
        "radius": 0.014,
        "en": "Sternum",
        "es": "Esternón"
      },
      {
        "structureId": "true-ribs",
        "x": 0.5566,
        "y": 0.256,
        "radius": 0.016,
        "en": "True ribs (1-7)",
        "es": "Costillas verdaderas (1-7)"
      },
      {
        "structureId": "false-ribs",
        "x": 0.5538,
        "y": 0.342,
        "radius": 0.014,
        "en": "False ribs (8-10)",
        "es": "Costillas falsas (8-10)"
      },
      {
        "structureId": "floating-ribs",
        "x": 0.5262,
        "y": 0.37,
        "radius": 0.012,
        "en": "Floating ribs (11-12)",
        "es": "Costillas flotantes (11-12)"
      },
      {
        "structureId": "humerus",
        "x": 0.5855,
        "y": 0.305,
        "radius": 0.014,
        "en": "Humerus",
        "es": "Húmero"
      },
      {
        "structureId": "radius",
        "x": 0.6145,
        "y": 0.444,
        "radius": 0.012,
        "en": "Radius",
        "es": "Radio"
      },
      {
        "structureId": "pelvis",
        "x": 0.54,
        "y": 0.412,
        "radius": 0.02,
        "en": "Pelvis (hip bone)",
        "es": "Pelvis (hueso coxal)"
      },
      {
        "structureId": "femur",
        "x": 0.5483,
        "y": 0.58,
        "radius": 0.014,
        "en": "Femur",
        "es": "Fémur"
      },
      {
        "structureId": "patella",
        "x": 0.5338,
        "y": 0.68,
        "radius": 0.012,
        "en": "Patella",
        "es": "Rótula"
      },
      {
        "structureId": "tibia",
        "x": 0.5297,
        "y": 0.75,
        "radius": 0.01,
        "en": "Tibia",
        "es": "Tibia"
      },
      {
        "structureId": "fibula",
        "x": 0.5414,
        "y": 0.8,
        "radius": 0.01,
        "en": "Fibula",
        "es": "Peroné"
      }
    ]
  },
  {
    "id": "asset-atlas-skeleton-posterior",
    "key": "skeleton-posterior",
    "svgPath": "assets/images/anatomy/atlas/atlas-09-skeleton-posterior.svg",
    "pngPath": "assets/images/anatomy/atlas/atlas-09-skeleton-posterior.png",
    "title": [
      "Posterior skeleton",
      "Esqueleto posterior"
    ],
    "description": [
      "Skeleton seen from behind: skull, scapulae, vertebral column with spinous processes, ribs, sacrum, coccyx, pelvis and limb bones. Patient right is on the viewer's right.",
      "Esqueleto visto desde atrás: cráneo, escápulas, columna vertebral con apófisis espinosas, costillas, sacro, cóccix, pelvis y huesos de las extremidades. La derecha del paciente queda a la derecha del observador."
    ],
    "orientation": "posterior view; patient right = viewer right",
    "labels": [
      {
        "structureId": "skull",
        "x": 0.5,
        "y": 0.1,
        "radius": 0.02,
        "en": "Skull",
        "es": "Cráneo"
      },
      {
        "structureId": "cervical-vertebrae",
        "x": 0.5,
        "y": 0.193,
        "radius": 0.01,
        "en": "Cervical vertebrae",
        "es": "Vértebras cervicales"
      },
      {
        "structureId": "clavicle",
        "x": 0.551,
        "y": 0.199,
        "radius": 0.012,
        "en": "Clavicle",
        "es": "Clavícula"
      },
      {
        "structureId": "scapula",
        "x": 0.54,
        "y": 0.278,
        "radius": 0.022,
        "en": "Scapula",
        "es": "Escápula"
      },
      {
        "structureId": "thoracic-vertebrae",
        "x": 0.5,
        "y": 0.285,
        "radius": 0.01,
        "en": "Thoracic vertebrae",
        "es": "Vértebras torácicas"
      },
      {
        "structureId": "lumbar-vertebrae",
        "x": 0.5,
        "y": 0.392,
        "radius": 0.012,
        "en": "Lumbar vertebrae",
        "es": "Vértebras lumbares"
      },
      {
        "structureId": "sacrum",
        "x": 0.5,
        "y": 0.468,
        "radius": 0.012,
        "en": "Sacrum",
        "es": "Sacro"
      },
      {
        "structureId": "coccyx",
        "x": 0.5,
        "y": 0.509,
        "radius": 0.008,
        "en": "Coccyx",
        "es": "Cóccix"
      },
      {
        "structureId": "pelvis",
        "x": 0.5428,
        "y": 0.412,
        "radius": 0.016,
        "en": "Pelvis (hip bone)",
        "es": "Pelvis (hueso coxal)"
      },
      {
        "structureId": "humerus",
        "x": 0.5855,
        "y": 0.305,
        "radius": 0.012,
        "en": "Humerus",
        "es": "Húmero"
      },
      {
        "structureId": "femur",
        "x": 0.5483,
        "y": 0.58,
        "radius": 0.012,
        "en": "Femur",
        "es": "Fémur"
      },
      {
        "structureId": "tibia",
        "x": 0.5297,
        "y": 0.76,
        "radius": 0.01,
        "en": "Tibia",
        "es": "Tibia"
      },
      {
        "structureId": "fibula",
        "x": 0.5414,
        "y": 0.805,
        "radius": 0.01,
        "en": "Fibula",
        "es": "Peroné"
      }
    ]
  },
  {
    "id": "asset-atlas-skeleton-axial-appendicular",
    "key": "skeleton-axial-appendicular",
    "svgPath": "assets/images/anatomy/atlas/atlas-10-skeleton-axial-appendicular.svg",
    "pngPath": "assets/images/anatomy/atlas/atlas-10-skeleton-axial-appendicular.png",
    "title": [
      "Axial and appendicular skeleton",
      "Esqueleto axial y apendicular"
    ],
    "description": [
      "Anterior skeleton in two tints. Blue-gray bones are axial: skull, sternum, ribs, vertebral column, sacrum and coccyx. Sand bones are appendicular: clavicles and scapulae, limb bones, hands, feet and the hip bones.",
      "Esqueleto anterior en dos tonos. Los huesos gris azulado son axiales: cráneo, esternón, costillas, columna vertebral, sacro y cóccix. Los huesos arena son apendiculares: clavículas y escápulas, huesos de las extremidades, manos, pies y huesos coxales."
    ],
    "orientation": "anterior view; patient right = viewer left; blue-gray = axial, sand = appendicular",
    "labels": [
      {
        "structureId": "skull",
        "x": 0.5,
        "y": 0.086,
        "radius": 0.02,
        "en": "Skull",
        "es": "Cráneo"
      },
      {
        "structureId": "sternum",
        "x": 0.5,
        "y": 0.265,
        "radius": 0.014,
        "en": "Sternum",
        "es": "Esternón"
      },
      {
        "structureId": "true-ribs",
        "x": 0.5566,
        "y": 0.256,
        "radius": 0.016,
        "en": "True ribs (1-7)",
        "es": "Costillas verdaderas (1-7)"
      },
      {
        "structureId": "lumbar-vertebrae",
        "x": 0.5,
        "y": 0.39,
        "radius": 0.012,
        "en": "Lumbar vertebrae",
        "es": "Vértebras lumbares"
      },
      {
        "structureId": "sacrum",
        "x": 0.5,
        "y": 0.464,
        "radius": 0.012,
        "en": "Sacrum",
        "es": "Sacro"
      },
      {
        "structureId": "coccyx",
        "x": 0.5,
        "y": 0.507,
        "radius": 0.008,
        "en": "Coccyx",
        "es": "Cóccix"
      },
      {
        "structureId": "clavicle",
        "x": 0.5428,
        "y": 0.197,
        "radius": 0.014,
        "en": "Clavicle",
        "es": "Clavícula"
      },
      {
        "structureId": "humerus",
        "x": 0.5855,
        "y": 0.305,
        "radius": 0.014,
        "en": "Humerus",
        "es": "Húmero"
      },
      {
        "structureId": "pelvis",
        "x": 0.54,
        "y": 0.412,
        "radius": 0.02,
        "en": "Pelvis (hip bone)",
        "es": "Pelvis (hueso coxal)"
      },
      {
        "structureId": "femur",
        "x": 0.5483,
        "y": 0.58,
        "radius": 0.014,
        "en": "Femur",
        "es": "Fémur"
      }
    ]
  }
] as AtlasPlate[];
