import type { Lesson, Module, Question, SourceRecord, Structure } from './model';

export const ENDOCRINE_SOURCE_ID = 'source-openstax-ap-2013-endocrine-ch17';
export const CARDIOVASCULAR_SOURCE_ID = 'source-openstax-ap-2013-cardiovascular-ch19';
export const VESSELS_SOURCE_ID = 'source-openstax-ap-2013-vessels-ch20';
export const LYMPHATIC_SOURCE_ID = 'source-openstax-ap-2013-lymphatic-ch21';
const license = 'CC BY 4.0; attribution to OpenStax and contributors required';
const source = (id: string, chapter: string, title: string, sourceUrl: string): SourceRecord => ({
  id, filename: `OpenStax Anatomy and Physiology (2013), ${chapter}`, hash: `openstax-2013-${id}`,
  pageCount: null, title, courseLabAssociation: null, sourceType: 'text',
  attributionLicenseStatus: license, notes: 'Chapter-level provenance with original-edition section URL.',
  verificationStatus: 'verified', sourceUrl, licenseUrl: 'https://creativecommons.org/licenses/by/4.0/',
});
export const circulationSources: SourceRecord[] = [
  source(ENDOCRINE_SOURCE_ID, 'Chapter 17', 'OpenStax 2013 · The Endocrine System', 'https://openstax.org/books/anatomy-and-physiology/pages/17-1-an-overview-of-the-endocrine-system'),
  source(CARDIOVASCULAR_SOURCE_ID, 'Chapter 19', 'OpenStax 2013 · The Heart', 'https://openstax.org/books/anatomy-and-physiology/pages/19-1-heart-anatomy'),
  source(VESSELS_SOURCE_ID, 'Chapter 20', 'OpenStax 2013 · Blood Vessels and Circulation', 'https://openstax.org/books/anatomy-and-physiology/pages/20-1-structure-and-function-of-blood-vessels'),
  source(LYMPHATIC_SOURCE_ID, 'Chapter 21', 'OpenStax 2013 · The Lymphatic System', 'https://openstax.org/books/anatomy-and-physiology/pages/21-1-anatomy-of-the-lymphatic-and-immune-systems'),
];
type R = [string, string, string, string[]];
const makeStructures = (moduleId: string, sourceId: string, data: R[]): Structure[] => data.map(([id, canonicalName, category, acceptedAliases]) => ({
  id, canonicalName, category, acceptedAliases, moduleId, sourceId, sourcePage: null, examPriority: false, verificationStatus: 'verified',
}));
const makeLesson = (id: string, title: string, summary: string, structureIds: string[], sourceId: string, recognitionCues: string[], landmarks: string[], relationships: string[], commonConfusions: string[]): Lesson => ({
  id, title, summary, structureIds,
  recognitionCues: id === 'endo-adrenal' ? [...recognitionCues, 'Gray1121 supports only gross adrenal location: suprarenal glands lie superior and medial to the kidneys beside the great vessels; it does not depict cortex, medulla, cortical zones, or chromaffin histology.'] : recognitionCues,
  landmarks, relationships: id === 'endo-adrenal' ? [...relationships, 'Use Gray1121 only for the gross suprarenal relationship to kidneys and great vessels, not for adrenal cortex, medulla, zones, or chromaffin cells.'] : relationships,
  commonConfusions, sourceIds: [sourceId],
});
const mc = (id: string, moduleId: string, structureIds: string[], prompt: string, answer: string, options: string[], explanation: string, sourceId: string): Question => ({
  id, moduleId, structureIds, taskType: 'multiple-choice', prompt, answer, acceptedAliases: [], options, explanation, sourceId, sourcePage: null, examPriority: false, verificationStatus: 'verified',
});
const recall = (id: string, moduleId: string, structureIds: string[], prompt: string, answer: string, aliases: string[], explanation: string, sourceId: string): Question => ({
  id, moduleId, structureIds, taskType: 'typed-recall', prompt, answer, acceptedAliases: aliases, explanation, sourceId, sourcePage: null, examPriority: false, verificationStatus: 'verified',
});
const select = (id: string, moduleId: string, structureIds: string[], prompt: string, answer: string[], options: string[], explanation: string, sourceId: string): Question => ({
  id, moduleId, structureIds, taskType: 'select-all', prompt, answer, acceptedAliases: [], options, explanation, sourceId, sourcePage: null, examPriority: false, verificationStatus: 'verified',
});
const order = (id: string, moduleId: string, structureIds: string[], prompt: string, answer: string[], options: string[], explanation: string, sourceId: string): Question => ({
  id, moduleId, structureIds, taskType: 'ordered-sequence', prompt, answer, acceptedAliases: [], options, explanation, sourceId, sourcePage: null, examPriority: false, verificationStatus: 'verified',
});
const relationship = (id: string, moduleId: string, structureIds: string[], prompt: string, answer: string, options: string[], explanation: string, sourceId: string): Question => ({
  id, moduleId, structureIds, taskType: 'function-relationship', prompt, answer, acceptedAliases: [], options, explanation, sourceId, sourcePage: null, examPriority: false, verificationStatus: 'verified',
});

const endocrineRows: R[] = [
  ['endo-hypothalamus','Hypothalamus','brain endocrine anatomy',[]],['endo-pituitary','Pituitary gland','brain endocrine anatomy',['hypophysis']],['endo-anterior-pituitary','Anterior pituitary','pituitary subdivisions',['adenohypophysis']],['endo-posterior-pituitary','Posterior pituitary','pituitary subdivisions',['neurohypophysis']],['endo-pars-intermedia','Pars intermedia','pituitary subdivisions',[]],['endo-pituitary-stalk','Pituitary stalk','pituitary subdivisions',['infundibulum']],['endo-pineal','Pineal gland','brain endocrine anatomy',[]],['endo-thyroid','Thyroid gland','neck glands',[]],['endo-thyroid-lobe','Thyroid lobe','thyroid gross anatomy',[]],['endo-thyroid-isthmus','Thyroid isthmus','thyroid gross anatomy',[]],['endo-thyroid-follicle','Thyroid follicle','thyroid histology',[]],['endo-thyroid-colloid','Thyroid colloid','thyroid histology',[]],['endo-follicular-cell','Thyroid follicular cell','thyroid histology',[]],['endo-parafollicular-cell','Parafollicular cell','thyroid histology',['C cell']],['endo-parathyroids','Parathyroid glands','neck glands',[]],['endo-parathyroid-chief-cell','Parathyroid chief cell','parathyroid histology',[]],['endo-thymus','Thymus','thoracic endocrine organs',[]],['endo-adrenal','Adrenal gland','suprarenal glands',[]],['endo-adrenal-cortex','Adrenal cortex','adrenal subdivisions',[]],['endo-adrenal-medulla','Adrenal medulla','adrenal subdivisions',[]],['endo-zona-glomerulosa','Zona glomerulosa','adrenal histology',[]],['endo-zona-fasciculata','Zona fasciculata','adrenal histology',[]],['endo-zona-reticularis','Zona reticularis','adrenal histology',[]],['endo-chromaffin-cell','Chromaffin cell','adrenal histology',[]],['endo-pancreas','Pancreas','mixed glands',[]],['endo-pancreatic-islet','Pancreatic islet','pancreas histology',['islet of Langerhans']],['endo-alpha-cell','Pancreatic alpha cell','pancreas histology',[]],['endo-beta-cell','Pancreatic beta cell','pancreas histology',[]],['endo-delta-cell','Pancreatic delta cell','pancreas histology',[]],['endo-ovary','Ovary endocrine tissue','gonadal endocrine anatomy',[]],['endo-corpus-luteum','Corpus luteum','ovary endocrine anatomy',[]],['endo-testis','Testis endocrine tissue','gonadal endocrine anatomy',[]],['endo-leydig-cell','Leydig cell','testis histology',[]],['endo-sertoli-cell','Sertoli cell','testis histology',[]],['endo-portal-system','Hypothalamic–hypophyseal portal system','portal endocrine anatomy',[]],['endo-neurosecretory-cell','Hypothalamic neurosecretory cell','endocrine histology',[]],['endo-endocrine-gland','Endocrine gland','gross glands',[]],['endo-exocrine-gland','Exocrine gland','gross glands',[]],
];
export const endocrineStructures = makeStructures('endocrine-system', ENDOCRINE_SOURCE_ID, endocrineRows);
export const endocrineLessons: Lesson[] = [
  makeLesson('endo-central-control','Central endocrine control','Hypothalamic neurons regulate pituitary tissue through distinct vascular and neural routes.',['endo-hypothalamus','endo-pituitary','endo-anterior-pituitary','endo-posterior-pituitary','endo-pars-intermedia','endo-pituitary-stalk','endo-portal-system','endo-neurosecretory-cell'],ENDOCRINE_SOURCE_ID,['Anterior and posterior pituitary are different tissues; pars intermedia is the narrow intervening zone.'],['The stalk connects hypothalamus and pituitary.'],['Portal blood reaches anterior pituitary; axons reach posterior pituitary.'],['Posterior pituitary is not a separate gland; pars intermedia is not the medulla.']),
  makeLesson('endo-thyroid-parathyroid','Thyroid and parathyroid histology','Follicles and chief cells distinguish the two adjacent neck endocrine organs.',['endo-thyroid','endo-thyroid-lobe','endo-thyroid-isthmus','endo-thyroid-follicle','endo-thyroid-colloid','endo-follicular-cell','endo-parafollicular-cell','endo-parathyroids','endo-parathyroid-chief-cell'],ENDOCRINE_SOURCE_ID,['Colloid is inside a follicle; chief cells are in parathyroid tissue.','A thyroid lobe is a lateral mass; the isthmus is the midline bridge.'],['Two thyroid lobes are joined anteriorly by the isthmus; parathyroids lie posteriorly.','A follicle is a spherical unit lined by follicular cells and filled with colloid.'],['Follicular cells surround colloid; parafollicular cells lie between follicles; parathyroid chief cells form the characteristic parathyroid population.'],['Colloid is not a cell; the isthmus is not a lobe; parathyroid tissue is not a thyroid follicle.']),
  makeLesson('endo-adrenal','Adrenal cortex and medulla','The adrenal cortex has three zones external to a medulla containing chromaffin cells.',['endo-adrenal','endo-adrenal-cortex','endo-adrenal-medulla','endo-zona-glomerulosa','endo-zona-fasciculata','endo-zona-reticularis','endo-chromaffin-cell'],ENDOCRINE_SOURCE_ID,['Cortex is zonal; medulla is central.','The cortex forms the outer shell of the gland; chromaffin cells identify the inner medulla.'],['Glomerulosa is outermost and reticularis deepest cortical zone.','The zones run from capsule inward: glomerulosa, fasciculata, reticularis, then medulla.'],['Cortex surrounds medulla; each cortical zone is a subdivision of the cortex, not a separate gland.'],['Zona fasciculata is not the medulla; chromaffin cells are not cortical cells.']),
  makeLesson('endo-pancreas-gonads','Pancreatic and gonadal endocrine tissue','Islets and gonadal interstitial tissues are endocrine components of organs with other functions.',['endo-pancreas','endo-pancreatic-islet','endo-alpha-cell','endo-beta-cell','endo-delta-cell','endo-ovary','endo-corpus-luteum','endo-testis','endo-leydig-cell','endo-sertoli-cell'],ENDOCRINE_SOURCE_ID,['Islets are pale clusters among pancreatic acini.'],['Corpus luteum follows ovulation; Leydig cells occupy testicular interstitium.'],['Beta, alpha, and delta cells occupy one islet but have different products.'],['Sertoli cells are not Leydig cells.']),
  makeLesson('endo-pineal-thymus','Pineal and thymus','Pineal and thymic tissues are recognizable endocrine-related organs outside the neck.',['endo-pineal','endo-thymus'],ENDOCRINE_SOURCE_ID,['The thymus is lobulated; the pineal is a small brain structure.'],['Thymus lies in the anterior mediastinum.'],['Both are endocrine-related but have distinct locations and roles.'],['Thymus is not a thyroid lobe.']),
  makeLesson('endo-gland-types','Endocrine versus exocrine glands','Duct presence separates endocrine secretion into blood from exocrine secretion through ducts.',['endo-endocrine-gland','endo-exocrine-gland','endo-pancreas'],ENDOCRINE_SOURCE_ID,['Endocrine tissue is ductless.'],['The pancreas contains both components.'],['The same organ can have endocrine and exocrine regions.'],['Ductless does not mean secretion is absent.']),
];
export const endocrineModule: Module = { id:'endocrine-system', title:'Endocrine System', ordering:7, sourceIds:[ENDOCRINE_SOURCE_ID], visible:true, published:true, contentStatus:'available', system:'endocrine', category:'Glands and endocrine histology', summary:'Recognize endocrine organs, subdivisions, and diagnostic tissue landmarks.', coursePriority:false, lessons:endocrineLessons };
export const endocrineQuestions: Question[] = [
  mc('q-endo-01','endocrine-system',['endo-thyroid-follicle'],'Which structure encloses thyroid colloid?','Thyroid follicle',['Thyroid follicle','Adrenal cortex','Pancreatic islet','Parathyroid gland'],'Follicles are spherical units surrounding colloid.',ENDOCRINE_SOURCE_ID),
  recall('q-endo-02','endocrine-system',['endo-posterior-pituitary'],'What is the other anatomical name for the posterior pituitary?','Neurohypophysis',['neurohypophysis'],'The posterior pituitary is the neurohypophysis.',ENDOCRINE_SOURCE_ID),
  mc('q-endo-03','endocrine-system',['endo-parathyroid-chief-cell'],'Which cell type is characteristic of parathyroid tissue?','Parathyroid chief cell',['Parathyroid chief cell','Thyroid follicular cell','Chromaffin cell','Leydig cell'],'Chief cells are the principal parathyroid cells.',ENDOCRINE_SOURCE_ID),
  mc('q-endo-04','endocrine-system',['endo-zona-glomerulosa','endo-adrenal-cortex'],'Which cortical zone is outermost?','Zona glomerulosa',['Zona reticularis','Zona glomerulosa','Zona fasciculata','Adrenal medulla'],'The cortex proceeds from glomerulosa to fasciculata to reticularis.',ENDOCRINE_SOURCE_ID),
  select('q-endo-05','endocrine-system',['endo-pancreatic-islet','endo-alpha-cell','endo-beta-cell'],'Which are endocrine cell types found in pancreatic islets?',['Pancreatic alpha cell','Pancreatic beta cell'],['Pancreatic alpha cell','Pancreatic beta cell','Thyroid follicular cell','Chromaffin cell'],'Alpha and beta cells are islet endocrine cells.',ENDOCRINE_SOURCE_ID),
  relationship('q-endo-06','endocrine-system',['endo-portal-system','endo-anterior-pituitary'],'How does the portal system relate to the anterior pituitary?','It carries hypothalamic releasing hormones directly to anterior-pituitary capillaries',['It carries hypothalamic releasing hormones directly to anterior-pituitary capillaries','It drains venous blood from the spleen','It carries axons to the posterior pituitary','It connects thyroid follicles'],'The portal vessels provide the vascular link to anterior pituitary tissue.',ENDOCRINE_SOURCE_ID),
  mc('q-endo-07','endocrine-system',['endo-chromaffin-cell','endo-adrenal-medulla'],'Chromaffin cells are found in which subdivision?','Adrenal medulla',['Adrenal cortex','Adrenal medulla','Parathyroid','Thyroid follicle'],'Chromaffin cells populate the medulla.',ENDOCRINE_SOURCE_ID),
  recall('q-endo-08','endocrine-system',['endo-corpus-luteum'],'Which ovarian structure remains after ovulation and has endocrine activity?','Corpus luteum',['corpus luteum'],'The corpus luteum is the post-ovulatory endocrine structure.',ENDOCRINE_SOURCE_ID),
  mc('q-endo-09','endocrine-system',['endo-leydig-cell','endo-testis'],'Where are Leydig cells located?','Testicular interstitium',['Testicular interstitium','Seminiferous lumen','Thyroid colloid','Adrenal capsule'],'Leydig cells occupy interstitial tissue between seminiferous tubules.',ENDOCRINE_SOURCE_ID),
  mc('q-endo-10','endocrine-system',['endo-pineal'],'Which endocrine structure is located in the brain?','Pineal gland',['Thymus','Pineal gland','Pancreas','Parathyroid gland'],'The pineal gland is a brain endocrine organ.',ENDOCRINE_SOURCE_ID),
  select('q-endo-11','endocrine-system',['endo-endocrine-gland','endo-exocrine-gland'],'Which features distinguish endocrine from exocrine glands?',['Endocrine glands are ductless','Exocrine glands use ducts'],['Endocrine glands are ductless','Exocrine glands use ducts','Both always use ducts','Neither releases a product'],'Duct presence distinguishes these gland types.',ENDOCRINE_SOURCE_ID),
  order('q-endo-12','endocrine-system',['endo-adrenal-cortex','endo-zona-glomerulosa','endo-zona-fasciculata','endo-zona-reticularis','endo-adrenal-medulla'],'Order adrenal regions from superficial to deep.',['Zona glomerulosa','Zona fasciculata','Zona reticularis','Adrenal medulla'],['Adrenal medulla','Zona reticularis','Zona glomerulosa','Zona fasciculata'],'The three cortical zones precede the medulla.',ENDOCRINE_SOURCE_ID),
  mc('q-endo-13','endocrine-system',['endo-thyroid-colloid'],'Where is thyroid colloid located?','Inside thyroid follicles',['Inside thyroid follicles','Inside parathyroid chief cells','Inside adrenal sinusoids','Inside pancreatic ducts'],'Colloid fills the follicular lumen.',ENDOCRINE_SOURCE_ID),
  relationship('q-endo-14','endocrine-system',['endo-beta-cell'],'Which pairing is anatomically correct?','Beta cell — pancreatic islet',['Beta cell — pancreatic islet','Leydig cell — thyroid follicle','Chief cell — adrenal medulla','Chromaffin cell — parathyroid'],'Beta cells are islet cells.',ENDOCRINE_SOURCE_ID),
  mc('q-endo-15','endocrine-system',['endo-thymus'],'Which organ lies in the anterior mediastinum and has endocrine-related functions?','Thymus',['Thymus','Pineal gland','Parathyroid gland','Ovary'],'The thymus occupies the anterior mediastinum.',ENDOCRINE_SOURCE_ID),
  recall('q-endo-16','endocrine-system',['endo-pituitary-stalk'],'What structure connects the hypothalamus with the pituitary gland?','Pituitary stalk',['infundibulum'],'The infundibulum is the pituitary stalk.',ENDOCRINE_SOURCE_ID),
];

const cvRows: R[] = [
  ['cv-heart','Heart','gross heart',[]],['cv-apex','Apex of heart','surfaces',[]],['cv-base','Base of heart','surfaces',[]],['cv-right-auricle','Right auricle','surfaces',[]],['cv-left-auricle','Left auricle','surfaces',[]],['cv-right-atrium','Right atrium','chambers',[]],['cv-left-atrium','Left atrium','chambers',[]],['cv-right-ventricle','Right ventricle','chambers',[]],['cv-left-ventricle','Left ventricle','chambers',[]],['cv-tricuspid','Tricuspid valve','valves',[]],['cv-mitral','Mitral valve','valves',['bicuspid valve']],['cv-pulmonary-valve','Pulmonary semilunar valve','valves',[]],['cv-aortic-valve','Aortic semilunar valve','valves',[]],['cv-interatrial-septum','Interatrial septum','septa',[]],['cv-interventricular-septum','Interventricular septum','septa',[]],['cv-chordae','Chordae tendineae','valves',[]],['cv-papillary','Papillary muscles','valves',[]],['cv-myocardium','Myocardium','wall',[]],['cv-endocardium','Endocardium','wall',[]],['cv-epicardium','Epicardium','wall',[]],['cv-fibrous-pericardium','Fibrous pericardium','pericardium',[]],['cv-serous-pericardium','Serous pericardium','pericardium',[]],['cv-pericardial-cavity','Pericardial cavity','pericardium',[]],['cv-coronary-sulcus','Coronary sulcus','surfaces',[]],['cv-right-coronary','Right coronary artery','coronary circulation',[]],['cv-left-coronary','Left coronary artery','coronary circulation',[]],
  ['cv-lad','Anterior interventricular artery','coronary circulation',['LAD']],['cv-circumflex','Circumflex artery','coronary circulation',[]],['cv-right-marginal','Right marginal artery','coronary circulation',[]],['cv-posterior-interventricular','Posterior interventricular artery','coronary circulation',[]],['cv-great-cardiac-vein','Great cardiac vein','coronary circulation',[]],['cv-middle-cardiac-vein','Middle cardiac vein','coronary circulation',[]],['cv-small-cardiac-vein','Small cardiac vein','coronary circulation',[]],['cv-coronary-sinus','Coronary sinus','coronary circulation',[]],['cv-sa-node','Sinoatrial node','conduction',['SA node']],['cv-av-node','Atrioventricular node','conduction',['AV node']],['cv-av-bundle','Atrioventricular bundle','conduction',['bundle of His']],['cv-purkinje','Purkinje fibers','conduction',[]],['cv-pulmonary-trunk','Pulmonary trunk','great vessels',[]],['cv-pulmonary-veins','Pulmonary veins','great vessels',[]],['cv-svc','Superior vena cava','great vessels',['SVC']],['cv-ivc','Inferior vena cava','great vessels',['IVC']],['cv-ascending-aorta','Ascending aorta','great vessels',[]],['cv-aortic-arch','Aortic arch','great vessels',[]],['cv-descending-aorta','Descending aorta','great vessels',[]],['cv-brachiocephalic','Brachiocephalic trunk','great vessels',[]],['cv-left-common-carotid','Left common carotid artery','great vessels',[]],['cv-left-subclavian','Left subclavian artery','great vessels',[]],['cv-right-pulmonary-artery','Right pulmonary artery','great vessels',[]],['cv-left-pulmonary-artery','Left pulmonary artery','great vessels',[]],
];
export const cardiovascularStructures = makeStructures('cardiovascular-system', CARDIOVASCULAR_SOURCE_ID, cvRows);
export const cardiovascularLessons: Lesson[] = [
  makeLesson('cv-orientation','Heart orientation','The apex, base, surfaces, and sulci orient the external heart.',['cv-heart','cv-apex','cv-base','cv-coronary-sulcus'],CARDIOVASCULAR_SOURCE_ID,['Apex points inferiorly and leftward; base is the broad superior/posterior aspect.','The coronary sulcus is the atrioventricular groove visible around the heart.'],['Coronary sulcus separates atria from ventricles; the apex is formed mainly by the left ventricle.'],['The base receives and gives rise to the great vessels, while the apex is the inferior tip.'],['Base is not the inferior tip; the coronary sulcus is not the interventricular sulcus.']),
  makeLesson('cv-chambers','Chambers and septa','Atria receive blood, ventricles eject blood, and septa separate circuits.',['cv-right-auricle','cv-left-auricle','cv-right-atrium','cv-left-atrium','cv-right-ventricle','cv-left-ventricle','cv-interatrial-septum','cv-interventricular-septum','cv-pericardial-cavity'],CARDIOVASCULAR_SOURCE_ID,['Auricles are ear-like appendages of the atria; right and left chambers are not interchangeable.','The right auricle projects from the right atrium and the left auricle from the left atrium.'],['The interatrial septum separates the atria; the interventricular septum lies between ventricles.'],['Chambers connect through valves and great vessels; the pericardial cavity surrounds the heart.'],['An auricle is not an atrium as a whole; a septum is not a valve; the interatrial septum is not interventricular.']),
  makeLesson('cv-valves','Valves and wall','Valves enforce one-way flow while wall layers provide contraction and lining.',['cv-tricuspid','cv-mitral','cv-pulmonary-valve','cv-aortic-valve','cv-chordae','cv-papillary','cv-myocardium','cv-endocardium','cv-epicardium','cv-fibrous-pericardium','cv-serous-pericardium'],CARDIOVASCULAR_SOURCE_ID,['Chordae attach AV valve cusps to papillary muscles; epicardium is visceral serous pericardium.','Fibrous pericardium is the tough outer sac; serous pericardium is the smooth double-layered lining.'],['Myocardium is the thick contractile middle layer; fibrous pericardium is external to serous pericardium.','The pericardial cavity is between parietal and visceral serous layers, not inside the myocardium.'],['Serous pericardium has parietal and visceral layers around the pericardial cavity; epicardium is the visceral layer on the heart.'],['Mitral is left AV; tricuspid is right AV; epicardium is not myocardium; pericardial cavity is not a wall layer.']),
  makeLesson('cv-coronary','Coronary circulation','Coronary arteries occupy sulci and cardiac veins converge on the coronary sinus.',['cv-right-coronary','cv-left-coronary','cv-lad','cv-circumflex','cv-right-marginal','cv-posterior-interventricular','cv-great-cardiac-vein','cv-middle-cardiac-vein','cv-small-cardiac-vein','cv-coronary-sinus'],CARDIOVASCULAR_SOURCE_ID,['Coronary vessels lie on the heart surface; the great cardiac vein accompanies the anterior interventricular artery.','The right and left coronary arteries arise near the aortic root; the left coronary divides into anterior interventricular and circumflex branches.'],['Anterior and posterior interventricular arteries occupy their respective sulci; right marginal follows the acute margin.','The circumflex artery follows the coronary sulcus; middle cardiac vein accompanies the posterior interventricular artery.'],['Cardiac veins converge on the coronary sinus, which drains to the right atrium; great, middle, and small cardiac veins occupy corresponding surface routes.'],['Coronary arteries are not pulmonary arteries; a cardiac vein is not a vena cava; anterior and posterior interventricular vessels are not interchangeable.']),
  makeLesson('cv-conduction','Conduction system','The cardiac impulse travels from pacemaker to ventricular conducting fibers.',['cv-sa-node','cv-av-node','cv-av-bundle','cv-purkinje'],CARDIOVASCULAR_SOURCE_ID,['SA node precedes AV node.'],['AV bundle enters the interventricular septum.'],['Conduction coordinates atrial then ventricular contraction.'],['Purkinje fibers do not initiate the normal rhythm.']),
  makeLesson('cv-great-vessels','Great vessels and flow','Great vessels connect pulmonary and systemic circuits to the four chambers.',['cv-pulmonary-trunk','cv-pulmonary-veins','cv-svc','cv-ivc','cv-ascending-aorta','cv-aortic-arch','cv-descending-aorta','cv-brachiocephalic','cv-left-common-carotid','cv-left-subclavian','cv-right-pulmonary-artery','cv-left-pulmonary-artery'],CARDIOVASCULAR_SOURCE_ID,['Pulmonary arteries leave the right ventricle; pulmonary veins enter the left atrium.','The SVC and IVC enter the right atrium; the ascending aorta begins at the left ventricle.'],['The aortic arch gives rise to the brachiocephalic trunk, left common carotid, and left subclavian arteries; the pulmonary trunk divides into right and left pulmonary arteries.'],['Vessel identity follows its chamber connection and oxygenation route; ascending, arch, and descending aorta are continuous segments.'],['Pulmonary arteries are arteries despite carrying deoxygenated blood; the left arch branches are not pulmonary branches; pulmonary veins are not venae cavae.']),
];
export const cardiovascularModule: Module = { id:'cardiovascular-system', title:'Cardiovascular System: Heart', ordering:8, sourceIds:[CARDIOVASCULAR_SOURCE_ID], visible:true, published:true, contentStatus:'available', system:'cardiovascular', category:'Heart anatomy and circulation', summary:'Map chambers, valves, coronary vessels, conduction tissue, and great-vessel flow.', coursePriority:false, lessons: cardiovascularLessons };
export const cardiovascularQuestions: Question[] = [
  mc('q-cv-01','cardiovascular-system',['cv-tricuspid'],'Which valve is between the right atrium and right ventricle?','Tricuspid valve',['Mitral valve','Tricuspid valve','Aortic valve','Pulmonary valve'],'The tricuspid valve is the right atrioventricular valve.',CARDIOVASCULAR_SOURCE_ID),
  mc('q-cv-02','cardiovascular-system',['cv-mitral'],'Which valve guards the left atrioventricular opening?','Mitral valve',['Pulmonary valve','Aortic valve','Mitral valve','Tricuspid valve'],'The mitral valve is the left AV valve.',CARDIOVASCULAR_SOURCE_ID),
  mc('q-cv-03','cardiovascular-system',['cv-myocardium'],'Which layer performs most cardiac contraction?','Myocardium',['Endocardium','Epicardium','Myocardium','Pericardial cavity'],'Myocardium contains cardiac muscle.',CARDIOVASCULAR_SOURCE_ID),
  mc('q-cv-04','cardiovascular-system',['cv-sa-node'],'Which structure is the normal cardiac pacemaker?','Sinoatrial node',['AV node','Purkinje fibers','Sinoatrial node','SA node','AV bundle'],'The SA node normally initiates depolarization.',CARDIOVASCULAR_SOURCE_ID),
  mc('q-cv-05','cardiovascular-system',['cv-coronary-sinus'],'Where does most cardiac venous blood collect?','Coronary sinus',['Pulmonary trunk','Coronary sinus','Aortic arch','SVC'],'The coronary sinus empties into the right atrium.',CARDIOVASCULAR_SOURCE_ID),
  mc('q-cv-06','cardiovascular-system',['cv-lad'],'Which artery occupies the anterior interventricular sulcus?','Anterior interventricular artery',['Circumflex artery','Right coronary artery','Anterior interventricular artery','Pulmonary artery'],'The LAD runs in the anterior interventricular sulcus.',CARDIOVASCULAR_SOURCE_ID),
  select('q-cv-07','cardiovascular-system',['cv-chordae','cv-papillary'],'Which structures support AV valve cusps?',['Chordae tendineae','Papillary muscles'],['Semilunar cusps','Chordae tendineae','Papillary muscles','Coronary sinus'],'Chordae and papillary muscles support AV valves.',CARDIOVASCULAR_SOURCE_ID),
  order('q-cv-08','cardiovascular-system',['cv-svc','cv-right-atrium','cv-tricuspid','cv-right-ventricle','cv-pulmonary-trunk'],'Order systemic venous blood through the right heart.',['Superior vena cava','Right atrium','Tricuspid valve','Right ventricle','Pulmonary trunk'],['Right ventricle','Superior vena cava','Pulmonary trunk','Tricuspid valve','Right atrium'],'Systemic venous blood enters the right atrium and exits through the pulmonary trunk.',CARDIOVASCULAR_SOURCE_ID),
  relationship('q-cv-09','cardiovascular-system',['cv-pulmonary-veins','cv-left-atrium'],'What is the relationship of pulmonary veins to the left atrium?','They return pulmonary blood to the left atrium',['They return pulmonary blood to the left atrium','They leave the right ventricle','They drain the coronary sinus','They supply the myocardium'],'Pulmonary veins enter the left atrium.',CARDIOVASCULAR_SOURCE_ID),
  recall('q-cv-10','cardiovascular-system',['cv-av-bundle'],'What is another name for the atrioventricular bundle?','Bundle of His',['bundle of His'],'The AV bundle is also called the bundle of His.',CARDIOVASCULAR_SOURCE_ID),
  mc('q-cv-11','cardiovascular-system',['cv-apex'],'Which part of the heart points inferiorly?','Apex',['Base','Apex','Coronary sulcus','Auricle'],'The apex is the inferior tip.',CARDIOVASCULAR_SOURCE_ID),
  mc('q-cv-12','cardiovascular-system',['cv-interventricular-septum'],'What separates the right and left ventricles?','Interventricular septum',['Interatrial septum','Interventricular septum','Coronary sinus','Fibrous pericardium'],'The interventricular septum divides the ventricles.',CARDIOVASCULAR_SOURCE_ID),
  mc('q-cv-13','cardiovascular-system',['cv-pulmonary-valve'],'Which valve lies between right ventricle and pulmonary trunk?','Pulmonary semilunar valve',['Aortic semilunar valve','Mitral valve','Pulmonary semilunar valve','Tricuspid valve'],'It guards right ventricular outflow.',CARDIOVASCULAR_SOURCE_ID),
  mc('q-cv-14','cardiovascular-system',['cv-aortic-valve'],'Which valve lies between left ventricle and aorta?','Aortic semilunar valve',['Pulmonary semilunar valve','Aortic semilunar valve','Mitral valve','Tricuspid valve'],'It guards systemic outflow.',CARDIOVASCULAR_SOURCE_ID),
  mc('q-cv-15','cardiovascular-system',['cv-endocardium'],'Which layer lines the heart chambers?','Endocardium',['Epicardium','Myocardium','Endocardium','Pericardium'],'Endocardium lines the chambers.',CARDIOVASCULAR_SOURCE_ID),
  mc('q-cv-16','cardiovascular-system',['cv-epicardium'],'Which layer is the visceral serous pericardium?','Epicardium',['Endocardium','Epicardium','Myocardium','Fibrous skeleton'],'Epicardium is the visceral serous layer.',CARDIOVASCULAR_SOURCE_ID),
  mc('q-cv-17','cardiovascular-system',['cv-aortic-arch'],'Which segment follows the ascending aorta?','Aortic arch',['Descending aorta','Aortic arch','Pulmonary trunk','Brachiocephalic trunk'],'The aortic arch follows the ascending segment.',CARDIOVASCULAR_SOURCE_ID),
  mc('q-cv-18','cardiovascular-system',['cv-svc'],'Which vessel returns blood from the upper body?','Superior vena cava',['Inferior vena cava','Superior vena cava','Pulmonary vein','Aorta'],'The SVC drains superior systemic regions.',CARDIOVASCULAR_SOURCE_ID),
  mc('q-cv-19','cardiovascular-system',['cv-pulmonary-trunk'],'Which vessel receives blood from the right ventricle?','Pulmonary trunk',['Aorta','Pulmonary trunk','Pulmonary vein','SVC'],'The pulmonary trunk exits the right ventricle.',CARDIOVASCULAR_SOURCE_ID),
  select('q-cv-20','cardiovascular-system',['cv-sa-node','cv-av-node','cv-purkinje'],'Which are conducting structures?',['Sinoatrial node','Atrioventricular node','Purkinje fibers'],['Sinoatrial node','Atrioventricular node','Purkinje fibers','Chordae tendineae'],'These structures conduct or initiate cardiac electrical activity.',CARDIOVASCULAR_SOURCE_ID),
  relationship('q-cv-21','cardiovascular-system',['cv-right-coronary','cv-left-coronary'],'What is the shared relationship of the right and left coronary arteries?','They supply the myocardium',['They supply the myocardium','They return blood to the lungs','They drain the atria','They form the pulmonary trunk'],'Coronary arteries deliver oxygenated blood to cardiac muscle.',CARDIOVASCULAR_SOURCE_ID),
  recall('q-cv-22','cardiovascular-system',['cv-base'],'What broad external surface is opposite the apex?','Base of heart',['base'],'The base is the superior broad aspect.',CARDIOVASCULAR_SOURCE_ID),
];

const vesselRows: R[] = [
  ['ves-artery','Artery','vessel type',[]],['ves-arteriole','Arteriole','vessel type',[]],['ves-capillary','Capillary','vessel type',[]],['ves-venule','Venule','vessel type',[]],['ves-vein','Vein','vessel type',[]],['ves-intima','Tunica intima','wall layer',[]],['ves-endothelium','Endothelium','wall layer',[]],['ves-media','Tunica media','wall layer',[]],['ves-externa','Tunica externa','wall layer',['adventitia']],['ves-elastic','Elastic artery','vessel type',[]],['ves-muscular','Muscular artery','vessel type',[]],['ves-continuous','Continuous capillary','capillary type',[]],['ves-fenestrated','Fenestrated capillary','capillary type',[]],['ves-sinusoid','Sinusoid capillary','capillary type',[]],['ves-rbc','Erythrocyte','formed element',['red blood cell']],['ves-platelet','Platelet','formed element',[]],['ves-neutrophil','Neutrophil','formed element',[]],['ves-aorta','Aorta','major artery',[]],['ves-celiac-trunk','Celiac trunk','major artery',[]],['ves-renal-artery','Renal artery','major artery',[]],['ves-common-carotid','Common carotid artery','head arteries',[]],['ves-internal-carotid','Internal carotid artery','head arteries',[]],['ves-external-carotid','External carotid artery','head arteries',[]],['ves-subclavian','Subclavian artery','upper limb arteries',[]],['ves-axillary','Axillary artery','upper limb arteries',[]],['ves-brachial','Brachial artery','upper limb arteries',[]],['ves-radial','Radial artery','upper limb arteries',[]],['ves-ulnar','Ulnar artery','upper limb arteries',[]],['ves-femoral','Femoral artery','lower limb arteries',[]],['ves-popliteal','Popliteal artery','lower limb arteries',[]],['ves-anterior-tibial','Anterior tibial artery','lower limb arteries',[]],['ves-posterior-tibial','Posterior tibial artery','lower limb arteries',[]],['ves-internal-jugular','Internal jugular vein','head veins',[]],['ves-brachiocephalic-vein','Brachiocephalic vein','great veins',[]],['ves-subclavian-vein','Subclavian vein','upper limb veins',[]],['ves-axillary-vein','Axillary vein','upper limb veins',[]],['ves-jugular','Jugular vein','head veins',[]],['ves-cephalic','Cephalic vein','upper limb veins',[]],['ves-median-cubital','Median cubital vein','upper limb veins',[]],['ves-great-saphenous','Great saphenous vein','lower limb veins',[]],['ves-hepatic-portal','Hepatic portal vein','portal circulation',[]],['ves-splenic','Splenic vein','portal circulation',[]],['ves-mesenteric','Superior mesenteric vein','portal circulation',[]],['ves-hepatic-vein','Hepatic veins','portal circulation',[]],['ves-sinusoids','Hepatic sinusoids','portal circulation',[]],
];
export const vesselsStructures = makeStructures('blood-vessels', VESSELS_SOURCE_ID, vesselRows);
export const vesselsLessons: Lesson[] = [
  makeLesson('ves-wall','Vessel wall','Tunics vary with pressure and vessel function.',['ves-intima','ves-endothelium','ves-media','ves-externa'],VESSELS_SOURCE_ID,['Endothelium forms the inner lining.'],['Media is smooth-muscle-rich.'],['Wall composition predicts compliance and resistance.'],['Tunica externa is not the lumen.']),
  makeLesson('ves-types','Vessel types','Arteries, capillaries, and veins form a continuous route.',['ves-artery','ves-arteriole','ves-capillary','ves-venule','ves-vein','ves-elastic','ves-muscular'],VESSELS_SOURCE_ID,['Capillaries have the simplest wall.'],['Arterioles lead into capillary beds.'],['Pressure falls from arteries toward veins.'],['Venules are not arteries.']),
  makeLesson('ves-capillary-types','Capillary types','Continuous, fenestrated, and sinusoid capillaries differ in permeability.',['ves-continuous','ves-fenestrated','ves-sinusoid'],VESSELS_SOURCE_ID,['Sinusoids have the largest gaps.'],['Fenestrations permit greater exchange.'],['Permeability matches local tissue needs.'],['A capillary type is not a tunic.']),
  makeLesson('ves-elements','Blood elements','Formed elements have distinct cellular or fragment morphology.',['ves-rbc','ves-platelet','ves-neutrophil'],VESSELS_SOURCE_ID,['Platelets are cell fragments.'],['Erythrocytes are abundant formed elements.'],['Cell form supports transport or defense.'],['Platelets are not leukocytes.']),
  makeLesson('ves-regional','Regional vessels','Named arterial and venous routes identify regions and clinical access points.',['ves-aorta','ves-common-carotid','ves-internal-carotid','ves-external-carotid','ves-subclavian','ves-axillary','ves-brachial','ves-radial','ves-ulnar','ves-femoral','ves-popliteal','ves-anterior-tibial','ves-posterior-tibial','ves-jugular','ves-internal-jugular','ves-cephalic','ves-median-cubital','ves-great-saphenous'],VESSELS_SOURCE_ID,['Brachial lies in the arm; femoral lies in the thigh; popliteal lies behind the knee.','The common carotid ascends the neck before dividing into internal and external carotid arteries.'],['The axillary artery continues as brachial; radial and ulnar arteries supply the forearm. Cephalic and median cubital veins are superficial.','Femoral continues to popliteal behind the knee, then to anterior and posterior tibial routes in the leg; internal jugular drains the deep neck.'],['Carotid, upper-limb, and lower-limb names mark continuous regional routes; the subclavian-to-axillary-to-brachial sequence crosses the upper limb.'],['Internal and external carotid are not the common carotid; brachial is not brachiocephalic; anterior tibial is not posterior tibial; an artery is not defined by oxygen content.']),
  makeLesson('ves-central-branches','Central arterial branches and great veins','The aorta and major great veins give named routes to and from body regions.',['ves-celiac-trunk','ves-renal-artery','ves-brachiocephalic-vein','ves-subclavian-vein'],VESSELS_SOURCE_ID,['The celiac trunk and renal arteries arise from the abdominal aorta.','The celiac trunk serves upper abdominal branches; renal arteries run laterally to the kidneys.'],['Brachiocephalic veins unite to form the superior vena cava; subclavian veins continue from the upper limbs toward that confluence.'],['Named branches preserve the route from aorta to organs and from upper limbs to the SVC.'],['Brachiocephalic trunk is arterial; brachiocephalic veins are venous; the celiac trunk is not the hepatic portal vein.']),
  makeLesson('ves-portal','Portal circulation','Portal blood passes from digestive organs through liver sinusoids before systemic return.',['ves-hepatic-portal','ves-splenic','ves-mesenteric','ves-hepatic-vein','ves-sinusoids'],VESSELS_SOURCE_ID,['Portal vein enters the liver; hepatic veins leave it.'],['Sinusoids lie between portal inflow and hepatic-vein outflow.'],['Two capillary beds are connected in series.'],['Hepatic portal and hepatic veins have opposite route roles.']),
  makeLesson('ves-flow','Flow sequence','Regional vessels can be traced from aorta through exchange beds to veins.',['ves-aorta','ves-artery','ves-arteriole','ves-capillary','ves-venule','ves-vein'],VESSELS_SOURCE_ID,['Arteries carry blood away from the heart.'],['Veins return blood toward the heart.'],['Microcirculation links both sides.'],['Direction, not oxygen content, defines artery.']),
  makeLesson('ves-large-arteries','Large artery structure','Elastic and muscular arteries distribute or regulate blood flow.',['ves-elastic','ves-muscular','ves-aorta','ves-common-carotid'],VESSELS_SOURCE_ID,['Aorta is elastic; muscular arteries distribute blood to regional territories.'],['Elastic recoil supports continuous flow; muscular arteries have a prominent smooth-muscle media for regional distribution.'],['The aorta is an elastic artery; muscular arteries regulate regional distribution without using common carotid as a generic example.'],['Elastic does not mean skeletal muscle; common carotid anatomy is covered in the regional-vessels lesson.']),
  makeLesson('ves-venous-return','Venous return','Veins and venules collect low-pressure blood from tissues.',['ves-venule','ves-vein','ves-jugular','ves-cephalic','ves-femoral'],VESSELS_SOURCE_ID,['Venules receive capillary blood.'],['Superficial veins have recognizable regional names.'],['Veins complete the return route.'],['A venule is smaller than a vein.']),
];
vesselsLessons.find((lesson) => lesson.id === 'ves-venous-return')?.structureIds.push('ves-axillary-vein');
export const vesselsModule: Module = { id:'blood-vessels', title:'Blood Vessels and Circulation', ordering:9, sourceIds:[VESSELS_SOURCE_ID], visible:true, published:true, contentStatus:'available', system:'vessels', category:'Vessel walls, regional routes, and portal flow', summary:'Identify vessel walls, types, regional vessels, and the hepatic portal route.', coursePriority:false, lessons:vesselsLessons };
export const vesselsQuestions: Question[] = [
  mc('q-ves-01','blood-vessels',['ves-media'],'Which tunic contains most vascular smooth muscle?','Tunica media',['Tunica intima','Tunica media','Tunica externa','Endothelium'],'The tunica media regulates diameter.',VESSELS_SOURCE_ID),
  mc('q-ves-02','blood-vessels',['ves-endothelium'],'What forms the inner cellular lining of a vessel?','Endothelium',['Endothelium','Tunica externa','Platelet','Elastic lamina'],'Endothelium lines the lumen.',VESSELS_SOURCE_ID),
  mc('q-ves-03','blood-vessels',['ves-capillary'],'Which vessel is the primary exchange site?','Capillary',['Artery','Capillary','Vein','Venule'],'Capillary walls support exchange.',VESSELS_SOURCE_ID),
  mc('q-ves-04','blood-vessels',['ves-elastic'],'Which vessel type uses elastic recoil to smooth pulsatile flow?','Elastic artery',['Muscular artery','Elastic artery','Venule','Sinusoid'],'Elastic arteries accommodate pressure pulses.',VESSELS_SOURCE_ID),
  mc('q-ves-05','blood-vessels',['ves-fenestrated'],'Which capillary has pores that increase exchange?','Fenestrated capillary',['Continuous capillary','Fenestrated capillary','Muscular artery','Vein'],'Fenestrations increase permeability.',VESSELS_SOURCE_ID),
  mc('q-ves-06','blood-vessels',['ves-sinusoid'],'Which capillary type has the most discontinuous wall?','Sinusoid capillary',['Continuous capillary','Fenestrated capillary','Sinusoid capillary','Arteriole'],'Sinusoids have wide gaps and a discontinuous basal lamina.',VESSELS_SOURCE_ID),
  select('q-ves-07','blood-vessels',['ves-rbc','ves-platelet','ves-neutrophil'],'Which are formed elements?',['Erythrocyte','Platelet','Neutrophil'],['Erythrocyte','Platelet','Neutrophil','Tunica media'],'These are cellular blood components or fragments.',VESSELS_SOURCE_ID),
  order('q-ves-08','blood-vessels',['ves-artery','ves-arteriole','ves-capillary','ves-venule','ves-vein'],'Order vessels from heart to return.',['Artery','Arteriole','Capillary','Venule','Vein'],['Vein','Capillary','Artery','Venule','Arteriole'],'Blood passes from arteries through microcirculation to veins.',VESSELS_SOURCE_ID),
  mc('q-ves-09','blood-vessels',['ves-hepatic-portal'],'Which vessel carries digestive venous blood into the liver?','Hepatic portal vein',['Hepatic vein','Hepatic portal vein','Inferior vena cava','Splenic artery'],'The portal vein enters the liver.',VESSELS_SOURCE_ID),
  mc('q-ves-10','blood-vessels',['ves-hepatic-vein'],'Which vessel carries blood away from liver sinusoids?','Hepatic vein',['Hepatic portal vein','Hepatic vein','Superior mesenteric vein','Splenic vein'],'Hepatic veins drain the liver.',VESSELS_SOURCE_ID),
  relationship('q-ves-11','blood-vessels',['ves-splenic','ves-hepatic-portal'],'How does splenic venous blood reach the liver?','It contributes to the hepatic portal route',['It contributes to the hepatic portal route','It enters the pulmonary trunk','It drains directly into the aorta','It bypasses the liver'],'Splenic blood joins portal circulation.',VESSELS_SOURCE_ID),
  mc('q-ves-12','blood-vessels',['ves-brachial'],'Which artery is named for the arm?','Brachial artery',['Femoral artery','Brachial artery','Radial vein','Carotid artery'],'Brachial denotes the arm region.',VESSELS_SOURCE_ID),
  mc('q-ves-13','blood-vessels',['ves-femoral'],'Which artery traverses the thigh?','Femoral artery',['Femoral artery','Brachial artery','Common carotid artery','Subclavian artery'],'Femoral denotes the thigh region.',VESSELS_SOURCE_ID),
  mc('q-ves-14','blood-vessels',['ves-common-carotid'],'Which artery supplies the head and neck region?','Common carotid artery',['Common carotid artery','Femoral artery','Radial artery','Hepatic artery'],'Carotid arteries ascend in the neck.',VESSELS_SOURCE_ID),
  mc('q-ves-15','blood-vessels',['ves-cephalic'],'Which is a superficial upper-limb vein?','Cephalic vein',['Cephalic vein','Jugular vein','Femoral artery','Aorta'],'The cephalic vein is a superficial upper-limb vein.',VESSELS_SOURCE_ID),
  recall('q-ves-16','blood-vessels',['ves-rbc'],'What is the anatomical name for a red blood cell?','Erythrocyte',['red blood cell'],'Erythrocyte is the formed-element term.',VESSELS_SOURCE_ID),
  mc('q-ves-17','blood-vessels',['ves-platelet'],'Which formed element is a cell fragment involved in clotting?','Platelet',['Neutrophil','Platelet','Erythrocyte','Endothelium'],'Platelets are fragments important in hemostasis.',VESSELS_SOURCE_ID),
  relationship('q-ves-18','blood-vessels',['ves-artery','ves-vein'],'What distinguishes artery from vein anatomically?','An artery carries blood away from the heart',['An artery carries blood away from the heart','An artery always carries oxygenated blood','A vein always has thick media','A vein carries blood away from the heart'],'Direction defines artery and vein.',VESSELS_SOURCE_ID),
  mc('q-ves-19','blood-vessels',['ves-arteriole'],'Which vessel directly regulates entry into capillary beds?','Arteriole',['Arteriole','Vein','Venule','Aorta'],'Arterioles regulate resistance and capillary inflow.',VESSELS_SOURCE_ID),
  mc('q-ves-20','blood-vessels',['ves-venule'],'Which vessel receives blood from capillaries?','Venule',['Artery','Venule','Elastic artery','Aorta'],'Venules collect capillary blood.',VESSELS_SOURCE_ID),
  select('q-ves-21','blood-vessels',['ves-intima','ves-media','ves-externa'],'Which are vessel tunics?',['Tunica intima','Tunica media','Tunica externa'],['Tunica media','Endothelium','Tunica externa','Tunica intima'],'The three tunics form the vessel wall.',VESSELS_SOURCE_ID),
  order('q-ves-22','blood-vessels',['ves-mesenteric','ves-hepatic-portal','ves-sinusoids','ves-hepatic-vein'],'Order a portal route after intestinal drainage.',['Superior mesenteric vein','Hepatic portal vein','Hepatic sinusoids','Hepatic vein'],['Hepatic vein','Hepatic sinusoids','Superior mesenteric vein','Hepatic portal vein'],'Portal blood passes through liver sinusoids before hepatic veins.',VESSELS_SOURCE_ID),
];

const lymphRows: R[] = [
  ['lymph-fluid','Lymph','fluid',[]],['lymph-capillary','Lymphatic capillary','vessels',[]],['lymph-collecting-vessel','Collecting lymphatic vessel','vessels',[]],['lymph-thoracic-duct','Thoracic duct','ducts',[]],['lymph-right-duct','Right lymphatic duct','ducts',[]],['lymph-node','Lymph node','nodes',[]],['lymph-cervical-nodes','Cervical lymph nodes','node groups',[]],['lymph-axillary-nodes','Axillary lymph nodes','node groups',[]],['lymph-inguinal-nodes','Inguinal lymph nodes','node groups',[]],['lymph-afferent','Afferent lymphatic vessel','node architecture',[]],['lymph-efferent','Efferent lymphatic vessel','node architecture',[]],['lymph-capsule','Node capsule','node architecture',[]],['lymph-subcapsular-sinus','Subcapsular sinus','node architecture',[]],['lymph-cortical-sinus','Cortical sinus','node architecture',[]],['lymph-cortex','Lymph node cortex','node architecture',[]],['lymph-medulla','Lymph node medulla','node architecture',[]],['lymph-medullary-sinus','Medullary sinus','node architecture',[]],['lymph-medullary-cord','Medullary cord','node architecture',[]],['lymph-hilum','Node hilum','node architecture',[]],['lymph-spleen','Spleen','organ',[]],['lymph-white-pulp','White pulp','spleen histology',[]],['lymph-marginal-zone','Splenic marginal zone','spleen histology',[]],['lymph-central-arteriole','Central arteriole','spleen histology',[]],['lymph-red-pulp','Red pulp','spleen histology',[]],['lymph-splenic-cords','Splenic cords','spleen histology',[]],['lymph-splenic-sinusoids','Splenic sinusoids','spleen histology',[]],['lymph-thymus','Thymus','organ',[]],['lymph-thymic-lobule','Thymic lobule','thymus histology',[]],['lymph-thymic-cortex','Thymic cortex','thymus histology',[]],['lymph-thymic-medulla','Thymic medulla','thymus histology',[]],['lymph-hassall','Hassall corpuscle','thymus histology',[]],['lymph-palatine-tonsil','Palatine tonsil','MALT',[]],['lymph-pharyngeal-tonsil','Pharyngeal tonsil','MALT',['adenoid']],['lymph-lingual-tonsil','Lingual tonsil','MALT',[]],['lymph-malt','Mucosa-associated lymphoid tissue','MALT',['MALT']],['lymph-peyers','Peyer patches','MALT',[]],['lymph-lacteal','Lacteal','intestinal lymphatics',[]],['lymph-follicle','Lymphoid follicle','MALT',[]],['lymph-germinal-center','Germinal center','MALT',[]],['lymph-cisterna','Cisterna chyli','ducts',[]],['lymph-trunk','Lymphatic trunk','vessels',[]],['lymph-jugular-trunk','Jugular lymphatic trunk','vessels',[]],['lymph-subclavian-trunk','Subclavian lymphatic trunk','vessels',[]],['lymph-intestinal-trunk','Intestinal lymphatic trunk','vessels',[]],['lymph-lumbar-trunks','Lumbar lymphatic trunks','vessels',[]],['lymph-appendix','Appendix lymphoid tissue','MALT',[]],['lymph-tonsil','Tonsil','MALT',[]],
];
export const lymphaticStructures = makeStructures('lymphatic-system', LYMPHATIC_SOURCE_ID, lymphRows);
export const lymphaticLessons: Lesson[] = [
  makeLesson('lymph-vessels','Lymphatic vessels and ducts','Lymph returns to venous blood through collecting vessels and ducts.',['lymph-fluid','lymph-capillary','lymph-collecting-vessel','lymph-trunk','lymph-thoracic-duct','lymph-right-duct','lymph-cisterna'],LYMPHATIC_SOURCE_ID,['Capillaries are blind-ended.'],['Thoracic duct drains most of the body.'],['Lymph flow is one-way toward venous angles.'],['A duct is larger than a capillary.']),
  makeLesson('lymph-node','Lymph node architecture','Nodes filter lymph through organized cortical and medullary compartments.',['lymph-node','lymph-cervical-nodes','lymph-axillary-nodes','lymph-inguinal-nodes','lymph-afferent','lymph-efferent','lymph-capsule','lymph-subcapsular-sinus','lymph-cortical-sinus','lymph-cortex','lymph-medulla','lymph-medullary-sinus','lymph-medullary-cord','lymph-hilum'],LYMPHATIC_SOURCE_ID,['Afferent vessels enter; efferent vessels leave at the hilum; named node groups follow drainage regions.','Cervical, axillary, and inguinal nodes are named for head/neck, upper-limb, and lower-limb drainage regions.'],['Subcapsular sinus lies beneath the capsule; cortical and medullary sinuses continue toward the hilum.','The capsule encloses cortex; medulla lies deeper and contains cords and sinuses near the hilum.'],['Cortex contains follicles, while medullary cords and sinuses lead to efferent drainage.'],['Afferent and efferent directions are opposite; a sinus is not a vessel; a node group is not a single sinus.']),
  makeLesson('lymph-spleen','Spleen architecture','White pulp supports immune surveillance while red pulp filters blood.',['lymph-spleen','lymph-white-pulp','lymph-marginal-zone','lymph-central-arteriole','lymph-red-pulp','lymph-splenic-cords','lymph-splenic-sinusoids'],LYMPHATIC_SOURCE_ID,['White pulp surrounds a central arteriole; red pulp contains cords and sinusoids.','The central arteriole is embedded in white pulp; the marginal zone forms its border with red pulp.'],['The marginal zone lies between white and red pulp; splenic cords lie between sinusoids.','Red pulp is organized into splenic cords and vascular sinusoids rather than lymph-node sinuses.'],['Spleen filters blood rather than lymph, with arterial blood passing from white pulp toward red pulp.'],['White pulp is not a lymph-node cortex; a central arteriole is not a node vessel; splenic sinusoids are not lymphatic sinuses.']),
  makeLesson('lymph-thymus','Thymus architecture','Thymic lobules contain a dark cortex and lighter medulla with Hassall corpuscles.',['lymph-thymus','lymph-thymic-lobule','lymph-thymic-cortex','lymph-thymic-medulla','lymph-hassall'],LYMPHATIC_SOURCE_ID,['Hassall corpuscles are medullary.'],['Cortex is peripheral to medulla in a lobule.'],['Thymus is a primary lymphoid organ.'],['Thymic cortex is not splenic red pulp.']),
  makeLesson('lymph-tonsils','Tonsils and MALT','Tonsils and mucosal lymphoid aggregates monitor exposed epithelial surfaces.',['lymph-palatine-tonsil','lymph-pharyngeal-tonsil','lymph-lingual-tonsil','lymph-tonsil','lymph-malt','lymph-follicle','lymph-germinal-center'],LYMPHATIC_SOURCE_ID,['Tonsils ring the pharyngeal entrance.'],['Pharyngeal tonsil is also called adenoid.'],['MALT is positioned at mucosal surfaces.'],['A tonsil is not a lymphatic duct.']),
  makeLesson('lymph-intestinal','Intestinal lymphatics','Lacteals and Peyer patches combine lipid uptake with mucosal immune surveillance.',['lymph-peyers','lymph-lacteal','lymph-appendix','lymph-intestinal-trunk'],LYMPHATIC_SOURCE_ID,['Lacteals lie in intestinal villi.'],['Peyer patches are prominent in ileal mucosa; intestinal lymphatics converge toward the intestinal trunk.'],['Lacteals absorb dietary lipids; MALT samples antigens.'],['A lacteal is not a blood capillary.']),
  makeLesson('lymph-trunks','Lymphatic trunks and regional drainage','Named trunks collect lymph from body regions before entering the major ducts.',['lymph-trunk','lymph-jugular-trunk','lymph-subclavian-trunk','lymph-intestinal-trunk','lymph-lumbar-trunks','lymph-cisterna','lymph-thoracic-duct','lymph-right-duct'],LYMPHATIC_SOURCE_ID,['Jugular and subclavian trunks drain head/neck and upper limb regions; lumbar trunks converge on the cisterna chyli.','The intestinal trunk collects abdominal lymph, including lipid-rich lymph from intestinal lacteals.'],['The cisterna chyli is the inferior origin of the thoracic duct; lumbar trunks enter it from the lower body.'],['Trunks converge into ducts that return lymph at the venous angles; jugular and subclavian trunks usually join near the root of the neck.'],['A trunk is not a node; the right lymphatic duct is regional, not the main body duct; cisterna chyli is not a trunk.']),
];
export const lymphaticModule: Module = { id:'lymphatic-system', title:'Lymphatic System', ordering:10, sourceIds:[LYMPHATIC_SOURCE_ID], visible:true, published:true, contentStatus:'available', system:'lymphatic', category:'Vessels, nodes, and lymphoid organs', summary:'Trace lymph and recognize node, spleen, thymus, tonsil, and MALT architecture.', coursePriority:false, lessons: lymphaticLessons };
export const lymphaticQuestions: Question[] = [
  mc('q-ly-01','lymphatic-system',['lymph-thoracic-duct'],'Which duct drains most of the body?','Thoracic duct',['Right lymphatic duct','Thoracic duct','Cisterna chyli','Collecting vessel'],'The thoracic duct drains all but the right upper quadrant.',LYMPHATIC_SOURCE_ID),
  mc('q-ly-02','lymphatic-system',['lymph-right-duct'],'Which duct drains the right upper quadrant?','Right lymphatic duct',['Thoracic duct','Right lymphatic duct','Lymphatic trunk','Cisterna chyli'],'The right duct serves the right upper quadrant.',LYMPHATIC_SOURCE_ID),
  mc('q-ly-03','lymphatic-system',['lymph-afferent'],'Which vessels enter a lymph node?','Afferent lymphatic vessels',['Efferent vessels','Afferent lymphatic vessels','Arteries','Lacteals'],'Afferent vessels enter the convex surface.',LYMPHATIC_SOURCE_ID),
  mc('q-ly-04','lymphatic-system',['lymph-efferent','lymph-hilum'],'Where does an efferent vessel leave a node?','Hilum',['Capsule','Subcapsular sinus','Hilum','Cortex'],'Efferent vessels exit at the hilum.',LYMPHATIC_SOURCE_ID),
  mc('q-ly-05','lymphatic-system',['lymph-subcapsular-sinus'],'Which space lies immediately beneath the node capsule?','Subcapsular sinus',['Medullary cord','Subcapsular sinus','Splenic sinusoid','Thymic medulla'],'The subcapsular sinus receives afferent lymph.',LYMPHATIC_SOURCE_ID),
  mc('q-ly-06','lymphatic-system',['lymph-white-pulp'],'Which splenic region contains lymphoid tissue around arterial branches?','White pulp',['Red pulp','White pulp','Node medulla','Thymic cortex'],'White pulp is the immune region of spleen.',LYMPHATIC_SOURCE_ID),
  mc('q-ly-07','lymphatic-system',['lymph-red-pulp','lymph-splenic-sinusoids'],'Which splenic region contains cords and sinusoids?','Red pulp',['White pulp','Red pulp','Node cortex','MALT'],'Red pulp filters blood through cords and sinusoids.',LYMPHATIC_SOURCE_ID),
  mc('q-ly-08','lymphatic-system',['lymph-hassall'],'Which structure identifies thymic medulla?','Hassall corpuscle',['Germinal center','Hassall corpuscle','Splenic cord','Subcapsular sinus'],'Hassall corpuscles are thymic medullary structures.',LYMPHATIC_SOURCE_ID),
  mc('q-ly-09','lymphatic-system',['lymph-thymic-cortex','lymph-thymic-medulla'],'Which thymic region is peripheral and darker?','Thymic cortex',['Thymic medulla','Thymic cortex','Red pulp','Node hilum'],'The cortex surrounds the medulla in a lobule.',LYMPHATIC_SOURCE_ID),
  mc('q-ly-10','lymphatic-system',['lymph-pharyngeal-tonsil'],'What is another name for the pharyngeal tonsil?','Adenoid',['Palatine tonsil','Adenoid','Lingual tonsil','Peyer patch'],'Pharyngeal tonsil is the adenoid.',LYMPHATIC_SOURCE_ID),
  select('q-ly-11','lymphatic-system',['lymph-palatine-tonsil','lymph-pharyngeal-tonsil','lymph-lingual-tonsil'],'Which are named tonsils?',['Palatine tonsil','Pharyngeal tonsil','Lingual tonsil'],['Palatine tonsil','Pharyngeal tonsil','Lingual tonsil','Thymic lobule'],'These are the major named pharyngeal tonsils.',LYMPHATIC_SOURCE_ID),
  mc('q-ly-12','lymphatic-system',['lymph-lacteal'],'What is the primary anatomical role of an intestinal lacteal?','Absorb dietary lipids',['Filter blood','Absorb dietary lipids','Drain the thymus','Produce red blood cells'],'Lacteals are lymphatic capillaries in villi that absorb lipids.',LYMPHATIC_SOURCE_ID),
  mc('q-ly-13','lymphatic-system',['lymph-peyers'],'Where are Peyer patches especially associated?','Ileal mucosa',['Ileal mucosa','Thymic medulla','Splenic capsule','Node hilum'],'Peyer patches are intestinal MALT, especially in ileum.',LYMPHATIC_SOURCE_ID),
  relationship('q-ly-14','lymphatic-system',['lymph-spleen','lymph-white-pulp','lymph-red-pulp'],'How does spleen differ from a lymph node?','Spleen filters blood whereas a lymph node filters lymph',['Spleen filters blood whereas a lymph node filters lymph','Spleen drains lymph into a duct','A node contains red pulp','A node filters only arterial blood'],'The spleen is a blood-filtering organ.',LYMPHATIC_SOURCE_ID),
  order('q-ly-15','lymphatic-system',['lymph-afferent','lymph-subcapsular-sinus','lymph-cortex','lymph-medulla','lymph-efferent'],'Order lymph through a node.',['Afferent vessel','Subcapsular sinus','Cortex','Medulla','Efferent vessel'],['Medulla','Afferent vessel','Efferent vessel','Cortex','Subcapsular sinus'],'Lymph enters afferently, crosses sinus and tissue, then exits efferently.',LYMPHATIC_SOURCE_ID),
  recall('q-ly-16','lymphatic-system',['lymph-fluid'],'What fluid travels in lymphatic vessels?','Lymph',['lymph'],'Lymph is the fluid carried by lymphatics.',LYMPHATIC_SOURCE_ID),
];