import type { Lesson, Question, Structure } from './model';
import { OPENSTAX_SOURCE_ID } from './anatomy.ts';

const moduleId = 'anatomy-foundations';
// Original anatomy-focused summaries checked against OpenStax Anatomy and
// Physiology (2013), §§28.1–28.2. No source figures are reproduced.
const rows: Array<[string, string, string, string[]]> = [
  ['fertilization', 'Fertilization', 'early development', ['conception']],
  ['zygote', 'Zygote', 'early development', ['fertilized egg cell']],
  ['cleavage', 'Cleavage', 'early development', ['early cleavage divisions']],
  ['blastomere', 'Blastomere', 'early development', ['cleavage cell']],
  ['morula', 'Morula', 'early development', ['compact ball of cells']],
  ['blastocyst', 'Blastocyst', 'early development', []],
  ['blastocoel', 'Blastocoel', 'blastocyst space', ['blastocyst cavity']],
  ['inner-cell-mass', 'Inner cell mass', 'blastocyst compartment', ['embryoblast']],
  ['trophoblast', 'Trophoblast', 'blastocyst compartment', ['outer blastocyst layer']],
  ['implantation', 'Implantation', 'uterine attachment', ['blastocyst implantation']],
  ['gastrulation', 'Gastrulation', 'germ-layer formation', []],
  ['primitive-streak', 'Primitive streak', 'germ-layer formation', []],
  ['ectoderm', 'Ectoderm', 'embryonic germ layer', ['outer germ layer']],
  ['mesoderm', 'Mesoderm', 'embryonic germ layer', ['middle germ layer']],
  ['endoderm', 'Endoderm', 'embryonic germ layer', ['inner germ layer']],
  ['neurulation', 'Neurulation', 'neural development', ['neural tube formation']],
  ['neural-plate', 'Neural plate', 'neural development', []],
  ['neural-tube', 'Neural tube', 'neural development', []],
  ['notochord', 'Notochord', 'axial development', []],
  ['somites', 'Somites', 'paraxial development', ['somite blocks']],
  ['embryonic-folding', 'Embryonic folding', 'body form', ['body folding']],
  ['primitive-gut', 'Primitive gut', 'body form', ['gut tube']],
  ['amnion', 'Amnion', 'extraembryonic membrane', ['amniotic membrane']],
  ['chorion', 'Chorion', 'extraembryonic membrane', ['chorionic membrane']],
  ['chorionic-villi', 'Chorionic villi', 'placental interface', ['chorionic villus']],
  ['placenta', 'Placenta', 'maternal-fetal interface', []],
  ['umbilical-cord', 'Umbilical cord', 'placental connection', ['umbilical connection']],
];
const id = (name: string) => `dev-${name}`;

export const foundationsDevelopmentStructures: Structure[] = rows.map(([name, canonicalName, category, acceptedAliases]) => ({
  id: id(name), canonicalName, category, acceptedAliases, moduleId, sourceId: OPENSTAX_SOURCE_ID,
  sourcePage: null, examPriority: true, verificationStatus: 'verified',
}));

const lesson = (
  name: string, title: string, summary: string, terms: string[],
  recognitionCues: string[], landmarks: string[], relationships: string[], commonConfusions: string[],
): Lesson => ({
  id: `foundations-dev-${name}`, title, summary, structureIds: terms.map(id),
  recognitionCues, landmarks, relationships, commonConfusions,
  sourceIds: [OPENSTAX_SOURCE_ID],
});

export const foundationsDevelopmentLessons: Lesson[] = [
  lesson('first-stages', 'From fertilization to blastocyst',
    'Follow the developing conceptus from a single cell in the uterine tube toward the uterus.',
    ['fertilization','zygote','cleavage','blastomere','morula','blastocyst','blastocoel','inner-cell-mass','trophoblast'],
    ['Fertilization joins sperm and oocyte nuclei to form a zygote; cleavage produces smaller blastomeres without much increase in overall size.',
      'A morula is a compact solid cell ball; a blastocyst has a fluid-filled blastocoel, an inner cell mass, and an outer trophoblast.'],
    ['Fertilization usually occurs in a uterine tube; the dividing conceptus travels toward the uterus, where a blastocyst later implants.'],
    ['The female reproductive module locates the uterine tube and its ampulla; the male module traces the sperm route. The inner cell mass gives rise to the embryo, while trophoblast contributes to fetal placental tissues.'],
    ['Cleavage increases cell number, not the overall size of the early conceptus.', 'A morula has no blastocyst cavity; the inner cell mass is not the trophoblast.']),
  lesson('implantation', 'Implantation in the uterine lining',
    'Connect blastocyst structure to the site where pregnancy becomes established.',
    ['blastocyst','trophoblast','implantation','chorion'],
    ['After reaching the uterus, a blastocyst attaches to and embeds in the endometrium via its outer trophoblast.',
      'The chorion develops from trophoblast and associated extraembryonic tissue; it later contributes to the fetal side of the placenta.'],
    ['The endometrium is the uterine lining described in the female reproductive module—not the muscular myometrium or the uterine-tube wall.'],
    ['Implantation follows the morula-to-blastocyst transition; it is not the same event as fertilization in the uterine tube.'],
    ['The blastocyst implants, not the earlier one-cell zygote.', 'The placenta develops after attachment; it is not already a mature organ at implantation.']),
  lesson('germ-layers', 'Gastrulation and the derivative map',
    'Use the three layers of the embryonic disc to predict broad adult tissue origins, not the origin of every cell in an organ.',
    ['gastrulation','primitive-streak','ectoderm','mesoderm','endoderm'],
    ['Gastrulation produces three germ layers as cells move through the primitive streak: ectoderm, mesoderm, and endoderm.',
      'Ectoderm contributes epidermis and nervous tissue; mesoderm contributes muscle, skeleton, connective tissue, heart, vessels, and kidneys.',
      'Endoderm contributes the epithelial lining of the gut and respiratory tract and epithelial components of liver and pancreas.'],
    ['In the early three-layer disc, ectoderm is outer/dorsal, mesoderm is middle, and endoderm is inner/ventral.'],
    ['The germ layers are developmental origins; an adult organ such as the gut also contains muscle and connective tissue from mesoderm around its endoderm-derived lining.'],
    ['Endoderm does not make every part of a digestive organ.', 'Ectoderm makes the epidermis, not the entire skin including its mesoderm-derived dermis.']),
  lesson('neural-axis', 'Neurulation and the body axis',
    'Locate the early central nervous system and adjacent supporting tissues in relation to the germ layers.',
    ['ectoderm','mesoderm','neurulation','neural-plate','neural-tube','notochord','somites'],
    ['The ectodermal neural plate folds and closes into the neural tube; the tube develops into the brain and spinal cord.',
      'A mesoderm-derived notochord runs beneath the tube, while paired mesodermal somites form alongside it.'],
    ['In a transverse view of the early embryo, look from dorsal toward ventral for neural tube above notochord; somites lie to either side.'],
    ['Somites contribute axial skeleton, skeletal muscle, and dermis. This is a broad origin map, not a list of every adult derivative.'],
    ['The neural tube is ectodermal, not mesodermal.', 'Somites are alongside the neural tube; they are not its hollow center.']),
  lesson('folding', 'From flat disc to body form',
    'Relate head-tail and side-to-side folding to the early body wall and gut tube.',
    ['embryonic-folding','primitive-gut','endoderm','amnion'],
    ['Folding changes a relatively flat embryonic disc into a more cylindrical body with head and tail ends.',
      'Part of the endoderm-lined yolk-sac region is enclosed as the primitive gut; the amnion comes to surround the folded embryo.'],
    ['The primitive gut lies inside the folded body and is lined by endoderm; the umbilical connection projects at the ventral side.'],
    ['This is a change in body geometry after germ-layer formation, not the creation of a fourth germ layer.'],
    ['Folding is not gastrulation.', 'The primitive gut is an early tube, not a fully formed stomach or intestine.']),
  lesson('placental-interface', 'Placenta and umbilical connection',
    'Distinguish fetal placental tissues, maternal uterine tissue, and the cord that connects the fetus to the placenta.',
    ['trophoblast','chorion','chorionic-villi','placenta','umbilical-cord'],
    ['Chorionic villi on the fetal side interface with maternal endometrial tissue to form the placenta.',
      'The umbilical cord connects the fetus to the placenta: two umbilical arteries carry fetal blood toward it; one umbilical vein returns blood to the fetus.'],
    ['The placenta attaches at the uterine wall; the cord runs between placenta and developing fetus, not directly into the maternal circulation.'],
    ['The placenta supports exchange of gases, nutrients, and wastes across the maternal-fetal interface; fetal and maternal blood travel in distinct vessels.'],
    ['An umbilical vein returns blood to the fetus despite the usual adult oxygenation mnemonic.', 'The cord is the connection, not the whole placenta.']),
];

const choice = (name: string, terms: string[], prompt: string, answer: string, options: string[], explanation: string): Question => ({
  id: `q-bac02-${name}`, moduleId, structureIds: terms.map(id), taskType: 'multiple-choice',
  prompt, answer, options, acceptedAliases: [], explanation, sourceId: OPENSTAX_SOURCE_ID,
  sourcePage: null, examPriority: true, verificationStatus: 'verified',
});
const order = (name: string, terms: string[], prompt: string, answer: string[], options: string[], explanation: string): Question => ({
  ...choice(name, terms, prompt, answer[0], options, explanation), taskType: 'ordered-sequence', answer,
});
const recall = (name: string, terms: string[], prompt: string, answer: string, acceptedAliases: string[], explanation: string): Question => ({
  ...choice(name, terms, prompt, answer, [], explanation), taskType: 'typed-recall', options: undefined, acceptedAliases,
});

export const foundationsDevelopmentQuestions: Question[] = [
  order('early-sequence', ['fertilization','zygote','cleavage','morula','blastocyst','implantation'],
    'Order these milestones from the joining of gametes to attachment in the uterus.',
    ['Fertilization','Zygote','Cleavage','Morula','Blastocyst','Implantation'],
    ['Blastocyst','Implantation','Cleavage','Zygote','Morula','Fertilization'],
    'Fertilization forms a zygote, then cleavage produces a morula, which becomes a blastocyst before implantation.'),
  choice('tube-to-uterus', ['fertilization','cleavage','implantation'],
    'Which route best connects the usual site of fertilization to the site of implantation?',
    'Uterine tube to uterine endometrium', ['Uterine tube to uterine endometrium','Uterine endometrium to uterine tube','Ovary to urinary bladder','Cervix to ovary'],
    'Fertilization normally occurs in a uterine tube; the dividing conceptus reaches the uterus and implants in its lining.'),
  choice('cleavage-size', ['cleavage','blastomere'],
    'During early cleavage, what happens to the conceptus?', 'Cell number rises with little overall size increase',
    ['Cell number rises with little overall size increase','One cell enlarges without dividing','Three germ layers appear immediately','The placenta is fully formed'],
    'Rapid divisions subdivide the original cytoplasm among smaller blastomeres.'),
  choice('morula-vs-blastocyst', ['morula','blastocyst','blastocoel'],
    'A fluid-filled internal cavity distinguishes which stage from a compact morula?',
    'Blastocyst', ['Blastocyst','Zygote','Somite','Neural plate'],
    'The blastocoel appears as the morula becomes a blastocyst.'),
  choice('inner-outer', ['inner-cell-mass','trophoblast','blastocyst'],
    'Which part of a blastocyst primarily gives rise to the embryo itself?',
    'Inner cell mass', ['Inner cell mass','Trophoblast','Blastocoel','Endometrium'],
    'The inner cell mass forms the embryo; outer trophoblast contributes to fetal placental tissues.'),
  choice('attachment-layer', ['implantation','trophoblast'],
    'Which blastocyst compartment attaches to the uterine lining during implantation?',
    'Trophoblast', ['Trophoblast','Blastocoel','Neural tube','Somite'],
    'The outer trophoblast attaches and embeds the blastocyst in the endometrium.'),
  choice('implant-site', ['implantation'],
    'A blastocyst implants in which uterine tissue, not in the tube where fertilization usually occurred?',
    'Endometrium', ['Endometrium','Myometrium','Ovarian cortex','Uterine tube wall'],
    'The endometrium is the uterine lining; the myometrium is its muscular wall.'),
  order('layers-outside-in', ['ectoderm','mesoderm','endoderm'],
    'Order the three embryonic germ layers from outer to inner in the early disc.',
    ['Ectoderm','Mesoderm','Endoderm'], ['Endoderm','Ectoderm','Mesoderm'],
    'Ectoderm is outer, mesoderm middle, and endoderm inner in the early three-layer disc.'),
  choice('gastrulation-result', ['gastrulation','primitive-streak'],
    'What major anatomical change results from cell movement through the primitive streak?',
    'Formation of three embryonic germ layers',
    ['Formation of three embryonic germ layers','Formation of a mature placenta','Formation of a hollow blastocyst','Closure of the neural tube'],
    'Gastrulation converts the early disc into ectoderm, mesoderm, and endoderm.'),
  choice('ectoderm-derivative', ['ectoderm'],
    'Which pairing fits a broad ectodermal derivative map?', 'Epidermis and nervous tissue',
    ['Epidermis and nervous tissue','Kidneys and skeletal muscle','Gut epithelial lining and liver epithelium','Heart muscle and blood vessels'],
    'Ectoderm contributes epidermis and central/peripheral nervous tissue.'),
  choice('mesoderm-derivative', ['mesoderm','somites'],
    'Somites arise from mesoderm. Which later structures do they help form?',
    'Axial skeleton, skeletal muscle, and dermis',
    ['Axial skeleton, skeletal muscle, and dermis','Epidermis and neural tube','Gut epithelium and liver epithelium','Trophoblast and blastocoel'],
    'Mesodermal somites contribute axial skeleton, skeletal muscle, and dermis.'),
  choice('endoderm-derivative', ['endoderm','primitive-gut'],
    'Which adult tissue is most directly linked to the endodermal lining of the primitive gut?',
    'Digestive-tract epithelium',
    ['Digestive-tract epithelium','Skin epidermis','Skeletal muscle','Spinal cord'],
    'Endoderm forms the digestive tract epithelial lining; surrounding muscle and connective tissues have other origins.'),
  choice('mixed-origin', ['endoderm','mesoderm'],
    'Why is “the whole intestine is endodermal” too broad?',
    'Its lining is endodermal, while muscle and connective tissues include mesodermal contributions',
    ['Its lining is endodermal, while muscle and connective tissues include mesodermal contributions','Every layer arises from ectoderm','Gastrulation occurs only after birth','The intestine is an extraembryonic membrane'],
    'Germ layers describe tissue lineages, not a single exclusive label for every tissue of a complex organ.'),
  order('neural-sequence', ['neural-plate','neurulation','neural-tube'],
    'Order these neural-development descriptions from first to last.',
    ['Ectodermal neural plate','Neural folds converge','Neural tube forms'],
    ['Neural tube forms','Ectodermal neural plate','Neural folds converge'],
    'The ectodermal plate folds; its edges converge into a neural tube.'),
  choice('neural-tube-outcome', ['neural-tube','ectoderm'],
    'Which major structures develop from the neural tube?',
    'Brain and spinal cord', ['Brain and spinal cord','Placenta and umbilical cord','Gut lining and liver epithelium','Kidneys and axial skeleton'],
    'The neural tube is an ectodermal precursor of the central nervous system.'),
  choice('axis-spatial', ['neural-tube','notochord','somites'],
    'In an early embryonic cross-section, where are the somites relative to the neural tube?',
    'Paired along its sides', ['Paired along its sides','Inside its lumen','Within the blastocoel','Only within the placenta'],
    'Mesodermal somites lie on either side of the dorsal neural tube; the notochord lies beneath it.'),
  choice('folding-gut', ['embryonic-folding','primitive-gut','endoderm'],
    'What body-form change accompanies embryonic folding?',
    'Part of an endoderm-lined sheet becomes an internal primitive gut tube',
    ['Part of an endoderm-lined sheet becomes an internal primitive gut tube','The morula gains its blastocoel','All three germ layers merge into one','The placenta becomes the spinal cord'],
    'Head-tail and lateral folding internalize a portion of endoderm as the primitive gut.'),
  choice('folding-amnion', ['embryonic-folding','amnion'],
    'As the flat disc folds into a more cylindrical embryo, which membrane comes to surround it?',
    'Amnion', ['Amnion','Endometrium','Notochord','Neural plate'],
    'The amniotic membrane comes to envelop the embryo during folding.'),
  choice('placental-sides', ['chorion','chorionic-villi','placenta'],
    'Which tissues meet at the placental exchange interface?',
    'Fetal chorionic villi and maternal endometrial tissue',
    ['Fetal chorionic villi and maternal endometrial tissue','Two fetal neural tubes','Uterine muscle and lung pleura','Ovary and blastocoel'],
    'Fetal chorionic villi interact with maternal uterine-lining tissue at the placenta.'),
  choice('cord-route', ['umbilical-cord','placenta'],
    'Which route correctly traces the fetal umbilical vessels?',
    'Two arteries go to the placenta; one vein returns to the fetus',
    ['Two arteries go to the placenta; one vein returns to the fetus','Two veins go to the placenta; one artery returns','All three vessels bring maternal blood directly into the fetus','The cord connects fetal brain to spinal cord'],
    'Umbilical arteries carry fetal blood toward the placenta; the single vein returns blood toward the fetus.'),
  recall('blastocyst-stage', ['morula','blastocyst'],
    'What is the hollow stage that follows the solid morula and precedes implantation?',
    'Blastocyst', ['blastocyst stage'], 'A blastocyst contains a blastocoel and has inner and outer cell populations.'),
  recall('neural-tube-process', ['neurulation','neural-plate'],
    'Name the process in which the ectodermal neural plate folds toward a neural tube.',
    'Neurulation', ['neural tube formation'], 'Neurulation forms the early central nervous system tube from ectoderm.'),
  recall('placental-projections', ['chorionic-villi','chorion'],
    'What are the fetal chorion’s projections at the placental interface called?',
    'Chorionic villi', ['chorionic villus'], 'Chorionic villi project into the maternal uterine lining and contribute to the fetal placental portion.'),
];