import type { Lesson, Question, Structure } from './model';
import { OPENSTAX_SOURCE_ID } from './anatomy.ts';

const moduleId = 'anatomy-foundations';
// Terms and relationships checked against OpenStax Anatomy and Physiology (2013),
// §§1.2 and 1.6. These are original summaries, not copied textbook passages.
const rows: Array<[string, string, string, string[]]> = [
  ['anatomical-position', 'Anatomical position', 'reference position', ['standard anatomical position']],
  ['superior', 'Superior', 'direction', ['cranial', 'above']],
  ['inferior', 'Inferior', 'direction', ['caudal', 'below']],
  ['anterior', 'Anterior', 'direction', ['ventral', 'front']],
  ['posterior', 'Posterior', 'direction', ['dorsal', 'back']],
  ['medial', 'Medial', 'direction', ['toward the midline']],
  ['lateral', 'Lateral', 'direction', ['away from the midline']],
  ['proximal', 'Proximal', 'direction', ['nearer the limb attachment']],
  ['distal', 'Distal', 'direction', ['farther from the limb attachment']],
  ['superficial', 'Superficial', 'direction', ['toward the body surface']],
  ['deep', 'Deep', 'direction', ['away from the body surface']],
  ['midsagittal-plane', 'Midsagittal plane', 'section', ['median plane']],
  ['oblique-section', 'Oblique section', 'section', ['oblique plane']],
  ['cephalic-region', 'Cephalic region', 'body region', ['head region']],
  ['cervical-region', 'Cervical region', 'body region', ['neck region']],
  ['thoracic-region', 'Thoracic region', 'body region', ['chest region']],
  ['abdominal-region', 'Abdominal region', 'body region', ['abdomen']],
  ['pelvic-region', 'Pelvic region', 'body region', ['pelvis region']],
  ['brachial-region', 'Brachial region', 'body region', ['upper arm region']],
  ['antebrachial-region', 'Antebrachial region', 'body region', ['forearm region']],
  ['carpal-region', 'Carpal region', 'body region', ['wrist region']],
  ['femoral-region', 'Femoral region', 'body region', ['thigh region']],
  ['crural-region', 'Crural region', 'body region', ['leg region', 'lower leg region']],
  ['patellar-region', 'Patellar region', 'body region', ['front of knee']],
  ['popliteal-region', 'Popliteal region', 'body region', ['back of knee']],
  ['axillary-region', 'Axillary region', 'body region', ['armpit']],
  ['inguinal-region', 'Inguinal region', 'body region', ['groin']],
  ['umbilical-landmark', 'Umbilicus', 'surface landmark', ['navel', 'belly button']],
  ['sternal-landmark', 'Sternal region', 'surface landmark', ['breastbone region']],
  ['dorsal-cavity', 'Dorsal body cavity', 'body cavity', ['posterior body cavity']],
  ['ventral-cavity', 'Ventral body cavity', 'body cavity', ['anterior body cavity']],
  ['abdominopelvic-cavity', 'Abdominopelvic cavity', 'body cavity', ['abdominal and pelvic cavities']],
  ['pleural-cavity', 'Pleural cavity', 'body cavity', ['pleural space']],
  ['mediastinum', 'Mediastinum', 'thoracic compartment', ['central thoracic compartment']],
  ['visceral-pleura', 'Visceral pleura', 'serous membrane', ['lung-surface pleura']],
  ['parietal-pleura', 'Parietal pleura', 'serous membrane', ['chest-wall pleura']],
  ['visceral-pericardium', 'Visceral pericardium', 'serous membrane', ['epicardium']],
  ['parietal-pericardium', 'Parietal pericardium', 'serous membrane', []],
  ['visceral-peritoneum', 'Visceral peritoneum', 'serous membrane', ['organ-surface peritoneum']],
  ['parietal-peritoneum', 'Parietal peritoneum', 'serous membrane', ['abdominal-wall peritoneum']],
  ['peritoneal-cavity', 'Peritoneal cavity', 'serous space', ['peritoneal space']],
  ['retroperitoneal-region', 'Retroperitoneal region', 'anatomical relationship', ['behind the parietal peritoneum']],
  ['right-upper-quadrant', 'Right upper quadrant', 'abdominal quadrant', ['RUQ']],
  ['left-upper-quadrant', 'Left upper quadrant', 'abdominal quadrant', ['LUQ']],
  ['right-lower-quadrant', 'Right lower quadrant', 'abdominal quadrant', ['RLQ']],
  ['left-lower-quadrant', 'Left lower quadrant', 'abdominal quadrant', ['LLQ']],
  ['right-hypochondriac-region', 'Right hypochondriac region', 'abdominal region', []],
  ['epigastric-region', 'Epigastric region', 'abdominal region', []],
  ['left-hypochondriac-region', 'Left hypochondriac region', 'abdominal region', []],
  ['right-lumbar-region', 'Right lumbar region', 'abdominal region', ['right lateral abdominal region']],
  ['umbilical-region', 'Umbilical region', 'abdominal region', ['central abdominal region']],
  ['left-lumbar-region', 'Left lumbar region', 'abdominal region', ['left lateral abdominal region']],
  ['right-iliac-region', 'Right iliac region', 'abdominal region', ['right inguinal abdominal region']],
  ['hypogastric-region', 'Hypogastric region', 'abdominal region', ['pubic region']],
  ['left-iliac-region', 'Left iliac region', 'abdominal region', ['left inguinal abdominal region']],
  ['tissue-level', 'Tissue', 'structural organization', ['tissue level']],
  ['organ-level', 'Organ', 'structural organization', ['organ level']],
  ['organ-system-level', 'Organ system', 'structural organization', ['organ system level']],
];

export const foundationsOrientationStructures: Structure[] = rows.map(([id, canonicalName, category, acceptedAliases]) => ({
  id, canonicalName, category, acceptedAliases, moduleId,
  sourceId: OPENSTAX_SOURCE_ID, sourcePage: null, examPriority: true, verificationStatus: 'verified',
}));

const lesson = (
  id: string, title: string, summary: string, structureIds: string[],
  recognitionCues: string[], landmarks: string[], relationships: string[], commonConfusions: string[],
  assetIds: string[] = [],
): Lesson => ({ id, title, summary, structureIds, recognitionCues, landmarks, relationships, commonConfusions,
  sourceIds: [OPENSTAX_SOURCE_ID], assetIds });

export const foundationsOrientationLessons: Lesson[] = [
  lesson('foundations-position-directions', 'Position and directions',
    'Describe one structure relative to another from anatomical position, regardless of how a person is lying or standing now.',
    ['anatomical-position','superior','inferior','anterior','posterior','medial','lateral','proximal','distal','superficial','deep'],
    ['Stand upright, face forward, arms at the sides with palms facing forward: the thumbs point laterally.',
      'Pair each term with a reference: the wrist is distal to the elbow; skin is superficial to muscle.'],
    ['The sternum is anterior to the heart; the vertebral column is posterior to it.',
      'The nose is medial to the eyes, and the knee is proximal to the ankle.'],
    ['Left and right refer to the person being described, not the observer. Proximal and distal track along a limb from its attachment.'],
    ['Anterior and posterior do not swap when the person turns over.', 'Superficial/deep describe depth, not superior/inferior.']),
  lesson('foundations-planes-sections', 'Planes and sections',
    'Read a slice by the direction it divides the body; a section is a cut made along a plane.',
    ['sagittal-plane','midsagittal-plane','coronal-plane','transverse-plane','oblique-section'],
    ['Sagittal divides left from right; midsagittal passes through the midline into equal halves.',
      'Coronal separates front and back; transverse (axial) separates upper and lower portions.'],
    ['A lengthwise midline cut through the nose and sternum is midsagittal. A horizontal slice through the abdomen is transverse.'],
    ['Oblique sections cross the standard planes at an angle; images and specimens may show either a cut surface or a projection.'],
    ['Any sagittal slice need not make equal halves.', 'A transverse slice is not a coronal front-to-back division.'],
    ['asset-original-anatomical-planes']),
  lesson('foundations-surface-regions', 'Body regions and surface landmarks',
    'Name a location on the body surface precisely before looking for deeper structures.',
    ['cephalic-region','cervical-region','thoracic-region','abdominal-region','pelvic-region',
      'brachial-region','antebrachial-region','carpal-region','femoral-region','crural-region',
      'patellar-region','popliteal-region','axillary-region','inguinal-region','umbilical-landmark',
      'sternal-landmark'],
    ['Brachial is upper arm; antebrachial is forearm; carpal is wrist. Femoral is thigh; crural is the leg between knee and ankle.',
      'Patellar names the front of the knee; popliteal names its back. Axillary is armpit; inguinal is groin.'],
    ['The umbilicus is a central abdominal landmark; the sternal region marks the midline chest.',
      'The iliac crest is the palpable upper rim of the hip bone, lateral to the lower abdomen.'],
    ['Regional names locate a surface finding; they do not identify the organ beneath it by themselves.'],
    ['Anatomical “leg” does not include the thigh.', 'The umbilical landmark is a point; the umbilical abdominal region covers a wider area.']),
  lesson('foundations-body-cavities', 'Dorsal and ventral cavities',
    'Trace the major protected spaces and their subdivisions without confusing an organ with the space containing it.',
    ['dorsal-cavity','cranial-cavity','vertebral-cavity','ventral-cavity','thoracic-cavity','pleural-cavity',
      'mediastinum','abdominopelvic-cavity','abdominal-cavity','pelvic-cavity'],
    ['Dorsal contains cranial (brain) and vertebral (spinal cord) spaces; ventral contains thoracic and abdominopelvic spaces.',
      'The diaphragm separates the thoracic space from the abdominal portion of the abdominopelvic cavity.'],
    ['Pleural cavities surround the lungs; the mediastinum is the central thoracic compartment between them.',
      'The heart lies in the mediastinum; the small pericardial cavity is between its serous membrane layers.'],
    ['The abdominal and pelvic cavities are continuous subdivisions of the abdominopelvic cavity.'],
    ['A lung is not the pleural cavity around it.', 'The pericardial cavity is a narrow potential space, not the entire mediastinum.'],
    ['asset-original-body-cavities']),
  lesson('foundations-serous-membranes', 'Organ surfaces and serous membranes',
    'Distinguish the organ, the membrane on it, the lining of its compartment, and the thin space between the layers.',
    ['visceral-pleura','parietal-pleura','pleural-cavity','visceral-pericardium','parietal-pericardium',
      'visceral-peritoneum','parietal-peritoneum','peritoneal-cavity','retroperitoneal-region'],
    ['Visceral names a serous layer on an organ; parietal names the layer lining the body wall or compartment.',
      'Pleura belongs to the lungs; serous pericardium to the heart; peritoneum to abdominopelvic organs and wall.'],
    ['The pleural cavity is the thin space between pleural layers, not lung tissue.',
      'Kidneys are retroperitoneal: posterior to the parietal peritoneum rather than suspended within the peritoneal cavity.'],
    ['Serous fluid between layers permits movement; the cavity, its lining, and the organ surface are different anatomical referents.'],
    ['Do not call the entire abdominal cavity the peritoneal cavity.', 'Visceral pleura covers the lung; parietal pleura lines the thoracic wall.']),
  lesson('foundations-abdomen-map', 'Quadrants and nine regions',
    'Use the patient’s right and left to describe an abdominopelvic location; quadrants and the nine-region grid are alternative maps.',
    ['right-upper-quadrant','left-upper-quadrant','right-lower-quadrant','left-lower-quadrant',
      'right-hypochondriac-region','epigastric-region','left-hypochondriac-region',
      'right-lumbar-region','umbilical-region','left-lumbar-region',
      'right-iliac-region','hypogastric-region','left-iliac-region'],
    ['Four quadrants divide at vertical and horizontal lines through the umbilical area.',
      'The nine regions run right hypochondriac–epigastric–left hypochondriac; right lumbar–umbilical–left lumbar; right iliac–hypogastric–left iliac.'],
    ['Much of the liver lies in the right upper quadrant; the stomach is usually in the left upper quadrant.',
      'The umbilical region is central; the hypogastric region is inferior to it.'],
    ['Quadrants and regions are surface maps of location, not borders around individual organs; organs can cross their boundaries.'],
    ['Right and left refer to the patient.', 'Right iliac region is not identical to the whole right lower quadrant.']),
  lesson('foundations-imaging-sections', 'Orientation in sections and imaging',
    'Use planes, depth, and patient-side labels to orient a cross-section before naming structures.',
    ['transverse-plane','coronal-plane','sagittal-plane','anterior','posterior','medial','lateral','superficial','deep'],
    ['In a transverse section, first find the anterior and posterior sides and the midline; then orient left and right using the image labels.',
      'A coronal section shows left/right and superior/inferior levels; a sagittal section shows anterior/posterior and superior/inferior levels.'],
    ['In the usual radiologic axial display, viewed as if from the feet, the patient’s right appears on the image’s left. Confirm labels rather than assuming every diagram follows that convention.'],
    ['Slices at different levels show different structures; a single section does not represent an entire organ.'],
    ['Screen left does not always mean patient left.', 'An axial image is a transverse section, not a view of the whole body.']),
  lesson('foundations-organization', 'From tissues to organ systems',
    'Recognize how tissues form organs and how organs cooperate in systems without treating the categories as exclusive.',
    ['tissue-level','organ-level','organ-system-level','heart','lungs','kidneys','pancreas','spleen'],
    ['A tissue is a group of related cells; an organ includes multiple tissue types; an organ system includes cooperating organs.',
      'Place the heart with cardiovascular structures, lungs with respiratory structures, and kidneys with urinary structures.'],
    ['The spleen is a lymphatic organ in the upper left abdomen; it is not a digestive organ.'],
    ['The pancreas contributes to both digestive and endocrine systems; an organ can participate in more than one system.'],
    ['A gland is an organ or part of an organ, not a separate level above an organ system.', 'An organ’s location alone does not determine its system.']),
];

const choice = (id: string, structureIds: string[], prompt: string, answer: string, options: string[], explanation: string): Question => ({
  id: `q-bac01-${id}`, moduleId, structureIds, taskType: 'multiple-choice', prompt, answer, options,
  acceptedAliases: [], explanation, sourceId: OPENSTAX_SOURCE_ID, sourcePage: null,
  examPriority: true, verificationStatus: 'verified',
});
const order = (id: string, structureIds: string[], prompt: string, answer: string[], options: string[], explanation: string): Question => ({
  ...choice(id, structureIds, prompt, answer[0], options, explanation), taskType: 'ordered-sequence', answer,
});
const recall = (id: string, structureIds: string[], prompt: string, answer: string, acceptedAliases: string[], explanation: string): Question => ({
  ...choice(id, structureIds, prompt, answer, [], explanation), taskType: 'typed-recall', acceptedAliases, options: undefined,
});

export const foundationsOrientationQuestions: Question[] = [
  choice('position', ['anatomical-position'], 'A person is lying face down. Which reference still governs anatomical direction words?', 'Standing upright with palms forward', ['Standing upright with palms forward','The person’s current pose','The observer facing the patient','Hands rotated palms backward'], 'Anatomical directions use the standard upright, forward-facing position regardless of the current pose.'),
  choice('patient-right', ['anatomical-position','lateral'], 'You face a patient. Which side is their anatomical right?', 'The patient’s own right, not yours', ['The patient’s own right, not yours','The side on your right','Whichever side is closest','The posterior side'], 'Anatomical left and right always belong to the body being described.'),
  choice('superior', ['superior','inferior'], 'The nose is above the mouth in anatomical position. The nose is…', 'Superior to the mouth', ['Superior to the mouth','Inferior to the mouth','Distal to the mouth','Deep to the mouth'], 'Superior means toward the head relative to another structure.'),
  choice('posterior', ['anterior','posterior'], 'The vertebral column lies behind the sternum. Which description is correct?', 'Vertebral column is posterior to sternum', ['Vertebral column is posterior to sternum','Vertebral column is anterior to sternum','Both are superficial to skin','Sternum is lateral to vertebral column'], 'Posterior names a position toward the back even when the person turns.'),
  choice('medial', ['medial','lateral'], 'Relative to the ears, the nose is…', 'Medial', ['Medial','Lateral','Distal','Inferior'], 'The nose is closer to the body midline.'),
  choice('distal', ['proximal','distal'], 'Relative to the elbow, the wrist is…', 'Distal', ['Distal','Proximal','Medial','Deep'], 'The wrist is farther along the limb from its trunk attachment.'),
  choice('deep', ['superficial','deep'], 'Relative to skin, skeletal muscle is generally…', 'Deep', ['Deep','Superficial','Superior','Distal'], 'Deep means farther from the body surface.'),
  choice('midline-section', ['sagittal-plane','midsagittal-plane'], 'A vertical section through the exact midline creates equal left and right halves. Name the plane.', 'Midsagittal plane', ['Midsagittal plane','Any parasagittal plane','Coronal plane','Transverse plane'], 'A midsagittal section is a sagittal cut through the midline; not every sagittal cut is midsagittal.'),
  choice('coronal', ['coronal-plane'], 'Which plane separates anterior from posterior portions?', 'Coronal plane', ['Coronal plane','Transverse plane','Midsagittal plane','Oblique horizontal plane'], 'The coronal (frontal) plane divides front and back.'),
  choice('axial', ['transverse-plane'], 'A horizontal abdominal section separates which portions?', 'Superior and inferior', ['Superior and inferior','Anterior and posterior','Equal left and right','Superficial and deep only'], 'A transverse or axial section separates upper and lower portions.'),
  choice('oblique', ['oblique-section'], 'A section angled across the standard planes is…', 'Oblique', ['Oblique','Midsagittal','Transverse by definition','Coronal by definition'], 'Oblique sections pass at an angle to the main anatomical planes.'),
  choice('forearm-region', ['brachial-region','antebrachial-region'], 'A mark between the elbow and wrist is in which region?', 'Antebrachial', ['Antebrachial','Brachial','Femoral','Carpal'], 'Antebrachial is the forearm; brachial is the upper arm.'),
  choice('knee-back', ['patellar-region','popliteal-region'], 'Which region names the back of the knee?', 'Popliteal', ['Popliteal','Patellar','Crural','Femoral'], 'Popliteal is posterior to the knee; patellar is anterior.'),
  choice('groin', ['inguinal-region','axillary-region'], 'Which term locates the groin, not the armpit?', 'Inguinal', ['Inguinal','Axillary','Cervical','Carpal'], 'Inguinal describes the groin; axillary describes the armpit.'),
  choice('navel', ['umbilical-landmark','umbilical-region'], 'Which is a point landmark rather than a broad abdominal area?', 'Umbilicus', ['Umbilicus','Umbilical region','Abdominal cavity','Pelvic cavity'], 'The umbilicus is a surface landmark; the umbilical region covers a larger central area.'),
  choice('dorsal', ['dorsal-cavity','cranial-cavity','vertebral-cavity'], 'The cranial and vertebral cavities belong to which major compartment?', 'Dorsal body cavity', ['Dorsal body cavity','Ventral body cavity','Thoracic cavity','Abdominal cavity'], 'The dorsal cavity includes cranial and vertebral subdivisions.'),
  choice('thorax', ['ventral-cavity','thoracic-cavity','abdominopelvic-cavity'], 'The diaphragm separates which ventral compartments?', 'Thoracic and abdominal portions', ['Thoracic and abdominal portions','Cranial and vertebral cavities','Left and right pleural cavities','Abdominal and pelvic portions'], 'The diaphragm lies between the thoracic and abdominal portions of the ventral cavity.'),
  choice('mediastinum', ['mediastinum','pleural-cavity','heart'], 'Where is the heart relative to the two pleural cavities?', 'In the mediastinum between them', ['In the mediastinum between them','Inside a pleural cavity','Inside the cranial cavity','Posterior to the vertebral cavity'], 'The heart lies in the central thoracic mediastinum, between the pleural cavities.'),
  choice('pleural-space', ['pleural-cavity','visceral-pleura','parietal-pleura'], 'Which term names the thin space between the lung-surface and wall-lining pleural layers?', 'Pleural cavity', ['Pleural cavity','Lung parenchyma','Visceral pleura','Mediastinum'], 'The pleural cavity is between the visceral and parietal pleura; neither layer is the space.'),
  choice('lung-surface', ['visceral-pleura','parietal-pleura'], 'Which serous layer directly covers the lung surface?', 'Visceral pleura', ['Visceral pleura','Parietal pleura','Peritoneum','Fibrous pericardium'], 'Visceral pleura is on the lung; parietal pleura lines the compartment.'),
  choice('heart-space', ['visceral-pericardium','parietal-pericardium'], 'Which term describes the narrow space between the two serous pericardial layers?', 'Pericardial cavity', ['Pericardial cavity','Heart muscle','Entire mediastinum','Pleural cavity'], 'The pericardial cavity is a potential space between visceral and parietal serous pericardium.'),
  choice('peritoneum', ['visceral-peritoneum','parietal-peritoneum','peritoneal-cavity'], 'Which layer lines the inner abdominopelvic wall?', 'Parietal peritoneum', ['Parietal peritoneum','Visceral peritoneum','Lung pleura','Pericardial cavity'], 'Parietal peritoneum lines the wall; visceral peritoneum covers the organs it invests.'),
  choice('retroperitoneal', ['retroperitoneal-region','kidneys'], 'Where are the kidneys in relation to the parietal peritoneum?', 'Posterior to it (retroperitoneal)', ['Posterior to it (retroperitoneal)','Inside the pleural cavity','Inside the pericardial cavity','Floating within the peritoneal cavity'], 'The kidneys lie posterior to the parietal peritoneum.'),
  choice('liver-quadrant', ['right-upper-quadrant','liver'], 'Most of the liver is in which quadrant (using the patient’s sides)?', 'Right upper quadrant', ['Right upper quadrant','Left upper quadrant','Right lower quadrant','Left lower quadrant'], 'Most liver tissue is in the patient’s right upper quadrant, although organs may cross quadrant lines.'),
  choice('stomach-quadrant', ['left-upper-quadrant','stomach'], 'The stomach is usually associated with which quadrant?', 'Left upper quadrant', ['Left upper quadrant','Right upper quadrant','Left lower quadrant','Right lower quadrant'], 'The stomach is mainly in the left upper quadrant; a quadrant is a location map, not an organ boundary.'),
  choice('central-region', ['umbilical-region','hypogastric-region','epigastric-region'], 'In the nine-region map, what is the central middle region?', 'Umbilical region', ['Umbilical region','Epigastric region','Hypogastric region','Right lumbar region'], 'The umbilical region occupies the center of the middle row.'),
  order('nine-regions', ['right-hypochondriac-region','epigastric-region','left-hypochondriac-region'], 'Order the top row of nine abdominal regions from the patient’s right to left.', ['Right hypochondriac','Epigastric','Left hypochondriac'], ['Left hypochondriac','Right hypochondriac','Epigastric'], 'The nine-region map is named from the patient’s right to left.'),
  choice('axial-view', ['transverse-plane','anatomical-position'], 'On a standard radiologic axial display viewed from the feet, the patient’s right appears where?', 'On the viewer’s left', ['On the viewer’s left','On the viewer’s right','Always at the top','Only on sagittal images'], 'In the usual radiologic axial convention, patient right is image left. Check labels because diagrams can use other conventions.'),
  choice('section-depth', ['superficial','deep','transverse-plane'], 'On a labeled cross-section, which relationship helps distinguish skin from underlying muscle?', 'Skin is superficial to muscle', ['Skin is superficial to muscle','Skin is deep to muscle','Skin is distal to muscle','Skin is medial to every muscle'], 'Superficial and deep describe depth relative to the body surface in sections too.'),
  choice('system-level', ['tissue-level','organ-level','organ-system-level'], 'Several tissue types form an anatomically distinct heart. What level is the heart?', 'Organ', ['Organ','Tissue','Single cell','Entire organ system'], 'An organ contains multiple tissue types; organs cooperate within organ systems.'),
  choice('pancreas-systems', ['organ-system-level','pancreas'], 'Why is it misleading to give the pancreas only one system label?', 'It participates in digestive and endocrine systems', ['It participates in digestive and endocrine systems','It is a body cavity','It belongs only to the nervous system','It is a tissue rather than an organ'], 'An organ may contribute to more than one system; the pancreas has digestive and endocrine roles.'),
  order('nine-regions-middle', ['right-lumbar-region','umbilical-region','left-lumbar-region'], 'Order the middle row of the nine-region map from the patient’s right to left.', ['Right lumbar','Umbilical','Left lumbar'], ['Left lumbar','Umbilical','Right lumbar'], 'Right and left follow the patient, with the umbilical region in the center.'),
  order('nine-regions-lower', ['right-iliac-region','hypogastric-region','left-iliac-region'], 'Order the lower row of the nine-region map from the patient’s right to left.', ['Right iliac','Hypogastric','Left iliac'], ['Hypogastric','Left iliac','Right iliac'], 'The hypogastric region is central between the iliac regions.'),
  recall('unequal-sides', ['sagittal-plane','midsagittal-plane'], 'What plane divides left and right portions without necessarily making equal halves?', 'Sagittal plane', ['sagittal'], 'Only the midline sagittal plane divides the body into equal left and right halves.'),
  recall('spinal-space', ['vertebral-cavity','dorsal-cavity'], 'What cavity encloses the spinal cord within the dorsal body cavity?', 'Vertebral cavity', ['spinal cavity'], 'The vertebral cavity is the spinal subdivision of the dorsal body cavity.'),
  recall('lower-leg', ['crural-region'], 'What anatomical region names the lower limb between the knee and ankle?', 'Crural region', ['crural'], 'The femoral region is the thigh; the crural region is the leg below the knee.'),
  recall('heart-cover', ['visceral-pericardium','parietal-pericardium'], 'Which serous pericardial layer is directly on the heart surface?', 'Visceral pericardium', ['epicardium'], 'The visceral serous pericardium (epicardium) covers the heart surface; the parietal layer lies outward.'),
  recall('above-navel', ['epigastric-region','umbilical-region'], 'Which central abdominal region is directly superior to the umbilical region?', 'Epigastric region', ['epigastric'], 'The epigastric region is the upper central square of the nine-region map.'),
];