/**
 * The one static asset registry used by both Expo screens.
 *
 * Keep these as static require calls: Metro cannot discover a dynamically
 * constructed require path in a production bundle. The IDs intentionally
 * mirror content.Asset.id, so a published asset can never silently render as
 * an empty image.
 */
import { bvis04ImageSources } from './bvis04-image-sources.generated';
import { bvis05ImageSources } from './bvis05-image-sources.generated';
import { bvis06ImageSources } from './bvis06-image-sources.generated';
export const imageSources: Record<string, number> = {
  'asset-skull-front': require('@/assets/images/anatomy/skeletal-atlas/skeletal-atlas-01-skull-anterior.png'),
  'asset-skull-lateral': require('@/assets/images/anatomy/skeletal-atlas/skeletal-atlas-02-skull-lateral.png'),
  'asset-vertebral-column': require('@/assets/images/anatomy/gray111-vertebral-column.png'),
  'asset-cervical-vertebra': require('@/assets/images/anatomy/skeletal-atlas/skeletal-atlas-07-vertebrae-regional.png'),
  'asset-gray946-sweat-gland': require('@/assets/images/anatomy/gray946-sweat-gland.png'),
  'asset-gray880-optic-nerve-head': require('@/assets/images/anatomy/gray880-optic-nerve-head.png'),
  'asset-gray491-heart-posterior': require('@/assets/images/anatomy/gray491-heart-posterior.png'),
  'asset-gray1121-posterior-abdominal-wall': require('@/assets/images/anatomy/gray1121-posterior-abdominal-wall.png'),
  'asset-commons-axial-skeleton-blank': require('@/assets/images/anatomy/commons-axial-skeleton-blank.png'),
  'asset-commons-appendicular-skeleton-blank': require('@/assets/images/anatomy/commons-appendicular-skeleton-blank.png'),
  'asset-openstax-spinal-cord-specimen': require('@/assets/images/anatomy/openstax-spinal-cord-specimen.jpg'),
  'asset-commons-simple-squamous-epithelium': require('@/assets/images/anatomy/commons-simple-squamous-epithelium.jpg'),
  'asset-commons-simple-cuboidal-epithelium': require('@/assets/images/anatomy/commons-simple-cuboidal-epithelium.jpg'),
  'asset-commons-simple-columnar-epithelium': require('@/assets/images/anatomy/commons-simple-columnar-epithelium.jpg'),
  'asset-openstax-muscle-face-neck': require('@/assets/images/anatomy/muscular-atlas/muscular-atlas-02-face-neck.png'),
  'asset-openstax-muscle-anterior-trunk': require('@/assets/images/anatomy/muscular-atlas/muscular-atlas-03-anterior-chest.png'),
  'asset-openstax-muscle-anterior-arm': require('@/assets/images/anatomy/muscular-atlas/muscular-atlas-06-anterior-arm.png'),
  'asset-openstax-muscle-anterior-leg': require('@/assets/images/anatomy/muscular-atlas/muscular-atlas-11-anterior-thigh.png'),
  'asset-openstax-muscle-posterior-back': require('@/assets/images/anatomy/muscular-atlas/muscular-atlas-04-superficial-back.png'),
  'asset-openstax-muscle-posterior-leg': require('@/assets/images/anatomy/muscular-atlas/muscular-atlas-13-posterior-leg-overview.png'),
  'asset-openstax-muscle-labeled-overview': require('@/assets/images/anatomy/muscular-atlas/muscular-atlas-01-overview.png'),
  'asset-openstax-diaphragm-labeled': require('@/assets/images/anatomy/muscular-atlas/muscular-atlas-17-diaphragm.png'),
  'asset-injurymap-rotator-cuff-labeled': require('@/assets/images/anatomy/muscular-atlas/muscular-atlas-16-rotator-cuff.png'),
  'asset-openstax-2016-humerus': require('@/assets/images/anatomy/openstax-2016-humerus-labeled.jpg'),
  'asset-openstax-2016-hand': require('@/assets/images/anatomy/openstax-2016-hand-labeled.jpg'),
  'asset-openstax-2016-leg': require('@/assets/images/anatomy/openstax-2016-leg-labeled.jpg'),
  'asset-openstax-2016-foot': require('@/assets/images/anatomy/openstax-2016-foot-labeled.jpg'),
  'asset-openstax-2016-floor': require('@/assets/images/anatomy/openstax-2016-floor-labeled.jpg'),
  'asset-openstax-2016-perineum': require('@/assets/images/anatomy/openstax-2016-perineum-labeled.jpg'),
  'asset-openstax-2016-hand-palmar': require('@/assets/images/anatomy/openstax-2016-hand-palmar-unlabeled.jpg'),
  'asset-openstax-2016-foot-plantar': require('@/assets/images/anatomy/openstax-2016-foot-plantar-unlabeled.jpg'),
  'asset-openstax-2016-foot-dorsal': require('@/assets/images/anatomy/openstax-2016-foot-dorsal-unlabeled.jpg'),
  'asset-openstax-historical-heart-valves': require('@/assets/images/anatomy/openstax-historical-heart-valves-labeled.jpg'),
  'asset-openstax-historical-skin-structure': require('@/assets/images/anatomy/openstax-historical-skin-structure-labeled.jpg'),
  'asset-openstax-historical-nephron': require('@/assets/images/anatomy/openstax-historical-nephron-labeled.jpg'),
  'asset-openstax-historical-peritoneum': require('@/assets/images/anatomy/openstax-historical-peritoneum-labeled.jpg'),
  'asset-original-cell-overview': require('@/assets/images/anatomy/original-cell-overview.png'),
  'asset-original-mitosis-stages': require('@/assets/images/anatomy/original-mitosis-stages.png'),
  'asset-original-anatomical-planes': require('@/assets/images/anatomy/original-anatomical-planes.png'),
  'asset-original-body-cavities': require('@/assets/images/anatomy/original-body-cavities.png'),
  'asset-servier-elbow-joint': require('@/assets/images/anatomy/servier-elbow-joint.png'),
  'asset-servier-brain-lateral': require('@/assets/images/anatomy/servier-brain-lateral.png'),
  'asset-servier-brain-sagittal': require('@/assets/images/anatomy/servier-brain-sagittal.png'),
  'asset-servier-heart-anterior': require('@/assets/images/anatomy/servier-heart-anterior.png'),
  'asset-servier-stomach-section': require('@/assets/images/anatomy/servier-stomach-section.png'),
  'asset-servier-kidney': require('@/assets/images/anatomy/servier-kidney.png'),
  'asset-servier-thyroid-anterior': require('@/assets/images/anatomy/servier-thyroid-anterior.png'),
  'asset-servier-ovary': require('@/assets/images/anatomy/servier-ovary.png'),
  'asset-servier-uterus': require('@/assets/images/anatomy/servier-uterus.png'),
  'asset-servier-eye-section': require('@/assets/images/anatomy/servier-eye-section.png'),
  'asset-servier-ear-section': require('@/assets/images/anatomy/servier-ear-section.png'),
  'asset-servier-muscle-overview': require('@/assets/images/anatomy/servier-muscle-overview.png'),
  'asset-servier-male-reproductive': require('@/assets/images/anatomy/servier-male-reproductive.png'),
  'asset-servier-lymph-node-section': require('@/assets/images/anatomy/servier-lymph-node-section.png'),
  'asset-servier-pelvis': require('@/assets/images/anatomy/servier-pelvis.png'),
  'asset-servier-adrenal-vessels': require('@/assets/images/anatomy/servier-adrenal-vessels.png'),
  'asset-servier-respiratory-system': require('@/assets/images/anatomy/servier-respiratory-system.png'),
  'asset-commons-kidney-cortex-human': require('@/assets/images/anatomy/commons-kidney-cortex-human.jpg'),
  'asset-commons-alveolar-sac': require('@/assets/images/anatomy/commons-alveolar-sac.jpg'),
  'asset-atlas-anterior-position': require('@/assets/images/anatomy/atlas/atlas-01-anterior-position.png'),
  'asset-atlas-posterior-position': require('@/assets/images/anatomy/atlas/atlas-02-posterior-position.png'),
  'asset-atlas-body-planes': require('@/assets/images/anatomy/atlas/atlas-03-body-planes.png'),
  'asset-atlas-body-cavities': require('@/assets/images/anatomy/atlas/atlas-04-body-cavities.png'),
  'asset-atlas-abdominal-quadrants': require('@/assets/images/anatomy/atlas/atlas-05-abdominal-quadrants.png'),
  'asset-atlas-abdominal-regions': require('@/assets/images/anatomy/atlas/atlas-06-abdominal-regions.png'),
  'asset-atlas-organ-locations': require('@/assets/images/anatomy/atlas/atlas-07-organ-locations.png'),
  'asset-atlas-skeleton-anterior': require('@/assets/images/anatomy/atlas/atlas-08-skeleton-anterior.png'),
  'asset-atlas-skeleton-posterior': require('@/assets/images/anatomy/atlas/atlas-09-skeleton-posterior.png'),
  'asset-atlas-skeleton-axial-appendicular': require('@/assets/images/anatomy/atlas/atlas-10-skeleton-axial-appendicular.png'),
  'asset-skeletal-atlas-skull-base-external': require('@/assets/images/anatomy/skeletal-atlas/skeletal-atlas-03-skull-base-external.png'),
  'asset-skeletal-atlas-cranial-floor-internal': require('@/assets/images/anatomy/skeletal-atlas/skeletal-atlas-04-cranial-floor-internal.png'),
  'asset-skeletal-atlas-skull-sutures': require('@/assets/images/anatomy/skeletal-atlas/skeletal-atlas-05-skull-sutures.png'),
  'asset-skeletal-atlas-vertebra-typical': require('@/assets/images/anatomy/skeletal-atlas/skeletal-atlas-06-vertebra-typical.png'),
  'asset-skeletal-atlas-atlas-axis': require('@/assets/images/anatomy/skeletal-atlas/skeletal-atlas-08-atlas-axis.png'),
  'asset-skeletal-atlas-thoracic-cage': require('@/assets/images/anatomy/skeletal-atlas/skeletal-atlas-09-thoracic-cage.png'),
  'asset-skeletal-atlas-rib-detail': require('@/assets/images/anatomy/skeletal-atlas/skeletal-atlas-10-rib-detail.png'),
  'asset-skeletal-atlas-scapula': require('@/assets/images/anatomy/skeletal-atlas/skeletal-atlas-11-scapula.png'),
  'asset-skeletal-atlas-pectoral-girdle': require('@/assets/images/anatomy/skeletal-atlas/skeletal-atlas-12-pectoral-girdle.png'),
  'asset-skeletal-atlas-humerus': require('@/assets/images/anatomy/skeletal-atlas/skeletal-atlas-13-humerus.png'),
  'asset-skeletal-atlas-forearm': require('@/assets/images/anatomy/skeletal-atlas/skeletal-atlas-14-forearm.png'),
  'asset-skeletal-atlas-hand-palmar': require('@/assets/images/anatomy/skeletal-atlas/skeletal-atlas-15-hand-palmar.png'),
  'asset-skeletal-atlas-hip-bone': require('@/assets/images/anatomy/skeletal-atlas/skeletal-atlas-16-hip-bone.png'),
  'asset-skeletal-atlas-femur': require('@/assets/images/anatomy/skeletal-atlas/skeletal-atlas-17-femur.png'),
  'asset-skeletal-atlas-leg-tibia-fibula': require('@/assets/images/anatomy/skeletal-atlas/skeletal-atlas-18-leg-tibia-fibula.png'),
  'asset-skeletal-atlas-foot-dorsal': require('@/assets/images/anatomy/skeletal-atlas/skeletal-atlas-19-foot-dorsal.png'),
  'asset-skeletal-atlas-synovial-joint': require('@/assets/images/anatomy/skeletal-atlas/skeletal-atlas-20-synovial-joint.png'),
  'asset-skeletal-atlas-shoulder-joint': require('@/assets/images/anatomy/skeletal-atlas/skeletal-atlas-21-shoulder-joint.png'),
  'asset-skeletal-atlas-knee-joint': require('@/assets/images/anatomy/skeletal-atlas/skeletal-atlas-22-knee-joint.png'),
  'asset-muscular-atlas-deep-back': require('@/assets/images/anatomy/muscular-atlas/muscular-atlas-05-deep-back.png'),
  'asset-muscular-atlas-posterior-arm': require('@/assets/images/anatomy/muscular-atlas/muscular-atlas-07-posterior-arm.png'),
  'asset-muscular-atlas-forearm': require('@/assets/images/anatomy/muscular-atlas/muscular-atlas-08-forearm.png'),
  'asset-muscular-atlas-abdominal-wall': require('@/assets/images/anatomy/muscular-atlas/muscular-atlas-09-abdominal-wall.png'),
  'asset-muscular-atlas-gluteal': require('@/assets/images/anatomy/muscular-atlas/muscular-atlas-10-gluteal.png'),
  'asset-muscular-atlas-deep-thigh': require('@/assets/images/anatomy/muscular-atlas/muscular-atlas-12-deep-thigh.png'),
  'asset-muscular-atlas-anterior-leg': require('@/assets/images/anatomy/muscular-atlas/muscular-atlas-14-anterior-lateral-leg.png'),
  'asset-muscular-atlas-calf': require('@/assets/images/anatomy/muscular-atlas/muscular-atlas-15-calf.png'),
  'asset-muscular-atlas-hand': require('@/assets/images/anatomy/muscular-atlas/muscular-atlas-18-hand-intrinsics.png'),
  'asset-muscular-atlas-foot': require('@/assets/images/anatomy/muscular-atlas/muscular-atlas-19-foot-intrinsics.png'),
  'asset-muscular-atlas-pelvic-floor': require('@/assets/images/anatomy/muscular-atlas/muscular-atlas-20-pelvic-floor.png'),
};

Object.assign(imageSources, bvis04ImageSources);
Object.assign(imageSources, bvis05ImageSources);
Object.assign(imageSources, bvis06ImageSources);

export function hasImageSource(assetId: string): boolean {
  return Object.prototype.hasOwnProperty.call(imageSources, assetId);
}