// GENERATED by scripts/atlas/muscular-generate.mjs - do not edit by hand.
export interface MuscularPlateLabel { structureId: string; x: number; y: number; radius: number; panel: string }
export interface MuscularPlate { id: string; key: string; replaces: string | null; svgPath: string; pngPath: string; title: [string, string]; description: [string, string]; orientation: string; orientationEs: string; purpose: string; lessons: string[]; labels: MuscularPlateLabel[] }
export const muscularPlates: MuscularPlate[] = [
  {
    "id": "asset-openstax-muscle-labeled-overview",
    "key": "overview",
    "replaces": "asset-openstax-muscle-labeled-overview",
    "svgPath": "assets/images/anatomy/muscular-atlas/muscular-atlas-01-overview.svg",
    "pngPath": "assets/images/anatomy/muscular-atlas/muscular-atlas-01-overview.png",
    "title": [
      "Superficial muscles, anterior and posterior views",
      "Músculos superficiales, vistas anterior y posterior"
    ],
    "description": [
      "Whole-body superficial view. Left figure is anterior (patient right is viewer left); right figure is posterior (patient right is viewer right). Only superficial muscles are drawn; deep muscles are on regional plates. Pins are on the patient right limb.",
      "Vista superficial del cuerpo entero. La figura izquierda es anterior (derecha del paciente a la izquierda del observador); la derecha es posterior (derecha del paciente a la derecha del observador). Solo se dibujan músculos superficiales; los profundos están en láminas regionales. Los marcadores están en el lado derecho del paciente."
    ],
    "orientation": "left figure anterior, right figure posterior; superficial layer only",
    "orientationEs": "figura izquierda anterior, figura derecha posterior; solo capa superficial",
    "purpose": "Whole-body superficial orientation: anterior and posterior muscles.",
    "lessons": [
      "muscle-orientation",
      "muscle-actions"
    ],
    "labels": [
      {
        "structureId": "adductor-longus",
        "x": 0.2429,
        "y": 0.5915,
        "radius": 0.018,
        "panel": "anterior"
      },
      {
        "structureId": "gracilis",
        "x": 0.2482,
        "y": 0.6242,
        "radius": 0.018,
        "panel": "anterior"
      },
      {
        "structureId": "vastus-lateralis",
        "x": 0.2097,
        "y": 0.676,
        "radius": 0.018,
        "panel": "anterior"
      },
      {
        "structureId": "vastus-medialis",
        "x": 0.2262,
        "y": 0.696,
        "radius": 0.018,
        "panel": "anterior"
      },
      {
        "structureId": "tensor-fasciae-latae",
        "x": 0.1982,
        "y": 0.5286,
        "radius": 0.018,
        "panel": "anterior"
      },
      {
        "structureId": "rectus-femoris",
        "x": 0.2166,
        "y": 0.6002,
        "radius": 0.018,
        "panel": "anterior"
      },
      {
        "structureId": "sartorius",
        "x": 0.2298,
        "y": 0.616,
        "radius": 0.018,
        "panel": "anterior"
      },
      {
        "structureId": "fibularis-longus",
        "x": 0.2072,
        "y": 0.7788,
        "radius": 0.018,
        "panel": "anterior"
      },
      {
        "structureId": "tibialis-anterior",
        "x": 0.2276,
        "y": 0.7854,
        "radius": 0.018,
        "panel": "anterior"
      },
      {
        "structureId": "serratus-anterior",
        "x": 0.2069,
        "y": 0.32,
        "radius": 0.018,
        "panel": "anterior"
      },
      {
        "structureId": "rectus-abdominis",
        "x": 0.249,
        "y": 0.4034,
        "radius": 0.018,
        "panel": "anterior"
      },
      {
        "structureId": "external-oblique",
        "x": 0.2044,
        "y": 0.4168,
        "radius": 0.018,
        "panel": "anterior"
      },
      {
        "structureId": "sternocleidomastoid",
        "x": 0.2462,
        "y": 0.1727,
        "radius": 0.018,
        "panel": "anterior"
      },
      {
        "structureId": "pectoralis-major",
        "x": 0.2306,
        "y": 0.26,
        "radius": 0.018,
        "panel": "anterior"
      },
      {
        "structureId": "biceps-brachii",
        "x": 0.1766,
        "y": 0.3337,
        "radius": 0.018,
        "panel": "anterior"
      },
      {
        "structureId": "deltoid",
        "x": 0.18,
        "y": 0.2454,
        "radius": 0.018,
        "panel": "anterior"
      },
      {
        "structureId": "infraspinatus",
        "x": 0.793,
        "y": 0.2799,
        "radius": 0.018,
        "panel": "posterior"
      },
      {
        "structureId": "teres-minor",
        "x": 0.8152,
        "y": 0.278,
        "radius": 0.018,
        "panel": "posterior"
      },
      {
        "structureId": "teres-major",
        "x": 0.7945,
        "y": 0.32,
        "radius": 0.018,
        "panel": "posterior"
      },
      {
        "structureId": "triceps-brachii",
        "x": 0.8285,
        "y": 0.3401,
        "radius": 0.018,
        "panel": "posterior"
      },
      {
        "structureId": "latissimus-dorsi",
        "x": 0.7772,
        "y": 0.3978,
        "radius": 0.018,
        "panel": "posterior"
      },
      {
        "structureId": "trapezius",
        "x": 0.7576,
        "y": 0.2552,
        "radius": 0.018,
        "panel": "posterior"
      },
      {
        "structureId": "semitendinosus",
        "x": 0.7669,
        "y": 0.666,
        "radius": 0.018,
        "panel": "posterior"
      },
      {
        "structureId": "biceps-femoris",
        "x": 0.7809,
        "y": 0.6524,
        "radius": 0.018,
        "panel": "posterior"
      },
      {
        "structureId": "gluteus-medius",
        "x": 0.8021,
        "y": 0.4813,
        "radius": 0.018,
        "panel": "posterior"
      },
      {
        "structureId": "gluteus-maximus",
        "x": 0.7772,
        "y": 0.546,
        "radius": 0.018,
        "panel": "posterior"
      },
      {
        "structureId": "gastrocnemius",
        "x": 0.77,
        "y": 0.7554,
        "radius": 0.018,
        "panel": "posterior"
      }
    ]
  },
  {
    "id": "asset-openstax-muscle-face-neck",
    "key": "face-neck",
    "replaces": "asset-openstax-muscle-face-neck",
    "svgPath": "assets/images/anatomy/muscular-atlas/muscular-atlas-02-face-neck.svg",
    "pngPath": "assets/images/anatomy/muscular-atlas/muscular-atlas-02-face-neck.png",
    "title": [
      "Face and neck muscles, right lateral view",
      "Músculos de la cara y el cuello, vista lateral derecha"
    ],
    "description": [
      "Right lateral view of head and neck, face toward the viewer's right. Rings of orbicularis oculi and oris, frontalis, temporalis and masseter, buccinator, platysma over the anterior neck, sternocleidomastoid, and scalenes deep in the posterior triangle.",
      "Vista lateral derecha de cabeza y cuello, con la cara hacia la derecha del observador. Anillos del orbicular de los ojos y de la boca, frontal, temporal y masetero, buccinador, platisma sobre el cuello anterior, esternocleidomastoideo y escalenos profundos en el triángulo posterior."
    ],
    "orientation": "right lateral view; face toward viewer right; platysma drawn over only the anterior half of the neck",
    "orientationEs": "vista lateral derecha; cara hacia la derecha del observador; el platisma cubre solo la mitad anterior del cuello",
    "purpose": "Muscles of facial expression, mastication and the lateral neck.",
    "lessons": [
      "muscle-orientation",
      "muscle-actions"
    ],
    "labels": [
      {
        "structureId": "temporalis",
        "x": 0.5094,
        "y": 0.257,
        "radius": 0.018,
        "panel": ""
      },
      {
        "structureId": "scalenes",
        "x": 0.4703,
        "y": 0.7309,
        "radius": 0.018,
        "panel": ""
      },
      {
        "structureId": "sternocleidomastoid",
        "x": 0.5224,
        "y": 0.6296,
        "radius": 0.018,
        "panel": ""
      },
      {
        "structureId": "buccinator",
        "x": 0.6248,
        "y": 0.4892,
        "radius": 0.018,
        "panel": ""
      },
      {
        "structureId": "masseter",
        "x": 0.5522,
        "y": 0.446,
        "radius": 0.018,
        "panel": ""
      },
      {
        "structureId": "platysma",
        "x": 0.6062,
        "y": 0.7565,
        "radius": 0.018,
        "panel": ""
      },
      {
        "structureId": "frontalis",
        "x": 0.6025,
        "y": 0.1679,
        "radius": 0.018,
        "panel": ""
      },
      {
        "structureId": "orbicularis-oculi",
        "x": 0.611,
        "y": 0.264,
        "radius": 0.018,
        "panel": ""
      },
      {
        "structureId": "orbicularis-oris",
        "x": 0.6745,
        "y": 0.498,
        "radius": 0.018,
        "panel": ""
      }
    ]
  },
  {
    "id": "asset-openstax-muscle-anterior-trunk",
    "key": "anterior-chest",
    "replaces": "asset-openstax-muscle-anterior-trunk",
    "svgPath": "assets/images/anatomy/muscular-atlas/muscular-atlas-03-anterior-chest.svg",
    "pngPath": "assets/images/anatomy/muscular-atlas/muscular-atlas-03-anterior-chest.png",
    "title": [
      "Anterior chest and shoulder muscles",
      "Músculos del tórax anterior y del hombro"
    ],
    "description": [
      "Anterior view. Patient right (viewer left): superficial pectoralis major, deltoid, serratus anterior, biceps, rectus abdominis and external oblique. Patient left (viewer right): pectoralis major and deltoid removed to expose pectoralis minor and the intercostal muscles between the ribs.",
      "Vista anterior. Derecha del paciente (izquierda del observador): pectoral mayor, deltoides, serrato anterior, bíceps, recto del abdomen y oblicuo externo superficiales. Izquierda del paciente (derecha del observador): pectoral mayor y deltoides retirados para exponer el pectoral menor y los músculos intercostales entre las costillas."
    ],
    "orientation": "anterior view; patient right = viewer left (superficial); patient left = viewer right (pectoralis major and deltoid removed)",
    "orientationEs": "vista anterior; derecha del paciente = izquierda del observador (superficial); izquierda del paciente = derecha del observador (pectoral mayor y deltoides retirados)",
    "purpose": "Anterior chest wall: superficial layer on patient right, pectoralis major removed on patient left.",
    "lessons": [
      "axial-muscles",
      "shoulder-rotator-cuff",
      "abdominal-wall"
    ],
    "labels": [
      {
        "structureId": "intercostals",
        "x": 0.5608,
        "y": 0.3206,
        "radius": 0.018,
        "panel": "patient-left-deep"
      },
      {
        "structureId": "pectoralis-minor",
        "x": 0.5981,
        "y": 0.2994,
        "radius": 0.018,
        "panel": "patient-left-deep"
      },
      {
        "structureId": "serratus-anterior",
        "x": 0.3908,
        "y": 0.429,
        "radius": 0.018,
        "panel": "patient-right-superficial"
      },
      {
        "structureId": "rectus-abdominis",
        "x": 0.4752,
        "y": 0.5478,
        "radius": 0.018,
        "panel": "patient-right-superficial"
      },
      {
        "structureId": "external-oblique",
        "x": 0.3908,
        "y": 0.573,
        "radius": 0.018,
        "panel": "patient-right-superficial"
      },
      {
        "structureId": "sternocleidomastoid",
        "x": 0.47,
        "y": 0.1106,
        "radius": 0.018,
        "panel": "patient-right-superficial"
      },
      {
        "structureId": "pectoralis-major",
        "x": 0.4404,
        "y": 0.276,
        "radius": 0.018,
        "panel": "patient-right-superficial"
      },
      {
        "structureId": "biceps-brachii",
        "x": 0.3381,
        "y": 0.4156,
        "radius": 0.018,
        "panel": "patient-right-superficial"
      },
      {
        "structureId": "deltoid",
        "x": 0.3446,
        "y": 0.2483,
        "radius": 0.018,
        "panel": "patient-right-superficial"
      }
    ]
  },
  {
    "id": "asset-openstax-muscle-posterior-back",
    "key": "superficial-back",
    "replaces": "asset-openstax-muscle-posterior-back",
    "svgPath": "assets/images/anatomy/muscular-atlas/muscular-atlas-04-superficial-back.svg",
    "pngPath": "assets/images/anatomy/muscular-atlas/muscular-atlas-04-superficial-back.png",
    "title": [
      "Superficial back and scapular muscles",
      "Músculos superficiales de la espalda y de la región escapular"
    ],
    "description": [
      "Posterior view, superficial layer only. Trapezius forms the upper diamond, latissimus dorsi the broad lower sheet; infraspinatus, teres minor and teres major lie on the scapula under the deltoid. Rhomboids, levator scapulae and erector spinae are deep and appear on the deep-back plate.",
      "Vista posterior, solo capa superficial. El trapecio forma el rombo superior y el dorsal ancho la lámina inferior amplia; infraespinoso, redondo menor y redondo mayor están sobre la escápula bajo el deltoides. Romboides, elevador de la escápula y erector de la columna son profundos y aparecen en la lámina de espalda profunda."
    ],
    "orientation": "posterior view; patient right = viewer right; superficial layer only",
    "orientationEs": "vista posterior; derecha del paciente = derecha del observador; solo capa superficial",
    "purpose": "Superficial posterior shoulder girdle and back layer.",
    "lessons": [
      "axial-muscles",
      "shoulder-rotator-cuff",
      "arm-forearm"
    ],
    "labels": [
      {
        "structureId": "infraspinatus",
        "x": 0.5869,
        "y": 0.364,
        "radius": 0.018,
        "panel": ""
      },
      {
        "structureId": "teres-minor",
        "x": 0.6221,
        "y": 0.361,
        "radius": 0.018,
        "panel": ""
      },
      {
        "structureId": "teres-major",
        "x": 0.6039,
        "y": 0.414,
        "radius": 0.018,
        "panel": ""
      },
      {
        "structureId": "triceps-brachii",
        "x": 0.643,
        "y": 0.459,
        "radius": 0.018,
        "panel": ""
      },
      {
        "structureId": "latissimus-dorsi",
        "x": 0.5621,
        "y": 0.55,
        "radius": 0.018,
        "panel": ""
      },
      {
        "structureId": "trapezius",
        "x": 0.531,
        "y": 0.325,
        "radius": 0.018,
        "panel": ""
      },
      {
        "structureId": "deltoid",
        "x": 0.6448,
        "y": 0.358,
        "radius": 0.018,
        "panel": ""
      }
    ]
  },
  {
    "id": "asset-muscular-atlas-deep-back",
    "key": "deep-back",
    "replaces": null,
    "svgPath": "assets/images/anatomy/muscular-atlas/muscular-atlas-05-deep-back.svg",
    "pngPath": "assets/images/anatomy/muscular-atlas/muscular-atlas-05-deep-back.png",
    "title": [
      "Deep back muscles (trapezius and latissimus dorsi removed)",
      "Músculos profundos de la espalda (trapecio y dorsal ancho retirados)"
    ],
    "description": [
      "Explicit deep dissection, posterior view. Trapezius, latissimus dorsi and deltoid are removed on both sides. Patient right (viewer right): rhomboid minor and major, levator scapulae, supraspinatus and the intact erector spinae column. Patient left (viewer left): erector spinae also removed to expose multifidus beside the spinous processes and quadratus lumborum in the lumbar region.",
      "Disección profunda explícita, vista posterior. Trapecio, dorsal ancho y deltoides están retirados en ambos lados. Derecha del paciente (derecha del observador): romboides menor y mayor, elevador de la escápula, supraespinoso y la columna intacta del erector de la columna. Izquierda del paciente (izquierda del observador): también se retira el erector para exponer el multífido junto a las apófisis espinosas y el cuadrado lumbar en la región lumbar."
    ],
    "orientation": "posterior view, deep dissection; patient right = viewer right",
    "orientationEs": "vista posterior, disección profunda; derecha del paciente = derecha del observador",
    "purpose": "Deep back layer: trapezius, latissimus dorsi and deltoid removed; erector spinae removed on patient left.",
    "lessons": [
      "axial-muscles",
      "abdominal-wall"
    ],
    "labels": [
      {
        "structureId": "multifidus",
        "x": 0.491,
        "y": 0.5,
        "radius": 0.018,
        "panel": ""
      },
      {
        "structureId": "quadratus-lumborum",
        "x": 0.4669,
        "y": 0.619,
        "radius": 0.018,
        "panel": ""
      },
      {
        "structureId": "erector-spinae",
        "x": 0.5176,
        "y": 0.5028,
        "radius": 0.018,
        "panel": ""
      },
      {
        "structureId": "supraspinatus",
        "x": 0.5683,
        "y": 0.307,
        "radius": 0.018,
        "panel": ""
      },
      {
        "structureId": "rhomboid-minor",
        "x": 0.5145,
        "y": 0.319,
        "radius": 0.018,
        "panel": ""
      },
      {
        "structureId": "rhomboid-major",
        "x": 0.5166,
        "y": 0.394,
        "radius": 0.018,
        "panel": ""
      },
      {
        "structureId": "levator-scapulae",
        "x": 0.5339,
        "y": 0.2368,
        "radius": 0.018,
        "panel": ""
      }
    ]
  },
  {
    "id": "asset-openstax-muscle-anterior-arm",
    "key": "anterior-arm",
    "replaces": "asset-openstax-muscle-anterior-arm",
    "svgPath": "assets/images/anatomy/muscular-atlas/muscular-atlas-06-anterior-arm.svg",
    "pngPath": "assets/images/anatomy/muscular-atlas/muscular-atlas-06-anterior-arm.png",
    "title": [
      "Anterior arm: superficial and deep layers",
      "Brazo anterior: capas superficial y profunda"
    ],
    "description": [
      "Right arm, anterior view. Left panel: deltoid, biceps brachii and the superficial anterior forearm (pronator teres, flexor carpi radialis). Right panel: biceps and deltoid removed to expose coracobrachialis and brachialis, which lies deep to biceps.",
      "Brazo derecho, vista anterior. Panel izquierdo: deltoides, bíceps braquial y antebrazo anterior superficial (pronador redondo, flexor radial del carpo). Panel derecho: bíceps y deltoides retirados para exponer el coracobraquial y el braquial, que queda profundo al bíceps."
    ],
    "orientation": "right arm, anterior view; patient right = viewer left; left panel superficial, right panel deep",
    "orientationEs": "brazo derecho, vista anterior; derecha del paciente = izquierda del observador; panel izquierdo superficial, derecho profundo",
    "purpose": "Anterior arm: superficial biceps compartment and the deeper layer beneath it.",
    "lessons": [
      "arm-forearm",
      "muscle-actions"
    ],
    "labels": [
      {
        "structureId": "biceps-brachii",
        "x": 0.289,
        "y": 0.3788,
        "radius": 0.018,
        "panel": "superficial"
      },
      {
        "structureId": "deltoid",
        "x": 0.2979,
        "y": 0.1465,
        "radius": 0.018,
        "panel": "superficial"
      },
      {
        "structureId": "pronator-teres",
        "x": 0.2276,
        "y": 0.656,
        "radius": 0.018,
        "panel": "superficial"
      },
      {
        "structureId": "flexor-carpi-radialis",
        "x": 0.2317,
        "y": 0.704,
        "radius": 0.018,
        "panel": "superficial"
      },
      {
        "structureId": "coracobrachialis",
        "x": 0.7979,
        "y": 0.2555,
        "radius": 0.018,
        "panel": "deep"
      },
      {
        "structureId": "brachialis",
        "x": 0.7603,
        "y": 0.435,
        "radius": 0.018,
        "panel": "deep"
      }
    ]
  },
  {
    "id": "asset-muscular-atlas-posterior-arm",
    "key": "posterior-arm",
    "replaces": null,
    "svgPath": "assets/images/anatomy/muscular-atlas/muscular-atlas-07-posterior-arm.svg",
    "pngPath": "assets/images/anatomy/muscular-atlas/muscular-atlas-07-posterior-arm.png",
    "title": [
      "Posterior arm and elbow",
      "Brazo posterior y codo"
    ],
    "description": [
      "Right arm, posterior view. Left panel: deltoid and the long and lateral heads of triceps brachii converging on one tendon at the olecranon. Right panel: enlarged elbow showing the triceps tendon and the small triangular anconeus.",
      "Brazo derecho, vista posterior. Panel izquierdo: deltoides y las cabezas larga y lateral del tríceps braquial convergiendo en un tendón en el olécranon. Panel derecho: codo ampliado con el tendón del tríceps y el pequeño ancóneo triangular."
    ],
    "orientation": "right arm, posterior view; patient right = viewer right; right panel is an enlarged elbow inset",
    "orientationEs": "brazo derecho, vista posterior; derecha del paciente = derecha del observador; el panel derecho es un recuadro ampliado del codo",
    "purpose": "Posterior arm and elbow: triceps brachii and anconeus.",
    "lessons": [
      "arm-forearm"
    ],
    "labels": [
      {
        "structureId": "teres-major",
        "x": 0.2215,
        "y": 0.3083,
        "radius": 0.018,
        "panel": "arm"
      },
      {
        "structureId": "triceps-brachii",
        "x": 0.2867,
        "y": 0.3833,
        "radius": 0.018,
        "panel": "arm"
      },
      {
        "structureId": "deltoid",
        "x": 0.2897,
        "y": 0.215,
        "radius": 0.018,
        "panel": "arm"
      },
      {
        "structureId": "anconeus",
        "x": 0.7238,
        "y": 0.2595,
        "radius": 0.018,
        "panel": "elbow"
      }
    ]
  },
  {
    "id": "asset-muscular-atlas-forearm",
    "key": "forearm",
    "replaces": null,
    "svgPath": "assets/images/anatomy/muscular-atlas/muscular-atlas-08-forearm.svg",
    "pngPath": "assets/images/anatomy/muscular-atlas/muscular-atlas-08-forearm.png",
    "title": [
      "Forearm: anterior and posterior views",
      "Antebrazo: vistas anterior y posterior"
    ],
    "description": [
      "Right forearm in two panels. Left: anterior (flexor) compartment with pronator teres and flexor carpi radialis. Right: posterior (extensor) compartment with extensor carpi radialis and anconeus; the superficial extensors are cut away proximally so the deeper supinator is visible beside the upper radius.",
      "Antebrazo derecho en dos paneles. Izquierda: compartimento anterior (flexor) con pronador redondo y flexor radial del carpo. Derecha: compartimento posterior (extensor) con extensor radial del carpo y ancóneo; los extensores superficiales están cortados proximalmente para mostrar el supinador, más profundo, junto al radio superior."
    ],
    "orientation": "right forearm; left panel anterior (patient right = viewer left); right panel posterior (patient right = viewer right) with extensors cut proximally to show supinator",
    "orientationEs": "antebrazo derecho; panel izquierdo anterior; panel derecho posterior con extensores cortados proximalmente para mostrar el supinador",
    "purpose": "Forearm flexor/anterior and extensor/posterior orientation plus the deep supinator.",
    "lessons": [
      "arm-forearm"
    ],
    "labels": [
      {
        "structureId": "pronator-teres",
        "x": 0.2566,
        "y": 0.286,
        "radius": 0.018,
        "panel": "anterior"
      },
      {
        "structureId": "flexor-carpi-radialis",
        "x": 0.2579,
        "y": 0.398,
        "radius": 0.018,
        "panel": "anterior"
      },
      {
        "structureId": "extensor-carpi-radialis",
        "x": 0.7633,
        "y": 0.4458,
        "radius": 0.018,
        "panel": "posterior"
      },
      {
        "structureId": "anconeus",
        "x": 0.709,
        "y": 0.2276,
        "radius": 0.018,
        "panel": "posterior"
      },
      {
        "structureId": "supinator",
        "x": 0.7727,
        "y": 0.3332,
        "radius": 0.018,
        "panel": "posterior"
      }
    ]
  },
  {
    "id": "asset-muscular-atlas-abdominal-wall",
    "key": "abdominal-wall",
    "replaces": null,
    "svgPath": "assets/images/anatomy/muscular-atlas/muscular-atlas-09-abdominal-wall.svg",
    "pngPath": "assets/images/anatomy/muscular-atlas/muscular-atlas-09-abdominal-wall.png",
    "title": [
      "Abdominal wall layers",
      "Capas de la pared abdominal"
    ],
    "description": [
      "Anterior view in three panels, superficial to deep. Left: external oblique (fibres run inferomedially) beside rectus abdominis. Middle: external oblique removed to show internal oblique (fibres superomedial). Right: both obliques and the rectus removed to show transversus abdominis with horizontal fibres.",
      "Vista anterior en tres paneles, de superficial a profundo. Izquierda: oblicuo externo (fibras inferomediales) junto al recto del abdomen. Centro: oblicuo externo retirado para mostrar el oblicuo interno (fibras superomediales). Derecha: ambos oblicuos y el recto retirados para mostrar el transverso del abdomen con fibras horizontales."
    ],
    "orientation": "anterior view; patient right = viewer left; panels run superficial (left) to deep (right)",
    "orientationEs": "vista anterior; derecha del paciente = izquierda del observador; los paneles van de superficial (izquierda) a profundo (derecha)",
    "purpose": "Anterolateral abdominal wall in three progressive layers.",
    "lessons": [
      "abdominal-wall"
    ],
    "labels": [
      {
        "structureId": "rectus-abdominis",
        "x": 0.1455,
        "y": 0.3462,
        "radius": 0.018,
        "panel": "external"
      },
      {
        "structureId": "external-oblique",
        "x": 0.0541,
        "y": 0.3735,
        "radius": 0.018,
        "panel": "external"
      },
      {
        "structureId": "internal-oblique",
        "x": 0.4005,
        "y": 0.4125,
        "radius": 0.018,
        "panel": "internal"
      },
      {
        "structureId": "transversus-abdominis",
        "x": 0.7388,
        "y": 0.432,
        "radius": 0.018,
        "panel": "transversus"
      }
    ]
  },
  {
    "id": "asset-muscular-atlas-gluteal",
    "key": "gluteal",
    "replaces": null,
    "svgPath": "assets/images/anatomy/muscular-atlas/muscular-atlas-10-gluteal.svg",
    "pngPath": "assets/images/anatomy/muscular-atlas/muscular-atlas-10-gluteal.png",
    "title": [
      "Gluteal region: surface and cutaway",
      "Región glútea: superficie y corte"
    ],
    "description": [
      "Right gluteal region, posterior view. Left panel: gluteus maximus covers most of the buttock. Right panel: gluteus maximus removed, fully exposing gluteus medius on the lateral ilium.",
      "Región glútea derecha, vista posterior. Panel izquierdo: el glúteo mayor cubre la mayor parte de la nalga. Panel derecho: glúteo mayor retirado, con el glúteo medio completamente expuesto sobre el ilion lateral."
    ],
    "orientation": "posterior view of right buttock; midline at panel left edge; patient right = viewer right; right panel is a cutaway",
    "orientationEs": "vista posterior de la nalga derecha; línea media en el borde izquierdo del panel; derecha del paciente = derecha del observador; el panel derecho es un corte",
    "purpose": "Gluteal region: surface layer and gluteus maximus removed.",
    "lessons": [
      "hip-thigh"
    ],
    "labels": [
      {
        "structureId": "gluteus-maximus",
        "x": 0.2083,
        "y": 0.3932,
        "radius": 0.018,
        "panel": "surface"
      },
      {
        "structureId": "gluteus-medius",
        "x": 0.768,
        "y": 0.1756,
        "radius": 0.018,
        "panel": "cutaway"
      }
    ]
  },
  {
    "id": "asset-openstax-muscle-anterior-leg",
    "key": "anterior-thigh",
    "replaces": "asset-openstax-muscle-anterior-leg",
    "svgPath": "assets/images/anatomy/muscular-atlas/muscular-atlas-11-anterior-thigh.svg",
    "pngPath": "assets/images/anatomy/muscular-atlas/muscular-atlas-11-anterior-thigh.png",
    "title": [
      "Anterior thigh: superficial layer",
      "Muslo anterior: capa superficial"
    ],
    "description": [
      "Anterior view of both thighs. Sartorius runs from the ASIS (lateral) obliquely to the medial proximal tibia. Quadriceps: rectus femoris centrally, vastus lateralis laterally, vastus medialis medially; the fourth member, vastus intermedius, is deep to rectus femoris and appears on the deep-thigh plate. Tensor fasciae latae, iliopsoas, adductor longus and gracilis are labelled.",
      "Vista anterior de ambos muslos. El sartorio va desde la EIAS (lateral) en diagonal hasta la tibia proximal medial. Cuádriceps: recto femoral en el centro, vasto lateral por fuera y vasto medial por dentro; el cuarto miembro, el vasto intermedio, es profundo al recto femoral y aparece en la lámina del muslo profundo. Se rotulan tensor de la fascia lata, iliopsoas, aductor largo y grácil."
    ],
    "orientation": "anterior view; patient right = viewer left; superficial layer",
    "orientationEs": "vista anterior; derecha del paciente = izquierda del observador; capa superficial",
    "purpose": "Superficial anterior and medial thigh, including all quadriceps members visible on the surface.",
    "lessons": [
      "hip-thigh",
      "leg-and-ankle"
    ],
    "labels": [
      {
        "structureId": "iliopsoas",
        "x": 0.4,
        "y": 0.195,
        "radius": 0.018,
        "panel": ""
      },
      {
        "structureId": "adductor-longus",
        "x": 0.4416,
        "y": 0.3806,
        "radius": 0.018,
        "panel": ""
      },
      {
        "structureId": "gracilis",
        "x": 0.4576,
        "y": 0.4804,
        "radius": 0.018,
        "panel": ""
      },
      {
        "structureId": "vastus-lateralis",
        "x": 0.3324,
        "y": 0.532,
        "radius": 0.018,
        "panel": ""
      },
      {
        "structureId": "vastus-medialis",
        "x": 0.3945,
        "y": 0.636,
        "radius": 0.018,
        "panel": ""
      },
      {
        "structureId": "tensor-fasciae-latae",
        "x": 0.3051,
        "y": 0.1884,
        "radius": 0.018,
        "panel": ""
      },
      {
        "structureId": "rectus-femoris",
        "x": 0.3611,
        "y": 0.4069,
        "radius": 0.018,
        "panel": ""
      },
      {
        "structureId": "sartorius",
        "x": 0.4014,
        "y": 0.4552,
        "radius": 0.018,
        "panel": ""
      }
    ]
  },
  {
    "id": "asset-muscular-atlas-deep-thigh",
    "key": "deep-thigh",
    "replaces": null,
    "svgPath": "assets/images/anatomy/muscular-atlas/muscular-atlas-12-deep-thigh.svg",
    "pngPath": "assets/images/anatomy/muscular-atlas/muscular-atlas-12-deep-thigh.png",
    "title": [
      "Deep thigh: anterior and posterior cutaways",
      "Muslo profundo: cortes anterior y posterior"
    ],
    "description": [
      "Right thigh in two explicit cutaways. Left, anterior: sartorius and rectus femoris removed to expose vastus intermedius, with articularis genus at the knee. Right, posterior: gluteus maximus, biceps femoris and semitendinosus removed to expose semimembranosus, the deepest hamstring.",
      "Muslo derecho en dos cortes explícitos. Izquierda, anterior: sartorio y recto femoral retirados para exponer el vasto intermedio, con el articular de la rodilla. Derecha, posterior: glúteo mayor, bíceps femoral y semitendinoso retirados para exponer el semimembranoso, el isquiotibial más profundo."
    ],
    "orientation": "left panel anterior (patient right = viewer left), right panel posterior (patient right = viewer right); both are deep cutaways",
    "orientationEs": "panel izquierdo anterior; panel derecho posterior; ambos son cortes profundos",
    "purpose": "Deep thigh: vastus intermedius, articularis genus, and semimembranosus.",
    "lessons": [
      "hip-thigh"
    ],
    "labels": [
      {
        "structureId": "vastus-intermedius",
        "x": 0.2402,
        "y": 0.4867,
        "radius": 0.018,
        "panel": "anterior-deep"
      },
      {
        "structureId": "articularis-genus",
        "x": 0.2654,
        "y": 0.6562,
        "radius": 0.018,
        "panel": "anterior-deep"
      },
      {
        "structureId": "semimembranosus",
        "x": 0.7283,
        "y": 0.67,
        "radius": 0.018,
        "panel": "posterior-deep"
      }
    ]
  },
  {
    "id": "asset-openstax-muscle-posterior-leg",
    "key": "posterior-leg",
    "replaces": "asset-openstax-muscle-posterior-leg",
    "svgPath": "assets/images/anatomy/muscular-atlas/muscular-atlas-13-posterior-leg-overview.svg",
    "pngPath": "assets/images/anatomy/muscular-atlas/muscular-atlas-13-posterior-leg-overview.png",
    "title": [
      "Posterior lower limb: contextual overview",
      "Miembro inferior posterior: panorama contextual"
    ],
    "description": [
      "Posterior view of both lower limbs. Gluteus maximus overlies gluteus medius, which is only partly exposed above it; biceps femoris is lateral and semitendinosus medial in the posterior thigh; gastrocnemius forms the calf surface. Deep muscles (semimembranosus, soleus) are not shown here and have their own cutaway plates.",
      "Vista posterior de ambos miembros inferiores. El glúteo mayor cubre al glúteo medio, que solo se expone en parte por encima; el bíceps femoral es lateral y el semitendinoso medial en el muslo posterior; el gastrocnemio forma la superficie de la pantorrilla. Los músculos profundos (semimembranoso, sóleo) no se muestran aquí y tienen sus propias láminas de corte."
    ],
    "orientation": "posterior view; patient right = viewer right; superficial layer only",
    "orientationEs": "vista posterior; derecha del paciente = derecha del observador; solo capa superficial",
    "purpose": "Contextual posterior lower-limb overview from gluteal region to heel.",
    "lessons": [
      "hip-thigh",
      "leg-and-ankle"
    ],
    "labels": [
      {
        "structureId": "semitendinosus",
        "x": 0.5587,
        "y": 0.4115,
        "radius": 0.018,
        "panel": ""
      },
      {
        "structureId": "biceps-femoris",
        "x": 0.5837,
        "y": 0.4063,
        "radius": 0.018,
        "panel": ""
      },
      {
        "structureId": "gluteus-medius",
        "x": 0.625,
        "y": 0.0733,
        "radius": 0.018,
        "panel": ""
      },
      {
        "structureId": "gluteus-maximus",
        "x": 0.5766,
        "y": 0.1991,
        "radius": 0.018,
        "panel": ""
      },
      {
        "structureId": "gastrocnemius",
        "x": 0.5624,
        "y": 0.607,
        "radius": 0.018,
        "panel": ""
      }
    ]
  },
  {
    "id": "asset-muscular-atlas-anterior-leg",
    "key": "anterior-leg",
    "replaces": null,
    "svgPath": "assets/images/anatomy/muscular-atlas/muscular-atlas-14-anterior-lateral-leg.svg",
    "pngPath": "assets/images/anatomy/muscular-atlas/muscular-atlas-14-anterior-lateral-leg.png",
    "title": [
      "Anterior and lateral leg",
      "Pierna anterior y lateral"
    ],
    "description": [
      "Right leg and dorsal foot, anterior view. Tibialis anterior lies against the lateral tibial surface and sends its tendon to the medial foot; fibularis longus occupies the lateral compartment at the viewer's left, its tendon passing behind the lateral malleolus.",
      "Pierna derecha y dorso del pie, vista anterior. El tibial anterior se apoya en la cara lateral de la tibia y envía su tendón al pie medial; el fibular largo ocupa el compartimento lateral, a la izquierda del observador, con su tendón detrás del maléolo lateral."
    ],
    "orientation": "right leg, anterior view; patient right = viewer left; lateral = viewer left",
    "orientationEs": "pierna derecha, vista anterior; derecha del paciente = izquierda del observador; lateral = izquierda del observador",
    "purpose": "Anterior and lateral leg compartments.",
    "lessons": [
      "leg-and-ankle"
    ],
    "labels": [
      {
        "structureId": "fibularis-longus",
        "x": 0.4481,
        "y": 0.2843,
        "radius": 0.018,
        "panel": ""
      },
      {
        "structureId": "tibialis-anterior",
        "x": 0.5342,
        "y": 0.312,
        "radius": 0.018,
        "panel": ""
      }
    ]
  },
  {
    "id": "asset-muscular-atlas-calf",
    "key": "calf",
    "replaces": null,
    "svgPath": "assets/images/anatomy/muscular-atlas/muscular-atlas-15-calf.svg",
    "pngPath": "assets/images/anatomy/muscular-atlas/muscular-atlas-15-calf.png",
    "title": [
      "Calf: surface and cutaway",
      "Pantorrilla: superficie y corte"
    ],
    "description": [
      "Right calf, posterior view. Left panel: gastrocnemius (two heads) and the calcaneal tendon. Right panel: gastrocnemius removed to show soleus lying deep to it, with popliteus behind the knee and tibialis posterior deeper still along the medial border.",
      "Pantorrilla derecha, vista posterior. Panel izquierdo: gastrocnemio (dos cabezas) y tendón calcáneo. Panel derecho: gastrocnemio retirado para mostrar el sóleo, profundo a él, con el poplíteo detrás de la rodilla y el tibial posterior aún más profundo en el borde medial."
    ],
    "orientation": "right calf, posterior view; patient right = viewer right; right panel is a cutaway",
    "orientationEs": "pantorrilla derecha, vista posterior; derecha del paciente = derecha del observador; el panel derecho es un corte",
    "purpose": "Calf surface and cutaway: gastrocnemius over soleus, with deep popliteus and tibialis posterior.",
    "lessons": [
      "leg-and-ankle"
    ],
    "labels": [
      {
        "structureId": "gastrocnemius",
        "x": 0.2528,
        "y": 0.2077,
        "radius": 0.018,
        "panel": "surface"
      },
      {
        "structureId": "soleus",
        "x": 0.7833,
        "y": 0.3534,
        "radius": 0.018,
        "panel": "cutaway"
      },
      {
        "structureId": "popliteus",
        "x": 0.7494,
        "y": 0.1566,
        "radius": 0.018,
        "panel": "cutaway"
      },
      {
        "structureId": "tibialis-posterior",
        "x": 0.673,
        "y": 0.3944,
        "radius": 0.018,
        "panel": "cutaway"
      }
    ]
  },
  {
    "id": "asset-injurymap-rotator-cuff-labeled",
    "key": "rotator-cuff",
    "replaces": "asset-injurymap-rotator-cuff-labeled",
    "svgPath": "assets/images/anatomy/muscular-atlas/muscular-atlas-16-rotator-cuff.svg",
    "pngPath": "assets/images/anatomy/muscular-atlas/muscular-atlas-16-rotator-cuff.png",
    "title": [
      "Rotator cuff: anterior and posterior views",
      "Manguito rotador: vistas anterior y posterior"
    ],
    "description": [
      "Right shoulder, deltoid removed. Left panel anterior: subscapularis fills the front of the scapula and inserts on the lesser tubercle. Right panel posterior: supraspinatus above the scapular spine, infraspinatus below it, teres minor along the lateral inferior border. Each cuff muscle runs into a tendon that attaches to the humerus: supraspinatus, infraspinatus and teres minor to the greater tubercle, subscapularis to the lesser tubercle. Teres major (greyer tone) runs from the inferior scapular angle to the proximal medial humeral shaft and is NOT a rotator cuff muscle.",
      "Hombro derecho, deltoides retirado. Panel izquierdo anterior: el subescapular llena la cara anterior de la escápula y se inserta en el tubérculo menor. Panel derecho posterior: supraespinoso sobre la espina de la escápula, infraespinoso bajo ella y redondo menor en el borde lateral inferior. Cada músculo del manguito pasa a un tendón que se inserta en el húmero: supraespinoso, infraespinoso y redondo menor en el tubérculo mayor, subescapular en el tubérculo menor. El redondo mayor (tono más gris) va del ángulo inferior de la escápula a la parte medial proximal de la diáfisis del húmero y NO es un músculo del manguito rotador."
    ],
    "orientation": "right shoulder; left panel anterior (patient right = viewer left); right panel posterior (patient right = viewer right); deltoid removed",
    "orientationEs": "hombro derecho; panel izquierdo anterior; panel derecho posterior; deltoides retirado",
    "purpose": "Rotator cuff (SITS) with teres major shown as a non-cuff neighbour.",
    "lessons": [
      "shoulder-rotator-cuff"
    ],
    "labels": [
      {
        "structureId": "subscapularis",
        "x": 0.2414,
        "y": 0.45,
        "radius": 0.018,
        "panel": "anterior"
      },
      {
        "structureId": "teres-major",
        "x": 0.7546,
        "y": 0.6315,
        "radius": 0.018,
        "panel": "posterior"
      },
      {
        "structureId": "infraspinatus",
        "x": 0.7034,
        "y": 0.47,
        "radius": 0.018,
        "panel": "posterior"
      },
      {
        "structureId": "teres-minor",
        "x": 0.806,
        "y": 0.509,
        "radius": 0.018,
        "panel": "posterior"
      },
      {
        "structureId": "supraspinatus",
        "x": 0.6724,
        "y": 0.318,
        "radius": 0.018,
        "panel": "posterior"
      }
    ]
  },
  {
    "id": "asset-openstax-diaphragm-labeled",
    "key": "diaphragm",
    "replaces": "asset-openstax-diaphragm-labeled",
    "svgPath": "assets/images/anatomy/muscular-atlas/muscular-atlas-17-diaphragm.svg",
    "pngPath": "assets/images/anatomy/muscular-atlas/muscular-atlas-17-diaphragm.png",
    "title": [
      "Diaphragm: domes and inferior view",
      "Diafragma: cúpulas y vista inferior"
    ],
    "description": [
      "Left panel: anterior coronal cutaway of the thorax. The diaphragm is a dome-shaped muscle sheet arching up into the chest beneath the lungs, with the right dome higher than the left; its muscular periphery attaches to the lower ribs and the pale central tendon forms the apex. Right panel: inferior view showing the central tendon, caval and esophageal openings, aortic opening between the crura, and the muscular periphery.",
      "Panel izquierdo: corte coronal anterior del tórax. El diafragma es una lámina muscular en forma de cúpula que se arquea hacia el tórax bajo los pulmones, con la cúpula derecha más alta que la izquierda; su periferia muscular se une a las costillas inferiores y el tendón central pálido forma el vértice. Panel derecho: vista inferior con el tendón central, los orificios de la vena cava y del esófago, el hiato aórtico entre los pilares y la periferia muscular."
    ],
    "orientation": "left panel anterior coronal cutaway, patient right = viewer left; right panel inferior view (tendon pale, muscle periphery darker)",
    "orientationEs": "panel izquierdo corte coronal anterior, derecha del paciente = izquierda del observador; panel derecho vista inferior",
    "purpose": "Diaphragm as a domed thoracoabdominal boundary.",
    "lessons": [
      "axial-muscles",
      "muscle-actions"
    ],
    "labels": [
      {
        "structureId": "diaphragm",
        "x": 0.0759,
        "y": 0.5812,
        "radius": 0.018,
        "panel": "coronal"
      }
    ]
  },
  {
    "id": "asset-muscular-atlas-hand",
    "key": "hand",
    "replaces": null,
    "svgPath": "assets/images/anatomy/muscular-atlas/muscular-atlas-18-hand-intrinsics.svg",
    "pngPath": "assets/images/anatomy/muscular-atlas/muscular-atlas-18-hand-intrinsics.png",
    "title": [
      "Hand: intrinsic muscles, palmar view",
      "Mano: músculos intrínsecos, vista palmar"
    ],
    "description": [
      "Right hand, palmar view, palmar aponeurosis removed. Thumb side (thenar: abductor pollicis brevis lateral, flexor pollicis brevis medial) at the viewer's left; little-finger side (hypothenar: abductor digiti minimi) at the viewer's right. Lumbricals are slender bellies arising from the flexor digitorum profundus tendons.",
      "Mano derecha, vista palmar, con la aponeurosis palmar retirada. El lado del pulgar (tenar: abductor corto del pulgar lateral, flexor corto del pulgar medial) queda a la izquierda del observador; el lado del meñique (hipotenar: abductor del meñique) a la derecha. Los lumbricales son vientres delgados que nacen de los tendones del flexor profundo de los dedos."
    ],
    "orientation": "right hand, palmar view; thumb at viewer left (patient right = viewer left)",
    "orientationEs": "mano derecha, vista palmar; pulgar a la izquierda del observador",
    "purpose": "Intrinsic muscles of the palm: thenar, hypothenar and lumbricals.",
    "lessons": [
      "arm-forearm"
    ],
    "labels": [
      {
        "structureId": "lumbricals-hand",
        "x": 0.4538,
        "y": 0.6245,
        "radius": 0.018,
        "panel": ""
      },
      {
        "structureId": "flexor-pollicis-brevis",
        "x": 0.4538,
        "y": 0.744,
        "radius": 0.018,
        "panel": ""
      },
      {
        "structureId": "abductor-pollicis-brevis",
        "x": 0.426,
        "y": 0.7258,
        "radius": 0.018,
        "panel": ""
      },
      {
        "structureId": "abductor-digiti-minimi-hand",
        "x": 0.5745,
        "y": 0.745,
        "radius": 0.018,
        "panel": ""
      }
    ]
  },
  {
    "id": "asset-muscular-atlas-foot",
    "key": "foot",
    "replaces": null,
    "svgPath": "assets/images/anatomy/muscular-atlas/muscular-atlas-19-foot-intrinsics.svg",
    "pngPath": "assets/images/anatomy/muscular-atlas/muscular-atlas-19-foot-intrinsics.png",
    "title": [
      "Foot: plantar first layer and dorsal inset",
      "Pie: primera capa plantar y recuadro dorsal"
    ],
    "description": [
      "Right foot. Left panel: plantar view with the plantar aponeurosis removed, showing abductor hallucis along the medial border, flexor digitorum brevis centrally and abductor digiti minimi along the lateral border (big toe at the viewer's right). Right panel: dorsal view with extensor digitorum brevis on the lateral dorsum (big toe at the viewer's left).",
      "Pie derecho. Panel izquierdo: vista plantar con la aponeurosis plantar retirada, que muestra el abductor del dedo gordo en el borde medial, el flexor corto de los dedos en el centro y el abductor del dedo pequeño en el borde lateral (dedo gordo a la derecha del observador). Panel derecho: vista dorsal con el extensor corto de los dedos en el dorso lateral (dedo gordo a la izquierda del observador)."
    ],
    "orientation": "left panel plantar view (big toe at viewer right); right panel dorsal view (big toe at viewer left); right foot",
    "orientationEs": "panel izquierdo vista plantar (dedo gordo a la derecha del observador); panel derecho vista dorsal (dedo gordo a la izquierda del observador); pie derecho",
    "purpose": "Intrinsic muscles of the sole (first layer) and the dorsal extensor digitorum brevis.",
    "lessons": [
      "leg-and-ankle"
    ],
    "labels": [
      {
        "structureId": "flexor-digitorum-brevis-foot",
        "x": 0.3145,
        "y": 0.663,
        "radius": 0.018,
        "panel": "plantar"
      },
      {
        "structureId": "abductor-digiti-minimi-foot",
        "x": 0.2786,
        "y": 0.685,
        "radius": 0.018,
        "panel": "plantar"
      },
      {
        "structureId": "abductor-hallucis",
        "x": 0.3608,
        "y": 0.6731,
        "radius": 0.018,
        "panel": "plantar"
      },
      {
        "structureId": "extensor-digitorum-brevis-foot",
        "x": 0.7483,
        "y": 0.6172,
        "radius": 0.018,
        "panel": "dorsal"
      }
    ]
  },
  {
    "id": "asset-muscular-atlas-pelvic-floor",
    "key": "pelvic-floor",
    "replaces": null,
    "svgPath": "assets/images/anatomy/muscular-atlas/muscular-atlas-20-pelvic-floor.svg",
    "pngPath": "assets/images/anatomy/muscular-atlas/muscular-atlas-20-pelvic-floor.png",
    "title": [
      "Pelvic floor: levator ani, superior view",
      "Suelo pélvico: elevador del ano, vista superior"
    ],
    "description": [
      "Pelvic floor seen from above, anterior (pubic symphysis) at the top. Pubococcygeus forms the medial band running from the pubis back toward the coccyx beside the midline hiatus; iliococcygeus is the thinner lateral sheet. The levator ani group pin sits on the posterior sling region between the two bands.",
      "Suelo pélvico visto desde arriba, con la parte anterior (sínfisis del pubis) arriba. El pubococcígeo forma la banda medial que va del pubis hacia el cóccix junto al hiato de la línea media; el iliococcígeo es la lámina lateral más delgada. El marcador del grupo elevador del ano está en la región del cabestrillo posterior entre las dos bandas."
    ],
    "orientation": "superior view; anterior (pubis) up; patient right = viewer right",
    "orientationEs": "vista superior; anterior (pubis) arriba; derecha del paciente = derecha del observador",
    "purpose": "Levator ani group of the pelvic floor.",
    "lessons": [
      "axial-muscles"
    ],
    "labels": [
      {
        "structureId": "levator-ani",
        "x": 0.5,
        "y": 0.612,
        "radius": 0.018,
        "panel": ""
      },
      {
        "structureId": "iliococcygeus",
        "x": 0.5986,
        "y": 0.52,
        "radius": 0.018,
        "panel": ""
      },
      {
        "structureId": "pubococcygeus",
        "x": 0.4512,
        "y": 0.4602,
        "radius": 0.018,
        "panel": ""
      }
    ]
  }
];
