import type { Question } from './model';
import { OPENSTAX_SOURCE_ID } from './anatomy.ts';
import { JOINTS_SOURCE_ID } from './systems.ts';

export const jointsPracticeExpansion: Question[] = [
  {
    id: 'q-depth-joints-syndesmosis',
    moduleId: 'joints-ligaments',
    structureIds: ['syndesmosis'],
    taskType: 'multiple-choice',
    prompt: 'Which fibrous-joint pattern is formed by bones linked by a ligament or interosseous membrane?',
    answer: 'Syndesmosis',
    acceptedAliases: [],
    options: ['Syndesmosis', 'Suture', 'Gomphosis', 'Symphysis'],
    explanation: 'A syndesmosis is a fibrous joint in which the bones are linked by a ligament or interosseous membrane.',
    sourceId: JOINTS_SOURCE_ID,
    sourcePage: null,
    examPriority: false,
    verificationStatus: 'verified',
  },
  {
    id: 'q-depth-joints-suture-gomphosis',
    moduleId: 'joints-ligaments',
    structureIds: ['suture-joint', 'gomphosis'],
    taskType: 'select-all',
    prompt: 'Select the two fibrous-joint patterns identified by their characteristic locations.',
    answer: ['Suture joins skull bones', 'Gomphosis anchors a tooth in its socket'],
    acceptedAliases: [],
    options: ['Suture joins skull bones', 'Gomphosis anchors a tooth in its socket', 'Suture contains a synovial cavity', 'Gomphosis is a fibrocartilaginous joint'],
    explanation: 'A suture joins skull bones, whereas a gomphosis anchors a tooth in its socket; both are fibrous joints.',
    sourceId: JOINTS_SOURCE_ID,
    sourcePage: null,
    examPriority: false,
    verificationStatus: 'verified',
  },
  {
    id: 'q-depth-joints-cartilage-types',
    moduleId: 'joints-ligaments',
    structureIds: ['synchondrosis', 'symphysis'],
    taskType: 'select-all',
    prompt: 'Select the accurate cartilage relationships.',
    answer: ['Synchondrosis uses hyaline cartilage', 'Symphysis uses fibrocartilage'],
    acceptedAliases: [],
    options: ['Synchondrosis uses hyaline cartilage', 'Symphysis uses fibrocartilage', 'Synchondrosis has a synovial cavity', 'Symphysis is united by dense connective tissue'],
    explanation: 'A synchondrosis is a cartilaginous joint united by hyaline cartilage; a symphysis is a cartilaginous joint using fibrocartilage.',
    sourceId: JOINTS_SOURCE_ID,
    sourcePage: null,
    examPriority: false,
    verificationStatus: 'verified',
  },
  {
    id: 'q-depth-joints-capsule-components',
    moduleId: 'joints-ligaments',
    structureIds: ['articular-cartilage', 'joint-cavity', 'fibrous-capsule', 'synovial-membrane', 'synovial-fluid'],
    taskType: 'select-all',
    prompt: 'Select the accurate synovial-joint component statements.',
    answer: [
      'Articular cartilage covers the ends of bones',
      'The joint cavity contains synovial fluid',
      'The fibrous capsule forms the outer capsule layer',
      'The synovial membrane lines the inner capsule',
    ],
    acceptedAliases: [],
    options: [
      'Articular cartilage covers the ends of bones',
      'The joint cavity contains synovial fluid',
      'The fibrous capsule forms the outer capsule layer',
      'The synovial membrane lines the inner capsule',
      'Synovial fluid connects muscle to bone',
    ],
    explanation: 'Articular cartilage covers bone ends; the joint cavity contains synovial fluid; the fibrous capsule is external; and the synovial membrane lines the inner capsule.',
    sourceId: JOINTS_SOURCE_ID,
    sourcePage: null,
    examPriority: false,
    verificationStatus: 'verified',
  },
  {
    id: 'q-depth-joints-atlantoaxial',
    moduleId: 'joints-ligaments',
    structureIds: ['atlantoaxial-joint'],
    taskType: 'function-relationship',
    prompt: 'What movement is specifically associated with the atlantoaxial joint?',
    answer: 'Rotation that allows the head to turn',
    acceptedAliases: ['head rotation'],
    options: ['Rotation that allows the head to turn', 'Knee extension', 'Wrist flexion', 'Ankle plantarflexion'],
    explanation: 'The atlantoaxial joint allows rotation as the atlas turns around the dens of the axis.',
    sourceId: JOINTS_SOURCE_ID,
    sourcePage: null,
    examPriority: false,
    verificationStatus: 'verified',
  },
  {
    id: 'q-depth-joints-intervertebral',
    moduleId: 'joints-ligaments',
    structureIds: ['intervertebral-joints'],
    taskType: 'multiple-choice',
    prompt: 'Which structures are combined in the source description of intervertebral joints?',
    answer: 'Intervertebral discs and facet joints',
    acceptedAliases: [],
    options: ['Intervertebral discs and facet joints', 'A tooth and its socket', 'The patella and quadriceps tendon', 'The radial head and annular ligament'],
    explanation: 'Intervertebral joints combine discs and facet joints to distribute spinal load while protecting the cord.',
    sourceId: JOINTS_SOURCE_ID,
    sourcePage: null,
    examPriority: false,
    verificationStatus: 'verified',
  },
  {
    id: 'q-depth-joints-distal-radioulnar',
    moduleId: 'joints-ligaments',
    structureIds: ['distal-radioulnar-joint'],
    taskType: 'function-relationship',
    prompt: 'What forearm action is enabled by the distal radioulnar joint?',
    answer: 'Pronation and supination',
    acceptedAliases: ['forearm rotation'],
    options: ['Pronation and supination', 'Head rotation', 'Knee flexion', 'Spinal extension'],
    explanation: 'The distal radioulnar joint participates in radius rotation during pronation and supination.',
    sourceId: JOINTS_SOURCE_ID,
    sourcePage: null,
    examPriority: false,
    verificationStatus: 'verified',
  },
  {
    id: 'q-depth-joints-glenohumeral',
    moduleId: 'joints-ligaments',
    structureIds: ['glenohumeral-ligaments'],
    taskType: 'function-relationship',
    prompt: 'What is the relationship of the glenohumeral ligaments to the shoulder?',
    answer: 'They contribute to shoulder stability',
    acceptedAliases: [],
    options: ['They contribute to shoulder stability', 'They form the knee menisci', 'They hold the radial head to the ulna', 'They reinforce the medial ankle'],
    explanation: 'The glenohumeral ligaments are shoulder ligaments that help stabilize the mobile shoulder joint.',
    sourceId: JOINTS_SOURCE_ID,
    sourcePage: null,
    examPriority: false,
    verificationStatus: 'verified',
  },
  {
    id: 'q-depth-joints-acromioclavicular',
    moduleId: 'joints-ligaments',
    structureIds: ['acromioclavicular-ligament'],
    taskType: 'function-relationship',
    prompt: 'Which joint region is reinforced by the acromioclavicular ligament?',
    answer: 'The acromioclavicular region of the shoulder',
    acceptedAliases: ['acromioclavicular joint'],
    options: ['The acromioclavicular region of the shoulder', 'The medial ankle', 'The knee interior', 'The proximal radioulnar joint'],
    explanation: 'The acromioclavicular ligament is a shoulder ligament associated with the acromioclavicular region.',
    sourceId: JOINTS_SOURCE_ID,
    sourcePage: null,
    examPriority: false,
    verificationStatus: 'verified',
  },
  {
    id: 'q-depth-joints-annular',
    moduleId: 'joints-ligaments',
    structureIds: ['annular-ligament'],
    taskType: 'function-relationship',
    prompt: 'What does the annular ligament of the radius hold in place?',
    answer: 'The radial head against the ulna',
    acceptedAliases: ['radial head'],
    options: ['The radial head against the ulna', 'The femoral head in the acetabulum', 'The patella against the tibia', 'The talus inside the ankle mortise'],
    explanation: 'The annular ligament of radius holds the radial head against the ulna while allowing forearm rotation.',
    sourceId: JOINTS_SOURCE_ID,
    sourcePage: null,
    examPriority: false,
    verificationStatus: 'verified',
  },
  {
    id: 'q-depth-joints-interosseous',
    moduleId: 'joints-ligaments',
    structureIds: ['interosseous-membrane'],
    taskType: 'function-relationship',
    prompt: 'What bones are linked by the forearm interosseous membrane?',
    answer: 'Radius and ulna',
    acceptedAliases: [],
    options: ['Radius and ulna', 'Femur and tibia', 'Mandible and temporal bone', 'Tibia and talus'],
    explanation: 'The forearm interosseous membrane links the radius and ulna and is distinct from the annular ligament.',
    sourceId: JOINTS_SOURCE_ID,
    sourcePage: null,
    examPriority: false,
    verificationStatus: 'verified',
  },
  {
    id: 'q-depth-joints-patellar',
    moduleId: 'joints-ligaments',
    structureIds: ['patellar-ligament'],
    taskType: 'multiple-choice',
    prompt: 'Which structure continues from the quadriceps tendon below the patella?',
    answer: 'Patellar ligament',
    acceptedAliases: [],
    options: ['Patellar ligament', 'Annular ligament', 'Deltoid ligament', 'Iliofemoral ligament'],
    explanation: 'The patellar ligament continues from the quadriceps tendon and crosses the front of the knee.',
    sourceId: JOINTS_SOURCE_ID,
    sourcePage: null,
    examPriority: false,
    verificationStatus: 'verified',
  },
  {
    id: 'q-depth-joints-iliofemoral',
    moduleId: 'joints-ligaments',
    structureIds: ['iliofemoral-ligament'],
    taskType: 'function-relationship',
    prompt: 'Which joint does the iliofemoral ligament reinforce?',
    answer: 'Hip joint',
    acceptedAliases: [],
    options: ['Hip joint', 'Knee joint', 'Ankle joint', 'Temporomandibular joint'],
    explanation: 'The iliofemoral ligament is a hip ligament associated with the hip joint.',
    sourceId: JOINTS_SOURCE_ID,
    sourcePage: null,
    examPriority: false,
    verificationStatus: 'verified',
  },
  {
    id: 'q-depth-joints-lcl',
    moduleId: 'joints-ligaments',
    structureIds: ['lcl'],
    taskType: 'multiple-choice',
    prompt: 'Which knee ligament reinforces the lateral side of the knee?',
    answer: 'Lateral collateral ligament',
    acceptedAliases: ['LCL'],
    options: ['Lateral collateral ligament', 'Medial collateral ligament', 'Anterior cruciate ligament', 'Posterior cruciate ligament'],
    explanation: 'The lateral collateral ligament (LCL) is the lateral collateral stabilizer of the knee.',
    sourceId: JOINTS_SOURCE_ID,
    sourcePage: null,
    examPriority: false,
    verificationStatus: 'verified',
  },
];

export const foundationsPracticeExpansion: Question[] = [
  {
    id: 'q-depth-foundations-heart-location',
    moduleId: 'anatomy-foundations',
    structureIds: ['heart'],
    taskType: 'multiple-choice',
    prompt: 'In which broad body cavity is the heart located?',
    answer: 'Thoracic cavity',
    acceptedAliases: [],
    options: ['Thoracic cavity', 'Cranial cavity', 'Abdominopelvic cavity', 'Pelvic cavity'],
    explanation: 'The heart occupies the thoracic cavity.',
    sourceId: OPENSTAX_SOURCE_ID,
    sourcePage: null,
    examPriority: false,
    verificationStatus: 'verified',
  },
  {
    id: 'q-depth-foundations-lungs-location',
    moduleId: 'anatomy-foundations',
    structureIds: ['lungs'],
    taskType: 'multiple-choice',
    prompt: 'In which broad body cavity are the lungs located?',
    answer: 'Thoracic cavity',
    acceptedAliases: [],
    options: ['Thoracic cavity', 'Cranial cavity', 'Abdominopelvic cavity', 'Pelvic cavity'],
    explanation: 'The lungs occupy the thoracic cavity.',
    sourceId: OPENSTAX_SOURCE_ID,
    sourcePage: null,
    examPriority: false,
    verificationStatus: 'verified',
  },
  {
    id: 'q-depth-foundations-liver-location',
    moduleId: 'anatomy-foundations',
    structureIds: ['liver'],
    taskType: 'multiple-choice',
    prompt: 'Which broad cavity contains the liver as a digestive organ?',
    answer: 'Abdominopelvic cavity',
    acceptedAliases: [],
    options: ['Abdominopelvic cavity', 'Thoracic cavity', 'Cranial cavity', 'Vertebral cavity'],
    explanation: 'The liver is one of the digestive organs located in the abdominopelvic cavity.',
    sourceId: OPENSTAX_SOURCE_ID,
    sourcePage: null,
    examPriority: false,
    verificationStatus: 'verified',
  },
  {
    id: 'q-depth-foundations-stomach-location',
    moduleId: 'anatomy-foundations',
    structureIds: ['stomach'],
    taskType: 'multiple-choice',
    prompt: 'Which broad cavity contains the stomach?',
    answer: 'Abdominopelvic cavity',
    acceptedAliases: [],
    options: ['Abdominopelvic cavity', 'Thoracic cavity', 'Cranial cavity', 'Vertebral cavity'],
    explanation: 'The stomach is a digestive organ in the abdominopelvic cavity.',
    sourceId: OPENSTAX_SOURCE_ID,
    sourcePage: null,
    examPriority: false,
    verificationStatus: 'verified',
  },
  {
    id: 'q-depth-foundations-kidneys-location',
    moduleId: 'anatomy-foundations',
    structureIds: ['kidneys'],
    taskType: 'function-relationship',
    prompt: 'Which location description is supported for the kidneys?',
    answer: 'Posterior in the abdominal region',
    acceptedAliases: ['posterior abdomen'],
    options: ['Posterior in the abdominal region', 'Anterior neck', 'Thoracic cavity', 'Pelvic cavity'],
    explanation: 'The organ map places the kidneys posteriorly in the abdominal region.',
    sourceId: OPENSTAX_SOURCE_ID,
    sourcePage: null,
    examPriority: false,
    verificationStatus: 'verified',
  },
  {
    id: 'q-depth-foundations-spleen',
    moduleId: 'anatomy-foundations',
    structureIds: ['spleen'],
    taskType: 'function-relationship',
    prompt: 'Which description correctly identifies the spleen in the organ map?',
    answer: 'A left-sided lymphatic organ',
    acceptedAliases: ['left-sided lymphatic'],
    options: ['A left-sided lymphatic organ', 'A digestive organ in the anterior neck', 'A gland superior to the kidneys', 'A respiratory organ in the thorax'],
    explanation: 'The spleen is identified as left-sided and lymphatic, not digestive.',
    sourceId: OPENSTAX_SOURCE_ID,
    sourcePage: null,
    examPriority: false,
    verificationStatus: 'verified',
  },
];