import type { Question, Structure } from './model';
import { SKELETAL_APPENDICULAR_SOURCE_ID, SKELETAL_AXIAL_SOURCE_ID } from './systems.ts';

const axial = SKELETAL_AXIAL_SOURCE_ID;
const appendicular = SKELETAL_APPENDICULAR_SOURCE_ID;
const previouslyTestedSkeletalIds = new Set([
  'acromion', 'ankle-mortise', 'asis', 'capitate', 'cervical-vertebrae', 'coracoid-process',
  'costal-groove', 'dens', 'femoral-condyles', 'femoral-head', 'femoral-linea-aspera',
  'femoral-neck', 'fibula', 'foramen-magnum', 'foramen-ovale', 'greater-trochanter',
  'greater-tubercle', 'hook-of-hamate', 'humeral-head', 'iliac-crest', 'ischial-tuberosity',
  'lateral-malleolus', 'lumbar-vertebrae', 'mandibular-condyle', 'mandibular-coronoid',
  'medial-malleolus', 'obturator-foramen', 'olecranon', 'posterior-cranial-fossa',
  'radial-head', 'radial-styloid', 'radial-tuberosity', 'radius', 'rib-head', 'rib-tubercle',
  'scapular-spine', 'superior-costal-facet', 'thoracic-vertebrae', 'tibia', 'tibial-tuberosity',
  'transverse-foramen', 'trochlear-notch',
]);

const q = (
  id: string,
  structureIds: string[],
  taskType: Question['taskType'],
  prompt: string,
  answer: string | string[],
  options: string[] | undefined,
  explanation: string,
  sourceId: string,
): Question => ({
  id: `q-depth-skeletal-${id}`,
  moduleId: 'skeletal-system',
  structureIds,
  taskType,
  prompt,
  answer,
  acceptedAliases: [],
  ...(options ? { options } : {}),
  explanation,
  sourceId,
  sourcePage: null,
  examPriority: false,
  verificationStatus: 'verified',
});

export const skeletalPracticeExpansion: Question[] = [
  q('skull-regions', ['frontal-bone', 'parietal-bone', 'temporal-bone', 'occipital-bone', 'sphenoid-bone', 'ethmoid-bone'], 'select-all',
    'Select the bones classified as cranial bones rather than facial bones.',
    ['Frontal bone', 'Parietal bone', 'Temporal bone', 'Occipital bone', 'Sphenoid bone', 'Ethmoid bone'],
    ['Frontal bone', 'Parietal bone', 'Temporal bone', 'Occipital bone', 'Sphenoid bone', 'Ethmoid bone', 'Maxilla', 'Vomer'],
    'The frontal, parietal, temporal, occipital, sphenoid, and ethmoid bones form the cranium; maxilla and vomer are facial bones.', axial),
  q('skull-facial-group', ['maxilla', 'zygomatic-bone', 'nasal-bone', 'lacrimal-bone', 'palatine-bone', 'vomer', 'inferior-nasal-concha'], 'select-all',
    'Which structures belong to the facial skeleton?',
    ['Maxilla', 'Zygomatic bone', 'Nasal bone', 'Lacrimal bone', 'Palatine bone', 'Vomer', 'Inferior nasal concha'],
    ['Maxilla', 'Zygomatic bone', 'Nasal bone', 'Lacrimal bone', 'Palatine bone', 'Vomer', 'Inferior nasal concha', 'Parietal bone'],
    'These bones shape the orbit, nasal cavity, and face; the parietal bone is cranial.', axial),
  q('skull-sutures-order', ['sagittal-suture', 'coronal-suture', 'lambdoid-suture'], 'ordered-sequence',
    'Order these sutures from anterior to posterior along the cranial vault.',
    ['Coronal suture', 'Sagittal suture', 'Lambdoid suture'],
    ['Lambdoid suture', 'Coronal suture', 'Sagittal suture'],
    'The coronal suture separates frontal and parietal bones anteriorly; sagittal runs between parietals; lambdoid borders occipital posteriorly.', axial),
  q('suture-confusion', ['coronal-suture', 'sagittal-suture'], 'function-relationship',
    'Which relationship correctly distinguishes the sagittal suture from the coronal suture?',
    'Sagittal suture lies between the two parietal bones',
    ['Sagittal suture lies between the two parietal bones', 'Coronal suture lies between the two parietal bones', 'Lambdoid suture joins the mandible to the temporal bone', 'Sagittal suture surrounds the foramen magnum'],
    'The sagittal suture is midline between the parietal bones; the coronal suture separates frontal from parietal bone.', axial),
  q('orbital-fissures', ['optic-canal'], 'multiple-choice',
    'Which opening is the narrow passage associated with the optic nerve rather than an orbital fissure?',
    'Optic canal',
    ['Optic canal', 'Superior orbital fissure', 'Inferior orbital fissure', 'Foramen spinosum'],
    'The optic canal is distinct from the superior and inferior orbital fissures and transmits the optic nerve.', axial),
  q('cranial-openings', ['foramen-ovale', 'foramen-rotundum', 'foramen-spinosum', 'carotid-canal', 'hypoglossal-canal'], 'select-all',
    'Select the openings located in the cranial base.',
    ['Foramen ovale', 'Foramen rotundum', 'Foramen spinosum', 'Carotid canal', 'Hypoglossal canal'],
    ['Foramen ovale', 'Foramen rotundum', 'Foramen spinosum', 'Carotid canal', 'Hypoglossal canal', 'Mental foramen', 'Obturator foramen'],
    'These openings occur in the sphenoid, temporal, or occipital regions of the cranial base; mental and obturator foramina are elsewhere.', axial),
  q('foramen-round-spiny', ['foramen-rotundum', 'foramen-spinosum'], 'multiple-choice',
    'Which opening is named for being round, in contrast to the nearby spiny opening?',
    'Foramen rotundum',
    ['Foramen rotundum', 'Foramen spinosum', 'Stylomastoid foramen', 'Incisive foramen'],
    'Rotundum means round; foramen spinosum is the neighboring opening named for its spine-related margin.', axial),
  q('carotid-hypoglossal', ['carotid-canal', 'hypoglossal-canal'], 'function-relationship',
    'Which pairing best matches the two skull-base canals?',
    'Carotid canal is a vascular passage; hypoglossal canal is associated with the hypoglossal nerve',
    ['Carotid canal is a vascular passage; hypoglossal canal is associated with the hypoglossal nerve', 'Both are sutures of the cranial vault', 'Carotid canal is in the mandible; hypoglossal canal is in the maxilla', 'Both form the orbit'],
    'Their names and skull-base relationships distinguish the carotid canal from the hypoglossal canal.', axial),
  q('temporal-openings', ['stylomastoid-foramen', 'internal-acoustic-meatus', 'external-acoustic-meatus'], 'select-all',
    'Which structures are openings or passages associated with the temporal bone?',
    ['Stylomastoid foramen', 'Internal acoustic meatus', 'External acoustic meatus'],
    ['Stylomastoid foramen', 'Internal acoustic meatus', 'External acoustic meatus', 'Mental foramen'],
    'The stylomastoid foramen and acoustic meatuses are temporal-bone landmarks; the mental foramen is mandibular.', axial),
  q('palatal-openings', ['incisive-foramen', 'greater-palatin-foramen'], 'function-relationship',
    'Which relationship correctly places the palatal foramina?',
    'The incisive foramen is anterior, while the greater palatine foramen is posterolateral',
    ['The incisive foramen is anterior, while the greater palatine foramen is posterolateral', 'The greater palatine foramen is in the cranial vault, while the incisive foramen is occipital', 'Both foramina are in the mandible', 'Both are located in the temporal bone'],
    'The incisive foramen lies near the anterior hard palate; the greater palatine foramen is farther posterior and lateral.', axial),
  q('ethmoid-landmarks', ['cribriform-plate', 'crista-galli'], 'select-all',
    'Select the landmarks belonging to the ethmoid bone.',
    ['Cribriform plate', 'Crista galli', 'Uncinate process'],
    ['Cribriform plate', 'Crista galli', 'Uncinate process', 'Pterygoid process', 'Clivus'],
    'The cribriform plate, crista galli, and ethmoidal uncinate process are ethmoid landmarks; pterygoid process is sphenoid and clivus is skull base.', axial),
  q('cribriform-recognition', ['cribriform-plate', 'crista-galli'], 'function-relationship',
    'What relationship best identifies the cribriform plate and crista galli?',
    'The crista galli projects from the cribriform plate, which forms the nasal cavity roof',
    ['The crista galli projects from the cribriform plate, which forms the nasal cavity roof', 'The cribriform plate projects from the mandible', 'The crista galli is a rib landmark', 'Both are parts of the femur'],
    'These paired ethmoid landmarks are recognized by their projection and the plate forming the roof of the nasal cavity.', axial),
  q('sphenoid-landmarks', ['pterygoid-process', 'sella-turcica', 'foramen-ovale', 'foramen-rotundum', 'foramen-spinosum'], 'select-all',
    'Which structures are associated with the sphenoid bone?',
    ['Pterygoid process', 'Sella turcica', 'Foramen ovale', 'Foramen rotundum', 'Foramen spinosum'],
    ['Pterygoid process', 'Sella turcica', 'Foramen ovale', 'Foramen rotundum', 'Foramen spinosum', 'Mastoid process'],
    'The sphenoid bears the pterygoid processes, sella turcica, and the three named foramina; mastoid process is temporal.', axial),
  q('clivus-location', ['clivus'], 'multiple-choice',
    'Which skull-base landmark slopes toward the foramen magnum?',
    'Clivus',
    ['Clivus', 'Internal occipital crest', 'Crista galli', 'Zygomatic arch'],
    'The clivus is the sloping skull-base region anterior to the foramen magnum.', axial),
  q('occipital-internal', ['internal-occipital-crest'], 'function-relationship',
    'Which landmark is an internal ridge associated with the occipital bone and the foramen magnum?',
    'Internal occipital crest',
    ['Internal occipital crest', 'Crista galli', 'Greater tubercle', 'Iliac crest'],
    'The internal occipital crest is an occipital landmark on the internal skull surface near the foramen magnum.', axial),
  q('fossa-order', ['anterior-cranial-fossa', 'middle-cranial-fossa', 'posterior-cranial-fossa'], 'ordered-sequence',
    'Order the cranial fossae from anterior to posterior.',
    ['Anterior cranial fossa', 'Middle cranial fossa', 'Posterior cranial fossa'],
    ['Posterior cranial fossa', 'Anterior cranial fossa', 'Middle cranial fossa'],
    'The three depressions progress from anterior to middle to posterior along the cranial base.', axial),
  q('fossa-cues', ['anterior-cranial-fossa', 'middle-cranial-fossa', 'posterior-cranial-fossa'], 'select-all',
    'Select the statements that correctly use cranial-fossa position as a recognition cue.',
    ['Anterior cranial fossa is most anterior', 'Posterior cranial fossa is nearest the foramen magnum', 'Middle cranial fossa lies between the other two'],
    ['Anterior cranial fossa is most anterior', 'Posterior cranial fossa is nearest the foramen magnum', 'Middle cranial fossa lies between the other two', 'Posterior cranial fossa is part of the mandible'],
    'The names describe their relative positions at the cranial base; the foramen magnum is in the occipital region.', axial),
  q('cervical-curves', ['cervical-lordosis', 'thoracic-kyphosis', 'lumbar-lordosis'], 'ordered-sequence',
    'Order these spinal curves from superior to inferior.',
    ['Cervical lordosis', 'Thoracic kyphosis', 'Lumbar lordosis'],
    ['Lumbar lordosis', 'Cervical lordosis', 'Thoracic kyphosis'],
    'The cervical curve is in the neck, thoracic curve in the chest, and lumbar curve in the lower back.', axial),
  q('curve-confusion', ['thoracic-kyphosis'], 'multiple-choice',
    'Which curve is the kyphotic thoracic region rather than a lordotic cervical or lumbar region?',
    'Thoracic kyphosis',
    ['Thoracic kyphosis', 'Cervical lordosis', 'Lumbar lordosis', 'Cervical vertebrae'],
    'Thoracic kyphosis names the posteriorly convex thoracic curve; cervical and lumbar curves are lordotic.', axial),
  q('cervical-uncinate', ['uncinate-process-vertebra'], 'function-relationship',
    'Which named landmark projects from the superior-lateral margin of a cervical vertebral body?',
    'Uncinate process of cervical vertebra',
    ['Uncinate process of cervical vertebra', 'Superior costal facet', 'Mammillary process', 'Hook of hamate'],
    'The uncinate process of cervical vertebra is a cervical-region cue, unlike thoracic costal facets or lumbar mammillary processes.', axial),
  q('thoracic-facets', ['superior-costal-facet', 'inferior-costal-facet', 'thoracic-vertebrae'], 'select-all',
    'Which landmarks indicate that a vertebra is in the thoracic region?',
    ['Superior costal facet', 'Inferior costal facet'],
    ['Superior costal facet', 'Inferior costal facet', 'Transverse foramen', 'Mammillary process'],
    'Thoracic vertebrae have costal facets for rib articulation; transverse foramina are cervical and mammillary processes are lumbar cues.', axial),
  q('lumbar-processes', ['accessory-process', 'lumbar-vertebrae'], 'function-relationship',
    'Which relationship is a useful lumbar-vertebra recognition cue?',
    'Mammillary and accessory processes occur on lumbar vertebrae',
    ['Mammillary and accessory processes occur on lumbar vertebrae', 'Costal facets occur only on lumbar vertebrae', 'Transverse foramina occur only on lumbar vertebrae', 'The dens projects from a lumbar vertebra'],
    'Mammillary and accessory processes are posterior landmarks of lumbar vertebrae.', axial),
  q('carpal-proximal-row', ['scaphoid', 'lunate', 'triquetrum', 'pisiform'], 'ordered-sequence',
    'Order the proximal carpal row from lateral (thumb side) to medial (little-finger side).',
    ['Scaphoid', 'Lunate', 'Triquetrum', 'Pisiform'],
    ['Pisiform', 'Scaphoid', 'Triquetrum', 'Lunate'],
    'The proximal row proceeds scaphoid, lunate, triquetrum, then pisiform from lateral to medial.', appendicular),
  q('carpal-distal-row', ['trapezium', 'trapezoid', 'capitate', 'hamate'], 'ordered-sequence',
    'Order the distal carpal row from lateral to medial.',
    ['Trapezium', 'Trapezoid', 'Capitate', 'Hamate'],
    ['Capitate', 'Hamate', 'Trapezium', 'Trapezoid'],
    'The distal row is trapezium, trapezoid, capitate, and hamate from thumb side to little-finger side.', appendicular),
  q('carpal-row-cues', ['scaphoid', 'lunate', 'triquetrum', 'pisiform'], 'select-all',
    'Select the bones that belong to the proximal carpal row.',
    ['Scaphoid', 'Lunate', 'Triquetrum', 'Pisiform'],
    ['Scaphoid', 'Lunate', 'Triquetrum', 'Pisiform', 'Trapezium', 'Capitate'],
    'Scaphoid, lunate, triquetrum, and pisiform form the proximal row; trapezium and capitate are distal-row carpals.', appendicular),
  q('carpal-thumb', ['trapezium'], 'bone-laterality',
    'Which carpal lies on the thumb side of the distal row and supports the first metacarpal?',
    'Trapezium',
    ['Trapezium', 'Trapezoid', 'Capitate', 'Hamate'],
    'The trapezium is the lateral distal-row carpal associated with the thumb side of the hand.', appendicular),
  q('carpal-central-cues', ['scaphoid', 'lunate', 'capitate'], 'function-relationship',
    'Which statement best separates the capitate from the scaphoid and lunate?',
    'Capitate is a distal-row central carpal, whereas scaphoid and lunate are proximal-row carpals',
    ['Capitate is a distal-row central carpal, whereas scaphoid and lunate are proximal-row carpals', 'Capitate is a tarsal and scaphoid is a femur landmark', 'Scaphoid and lunate are distal-row bones only', 'All three are metacarpals'],
    'Row and position are reliable recognition cues: capitate is central in the distal row, while scaphoid and lunate are proximal.', appendicular),
  q('hamate-hook', ['hamate'], 'function-relationship',
    'What relationship identifies the hook of hamate?',
    'It is a palmar projection of the hamate',
    ['It is a palmar projection of the hamate', 'It is a projection of the radius', 'It is the proximal head of the femur', 'It is a process of the talus'],
    'The hook is a palpable palmar landmark belonging to the hamate carpal.', appendicular),
  q('tarsal-group', ['navicular', 'medial-cuneiform', 'intermediate-cuneiform', 'lateral-cuneiform', 'cuboid'], 'select-all',
    'Select the tarsals that lie anterior to the talus in the midfoot.',
    ['Navicular', 'Medial cuneiform', 'Intermediate cuneiform', 'Lateral cuneiform', 'Cuboid'],
    ['Navicular', 'Medial cuneiform', 'Intermediate cuneiform', 'Lateral cuneiform', 'Cuboid', 'Scaphoid'],
    'The navicular, three cuneiforms, and cuboid occupy the midfoot anterior to the talus; scaphoid is a carpal.', appendicular),
  q('tarsal-medial-order', ['navicular', 'medial-cuneiform', 'intermediate-cuneiform', 'lateral-cuneiform'], 'ordered-sequence',
    'Order the three cuneiforms from medial to lateral; identify their proximal neighbor.',
    ['Medial cuneiform', 'Intermediate cuneiform', 'Lateral cuneiform'],
    ['Lateral cuneiform', 'Medial cuneiform', 'Intermediate cuneiform'],
    'The navicular is proximal to all three cuneiforms; the cuneiforms lie side-by-side in medial, intermediate, and lateral order rather than in a proximal-to-distal row.', appendicular),
  q('cuboid-lateral', ['cuboid', 'navicular'], 'bone-laterality',
    'Which tarsal is the lateral midfoot counterpart to the more medial navicular/cuneiform group?',
    'Cuboid',
    ['Cuboid', 'Navicular', 'Medial cuneiform', 'Intermediate cuneiform'],
    'Cuboid is the lateral midfoot tarsal, while the navicular and cuneiforms occupy the more medial/central pathway.', appendicular),
  q('ankle-bones', ['tibia', 'fibula', 'talus', 'ankle-mortise'], 'function-relationship',
    'Which relationship correctly describes the ankle mortise?',
    'Tibia and fibula form the mortise around the talus',
    ['Tibia and fibula form the mortise around the talus', 'Talus forms a mortise around the femur', 'Radius and ulna form the mortise around the lunate', 'Calcaneus forms a mortise around the tibia'],
    'The distal tibia and fibula bracket the talus to form the ankle mortise.', appendicular),
  q('tibial-plateau', ['tibial-plateau'], 'function-relationship',
    'Which surface receives the femoral condyles at the knee?',
    'Tibial plateau',
    ['Tibial plateau', 'Linea aspera', 'Radial tuberosity', 'Ankle mortise'],
    'The tibial plateau is the proximal tibial articular region that receives the femoral condyles.', appendicular),
  q('intercondylar-eminence', ['intercondylar-eminence', 'tibial-plateau', 'tibia'], 'multiple-choice',
    'Where is the intercondylar eminence located?',
    'Between the articular regions of the tibial plateau',
    ['Between the articular regions of the tibial plateau', 'On the posterior shaft of the femur', 'At the distal radius', 'Inside the ankle mortise'],
    'The intercondylar eminence rises between the medial and lateral areas of the tibial plateau.', appendicular),
  q('radius-landmarks-new', ['radial-head'], 'ordered-sequence',
    'Order these radius landmarks from proximal to distal.',
    ['Head of radius', 'Radial tuberosity', 'Radial styloid process'],
    ['Radial styloid process', 'Radial tuberosity', 'Head of radius'],
    'The head of radius is proximal, the tuberosity lies near the proximal shaft, and the styloid is distal.', appendicular),
  q('ulnar-styloid-side', ['ulnar-styloid'], 'bone-laterality',
    'Which distal forearm landmark belongs to the medial, little-finger-side bone?',
    'Ulnar styloid process',
    ['Ulnar styloid process', 'Radial styloid process', 'Olecranon', 'Radial tuberosity'],
    'The ulna is medial in anatomical position and ends distally in the ulnar styloid process.', appendicular),
  q('axial-vertebral-group', ['atlas-c1', 'axis-c2', 'sacrum', 'coccyx'], 'ordered-sequence',
    'Order these axial structures from superior to inferior.',
    ['Atlas (C1)', 'Axis (C2)', 'Sacrum', 'Coccyx'],
    ['Coccyx', 'Axis (C2)', 'Atlas (C1)', 'Sacrum'],
    'C1 and C2 are superior cervical vertebrae; the sacrum and coccyx are inferior terminal regions of the column.', axial),
  q('thoracic-cage-groups', ['true-ribs', 'false-ribs', 'floating-ribs'], 'select-all',
    'Select the rib groups classified by their anterior attachment pattern.',
    ['True ribs', 'False ribs', 'Floating ribs'],
    ['True ribs', 'False ribs', 'Floating ribs', 'Cervical ribs'],
    'The named groups distinguish ribs by direct, indirect, or absent anterior sternal attachment.', axial),
  q('sternum-order', ['manubrium', 'body-of-sternum', 'xiphoid-process'], 'ordered-sequence',
    'Order the sternum parts from superior to inferior.',
    ['Manubrium', 'Body of sternum', 'Xiphoid process'],
    ['Xiphoid process', 'Body of sternum', 'Manubrium'],
    'The manubrium is superior, the body is central, and the xiphoid process is inferior.', axial),
  q('pelvic-regions', ['ilium', 'ischium', 'pubis', 'acetabulum'], 'select-all',
    'Select the three regions that unite to form the hip bone around the acetabulum.',
    ['Ilium', 'Ischium', 'Pubis'],
    ['Ilium', 'Ischium', 'Pubis', 'Sacrum', 'Femur'],
    'The ilium, ischium, and pubis contribute to the hip bone and meet at the acetabulum; sacrum and femur are neighboring bones.', appendicular),
  q('shoulder-girdle', ['clavicle', 'scapula', 'glenoid-cavity'], 'function-relationship',
    'Which relationship correctly describes the pectoral girdle?',
    'Clavicle and scapula connect the upper limb, with the glenoid cavity receiving the humeral head',
    ['Clavicle and scapula connect the upper limb, with the glenoid cavity receiving the humeral head', 'Ilium and pubis form the shoulder socket', 'The acromion receives the femoral head', 'The scapula is part of the vertebral column'],
    'The clavicle and scapula form the pectoral girdle; the glenoid cavity is its lateral shoulder socket.', appendicular),
  q('lower-limb-recognition', ['femur', 'tibia', 'fibula', 'patella'], 'select-all',
    'Select the bones of the lower limb between the pelvic girdle and the ankle.',
    ['Femur', 'Patella', 'Tibia', 'Fibula'],
    ['Femur', 'Patella', 'Tibia', 'Fibula', 'Humerus', 'Radius'],
    'Femur, patella, tibia, and fibula make up the thigh/knee/leg region; humerus and radius are upper-limb bones.', appendicular),
  q('foot-sequence', ['talus', 'navicular', 'metatarsals', 'phalanges-foot'], 'ordered-sequence',
    'Order these foot structures from proximal to distal.',
    ['Talus', 'Navicular', 'Metatarsals', 'Phalanges of foot'],
    ['Phalanges of foot', 'Talus', 'Metatarsals', 'Navicular'],
    'The talus is proximal, followed by navicular in the tarsal region, then metatarsals and toe phalanges.', appendicular),
  q('hand-sequence', ['carpals', 'metacarpals', 'phalanges-hand'], 'ordered-sequence',
    'Order these hand regions from proximal to distal.',
    ['Carpals', 'Metacarpals', 'Phalanges of hand'],
    ['Phalanges of hand', 'Carpals', 'Metacarpals'],
    'Carpals form the wrist, metacarpals the palm, and phalanges the fingers.', appendicular),
  q('skull-orientation', ['mandible', 'maxilla', 'nasal-bone'], 'bone-laterality',
    'Which facial bone is the mobile lower jaw rather than a fixed upper-jaw or cheek-region bone?',
    'Mandible',
    ['Mandible', 'Maxilla', 'Zygomatic bone', 'Nasal bone'],
    'The mandible is the mobile lower jaw; maxilla, zygomatic, and nasal bones are fixed facial bones.', axial),
  q('hyoid-region', ['hyoid'], 'function-relationship',
    'Which structure is a free-standing neck bone that does not directly articulate with another bone?',
    'Hyoid bone',
    ['Hyoid bone', 'Mandible', 'Sternum', 'Clavicle'],
    'The hyoid is suspended by muscles and ligaments in the neck rather than forming a direct bony joint.', axial),
  q('vertebral-landmark-group', ['vertebral-body', 'vertebral-foramen', 'spinous-process', 'transverse-process'], 'select-all',
    'Select the structures that are typical landmarks of an individual vertebra.',
    ['Vertebral body', 'Vertebral foramen', 'Spinous process', 'Transverse process'],
    ['Vertebral body', 'Vertebral foramen', 'Spinous process', 'Transverse process', 'Acetabulum'],
    'A typical vertebra has a body, central vertebral foramen, and projecting spinous and transverse processes.', axial),
  q('rib-landmark-order', ['rib-head', 'rib-tubercle', 'costal-groove'], 'ordered-sequence',
    'Order these rib landmarks from posterior/proximal articulation toward the inferior border cue.',
    ['Head of rib', 'Tubercle of rib', 'Costal groove'],
    ['Costal groove', 'Tubercle of rib', 'Head of rib'],
    'The rib head is posterior at the vertebral end, the tubercle lies lateral to it, and the costal groove runs along the inferior internal border.', axial),
  q('scapular-landmarks', ['scapular-spine', 'acromion', 'coracoid-process', 'glenoid-cavity'], 'select-all',
    'Select the structures that are scapular landmarks.',
    ['Spine of scapula', 'Acromion', 'Coracoid process', 'Glenoid cavity'],
    ['Spine of scapula', 'Acromion', 'Coracoid process', 'Glenoid cavity', 'Acetabulum'],
    'The spine, acromion, coracoid process, and glenoid cavity belong to the scapula; the acetabulum is in the pelvis.', appendicular),
  q('humerus-landmark-group', ['humeral-head', 'greater-tubercle', 'deltoid-tuberosity', 'capitulum', 'trochlea'], 'select-all',
    'Select the landmarks belonging to the humerus.',
    ['Head of humerus', 'Greater tubercle of humerus', 'Deltoid tuberosity', 'Capitulum of humerus', 'Trochlea of humerus'],
    ['Head of humerus', 'Greater tubercle of humerus', 'Deltoid tuberosity', 'Capitulum of humerus', 'Trochlea of humerus', 'Radial tuberosity'],
    'The listed head, tubercle, tuberosity, capitulum, and trochlea are humeral landmarks; radial tuberosity belongs to the radius.', appendicular),
  q('elbow-landmarks', ['capitulum', 'trochlea'], 'function-relationship',
    'Which relationship correctly distinguishes the elbow articular landmarks?',
    'Capitulum of humerus articulates with the radius, while trochlea of humerus articulates with the ulna',
    ['Capitulum of humerus articulates with the radius, while trochlea of humerus articulates with the ulna', 'Trochlea of humerus articulates with the radius, while capitulum of humerus articulates with the femur', 'Olecranon is a humeral articular surface', 'Both epicondyles are articular surfaces for the wrist'],
    'The capitulum of humerus is the lateral humeral surface for the radial head; the trochlea of humerus is the spool-shaped surface for the ulna.', appendicular),
  q('pelvis-landmark-group', ['iliac-crest', 'asis', 'ischial-tuberosity', 'obturator-foramen'], 'select-all',
    'Select the landmarks found on the hip bone.',
    ['Iliac crest', 'Anterior superior iliac spine', 'Ischial tuberosity', 'Obturator foramen'],
    ['Iliac crest', 'Anterior superior iliac spine', 'Ischial tuberosity', 'Obturator foramen', 'Greater trochanter'],
    'The crest, ASIS, ischial tuberosity, and obturator foramen are pelvic landmarks; the greater trochanter is femoral.', appendicular),
  q('hip-landmarks', ['greater-trochanter', 'acetabulum'], 'function-relationship',
    'Which relationship identifies the hip articulation?',
    'The femoral head passes through the femoral neck to enter the acetabulum; the greater trochanter is lateral',
    ['The femoral head passes through the femoral neck to enter the acetabulum; the greater trochanter is lateral', 'The femoral head enters the glenoid cavity', 'The greater trochanter is part of the tibia', 'The femoral neck is a carpal'],
    'The femoral head is proximal to the neck and articulates with the acetabulum; the greater trochanter projects laterally.', appendicular),
  q('leg-landmarks-group', ['tibial-tuberosity', 'medial-malleolus', 'lateral-malleolus', 'tibia', 'fibula'], 'select-all',
    'Select the correct bone-landmark pairings for the leg.',
    ['Tibial tuberosity—tibia', 'Medial malleolus—tibia', 'Lateral malleolus—fibula'],
    ['Tibial tuberosity—tibia', 'Medial malleolus—tibia', 'Lateral malleolus—fibula', 'Lateral malleolus—femur'],
    'The tibia bears the tibial tuberosity and medial malleolus; the fibula forms the lateral malleolus.', appendicular),
  q('bone-orientation-upper', ['ulna'], 'bone-laterality',
    'In anatomical position, which pairing places each forearm bone and its distal styloid correctly?',
    'Radius—thumb side with radial styloid; ulna—little-finger side with ulnar styloid',
    ['Radius—thumb side with radial styloid; ulna—little-finger side with ulnar styloid', 'Radius—little-finger side with ulnar styloid; ulna—thumb side with radial styloid', 'Both styloids belong to the radius', 'Both bones lie on the thumb side'],
    'The radius is lateral and thumb-side; the ulna is medial and little-finger-side in anatomical position.', appendicular),
  q('axial-articulations', ['occipital-condyles', 'dens'], 'function-relationship',
    'Which relationship distinguishes the two upper cervical articulations?',
    'Occipital condyles articulate with atlas, while atlas rotates around the dens of axis',
    ['Occipital condyles articulate with atlas, while atlas rotates around the dens of axis', 'Dens articulates directly with the femur', 'Atlas is the second cervical vertebra with the dens', 'Occipital condyles form the ankle mortise'],
    'The occipital condyles meet C1; the dens of C2 provides the pivot for atlantoaxial rotation.', axial),
  q('foramen-location-cues', ['mental-foramen', 'supraorbital-foramen', 'obturator-foramen', 'foramen-magnum'], 'select-all',
    'Select the opening-to-region pairings that are correct.',
    ['Mental foramen—mandible', 'Supraorbital foramen—frontal bone', 'Obturator foramen—pelvis', 'Foramen magnum—occipital bone'],
    ['Mental foramen—mandible', 'Supraorbital foramen—frontal bone', 'Obturator foramen—pelvis', 'Foramen magnum—occipital bone', 'Mental foramen—temporal bone'],
    'These openings are recognized by region: mandible, frontal bone, pelvic hip bone, and occipital bone respectively.', axial),
  q('articulation-sockets', ['glenoid-cavity', 'acetabulum', 'humeral-head', 'femoral-head'], 'select-all',
    'Select the correctly matched socket-and-head relationships.',
    ['Glenoid cavity—head of humerus', 'Acetabulum—head of femur'],
    ['Glenoid cavity—head of humerus', 'Acetabulum—head of femur', 'Glenoid cavity—head of femur', 'Acetabulum—head of humerus'],
    'The glenoid cavity receives the humeral head at the shoulder; the acetabulum receives the femoral head at the hip.', appendicular),
  q('bone-region-confusions', ['carpals', 'tarsals', 'metacarpals', 'metatarsals'], 'multiple-choice',
    'Which pairing correctly distinguishes the wrist/hand from the ankle/foot?',
    'Carpals are wrist bones and tarsals are ankle/foot bones',
    ['Carpals are wrist bones and tarsals are ankle/foot bones', 'Tarsals are wrist bones and carpals are ankle bones', 'Metacarpals are ankle bones and metatarsals are wrist bones', 'Carpals are toe bones and tarsals are finger bones'],
    'Carpals occupy the wrist and tarsals occupy the ankle/foot; metacarpals and metatarsals are the palm and midfoot bones.', appendicular),
  q('typed-ethmoid-ridge', ['crista-galli'], 'typed-recall',
    'What ethmoid projection rises superiorly from the cribriform plate?',
    'Crista galli',
    undefined,
    'Crista galli is the midline ethmoid projection associated with the cribriform plate.', axial),
  q('typed-foot-bone', ['navicular'], 'typed-recall',
    'Which tarsal lies immediately anterior to the talus and proximal to the cuneiforms?',
    'Navicular',
    undefined,
    'The navicular occupies this proximal midfoot position between talus and cuneiforms.', appendicular),
  q('typed-ulnar-landmark', ['ulnar-styloid'], 'typed-recall',
    'What distal landmark names the projection of the ulna on the little-finger side?',
    'Ulnar styloid process',
    undefined,
    'The ulnar styloid process is the distal projection of the ulna on its medial side in anatomical position.', appendicular),
  q('typed-sphenoid-process', ['pterygoid-process'], 'typed-recall',
    'Which sphenoid process projects inferiorly and contributes to the attachment region of the pterygoid area?',
    'Pterygoid process',
    undefined,
    'The pterygoid process is a paired inferior projection of the sphenoid.', axial),
  q('typed-cervical-landmark', ['uncinate-process-vertebra'], 'typed-recall',
    'What cervical vertebral landmark projects from the superior-lateral margin of its body?',
    'Uncinate process of cervical vertebra',
    undefined,
    'The uncinate process of a cervical vertebra is a regional recognition landmark.', axial),
  q('axial-appendicular', ['skull', 'atlas-c1', 'sternum', 'clavicle', 'pelvis'], 'select-all',
    'Select the structures that belong to the axial skeleton or its thoracic cage, not the appendicular girdles.',
    ['Skull', 'Atlas (C1)', 'Sternum'],
    ['Skull', 'Atlas (C1)', 'Sternum', 'Clavicle', 'Pelvic girdle'],
    'The skull, vertebral column (represented here by C1), and sternum are axial; the clavicle and pelvic girdle are appendicular.', axial),
  q('appendicular-groups', ['clavicle', 'scapula', 'pelvis', 'humerus', 'femur'], 'select-all',
    'Select the appendicular structures from this mixed group.',
    ['Clavicle', 'Scapula', 'Pelvic girdle', 'Humerus', 'Femur'],
    ['Clavicle', 'Scapula', 'Pelvic girdle', 'Humerus', 'Femur', 'Sternum'],
    'The girdles and limb bones are appendicular; the sternum is part of the axial thoracic cage.', appendicular),
];

/** Returns question/structure pairs that are not explicitly named in answer evidence. */
export const auditSkeletalPracticeExpansionSemantics = (structures: Structure[]): string[] => {
  const byId = new Map(structures.map((structure) => [structure.id, structure]));
  return skeletalPracticeExpansion.flatMap((question) => {
    const evidence = `${Array.isArray(question.answer) ? question.answer.join(' ') : question.answer} ${question.explanation ?? ''}`.toLowerCase();
    return question.structureIds
      .filter((structureId) => {
        const structure = byId.get(structureId);
        return !structure || ![structure.canonicalName, ...structure.acceptedAliases]
          .some((term) => evidence.includes(term.toLowerCase()));
      })
      .map((structureId) => `${question.id}:${structureId}`);
  });
};