import type { Question } from './model';
import { organSystemsStructures } from './organ-systems.ts';

const normalizeEvidence = (value: string) => value.toLocaleLowerCase().replace(/[^a-z0-9]+/g, ' ').replace(/\b(the|a|an)\b/g, '').replace(/\b(\w+)s\b/g, '$1').replace(/\s+/g, ' ').trim();
const organStructureNames = new Map(organSystemsStructures.map((structure) => [structure.id, [structure.canonicalName, ...structure.acceptedAliases].map(normalizeEvidence)]));

const make = (
  id: string,
  moduleId: string,
  structureIds: string[],
  taskType: Question['taskType'],
  prompt: string,
  answer: string | string[],
  options: string[] | undefined,
  explanation: string,
  sourceId: string,
): Question => ({
  id, moduleId, structureIds: structureIds.filter((structureId) => {
    const names = organStructureNames.get(structureId);
    if (!names) return true;
    const evidence = normalizeEvidence(`${Array.isArray(answer) ? answer.join(' ') : answer} ${explanation}`);
    return names.some((name) => evidence.includes(name));
  }), taskType, prompt, answer, acceptedAliases: [],
  options, explanation, sourceId, sourcePage: null, examPriority: false,
  verificationStatus: 'verified',
});

const R = 'source-openstax-ap-2013-respiratory';
const D = 'source-openstax-ap-2013-digestive';
const U = 'source-openstax-ap-2013-urinary';
const M = 'source-openstax-ap-2013-male-reproductive';
const F = 'source-openstax-ap-2013-female-reproductive';

export const respiratoryPracticeExpansion: Question[] = [
  make('q-depth-resp-airflow', 'respiratory-system',
    ['respiratory-system-nasal-cavity','respiratory-system-nasopharynx','respiratory-system-oropharynx','respiratory-system-laryngopharynx','respiratory-system-larynx','respiratory-system-trachea','respiratory-system-carina','respiratory-system-right-main-bronchus','respiratory-system-lobar-bronchus','respiratory-system-segmental-bronchus','respiratory-system-terminal-bronchiole','respiratory-system-respiratory-bronchiole','respiratory-system-alveolar-duct','respiratory-system-alveolus'],
    'ordered-sequence','Order airflow from the upper airway to the gas-exchange surface.',
    ['Nasal cavity','Nasopharynx','Oropharynx','Laryngopharynx','Larynx','Trachea','Carina','Right main bronchus','Lobar bronchus','Segmental bronchus','Terminal bronchiole','Respiratory bronchiole','Alveolar duct','Alveolus'],
    ['Alveolus','Nasal cavity','Trachea','Carina','Nasopharynx','Lobar bronchus','Oropharynx','Segmental bronchus','Laryngopharynx','Right main bronchus','Terminal bronchiole','Larynx','Alveolar duct','Respiratory bronchiole'],
    'The conducting passages precede the respiratory zone.', R),
  make('q-depth-resp-sinuses','respiratory-system',['respiratory-system-frontal-sinus','respiratory-system-maxillary-sinus','respiratory-system-ethmoidal-sinus','respiratory-system-sphenoidal-sinus'],'select-all','Which named spaces are paranasal sinuses?',['Frontal sinus','Maxillary sinus','Ethmoidal sinus','Sphenoidal sinus'],['Frontal sinus','Maxillary sinus','Ethmoidal sinus','Sphenoidal sinus','Pleural cavity'],'These four spaces surround the nasal cavity in the skull.',R),
  make('q-depth-resp-nasal-boundaries','respiratory-system',['respiratory-system-nasal-vestibule','respiratory-system-nasal-cavity','respiratory-system-nasal-septum','respiratory-system-choanae'],'function-relationship','Which structures together orient the nasal passage from its entrance toward the pharynx?',['Nasal vestibule','Nasal cavity','Nasal septum','Choanae'],['Nasal vestibule','Nasal cavity','Nasal septum','Choanae','Pleural cavity'],'The nasal vestibule is the entrance, the nasal septum divides the nasal cavity, and the choanae open posteriorly toward the pharynx.',R),
  make('q-depth-resp-larynx','respiratory-system',['respiratory-system-epiglottis','respiratory-system-thyroid-cartilage','respiratory-system-cricoid-cartilage','respiratory-system-arytenoid-cartilage','respiratory-system-vocal-folds','respiratory-system-vestibular-folds'],'select-all','Select laryngeal structures in this list.',['Epiglottis','Thyroid cartilage','Cricoid cartilage','Arytenoid cartilage','Vocal folds','Vestibular folds'],['Epiglottis','Thyroid cartilage','Cricoid cartilage','Arytenoid cartilage','Vocal folds','Vestibular folds','Carina'],'All selected structures belong to the larynx.',R),
  make('q-depth-resp-larynx-relation','respiratory-system',['respiratory-system-epiglottis','respiratory-system-vocal-folds','respiratory-system-larynx'],'function-relationship','Which relationship correctly pairs laryngeal structures with their location?','The epiglottis and vocal folds are structures of the larynx',['The epiglottis and vocal folds are structures of the larynx','Carina is within the nasal cavity','Epiglottis is a pleural layer','Larynx is a lung lobe'],'The epiglottis and vocal folds are both laryngeal structures.',R),
  make('q-depth-resp-branching','respiratory-system',['respiratory-system-left-main-bronchus','respiratory-system-lobar-bronchus','respiratory-system-segmental-bronchus'],'ordered-sequence','Order the bronchial branches after the trachea.',['Left main bronchus','Lobar bronchus','Segmental bronchus'],['Segmental bronchus','Left main bronchus','Lobar bronchus'],'A main bronchus divides into a lobar bronchus and then a segmental bronchus.',R),
  make('q-depth-resp-lungs','respiratory-system',['respiratory-system-right-lung','respiratory-system-left-lung','respiratory-system-superior-lobe','respiratory-system-middle-lobe','respiratory-system-inferior-lobe','respiratory-system-cardiac-notch'],'select-all','Select the structures that distinguish the two lungs or their lobes.',['Right lung','Left lung','Superior lobe','Middle lobe','Inferior lobe','Cardiac notch'],['Right lung','Left lung','Superior lobe','Middle lobe','Inferior lobe','Cardiac notch','Carina'],'The middle lobe is a right-lung landmark and the cardiac notch is a left-lung landmark.',R),
  make('q-depth-resp-fissures','respiratory-system',['respiratory-system-horizontal-fissure'],'function-relationship','Which fissure separates the right superior and middle lobes?','Horizontal fissure',['Horizontal fissure','Oblique fissure','Cardiac notch','Pleural cavity'],'The horizontal fissure separates the superior and middle right-lung lobes.',R),
  make('q-depth-resp-root','respiratory-system',['respiratory-system-hilum-of-lung','respiratory-system-root-of-lung'],'function-relationship','Which relationship is anatomically correct?','The root of the lung passes through the hilum',['The root of the lung passes through the hilum','The hilum is inside an alveolus','The root is a pleural cavity','The hilum separates the lobes'],'The hilum is the entry and exit region for the root of the lung.',R),
  make('q-depth-resp-pleura','respiratory-system',['respiratory-system-visceral-pleura','respiratory-system-parietal-pleura','respiratory-system-pleural-cavity'],'function-relationship','Which arrangement is correct from lung surface outward?','Visceral pleura, pleural cavity, parietal pleura',['Parietal pleura, visceral pleura, pleural cavity','Visceral pleura, pleural cavity, parietal pleura','Pleural cavity, lung, visceral pleura','Visceral pleura, lung, parietal pleura'],'The pleural cavity lies between visceral pleura and parietal pleura.',R),
  make('q-depth-resp-mechanics','respiratory-system',['respiratory-system-diaphragm','respiratory-system-pleural-cavity'],'function-relationship','Which relationship describes the diaphragm and pleural cavity during ventilation?','Diaphragm movement changes thoracic volume and the pleural cavity transmits that movement to the lungs',['Diaphragm movement changes thoracic volume and the pleural cavity transmits that movement to the lungs','The diaphragm lines the pleural cavity','The pleural cavity is an airway','The diaphragm is an alveolar cell'],'The diaphragm changes thoracic volume; the pleural cavity is the potential space between pleural layers.',R),
  make('q-depth-resp-zone','respiratory-system',['respiratory-system-respiratory-bronchiole','respiratory-system-alveolar-duct','respiratory-system-alveolar-sac','respiratory-system-alveolus'],'ordered-sequence','Order these respiratory-zone passages toward an individual air space.',['Respiratory bronchiole','Alveolar duct','Alveolar sac','Alveolus'],['Alveolus','Alveolar sac','Respiratory bronchiole','Alveolar duct'],'The respiratory bronchiole leads to ducts, sacs, and alveoli.',R),
  make('q-depth-resp-sac','respiratory-system',['respiratory-system-alveolar-sac'],'function-relationship','Which structure is a cluster of alveoli at the end of an alveolar duct?','Alveolar sac',['Alveolar sac','Terminal bronchiole','Carina','Hilum of lung'],'An alveolar sac is a grouping of alveoli.',R),
  make('q-depth-resp-membrane','respiratory-system',['respiratory-system-type-i-pneumocyte','respiratory-system-respiratory-membrane','respiratory-system-pulmonary-capillary'],'function-relationship','Which structure is the thin gas-exchange interface between a Type I pneumocyte and a pulmonary capillary?','Respiratory membrane',['Respiratory membrane','Goblet cell','Pleural cavity','Smooth muscle of airway'],'The respiratory membrane is the thin interface between a Type I pneumocyte and a pulmonary capillary.',R),
  make('q-depth-resp-cells','respiratory-system',['respiratory-system-type-i-pneumocyte','respiratory-system-type-ii-pneumocyte','respiratory-system-alveolar-macrophage'],'select-all','Select the alveolar cell types.',['Type I pneumocyte','Type II pneumocyte','Alveolar macrophage'],['Type I pneumocyte','Type II pneumocyte','Alveolar macrophage','Goblet cell'],'These are the listed cells of the alveolar region.',R),
  make('q-depth-resp-epithelium','respiratory-system',['respiratory-system-ciliated-pseudostratified-epithelium','respiratory-system-goblet-cell','respiratory-system-smooth-muscle-of-airway','respiratory-system-elastic-fiber'],'select-all','Select features associated with conducting-airway tissue.',['Ciliated pseudostratified epithelium','Goblet cell','Smooth muscle of airway','Elastic fiber'],['Ciliated pseudostratified epithelium','Goblet cell','Smooth muscle of airway','Elastic fiber','Type I pneumocyte'],'These structures are listed for respiratory histology and airway walls.',R),
  make('q-depth-resp-macrophage','respiratory-system',['respiratory-system-alveolar-macrophage','respiratory-system-alveolar-sac','respiratory-system-alveolus'],'function-relationship','Where would an alveolar macrophage be found?','In an alveolar air space',['In an alveolar air space','In the nasal septum','Inside the pleural cavity','In the carina'],'An alveolar macrophage is associated with the alveolar sac and alveolus.',R),
  make('q-depth-resp-sides','respiratory-system',['respiratory-system-right-main-bronchus'],'function-relationship','Which main bronchus enters the right lung?','Right main bronchus',['Right main bronchus','Left main bronchus','Lobar bronchus','Carina'],'The right main bronchus conducts air to the right lung.',R),
].filter((question) => question.structureIds.length > 0);

export const digestivePracticeExpansion: Question[] = [
  make('q-depth-digestive-canal','digestive-system',['digestive-system-mouth','digestive-system-pharynx','digestive-system-esophagus','digestive-system-stomach','digestive-system-duodenum','digestive-system-jejunum','digestive-system-ileum','digestive-system-cecum','digestive-system-ascending-colon','digestive-system-transverse-colon','digestive-system-descending-colon','digestive-system-sigmoid-colon','digestive-system-rectum','digestive-system-anal-canal','digestive-system-anus'],'ordered-sequence','Order the alimentary canal from its proximal opening to its terminal opening.',['Mouth','Pharynx','Esophagus','Stomach','Duodenum','Jejunum','Ileum','Cecum','Ascending colon','Transverse colon','Descending colon','Sigmoid colon','Rectum','Anal canal','Anus'],['Anus','Mouth','Ileum','Stomach','Rectum','Duodenum','Cecum','Esophagus','Ascending colon','Pharynx','Jejunum','Sigmoid colon','Anal canal','Transverse colon','Descending colon'],'The sequence follows the continuous lumen; accessory organs are not inserted.',D),
  make('q-depth-digestive-oral','digestive-system',['digestive-system-mouth','digestive-system-tongue','digestive-system-teeth','digestive-system-hard-palate','digestive-system-soft-palate'],'select-all','Select structures of the oral cavity.',['Mouth','Tongue','Teeth','Hard palate','Soft palate'],['Mouth','Tongue','Teeth','Hard palate','Soft palate','Esophagus'],'These structures are listed in the oral-cavity group.',D),
  make('q-depth-digestive-salivary','digestive-system',['digestive-system-parotid-gland','digestive-system-submandibular-gland','digestive-system-sublingual-gland','digestive-system-sublingual-duct'],'function-relationship','Which set contains major salivary glands and a named duct?',['Parotid gland','Submandibular gland','Sublingual gland','Sublingual duct'],['Parotid gland','Submandibular gland','Sublingual gland','Sublingual duct','Pancreas'],'The parotid gland, submandibular gland, sublingual gland, and sublingual duct belong to the oral region.',D),
  make('q-depth-digestive-stomach','digestive-system',['digestive-system-cardia','digestive-system-fundus','digestive-system-body-of-stomach','digestive-system-pyloric-antrum','digestive-system-pylorus'],'select-all','Select the named regions of the stomach.',['Cardia','Fundus','Body of stomach','Pyloric antrum','Pylorus'],['Cardia','Fundus','Body of stomach','Pyloric antrum','Pylorus','Cecum'],'The cardia, fundus, body of stomach, pyloric antrum, and pylorus are stomach regions; fundus is not a serial segment between cardia and body.',D),
  make('q-depth-digestive-rugae','digestive-system',['digestive-system-rugae'],'function-relationship','Which structure is a fold of the empty stomach lining?','Rugae',['Rugae','Villi','Microvilli','Mesentery'],'Rugae are stomach folds, distinct from intestinal villi.',D),
  make('q-depth-digestive-micro','digestive-system',['digestive-system-villi','digestive-system-microvilli','digestive-system-enterocyte','digestive-system-goblet-cell','digestive-system-intestinal-crypt'],'select-all','Select structures or cells associated with small-intestinal mucosa.',['Villi','Microvilli','Enterocyte','Goblet cell','Intestinal crypt'],['Villi','Microvilli','Enterocyte','Goblet cell','Intestinal crypt','Rugae'],'These specializations and cells are listed for small-intestinal tissue.',D),
  make('q-depth-digestive-cells','digestive-system',['digestive-system-paneth-cell','digestive-system-intestinal-crypt'],'function-relationship','Which cell is associated with an intestinal crypt rather than absorptive villus surface?','Paneth cell',['Paneth cell','Enterocyte','Goblet cell','Parietal cell'],'Paneth cells are listed with the intestinal crypt.',D),
  make('q-depth-digestive-large','digestive-system',['digestive-system-cecum','digestive-system-appendix','digestive-system-ascending-colon','digestive-system-transverse-colon','digestive-system-descending-colon','digestive-system-sigmoid-colon','digestive-system-rectum','digestive-system-anal-canal','digestive-system-anus'],'ordered-sequence','Order these large-intestinal structures from proximal to terminal.',['Cecum','Ascending colon','Transverse colon','Descending colon','Sigmoid colon','Rectum','Anal canal','Anus'],['Anus','Cecum','Sigmoid colon','Rectum','Ascending colon','Anal canal','Transverse colon','Descending colon'],'The appendix is a cecal projection, not a segment in this lumen sequence.',D),
  make('q-depth-digestive-wall','digestive-system',['digestive-system-mucosa','digestive-system-lamina-propria','digestive-system-muscularis-mucosae','digestive-system-submucosa','digestive-system-muscularis-externa','digestive-system-serosa'],'ordered-sequence','Order the digestive wall layers from lumen outward.',['Mucosa','Submucosa','Muscularis externa','Serosa'],['Serosa','Mucosa','Muscularis externa','Submucosa'],'The mucosa includes lamina propria and muscularis mucosae.',D),
  make('q-depth-digestive-muscle','digestive-system',['digestive-system-muscularis-externa','digestive-system-circular-muscle-layer','digestive-system-longitudinal-muscle-layer'],'function-relationship','Which two layers are components of the muscularis externa?',['Circular muscle layer','Longitudinal muscle layer'],['Circular muscle layer','Longitudinal muscle layer','Lamina propria','Serosa'],'The muscularis externa is represented by circular and longitudinal muscle layers.',D),
  make('q-depth-digestive-gastric','digestive-system',['digestive-system-gastric-pit','digestive-system-parietal-cell','digestive-system-chief-cell'],'select-all','Select structures or cells of the gastric mucosa.',['Gastric pit','Parietal cell','Chief cell'],['Gastric pit','Parietal cell','Chief cell','Villi'],'The gastric pit, parietal cell, and chief cell are listed under digestive wall and histology.',D),
  make('q-depth-digestive-bile','digestive-system',['digestive-system-gallbladder','digestive-system-cystic-duct','digestive-system-common-bile-duct'],'ordered-sequence','Order the biliary route after storage.',['Gallbladder','Cystic duct','Common bile duct'],['Common bile duct','Gallbladder','Cystic duct'],'After gallbladder storage, bile enters the cystic duct and then the common bile duct.',D),
  make('q-depth-digestive-accessory','digestive-system',['digestive-system-liver','digestive-system-gallbladder','digestive-system-pancreas'],'select-all','Select accessory digestive organs.',['Liver','Gallbladder','Pancreas'],['Liver','Gallbladder','Pancreas','Jejunum'],'The liver, gallbladder, and pancreas support digestion but are outside the alimentary lumen.',D),
  make('q-depth-digestive-pancreas','digestive-system',['digestive-system-pancreas','digestive-system-head-of-pancreas','digestive-system-body-of-pancreas','digestive-system-tail-of-pancreas','digestive-system-pancreatic-duct'],'select-all','Select named parts or drainage structures of this gland.',['Pancreas','Head of pancreas','Body of pancreas','Tail of pancreas','Pancreatic duct'],['Pancreas','Head of pancreas','Body of pancreas','Tail of pancreas','Pancreatic duct','Common hepatic duct'],'These structures are grouped under pancreatic anatomy.',D),
  make('q-depth-digestive-entry','digestive-system',['digestive-system-hepatopancreatic-ampulla'],'function-relationship','Which structure is the shared entry region for bile and pancreatic secretions?','Hepatopancreatic ampulla',['Hepatopancreatic ampulla','Major duodenal papilla','Ileocecal valve','Pyloric sphincter'],'The hepatopancreatic ampulla is the shared entry region before the duodenal opening.',D),
  make('q-depth-digestive-peritoneum','digestive-system',['digestive-system-mesentery','digestive-system-greater-omentum','digestive-system-lesser-omentum'],'select-all','Select peritoneal folds.',['Mesentery','Greater omentum','Lesser omentum'],['Mesentery','Greater omentum','Lesser omentum','Serosa'],'The mesentery, greater omentum, and lesser omentum are the named peritoneal folds.',D),
  make('q-depth-digestive-omentum','digestive-system',['digestive-system-greater-omentum','digestive-system-lesser-omentum'],'function-relationship','Which pair are omental folds related to abdominal organs?',['Greater omentum','Lesser omentum'],['Greater omentum','Lesser omentum','Mesentery','Villi'],'The greater omentum and lesser omentum are named peritoneal folds.',D),
  make('q-depth-digestive-portal-cell','digestive-system',['digestive-system-hepatocyte','digestive-system-liver'],'function-relationship','Which liver cell receives blood within the liver after portal delivery?','Hepatocyte',['Hepatocyte','Enterocyte','Chief cell','Paneth cell'],'Hepatocytes are the named liver cells.',D),
  make('q-depth-digestive-terminal','digestive-system',['digestive-system-rectum','digestive-system-anal-canal','digestive-system-anus','digestive-system-sigmoid-colon'],'ordered-sequence','Order the distal canal.',['Sigmoid colon','Rectum','Anal canal','Anus'],['Anus','Anal canal','Sigmoid colon','Rectum'],'The rectum follows the sigmoid colon and precedes the anal canal.',D),
].filter((question) => question.structureIds.length > 0);

export const urinaryPracticeExpansion: Question[] = [
  make('q-depth-urinary-kidney','urinary-system',['urinary-system-renal-capsule','urinary-system-renal-cortex','urinary-system-renal-medulla'],'function-relationship','Which arrangement places the renal capsule outside cortex and medulla?','Renal capsule, renal cortex, renal medulla',['Renal medulla, renal cortex, renal capsule','Renal capsule, renal cortex, renal medulla','Renal cortex, renal capsule, renal medulla','Renal pelvis, renal cortex, renal capsule'],'The renal capsule covers the kidney; the renal cortex is peripheral to the renal medulla.',U),
  make('q-depth-urinary-calyces','urinary-system',['urinary-system-renal-papilla','urinary-system-minor-calyx','urinary-system-major-calyx','urinary-system-renal-pelvis'],'ordered-sequence','Order urine drainage from a papilla toward the next outlet.',['Renal papilla','Minor calyx','Major calyx','Renal pelvis'],['Renal pelvis','Major calyx','Renal papilla','Minor calyx'],'A minor calyx receives a papilla, then joins a major calyx and pelvis.',U),
  make('q-depth-urinary-tract','urinary-system',['urinary-system-renal-pelvis','urinary-system-ureter','urinary-system-urinary-bladder','urinary-system-urethra'],'ordered-sequence','Order the downstream urinary structures.',['Renal pelvis','Ureter','Urinary bladder','Urethra'],['Urethra','Urinary bladder','Renal pelvis','Ureter'],'The ureter leads to the bladder, then the urethra.',U),
  make('q-depth-urinary-nephron','urinary-system',['urinary-system-glomerulus','urinary-system-glomerular-capsule','urinary-system-proximal-convoluted-tubule','urinary-system-nephron-loop','urinary-system-distal-convoluted-tubule','urinary-system-collecting-duct','urinary-system-papillary-duct'],'ordered-sequence','Order filtrate through the corpuscle, tubular segments, and collecting system.',['Glomerulus','Glomerular capsule','Proximal convoluted tubule','Nephron loop','Distal convoluted tubule','Collecting duct','Papillary duct'],['Papillary duct','Glomerulus','Distal convoluted tubule','Glomerular capsule','Nephron loop','Collecting duct','Proximal convoluted tubule'],'The corpuscle is followed by the tubular segments and collecting system.',U),
  make('q-depth-urinary-corpuscle','urinary-system',['urinary-system-renal-corpuscle','urinary-system-glomerulus','urinary-system-glomerular-capsule','urinary-system-podocyte','urinary-system-filtration-membrane'],'select-all','Select components of the filtration unit or its interface.',['Renal corpuscle','Glomerulus','Glomerular capsule','Podocyte','Filtration membrane'],['Renal corpuscle','Glomerulus','Glomerular capsule','Podocyte','Filtration membrane','Collecting duct'],'These structures are grouped in the corpuscle lesson.',U),
  make('q-depth-urinary-barrier','urinary-system',['urinary-system-podocyte','urinary-system-filtration-membrane','urinary-system-glomerulus','urinary-system-glomerular-capsule'],'function-relationship','Which cell contributes processes to the glomerular filtration interface?','Podocyte',['Podocyte','Macula densa','Principal cell','Intercalated cell'],'Podocytes wrap glomerular capillaries.',U),
  make('q-depth-urinary-limbs','urinary-system',['urinary-system-nephron-loop','urinary-system-descending-limb','urinary-system-ascending-limb','urinary-system-distal-convoluted-tubule'],'function-relationship','Which two structures are limbs of the nephron loop?',['Descending limb','Ascending limb'],['Descending limb','Ascending limb','Distal convoluted tubule','Collecting duct'],'The loop has descending and ascending limbs.',U),
  make('q-depth-urinary-vessels','urinary-system',['urinary-system-renal-artery','urinary-system-segmental-artery','urinary-system-interlobar-artery','urinary-system-arcuate-artery','urinary-system-cortical-radiate-artery','urinary-system-afferent-arteriole','urinary-system-efferent-arteriole'],'ordered-sequence','Order the arterial branches toward a glomerulus.',['Renal artery','Segmental artery','Interlobar artery','Arcuate artery','Cortical radiate artery','Afferent arteriole'],['Afferent arteriole','Arcuate artery','Renal artery','Cortical radiate artery','Segmental artery','Interlobar artery'],'The named arteries branch progressively before the afferent arteriole.',U),
  make('q-depth-urinary-outflow','urinary-system',['urinary-system-glomerulus','urinary-system-efferent-arteriole'],'function-relationship','Which vessel leaves the glomerulus?','Efferent arteriole',['Efferent arteriole','Afferent arteriole','Renal vein','Arcuate artery'],'The efferent arteriole drains the glomerulus.',U),
  make('q-depth-urinary-capillaries','urinary-system',['urinary-system-peritubular-capillary','urinary-system-vasa-recta','urinary-system-nephron-loop','urinary-system-proximal-convoluted-tubule'],'select-all','Select capillary networks associated with nephron tubules.',['Peritubular capillary','Vasa recta'],['Peritubular capillary','Vasa recta','Glomerulus','Renal pelvis'],'Both are listed in the renal-vessel group.',U),
  make('q-depth-urinary-cortical','urinary-system',['urinary-system-cortical-radiate-artery','urinary-system-cortical-radiate-vein','urinary-system-renal-cortex'],'select-all','Select vessels named as cortical radiate vessels.',['Cortical radiate artery','Cortical radiate vein'],['Cortical radiate artery','Cortical radiate vein','Arcuate artery','Renal vein'],'Both are listed in the vessel and histology group.',U),
  make('q-depth-urinary-jga','urinary-system',['urinary-system-juxtaglomerular-apparatus','urinary-system-macula-densa','urinary-system-juxtaglomerular-cell','urinary-system-distal-convoluted-tubule'],'select-all','Select structures or cells in the renal pressure-sensing complex.',['Juxtaglomerular apparatus','Macula densa','Juxtaglomerular cell'],['Juxtaglomerular apparatus','Macula densa','Juxtaglomerular cell','Podocyte'],'These are the named JGA structures.',U),
  make('q-depth-urinary-collecting','urinary-system',['urinary-system-collecting-duct','urinary-system-principal-cell','urinary-system-intercalated-cell','urinary-system-papillary-duct'],'select-all','Select cells associated with collecting-duct histology.',['Principal cell','Intercalated cell'],['Principal cell','Intercalated cell','Podocyte','Macula densa'],'Both cells are listed in urinary histology.',U),
  make('q-depth-urinary-final','urinary-system',['urinary-system-collecting-duct','urinary-system-papillary-duct','urinary-system-minor-calyx'],'function-relationship','Which structure follows the collecting duct before a minor calyx?','Papillary duct',['Papillary duct','Distal convoluted tubule','Ureter','Renal vein'],'The papillary duct delivers urine to a minor calyx.',U),
  make('q-depth-urinary-nephron-name','urinary-system',['urinary-system-nephron','urinary-system-renal-corpuscle','urinary-system-proximal-convoluted-tubule','urinary-system-distal-convoluted-tubule'],'function-relationship','Which term names the complete functional unit containing a renal corpuscle and tubules?','Nephron',['Nephron','Renal pelvis','Ureter','Trigone'],'The nephron includes the corpuscle and tubular segments.',U),
  make('q-depth-urinary-vein','urinary-system',['urinary-system-renal-vein','urinary-system-renal-artery','urinary-system-cortical-radiate-vein','urinary-system-kidney'],'function-relationship','Which named vessel carries blood away from the kidney?','Renal vein',['Renal vein','Renal artery','Afferent arteriole','Arcuate artery'],'The renal vein is the kidney outflow vessel.',U),
].filter((question) => question.structureIds.length > 0);

export const malePracticeExpansion: Question[] = [
  make('q-depth-male-testis','male-reproductive',['male-reproductive-tunica-albuginea'],'function-relationship','Which structure is the fibrous covering of the testis?','Tunica albuginea',['Tunica albuginea','Testicular lobule','Rete testis','Spermatic cord'],'The tunica albuginea is the named testicular covering.',M),
  make('q-depth-male-tubules','male-reproductive',['male-reproductive-seminiferous-tubule','male-reproductive-rete-testis','male-reproductive-efferent-ductule','male-reproductive-epididymis'],'ordered-sequence','Order the proximal sperm-conducting route.',['Seminiferous tubule','Rete testis','Efferent ductule','Epididymis'],['Epididymis','Efferent ductule','Seminiferous tubule','Rete testis'],'These structures form the proximal sperm-conducting route.',M),
  make('q-depth-male-epididymis','male-reproductive',['male-reproductive-head-of-epididymis','male-reproductive-body-of-epididymis','male-reproductive-tail-of-epididymis','male-reproductive-ductus-deferens'],'ordered-sequence','Order these duct structures from proximal to distal.',['Head of epididymis','Body of epididymis','Tail of epididymis','Ductus deferens'],['Ductus deferens','Tail of epididymis','Head of epididymis','Body of epididymis'],'The ductus deferens continues from the tail.',M),
  make('q-depth-male-ducts','male-reproductive',['male-reproductive-prostatic-urethra','male-reproductive-spongy-urethra'],'function-relationship','Which relationship correctly describes the prostatic and spongy urethra?','The prostatic urethra and spongy urethra are both regions of the urethra, with the membranous urethra between them',['The prostatic urethra and spongy urethra are both regions of the urethra, with the membranous urethra between them','The prostatic urethra is part of the epididymis','The spongy urethra is inside a seminiferous tubule','The prostatic urethra is a lung passage'],'The prostatic urethra and spongy urethra are distinct urethral regions; the membranous urethra lies between them.',M),
  make('q-depth-male-glands','male-reproductive',['male-reproductive-seminal-vesicle','male-reproductive-prostate-gland','male-reproductive-bulbourethral-gland'],'select-all','Select the accessory glands of the male reproductive system.',['Seminal vesicle','Prostate gland','Bulbourethral gland'],['Seminal vesicle','Prostate gland','Bulbourethral gland','Testicular lobule'],'The seminal vesicle, prostate gland, and bulbourethral gland are the accessory glands.',M),
  make('q-depth-male-prostate','male-reproductive',['male-reproductive-prostate-gland','male-reproductive-prostatic-urethra','male-reproductive-ejaculatory-duct'],'function-relationship','Which structure is surrounded by the prostate gland?','Prostatic urethra',['Prostatic urethra','Spongy urethra','Epididymis','Rete testis'],'The prostatic urethra is the urethral segment associated with the prostate.',M),
  make('q-depth-male-external','male-reproductive',['male-reproductive-penis','male-reproductive-root-of-penis','male-reproductive-body-of-penis','male-reproductive-glans-penis','male-reproductive-prepuce','male-reproductive-scrotum'],'select-all','Select named external reproductive structures.',['Penis','Root of penis','Body of penis','Glans penis','Prepuce','Scrotum'],['Penis','Root of penis','Body of penis','Glans penis','Prepuce','Scrotum','Seminiferous tubule'],'The penis, its named regions, prepuce, and scrotum are external structures.',M),
  make('q-depth-male-erectile','male-reproductive',['male-reproductive-corpus-cavernosum','male-reproductive-corpus-spongiosum','male-reproductive-spongy-urethra','male-reproductive-penis'],'function-relationship','Which erectile body surrounds the spongy urethra?','Corpus spongiosum',['Corpus spongiosum','Corpus cavernosum','Pampiniform plexus','Dartos muscle'],'The corpus spongiosum encloses the spongy urethra.',M),
  make('q-depth-male-scrotal','male-reproductive',['male-reproductive-scrotum','male-reproductive-dartos-muscle','male-reproductive-cremaster-muscle','male-reproductive-spermatic-cord'],'select-all','Select structures associated with scrotal/testicular support.',['Scrotum','Dartos muscle','Cremaster muscle','Spermatic cord'],['Scrotum','Dartos muscle','Cremaster muscle','Spermatic cord','Seminal vesicle'],'These structures are listed in male external and cord anatomy.',M),
  make('q-depth-male-cord','male-reproductive',['male-reproductive-spermatic-cord','male-reproductive-pampiniform-plexus','male-reproductive-ductus-deferens','male-reproductive-testis'],'function-relationship','Which vascular network is associated with the spermatic cord?','Pampiniform plexus',['Pampiniform plexus','Rete testis','Corpus cavernosum','Seminal plasma'],'The pampiniform plexus is a named cord structure.',M),
  make('q-depth-male-germ','male-reproductive',['male-reproductive-spermatogonium','male-reproductive-primary-spermatocyte','male-reproductive-secondary-spermatocyte','male-reproductive-spermatid','male-reproductive-spermatozoon'],'ordered-sequence','Order the listed germ-cell stages from earliest to mature.',['Spermatogonium','Primary spermatocyte','Secondary spermatocyte','Spermatid','Spermatozoon'],['Spermatozoon','Spermatid','Spermatogonium','Primary spermatocyte','Secondary spermatocyte'],'The stages progress from spermatogonium to spermatozoon.',M),
  make('q-depth-male-support','male-reproductive',['male-reproductive-sertoli-cell','male-reproductive-blood-testis-barrier','male-reproductive-peritubular-myoid-cell','male-reproductive-seminiferous-tubule'],'select-all','Select structures that support or form the seminiferous-tubule compartment.',['Sertoli cell','Blood-testis barrier','Peritubular myoid cell','Seminiferous tubule'],['Sertoli cell','Blood-testis barrier','Peritubular myoid cell','Seminiferous tubule','Leydig cell','Epididymis'],'Sertoli cells, the blood-testis barrier, peritubular myoid cells, and seminiferous tubules belong to this compartment; Leydig cells and the epididymis are plausible but incorrect distractors.',M),
  make('q-depth-male-barrier','male-reproductive',['male-reproductive-sertoli-cell','male-reproductive-blood-testis-barrier','male-reproductive-seminiferous-tubule'],'function-relationship','Which cell forms the blood-testis barrier?','Sertoli cell',['Sertoli cell','Leydig cell','Spermatid','Peritubular myoid cell'],'The blood-testis barrier is associated with Sertoli cells.',M),
  make('q-depth-male-histology','male-reproductive',['male-reproductive-acrosome','male-reproductive-flagellum','male-reproductive-spermatozoon','male-reproductive-seminal-plasma'],'select-all','Select structures or materials associated with a mature gamete.',['Acrosome','Flagellum','Spermatozoon','Seminal plasma'],['Acrosome','Flagellum','Spermatozoon','Seminal plasma','Rugae'],'These named structures and material occur in the male histology list.',M),
  make('q-depth-male-sperm','male-reproductive',['male-reproductive-acrosome','male-reproductive-flagellum','male-reproductive-spermatozoon'],'function-relationship','Which sperm structure is associated with motility?','Flagellum',['Flagellum','Acrosome','Seminal plasma','Blood-testis barrier'],'The flagellum is the named motility structure.',M),
  make('q-depth-male-urethra','male-reproductive',['male-reproductive-prostatic-urethra','male-reproductive-spongy-urethra','male-reproductive-urethra','male-reproductive-corpus-spongiosum'],'function-relationship','Which urethral segment is enclosed by the corpus spongiosum?','Spongy urethra',['Spongy urethra','Prostatic urethra','Urethra','Ejaculatory duct'],'The corpus spongiosum surrounds the spongy urethra.',M),
  make('q-depth-male-gland-path','male-reproductive',['male-reproductive-seminal-vesicle','male-reproductive-ampulla-of-ductus-deferens','male-reproductive-ejaculatory-duct','male-reproductive-prostate-gland'],'function-relationship','Which duct receives the seminal-vesicle contribution before entering the urethra?','Ejaculatory duct',['Ejaculatory duct','Efferent ductule','Rete testis','Ductus deferens'],'The ejaculatory duct is the distal duct associated with the seminal vesicle and prostate.',M),
  make('q-depth-male-testis-cells','male-reproductive',['male-reproductive-seminiferous-tubule','male-reproductive-sertoli-cell','male-reproductive-leydig-cell','male-reproductive-testicular-lobule'],'select-all','Select structures found in the testis group.',['Seminiferous tubule','Sertoli cell','Leydig cell','Testicular lobule'],['Seminiferous tubule','Sertoli cell','Leydig cell','Testicular lobule','Epididymis'],'All selected structures are listed under testis anatomy.',M),
  make('q-depth-male-distinct','male-reproductive',['male-reproductive-corpus-cavernosum','male-reproductive-corpus-spongiosum','male-reproductive-pampiniform-plexus','male-reproductive-dartos-muscle'],'select-all','Select structures that are not sperm ducts.',['Corpus cavernosum','Corpus spongiosum','Pampiniform plexus','Dartos muscle'],['Corpus cavernosum','Corpus spongiosum','Pampiniform plexus','Dartos muscle','Ductus deferens'],'These structures belong to erectile, vascular, or external support anatomy.',M),
  make('q-depth-male-tail','male-reproductive',['male-reproductive-tail-of-epididymis','male-reproductive-ductus-deferens','male-reproductive-epididymis'],'function-relationship','Which epididymal region continues into the ductus deferens?','Tail of epididymis',['Tail of epididymis','Head of epididymis','Body of epididymis','Rete testis'],'The tail is the distal epididymal region that continues as the ductus deferens.',M),
].filter((question) => question.structureIds.length > 0);

export const femalePracticeExpansion: Question[] = [
  make('q-depth-female-ovary','female-reproductive',['female-reproductive-ovary','female-reproductive-ovarian-cortex','female-reproductive-ovarian-medulla','female-reproductive-ovarian-follicle'],'function-relationship','Which ovarian region contains most follicles?','Ovarian cortex',['Ovarian cortex','Ovarian medulla','Myometrium','Perimetrium'],'Follicles are located in the ovarian cortex.',F),
  make('q-depth-female-follicles','female-reproductive',['female-reproductive-primordial-follicle','female-reproductive-primary-follicle','female-reproductive-secondary-follicle','female-reproductive-antral-follicle','female-reproductive-mature-follicle'],'ordered-sequence','Order follicle stages from earliest to pre-ovulatory.',['Primordial follicle','Primary follicle','Secondary follicle','Antral follicle','Mature follicle'],['Mature follicle','Primordial follicle','Antral follicle','Primary follicle','Secondary follicle'],'The named stages progress from primordial through mature follicle.',F),
  make('q-depth-female-follicle-cells','female-reproductive',['female-reproductive-oocyte','female-reproductive-granulosa-cell','female-reproductive-theca-cell','female-reproductive-corona-radiata','female-reproductive-zona-pellucida','female-reproductive-follicular-fluid'],'select-all','Select structures or cells associated with an ovarian follicle.',['Oocyte','Granulosa cell','Theca cell','Corona radiata','Zona pellucida','Follicular fluid'],['Oocyte','Granulosa cell','Theca cell','Corona radiata','Zona pellucida','Follicular fluid','Endometrium'],'These are the named follicular structures and cells.',F),
  make('q-depth-female-postovulation','female-reproductive',['female-reproductive-mature-follicle','female-reproductive-corpus-luteum','female-reproductive-corpus-albicans','female-reproductive-ovary'],'function-relationship','Which ovarian structure follows the mature follicle after ovulation?','Corpus luteum',['Corpus luteum','Corpus albicans','Ovarian medulla','Primordial follicle'],'The corpus luteum is the post-ovulatory follicular structure.',F),
  make('q-depth-female-theca','female-reproductive',['female-reproductive-theca-cell','female-reproductive-theca-interna','female-reproductive-theca-externa','female-reproductive-granulosa-cell'],'select-all','Select theca structures or cells.',['Theca cell','Theca interna','Theca externa'],['Theca cell','Theca interna','Theca externa','Granulosa cell'],'These names are grouped in follicle histology.',F),
  make('q-depth-female-tube','female-reproductive',['female-reproductive-fimbriae','female-reproductive-infundibulum','female-reproductive-ampulla-of-uterine-tube','female-reproductive-isthmus-of-uterine-tube','female-reproductive-uterine-tube'],'ordered-sequence','Order the uterine tube from its ovarian end toward the uterus.',['Fimbriae','Infundibulum','Ampulla of uterine tube','Isthmus of uterine tube'],['Isthmus of uterine tube','Ampulla of uterine tube','Fimbriae','Infundibulum'],'Fimbriae border the infundibulum; the isthmus is the medial narrow segment.',F),
  make('q-depth-female-tube-rel','female-reproductive',['female-reproductive-fimbriae','female-reproductive-infundibulum','female-reproductive-ampulla-of-uterine-tube','female-reproductive-fallopian-epithelium'],'function-relationship','Which structure is a fringe near the ovary?','Fimbriae',['Fimbriae','Ampulla of uterine tube','Cervix','Vaginal fornix'],'Fimbriae fringe the infundibulum.',F),
  make('q-depth-female-uterus','female-reproductive',['female-reproductive-fundus-of-uterus','female-reproductive-body-of-uterus','female-reproductive-cervix','female-reproductive-cervical-canal'],'select-all','Select named regions of the uterus and its cervical passage.',['Fundus of uterus','Body of uterus','Cervix','Cervical canal'],['Fundus of uterus','Body of uterus','Cervix','Cervical canal','Vagina','Ampulla of uterine tube'],'The fundus and body are uterine regions; the cervix contains the cervical canal. The vagina is a separate canal inferior to the cervix.',F),
  make('q-depth-female-os','female-reproductive',['female-reproductive-internal-os','female-reproductive-cervical-canal','female-reproductive-external-os','female-reproductive-vagina'],'ordered-sequence','Order the cervical passage from the uterine side toward its outlet.',['Internal os','Cervical canal','External os','Vagina'],['External os','Vagina','Internal os','Cervical canal'],'The internal os opens into the canal and the external os toward the vagina.',F),
  make('q-depth-female-wall','female-reproductive',['female-reproductive-endometrium','female-reproductive-myometrium','female-reproductive-perimetrium','female-reproductive-uterine-gland','female-reproductive-smooth-muscle-of-uterus'],'ordered-sequence','Order the uterine wall from lumen outward.',['Endometrium','Myometrium','Perimetrium'],['Perimetrium','Endometrium','Myometrium'],'The endometrium is internal, myometrium muscular, and perimetrium external.',F),
  make('q-depth-female-wall-rel','female-reproductive',['female-reproductive-endometrium','female-reproductive-myometrium','female-reproductive-perimetrium','female-reproductive-smooth-muscle-of-uterus'],'function-relationship','Which layer is the smooth-muscle wall of the uterus?','Myometrium',['Myometrium','Endometrium','Perimetrium','Uterine gland'],'The myometrium is the muscular uterine layer.',F),
  make('q-depth-female-support','female-reproductive',['female-reproductive-broad-ligament','female-reproductive-suspensory-ligament-of-ovary','female-reproductive-ovarian-ligament','female-reproductive-round-ligament','female-reproductive-mesovarium'],'select-all','Select named ligaments or peritoneal supports.',['Broad ligament','Suspensory ligament of ovary','Ovarian ligament','Round ligament','Mesovarium'],['Broad ligament','Suspensory ligament of ovary','Ovarian ligament','Round ligament','Mesovarium','Vaginal fornix'],'These structures are listed under reproductive support.',F),
  make('q-depth-female-support-rel','female-reproductive',['female-reproductive-ovary','female-reproductive-ovarian-ligament','female-reproductive-uterus','female-reproductive-suspensory-ligament-of-ovary'],'function-relationship','Which ligament connects the ovary to the uterus?','Ovarian ligament',['Ovarian ligament','Suspensory ligament of ovary','Round ligament','Broad ligament'],'The ovarian ligament connects ovary and uterus.',F),
  make('q-depth-female-external','female-reproductive',['female-reproductive-vulva','female-reproductive-mons-pubis','female-reproductive-labium-majus','female-reproductive-labium-minus','female-reproductive-clitoris','female-reproductive-vestibule','female-reproductive-greater-vestibular-gland'],'select-all','Select external genital structures and associated glands.',['Vulva','Mons pubis','Labium majus','Labium minus','Clitoris','Vestibule','Greater vestibular gland'],['Vulva','Mons pubis','Labium majus','Labium minus','Clitoris','Vestibule','Greater vestibular gland','Cervix'],'These structures are grouped under external anatomy.',F),
  make('q-depth-female-clitoris','female-reproductive',['female-reproductive-clitoris','female-reproductive-vulva','female-reproductive-vestibule'],'function-relationship','Which external structure is erectile tissue?','Clitoris',['Clitoris','Labium majus','Vestibule','Cervical canal'],'The clitoris is the named erectile external structure.',F),
  make('q-depth-female-mammary','female-reproductive',['female-reproductive-mammary-gland','female-reproductive-nipple','female-reproductive-areola','female-reproductive-mammary-lobule','female-reproductive-lactiferous-duct','female-reproductive-lactiferous-sinus'],'ordered-sequence','Order milk drainage from a glandular unit toward its terminal landmark.',['Mammary lobule','Lactiferous duct','Lactiferous sinus','Nipple'],['Nipple','Mammary lobule','Lactiferous sinus','Lactiferous duct'],'The duct and sinus conduct toward the nipple.',F),
  make('q-depth-female-mammary-select','female-reproductive',['female-reproductive-mammary-gland','female-reproductive-mammary-lobule','female-reproductive-lactiferous-duct','female-reproductive-lactiferous-sinus','female-reproductive-nipple','female-reproductive-areola'],'select-all','Select mammary structures.',['Mammary gland','Mammary lobule','Lactiferous duct','Lactiferous sinus','Nipple','Areola'],['Mammary gland','Mammary lobule','Lactiferous duct','Lactiferous sinus','Nipple','Areola','Uterine gland'],'These names are listed in external and mammary anatomy.',F),
  make('q-depth-female-histology','female-reproductive',['female-reproductive-fallopian-epithelium','female-reproductive-nonkeratinized-stratified-squamous-epithelium','female-reproductive-secretory-endometrium','female-reproductive-proliferative-endometrium','female-reproductive-smooth-muscle-of-uterus'],'select-all','Select female reproductive histology terms.',['Fallopian epithelium','Nonkeratinized stratified squamous epithelium','Secretory endometrium','Proliferative endometrium','Smooth muscle of uterus'],['Fallopian epithelium','Nonkeratinized stratified squamous epithelium','Secretory endometrium','Proliferative endometrium','Smooth muscle of uterus','Paneth cell'],'These structures and tissue descriptions are in the female histology group.',F),
  make('q-depth-female-epithelium','female-reproductive',['female-reproductive-fallopian-epithelium','female-reproductive-nonkeratinized-stratified-squamous-epithelium','female-reproductive-vagina','female-reproductive-uterine-tube'],'function-relationship','Which epithelium is associated with the vagina in this module?','Nonkeratinized stratified squamous epithelium',['Nonkeratinized stratified squamous epithelium','Fallopian epithelium','Transitional epithelium','Ciliated pseudostratified epithelium'],'The vaginal lining is represented by the named nonkeratinized stratified squamous epithelium.',F),
  make('q-depth-female-fornix','female-reproductive',['female-reproductive-vaginal-fornix','female-reproductive-vagina','female-reproductive-cervix','female-reproductive-external-os'],'function-relationship','Which structure is a recess around the vaginal portion of the cervix?','Vaginal fornix',['Vaginal fornix','External os','Round ligament','Infundibulum'],'The vaginal fornix is listed with cervix and vagina anatomy.',F),
  make('q-depth-female-pathway','female-reproductive',['female-reproductive-ovary','female-reproductive-fimbriae','female-reproductive-infundibulum','female-reproductive-ampulla-of-uterine-tube','female-reproductive-isthmus-of-uterine-tube','female-reproductive-uterus'],'ordered-sequence','Order the oocyte pathway through the uterine tube toward its destination.',['Ovary','Fimbriae','Infundibulum','Ampulla of uterine tube','Isthmus of uterine tube','Uterus'],['Uterus','Ovary','Ampulla of uterine tube','Fimbriae','Isthmus of uterine tube','Infundibulum'],'The named tube regions carry the pathway from the ovary toward the uterus.',F),
  make('q-depth-female-cells','female-reproductive',['female-reproductive-oocyte','female-reproductive-zona-pellucida'],'function-relationship','Which structure is the glycoprotein coat around the oocyte?','Zona pellucida',['Zona pellucida','Corona radiata','Theca externa','Follicular fluid'],'The zona pellucida is the glycoprotein coat surrounding the oocyte.',F),
  make('q-depth-female-glands','female-reproductive',['female-reproductive-uterine-gland','female-reproductive-greater-vestibular-gland','female-reproductive-mammary-gland','female-reproductive-endometrium'],'select-all','Select named glands in female reproductive anatomy.',['Uterine gland','Greater vestibular gland','Mammary gland'],['Uterine gland','Greater vestibular gland','Mammary gland','Ovarian medulla'],'These glands are listed in uterine, external, and mammary groups.',F),
  make('q-depth-female-ligament','female-reproductive',['female-reproductive-suspensory-ligament-of-ovary','female-reproductive-ovary','female-reproductive-mesovarium','female-reproductive-broad-ligament'],'function-relationship','Which support is associated with ovarian vessels?','Suspensory ligament of ovary',['Suspensory ligament of ovary','Ovarian ligament','Round ligament','Vaginal fornix'],'The suspensory ligament is the named ovarian support.',F),
].filter((question) => question.structureIds.length > 0);