// GENERATED by scripts/atlas/skeletal-generate.mjs - do not edit by hand.
export interface SkeletalPlateLabel { structureId: string; x: number; y: number; radius: number }
export interface SkeletalPlate { id: string; key: string; replaces: string | null; svgPath: string; pngPath: string; title: [string, string]; description: [string, string]; orientation: string; labels: SkeletalPlateLabel[] }
export const skeletalPlates: SkeletalPlate[] = [
  {
    "id": "asset-skull-front",
    "key": "skull-anterior",
    "replaces": "asset-skull-front",
    "svgPath": "assets/images/anatomy/skeletal-atlas/skeletal-atlas-01-skull-anterior.svg",
    "pngPath": "assets/images/anatomy/skeletal-atlas/skeletal-atlas-01-skull-anterior.png",
    "title": [
      "Anterior skull: facial bones and openings",
      "Cráneo anterior: huesos faciales y orificios"
    ],
    "description": [
      "Skull seen from the front, mandible included. Orbital openings (optic canal, superior and inferior orbital fissures), supraorbital and mental foramina are drawn as holes. Patient right is on the viewer's left; one pin per structure on that side.",
      "Cráneo visto de frente, con la mandíbula. Los orificios orbitarios (canal óptico, fisuras orbitarias superior e inferior) y los forámenes supraorbitario y mentoniano se dibujan como huecos. La derecha del paciente queda a la izquierda del observador; un solo marcador por estructura en ese lado."
    ],
    "orientation": "anterior view; patient right = viewer left",
    "labels": [
      {
        "structureId": "parietal-bone",
        "x": 0.3801,
        "y": 0.2276,
        "radius": 0.016
      },
      {
        "structureId": "frontal-bone",
        "x": 0.5,
        "y": 0.185,
        "radius": 0.016
      },
      {
        "structureId": "temporal-bone",
        "x": 0.3524,
        "y": 0.4229,
        "radius": 0.016
      },
      {
        "structureId": "sphenoid-bone",
        "x": 0.3891,
        "y": 0.403,
        "radius": 0.016
      },
      {
        "structureId": "zygomatic-bone",
        "x": 0.3945,
        "y": 0.492,
        "radius": 0.016
      },
      {
        "structureId": "maxilla",
        "x": 0.4441,
        "y": 0.6716,
        "radius": 0.016
      },
      {
        "structureId": "nasal-bone",
        "x": 0.4906,
        "y": 0.475,
        "radius": 0.016
      },
      {
        "structureId": "mandible",
        "x": 0.4418,
        "y": 0.8596,
        "radius": 0.016
      },
      {
        "structureId": "vomer",
        "x": 0.5,
        "y": 0.593,
        "radius": 0.016
      },
      {
        "structureId": "inferior-nasal-concha",
        "x": 0.4869,
        "y": 0.61,
        "radius": 0.016
      },
      {
        "structureId": "lacrimal-bone",
        "x": 0.4772,
        "y": 0.458,
        "radius": 0.016
      },
      {
        "structureId": "supraorbital-foramen",
        "x": 0.4517,
        "y": 0.376,
        "radius": 0.016
      },
      {
        "structureId": "optic-canal",
        "x": 0.4634,
        "y": 0.424,
        "radius": 0.012
      },
      {
        "structureId": "superior-orbital-fissure",
        "x": 0.4448,
        "y": 0.464,
        "radius": 0.012
      },
      {
        "structureId": "inferior-orbital-fissure",
        "x": 0.4138,
        "y": 0.484,
        "radius": 0.012
      },
      {
        "structureId": "mental-foramen",
        "x": 0.4276,
        "y": 0.836,
        "radius": 0.012
      }
    ]
  },
  {
    "id": "asset-skull-lateral",
    "key": "skull-lateral",
    "replaces": "asset-skull-lateral",
    "svgPath": "assets/images/anatomy/skeletal-atlas/skeletal-atlas-02-skull-lateral.svg",
    "pngPath": "assets/images/anatomy/skeletal-atlas/skeletal-atlas-02-skull-lateral.png",
    "title": [
      "Left lateral skull",
      "Cráneo lateral izquierdo"
    ],
    "description": [
      "Skull seen from the patient's left side, mandible included. Anterior (face) points toward the viewer's left. Zygomatic arch, external acoustic meatus, mastoid and styloid processes, mandibular condyle and coronoid process are separate shapes.",
      "Cráneo visto desde el lado izquierdo del paciente, con la mandíbula. La cara (anterior) mira hacia la izquierda del observador. El arco cigomático, el meato acústico externo, las apófisis mastoides y estiloides, el cóndilo mandibular y la apófisis coronoides son formas separadas."
    ],
    "orientation": "left lateral view; anterior toward viewer-left",
    "labels": [
      {
        "structureId": "frontal-bone",
        "x": 0.3979,
        "y": 0.2635,
        "radius": 0.016
      },
      {
        "structureId": "parietal-bone",
        "x": 0.5593,
        "y": 0.206,
        "radius": 0.016
      },
      {
        "structureId": "occipital-bone",
        "x": 0.6458,
        "y": 0.3786,
        "radius": 0.016
      },
      {
        "structureId": "temporal-bone",
        "x": 0.5172,
        "y": 0.33,
        "radius": 0.016
      },
      {
        "structureId": "sphenoid-bone",
        "x": 0.4463,
        "y": 0.4257,
        "radius": 0.016
      },
      {
        "structureId": "nasal-bone",
        "x": 0.3221,
        "y": 0.424,
        "radius": 0.016
      },
      {
        "structureId": "maxilla",
        "x": 0.3526,
        "y": 0.5244,
        "radius": 0.016
      },
      {
        "structureId": "zygomatic-bone",
        "x": 0.4207,
        "y": 0.47,
        "radius": 0.016
      },
      {
        "structureId": "zygomatic-arch",
        "x": 0.4931,
        "y": 0.47,
        "radius": 0.016
      },
      {
        "structureId": "mastoid-process",
        "x": 0.5862,
        "y": 0.5,
        "radius": 0.016
      },
      {
        "structureId": "styloid-process",
        "x": 0.5266,
        "y": 0.508,
        "radius": 0.016
      },
      {
        "structureId": "external-acoustic-meatus",
        "x": 0.5483,
        "y": 0.425,
        "radius": 0.013
      },
      {
        "structureId": "mandible",
        "x": 0.3625,
        "y": 0.6775,
        "radius": 0.016
      },
      {
        "structureId": "mandibular-condyle",
        "x": 0.5483,
        "y": 0.495,
        "radius": 0.016
      },
      {
        "structureId": "mandibular-coronoid",
        "x": 0.5207,
        "y": 0.5025,
        "radius": 0.016
      },
      {
        "structureId": "mental-foramen",
        "x": 0.3876,
        "y": 0.684,
        "radius": 0.012
      }
    ]
  },
  {
    "id": "asset-skeletal-atlas-skull-base-external",
    "key": "skull-base-external",
    "replaces": null,
    "svgPath": "assets/images/anatomy/skeletal-atlas/skeletal-atlas-03-skull-base-external.svg",
    "pngPath": "assets/images/anatomy/skeletal-atlas/skeletal-atlas-03-skull-base-external.png",
    "title": [
      "Skull base, external (inferior) view",
      "Base del cráneo, vista externa (inferior)"
    ],
    "description": [
      "Skull base seen from below, mandible omitted. Anterior is at the top. Patient right is on the viewer's LEFT in this inferior view. Foramen spinosum lies posterolateral to foramen ovale; paired openings are pinned once on the patient's right.",
      "Base del cráneo vista desde abajo, sin mandíbula. La parte anterior queda arriba. En esta vista inferior la derecha del paciente queda a la IZQUIERDA del observador. El foramen espinoso queda posterolateral al foramen oval; los orificios pares llevan un solo marcador del lado derecho del paciente."
    ],
    "orientation": "inferior view; anterior at top; patient right = viewer left; mandible omitted",
    "labels": [
      {
        "structureId": "maxilla",
        "x": 0.5,
        "y": 0.146,
        "radius": 0.016
      },
      {
        "structureId": "palatine-bone",
        "x": 0.5,
        "y": 0.3505,
        "radius": 0.016
      },
      {
        "structureId": "incisive-foramen",
        "x": 0.5,
        "y": 0.205,
        "radius": 0.012
      },
      {
        "structureId": "greater-palatin-foramen",
        "x": 0.4462,
        "y": 0.335,
        "radius": 0.012
      },
      {
        "structureId": "zygomatic-arch",
        "x": 0.3092,
        "y": 0.3833,
        "radius": 0.016
      },
      {
        "structureId": "sphenoid-bone",
        "x": 0.4317,
        "y": 0.4325,
        "radius": 0.016
      },
      {
        "structureId": "pterygoid-process",
        "x": 0.4662,
        "y": 0.42,
        "radius": 0.016
      },
      {
        "structureId": "temporal-bone",
        "x": 0.35,
        "y": 0.501,
        "radius": 0.016
      },
      {
        "structureId": "foramen-ovale",
        "x": 0.4207,
        "y": 0.44,
        "radius": 0.012
      },
      {
        "structureId": "foramen-spinosum",
        "x": 0.3966,
        "y": 0.482,
        "radius": 0.012
      },
      {
        "structureId": "carotid-canal",
        "x": 0.4172,
        "y": 0.52,
        "radius": 0.012
      },
      {
        "structureId": "jugular-foramen",
        "x": 0.3966,
        "y": 0.56,
        "radius": 0.012
      },
      {
        "structureId": "styloid-process",
        "x": 0.3614,
        "y": 0.458,
        "radius": 0.016
      },
      {
        "structureId": "stylomastoid-foramen",
        "x": 0.369,
        "y": 0.528,
        "radius": 0.012
      },
      {
        "structureId": "mastoid-process",
        "x": 0.331,
        "y": 0.548,
        "radius": 0.016
      },
      {
        "structureId": "occipital-condyles",
        "x": 0.4572,
        "y": 0.65,
        "radius": 0.016
      },
      {
        "structureId": "hypoglossal-canal",
        "x": 0.4345,
        "y": 0.625,
        "radius": 0.012
      },
      {
        "structureId": "vomer",
        "x": 0.5,
        "y": 0.42,
        "radius": 0.016
      },
      {
        "structureId": "occipital-bone",
        "x": 0.5,
        "y": 0.775,
        "radius": 0.016
      },
      {
        "structureId": "foramen-magnum",
        "x": 0.5,
        "y": 0.665,
        "radius": 0.02
      }
    ]
  },
  {
    "id": "asset-skeletal-atlas-cranial-floor-internal",
    "key": "cranial-floor-internal",
    "replaces": null,
    "svgPath": "assets/images/anatomy/skeletal-atlas/skeletal-atlas-04-cranial-floor-internal.svg",
    "pngPath": "assets/images/anatomy/skeletal-atlas/skeletal-atlas-04-cranial-floor-internal.png",
    "title": [
      "Cranial floor, internal (superior) view",
      "Suelo craneal, vista interna (superior)"
    ],
    "description": [
      "Floor of the cranial cavity seen from above with the vault removed. Anterior is at the top and patient right is on the viewer's RIGHT. Anterior, middle and posterior cranial fossae are tinted regions; optic canal, fissure, rotundum, ovale, spinosum, internal acoustic meatus, jugular foramen, hypoglossal canal and foramen magnum are holes.",
      "Suelo de la cavidad craneal visto desde arriba sin la bóveda. La parte anterior queda arriba y la derecha del paciente a la DERECHA del observador. Las fosas craneales anterior, media y posterior son regiones teñidas; el canal óptico, la fisura, los forámenes redondo, oval y espinoso, el meato acústico interno, el foramen yugular, el canal del hipogloso y el foramen magno son huecos."
    ],
    "orientation": "superior view; anterior at top; patient right = viewer right",
    "labels": [
      {
        "structureId": "anterior-cranial-fossa",
        "x": 0.3986,
        "y": 0.2475,
        "radius": 0.016
      },
      {
        "structureId": "middle-cranial-fossa",
        "x": 0.629,
        "y": 0.4848,
        "radius": 0.016
      },
      {
        "structureId": "posterior-cranial-fossa",
        "x": 0.411,
        "y": 0.808,
        "radius": 0.016
      },
      {
        "structureId": "ethmoid-bone",
        "x": 0.5,
        "y": 0.3133,
        "radius": 0.012
      },
      {
        "structureId": "cribriform-plate",
        "x": 0.4766,
        "y": 0.255,
        "radius": 0.016
      },
      {
        "structureId": "crista-galli",
        "x": 0.5,
        "y": 0.225,
        "radius": 0.016
      },
      {
        "structureId": "sella-turcica",
        "x": 0.5,
        "y": 0.405,
        "radius": 0.014
      },
      {
        "structureId": "clivus",
        "x": 0.5,
        "y": 0.48,
        "radius": 0.016
      },
      {
        "structureId": "optic-canal",
        "x": 0.5428,
        "y": 0.345,
        "radius": 0.012
      },
      {
        "structureId": "superior-orbital-fissure",
        "x": 0.5793,
        "y": 0.382,
        "radius": 0.012
      },
      {
        "structureId": "foramen-rotundum",
        "x": 0.5931,
        "y": 0.418,
        "radius": 0.012
      },
      {
        "structureId": "foramen-ovale",
        "x": 0.6138,
        "y": 0.455,
        "radius": 0.012
      },
      {
        "structureId": "foramen-spinosum",
        "x": 0.631,
        "y": 0.492,
        "radius": 0.012
      },
      {
        "structureId": "internal-acoustic-meatus",
        "x": 0.6241,
        "y": 0.59,
        "radius": 0.012
      },
      {
        "structureId": "jugular-foramen",
        "x": 0.6034,
        "y": 0.655,
        "radius": 0.012
      },
      {
        "structureId": "hypoglossal-canal",
        "x": 0.5607,
        "y": 0.668,
        "radius": 0.012
      },
      {
        "structureId": "foramen-magnum",
        "x": 0.5,
        "y": 0.705,
        "radius": 0.02
      },
      {
        "structureId": "internal-occipital-crest",
        "x": 0.5,
        "y": 0.805,
        "radius": 0.016
      }
    ]
  },
  {
    "id": "asset-skeletal-atlas-skull-sutures",
    "key": "skull-sutures",
    "replaces": null,
    "svgPath": "assets/images/anatomy/skeletal-atlas/skeletal-atlas-05-skull-sutures.svg",
    "pngPath": "assets/images/anatomy/skeletal-atlas/skeletal-atlas-05-skull-sutures.png",
    "title": [
      "Cranial sutures: superior and posterior views",
      "Suturas craneales: vistas superior y posterior"
    ],
    "description": [
      "Left panel: skull vault from above (anterior at top, patient right = viewer right) showing the frontal, parietal and occipital bones and the coronal and sagittal sutures. Right panel: skull from behind (patient right = viewer right) showing the lambdoid suture, occipital bone and temporal bone.",
      "Panel izquierdo: bóveda craneal vista desde arriba (anterior arriba, derecha del paciente a la derecha del observador) con los huesos frontal, parietal y occipital y las suturas coronal y sagital. Panel derecho: cráneo visto desde atrás (derecha del paciente a la derecha del observador) con la sutura lambdoidea y los huesos occipital y temporal."
    ],
    "orientation": "left panel superior view, anterior at top; right panel posterior view; patient right = viewer right in both",
    "labels": [
      {
        "structureId": "frontal-bone",
        "x": 0.269,
        "y": 0.2295,
        "radius": 0.016
      },
      {
        "structureId": "parietal-bone",
        "x": 0.1759,
        "y": 0.53,
        "radius": 0.016
      },
      {
        "structureId": "occipital-bone",
        "x": 0.269,
        "y": 0.7668,
        "radius": 0.016
      },
      {
        "structureId": "coronal-suture",
        "x": 0.1738,
        "y": 0.3735,
        "radius": 0.016
      },
      {
        "structureId": "sagittal-suture",
        "x": 0.269,
        "y": 0.5586,
        "radius": 0.016
      },
      {
        "structureId": "temporal-bone",
        "x": 0.8897,
        "y": 0.57,
        "radius": 0.016
      },
      {
        "structureId": "lambdoid-suture",
        "x": 0.8159,
        "y": 0.4225,
        "radius": 0.016
      }
    ]
  },
  {
    "id": "asset-skeletal-atlas-vertebra-typical",
    "key": "vertebra-typical",
    "replaces": null,
    "svgPath": "assets/images/anatomy/skeletal-atlas/skeletal-atlas-06-vertebra-typical.svg",
    "pngPath": "assets/images/anatomy/skeletal-atlas/skeletal-atlas-06-vertebra-typical.png",
    "title": [
      "Typical vertebra: superior view with lateral inset",
      "Vértebra típica: vista superior con recuadro lateral"
    ],
    "description": [
      "Main panel: the shared vertebral plan from above, with body/anterior at the top and spinous process at the bottom. Inset: a thoracic lateral detail with upper and lower costal demifacets on the posterior body margin, an attached inferior articular facet, and a disc between adjacent bodies. Anterior is toward the viewer's left. The inferior costal facet is shown only in this lateral detail, not as a visible superior surface.",
      "Panel principal: el plan vertebral común desde arriba, con cuerpo/anterior arriba y apófisis espinosa abajo. Recuadro: detalle torácico lateral con hemicarillas costales superior e inferior en el margen posterior del cuerpo, una carilla articular inferior unida al hueso y un disco entre cuerpos vecinos. Anterior está hacia la izquierda del observador. La carilla costal inferior se muestra solo en este detalle lateral, no como superficie visible desde arriba."
    ],
    "orientation": "main: superior view, body/anterior at top; inset: thoracic lateral detail, anterior toward viewer-left",
    "labels": [
      {
        "structureId": "spinous-process",
        "x": 0.3103,
        "y": 0.7786,
        "radius": 0.016
      },
      {
        "structureId": "transverse-process",
        "x": 0.2025,
        "y": 0.475,
        "radius": 0.016
      },
      {
        "structureId": "vertebral-body",
        "x": 0.3103,
        "y": 0.247,
        "radius": 0.016
      },
      {
        "structureId": "vertebral-foramen",
        "x": 0.3103,
        "y": 0.4607,
        "radius": 0.02
      },
      {
        "structureId": "superior-articular-facet",
        "x": 0.2448,
        "y": 0.56,
        "radius": 0.016
      },
      {
        "structureId": "inferior-articular-facet",
        "x": 0.7766,
        "y": 0.648,
        "radius": 0.014
      },
      {
        "structureId": "superior-costal-facet",
        "x": 0.7476,
        "y": 0.452,
        "radius": 0.012
      },
      {
        "structureId": "inferior-costal-facet",
        "x": 0.7476,
        "y": 0.605,
        "radius": 0.012
      },
      {
        "structureId": "intervertebral-disc",
        "x": 0.6931,
        "y": 0.639,
        "radius": 0.014
      }
    ]
  },
  {
    "id": "asset-cervical-vertebra",
    "key": "vertebrae-regional",
    "replaces": "asset-cervical-vertebra",
    "svgPath": "assets/images/anatomy/skeletal-atlas/skeletal-atlas-07-vertebrae-regional.svg",
    "pngPath": "assets/images/anatomy/skeletal-atlas/skeletal-atlas-07-vertebrae-regional.png",
    "title": [
      "Regional vertebrae compared: cervical, thoracic, lumbar (superior view)",
      "Vértebras regionales comparadas: cervical, torácica y lumbar (vista superior)"
    ],
    "description": [
      "Three vertebrae from above, left to right: cervical (small body, transverse foramina), thoracic (heart-shaped body, costal facets, long spinous process) and lumbar (large kidney-shaped body). Body and anterior at the top; spinous process at the bottom.",
      "Tres vértebras vistas desde arriba, de izquierda a derecha: cervical (cuerpo pequeño, forámenes transversos), torácica (cuerpo en forma de corazón, carillas costales, apófisis espinosa larga) y lumbar (cuerpo grande en forma de riñón). Cuerpo y parte anterior arriba; apófisis espinosa abajo."
    ],
    "orientation": "superior views; body/anterior at top; panels cervical, thoracic, lumbar",
    "labels": [
      {
        "structureId": "cervical-vertebrae",
        "x": 0.1793,
        "y": 0.2776,
        "radius": 0.016
      },
      {
        "structureId": "uncinate-process-vertebra",
        "x": 0.1248,
        "y": 0.315,
        "radius": 0.016
      },
      {
        "structureId": "vertebral-foramen",
        "x": 0.1793,
        "y": 0.4267,
        "radius": 0.02
      },
      {
        "structureId": "transverse-foramen",
        "x": 0.0841,
        "y": 0.445,
        "radius": 0.014
      },
      {
        "structureId": "spinous-process",
        "x": 0.5,
        "y": 0.8216,
        "radius": 0.016
      },
      {
        "structureId": "thoracic-vertebrae",
        "x": 0.5,
        "y": 0.259,
        "radius": 0.016
      },
      {
        "structureId": "superior-costal-facet",
        "x": 0.4434,
        "y": 0.34,
        "radius": 0.012
      },
      {
        "structureId": "accessory-process",
        "x": 0.7455,
        "y": 0.48,
        "radius": 0.016
      },
      {
        "structureId": "lumbar-vertebrae",
        "x": 0.8207,
        "y": 0.2955,
        "radius": 0.016
      },
      {
        "structureId": "mammillary-process",
        "x": 0.7517,
        "y": 0.495,
        "radius": 0.012
      }
    ]
  },
  {
    "id": "asset-skeletal-atlas-atlas-axis",
    "key": "atlas-axis",
    "replaces": null,
    "svgPath": "assets/images/anatomy/skeletal-atlas/skeletal-atlas-08-atlas-axis.svg",
    "pngPath": "assets/images/anatomy/skeletal-atlas/skeletal-atlas-08-atlas-axis.png",
    "title": [
      "Atlas (C1) from above and axis (C2) from the side",
      "Atlas (C1) desde arriba y axis (C2) de lado"
    ],
    "description": [
      "Left: the atlas (C1) from above, a ring with no body, anterior at top. Right: the axis (C2) from the side, anterior toward the viewer's left, with the dens projecting upward from the body.",
      "Izquierda: el atlas (C1) visto desde arriba, un anillo sin cuerpo, con la parte anterior arriba. Derecha: el axis (C2) de lado, con la parte anterior a la izquierda del observador y el diente proyectado hacia arriba desde el cuerpo."
    ],
    "orientation": "left: C1 superior view, anterior at top; right: C2 lateral view, anterior toward viewer-left",
    "labels": [
      {
        "structureId": "atlas-c1",
        "x": 0.2621,
        "y": 0.2744,
        "radius": 0.016
      },
      {
        "structureId": "vertebral-foramen",
        "x": 0.2621,
        "y": 0.44,
        "radius": 0.02
      },
      {
        "structureId": "superior-articular-facet",
        "x": 0.1586,
        "y": 0.44,
        "radius": 0.016
      },
      {
        "structureId": "transverse-foramen",
        "x": 0.1076,
        "y": 0.43,
        "radius": 0.012
      },
      {
        "structureId": "axis-c2",
        "x": 0.6634,
        "y": 0.7152,
        "radius": 0.014
      },
      {
        "structureId": "vertebral-body",
        "x": 0.709,
        "y": 0.64,
        "radius": 0.016
      },
      {
        "structureId": "dens",
        "x": 0.7041,
        "y": 0.346,
        "radius": 0.016
      },
      {
        "structureId": "spinous-process",
        "x": 0.8873,
        "y": 0.64,
        "radius": 0.016
      },
      {
        "structureId": "inferior-articular-facet",
        "x": 0.7655,
        "y": 0.8,
        "radius": 0.014
      }
    ]
  },
  {
    "id": "asset-skeletal-atlas-thoracic-cage",
    "key": "thoracic-cage",
    "replaces": null,
    "svgPath": "assets/images/anatomy/skeletal-atlas/skeletal-atlas-09-thoracic-cage.svg",
    "pngPath": "assets/images/anatomy/skeletal-atlas/skeletal-atlas-09-thoracic-cage.png",
    "title": [
      "Thoracic cage, anterior view",
      "Caja torácica, vista anterior"
    ],
    "description": [
      "Sternum (manubrium, body, xiphoid process) with 12 rib pairs and costal cartilages, anterior view. Patient right is on the viewer's left. True ribs 1-7 reach the sternum, false ribs 8-10 join the cartilage above, and ribs 11-12 float. Clavicles omitted.",
      "Esternón (manubrio, cuerpo, apófisis xifoides) con 12 pares de costillas y cartílagos costales, vista anterior. La derecha del paciente queda a la izquierda del observador. Las costillas verdaderas 1-7 llegan al esternón, las falsas 8-10 se unen al cartílago superior y las 11-12 son flotantes. Clavículas omitidas."
    ],
    "orientation": "anterior view; patient right = viewer left; clavicles omitted",
    "labels": [
      {
        "structureId": "true-ribs",
        "x": 0.3324,
        "y": 0.381,
        "radius": 0.016
      },
      {
        "structureId": "false-ribs",
        "x": 0.3557,
        "y": 0.6685,
        "radius": 0.016
      },
      {
        "structureId": "floating-ribs",
        "x": 0.4348,
        "y": 0.8365,
        "radius": 0.016
      },
      {
        "structureId": "sternum",
        "x": 0.5,
        "y": 0.4125,
        "radius": 0.016
      },
      {
        "structureId": "manubrium",
        "x": 0.5,
        "y": 0.185,
        "radius": 0.014
      },
      {
        "structureId": "body-of-sternum",
        "x": 0.5,
        "y": 0.441,
        "radius": 0.014
      },
      {
        "structureId": "xiphoid-process",
        "x": 0.5,
        "y": 0.668,
        "radius": 0.012
      }
    ]
  },
  {
    "id": "asset-skeletal-atlas-rib-detail",
    "key": "rib-detail",
    "replaces": null,
    "svgPath": "assets/images/anatomy/skeletal-atlas/skeletal-atlas-10-rib-detail.svg",
    "pngPath": "assets/images/anatomy/skeletal-atlas/skeletal-atlas-10-rib-detail.png",
    "title": [
      "Rib detail: head, tubercle and costal groove",
      "Detalle de costilla: cabeza, tubérculo y surco costal"
    ],
    "description": [
      "Left panel: posterior end of a right rib from behind (patient right = viewer right, so the spine is at the viewer's left) meeting a thoracic vertebra. Right panel: the same rib seen from its inner surface, with the costal groove along the lower border.",
      "Panel izquierdo: extremo posterior de una costilla derecha vista desde atrás (derecha del paciente a la derecha del observador, por lo que la columna queda a la izquierda) articulada con una vértebra torácica. Panel derecho: la misma costilla vista por su cara interna, con el surco costal en el borde inferior."
    ],
    "orientation": "left: posterior view of right rib, spine at viewer-left; right: inner (visceral) surface",
    "labels": [
      {
        "structureId": "vertebral-body",
        "x": 0.1172,
        "y": 0.505,
        "radius": 0.016
      },
      {
        "structureId": "superior-costal-facet",
        "x": 0.1807,
        "y": 0.36,
        "radius": 0.012
      },
      {
        "structureId": "transverse-process",
        "x": 0.2253,
        "y": 0.54,
        "radius": 0.016
      },
      {
        "structureId": "rib-head",
        "x": 0.2069,
        "y": 0.36,
        "radius": 0.016
      },
      {
        "structureId": "rib-tubercle",
        "x": 0.2897,
        "y": 0.43,
        "radius": 0.016
      },
      {
        "structureId": "costal-groove",
        "x": 0.7503,
        "y": 0.5875,
        "radius": 0.016
      }
    ]
  },
  {
    "id": "asset-skeletal-atlas-scapula",
    "key": "scapula",
    "replaces": null,
    "svgPath": "assets/images/anatomy/skeletal-atlas/skeletal-atlas-11-scapula.svg",
    "pngPath": "assets/images/anatomy/skeletal-atlas/skeletal-atlas-11-scapula.png",
    "title": [
      "Right scapula: anterior (left) and posterior (right)",
      "Escápula derecha: anterior (izquierda) y posterior (derecha)"
    ],
    "description": [
      "Right scapula twice. Anterior view: glenoid cavity toward the viewer's left, coracoid process projecting forward. Posterior view: glenoid toward the viewer's right, with the scapular spine ending in the acromion. The spine is posterior only; the coracoid is anterior.",
      "Escápula derecha dos veces. Vista anterior: cavidad glenoidea hacia la izquierda del observador y apófisis coracoides proyectada hacia delante. Vista posterior: glenoides hacia la derecha, con la espina de la escápula terminando en el acromion. La espina es solo posterior; la coracoides es anterior."
    ],
    "orientation": "right scapula; anterior panel: glenoid at viewer-left; posterior panel: glenoid at viewer-right",
    "labels": [
      {
        "structureId": "scapula",
        "x": 0.3369,
        "y": 0.5243,
        "radius": 0.016
      },
      {
        "structureId": "coracoid-process",
        "x": 0.1931,
        "y": 0.2233,
        "radius": 0.016
      },
      {
        "structureId": "glenoid-cavity",
        "x": 0.2103,
        "y": 0.31,
        "radius": 0.016
      },
      {
        "structureId": "scapular-spine",
        "x": 0.7121,
        "y": 0.2613,
        "radius": 0.016
      },
      {
        "structureId": "acromion",
        "x": 0.8195,
        "y": 0.179,
        "radius": 0.016
      }
    ]
  },
  {
    "id": "asset-skeletal-atlas-pectoral-girdle",
    "key": "pectoral-girdle",
    "replaces": null,
    "svgPath": "assets/images/anatomy/skeletal-atlas/skeletal-atlas-12-pectoral-girdle.svg",
    "pngPath": "assets/images/anatomy/skeletal-atlas/skeletal-atlas-12-pectoral-girdle.png",
    "title": [
      "Pectoral girdle relationships, anterior view (right side detailed)",
      "Relaciones de la cintura escapular, vista anterior (lado derecho detallado)"
    ],
    "description": [
      "Anterior view. Patient right is on the viewer's left and is drawn in detail: clavicle from manubrium to acromion, acromioclavicular ligament, coracoid process below the clavicle, scapula behind, glenoid cavity and the humeral head. The left clavicle is shown plain.",
      "Vista anterior. La derecha del paciente queda a la izquierda del observador y está dibujada con detalle: clavícula del manubrio al acromion, ligamento acromioclavicular, apófisis coracoides bajo la clavícula, escápula detrás, cavidad glenoidea y cabeza del húmero. La clavícula izquierda se muestra sin detalle."
    ],
    "orientation": "anterior view; patient right = viewer left",
    "labels": [
      {
        "structureId": "scapula",
        "x": 0.3179,
        "y": 0.538,
        "radius": 0.016
      },
      {
        "structureId": "glenoid-cavity",
        "x": 0.24,
        "y": 0.4,
        "radius": 0.016
      },
      {
        "structureId": "humeral-head",
        "x": 0.2069,
        "y": 0.41,
        "radius": 0.016
      },
      {
        "structureId": "manubrium",
        "x": 0.5,
        "y": 0.3225,
        "radius": 0.016
      },
      {
        "structureId": "clavicle",
        "x": 0.3741,
        "y": 0.2564,
        "radius": 0.016
      },
      {
        "structureId": "acromion",
        "x": 0.2379,
        "y": 0.3,
        "radius": 0.016
      },
      {
        "structureId": "acromioclavicular-ligament",
        "x": 0.269,
        "y": 0.286,
        "radius": 0.014
      },
      {
        "structureId": "coracoid-process",
        "x": 0.2851,
        "y": 0.3563,
        "radius": 0.016
      }
    ]
  },
  {
    "id": "asset-skeletal-atlas-humerus",
    "key": "humerus",
    "replaces": null,
    "svgPath": "assets/images/anatomy/skeletal-atlas/skeletal-atlas-13-humerus.svg",
    "pngPath": "assets/images/anatomy/skeletal-atlas/skeletal-atlas-13-humerus.png",
    "title": [
      "Right humerus: anterior (left) and posterior (right)",
      "Húmero derecho: anterior (izquierda) y posterior (derecha)"
    ],
    "description": [
      "Right humerus twice. Anterior view: the head points medially (viewer's right); capitulum is lateral and trochlea medial. Posterior view: the head points toward the viewer's left (medial).",
      "Húmero derecho dos veces. Vista anterior: la cabeza apunta medialmente (derecha del observador); el capitulum es lateral y la tróclea medial. Vista posterior: la cabeza apunta hacia la izquierda del observador (medial)."
    ],
    "orientation": "right humerus; anterior panel head medial = viewer-right; posterior panel head medial = viewer-left",
    "labels": [
      {
        "structureId": "humerus",
        "x": 0.2841,
        "y": 0.537,
        "radius": 0.016
      },
      {
        "structureId": "humeral-head",
        "x": 0.3117,
        "y": 0.166,
        "radius": 0.016
      },
      {
        "structureId": "greater-tubercle",
        "x": 0.2366,
        "y": 0.166,
        "radius": 0.016
      },
      {
        "structureId": "deltoid-tuberosity",
        "x": 0.2566,
        "y": 0.47,
        "radius": 0.014
      },
      {
        "structureId": "lateral-epicondyle",
        "x": 0.2303,
        "y": 0.788,
        "radius": 0.014
      },
      {
        "structureId": "medial-epicondyle",
        "x": 0.3241,
        "y": 0.788,
        "radius": 0.014
      },
      {
        "structureId": "capitulum",
        "x": 0.2524,
        "y": 0.848,
        "radius": 0.016
      },
      {
        "structureId": "trochlea",
        "x": 0.2979,
        "y": 0.852,
        "radius": 0.016
      }
    ]
  },
  {
    "id": "asset-skeletal-atlas-forearm",
    "key": "forearm",
    "replaces": null,
    "svgPath": "assets/images/anatomy/skeletal-atlas/skeletal-atlas-14-forearm.svg",
    "pngPath": "assets/images/anatomy/skeletal-atlas/skeletal-atlas-14-forearm.png",
    "title": [
      "Right forearm, anterior view, with proximal-ulna inset",
      "Antebrazo derecho, vista anterior, con recuadro del cúbito proximal"
    ],
    "description": [
      "Right radius (viewer's left, lateral) and ulna (viewer's right, medial) from the front, joined by the interosseous membrane. Inset: the proximal ulna from the side showing the olecranon and the trochlear notch.",
      "Radio derecho (a la izquierda del observador, lateral) y cúbito (a la derecha, medial) vistos de frente, unidos por la membrana interósea. Recuadro: cúbito proximal de lado con el olécranon y la incisura troclear."
    ],
    "orientation": "right forearm anterior view: radius viewer-left, ulna viewer-right; inset lateral view of proximal ulna",
    "labels": [
      {
        "structureId": "interosseous-membrane",
        "x": 0.3483,
        "y": 0.515,
        "radius": 0.014
      },
      {
        "structureId": "radius",
        "x": 0.2931,
        "y": 0.576,
        "radius": 0.016
      },
      {
        "structureId": "radial-head",
        "x": 0.2966,
        "y": 0.19,
        "radius": 0.014
      },
      {
        "structureId": "radial-tuberosity",
        "x": 0.3186,
        "y": 0.29,
        "radius": 0.014
      },
      {
        "structureId": "radial-styloid",
        "x": 0.2603,
        "y": 0.825,
        "radius": 0.012
      },
      {
        "structureId": "ulna",
        "x": 0.3983,
        "y": 0.5265,
        "radius": 0.016
      },
      {
        "structureId": "ulnar-styloid",
        "x": 0.4255,
        "y": 0.815,
        "radius": 0.012
      },
      {
        "structureId": "olecranon",
        "x": 0.7641,
        "y": 0.188,
        "radius": 0.016
      },
      {
        "structureId": "trochlear-notch",
        "x": 0.7469,
        "y": 0.27,
        "radius": 0.016
      }
    ]
  },
  {
    "id": "asset-skeletal-atlas-hand-palmar",
    "key": "hand-palmar",
    "replaces": null,
    "svgPath": "assets/images/anatomy/skeletal-atlas/skeletal-atlas-15-hand-palmar.svg",
    "pngPath": "assets/images/anatomy/skeletal-atlas/skeletal-atlas-15-hand-palmar.png",
    "title": [
      "Right hand, palmar view: carpals, metacarpals, phalanges",
      "Mano derecha, vista palmar: carpos, metacarpianos y falanges"
    ],
    "description": [
      "Right hand from the palm side, thumb at the viewer's left. Proximal carpal row (radial to ulnar): scaphoid, lunate, triquetrum with the pisiform on its palmar surface. Distal row: trapezium, trapezoid, capitate, hamate with its hook. The thumb has 2 phalanges; the other digits have 3.",
      "Mano derecha vista por la palma, con el pulgar a la izquierda del observador. Fila proximal del carpo (de radial a cubital): escafoides, semilunar, piramidal con el pisiforme en su cara palmar. Fila distal: trapecio, trapezoide, hueso grande, ganchoso con su gancho. El pulgar tiene 2 falanges; los demás dedos, 3."
    ],
    "orientation": "right palmar view; thumb at viewer-left; wrist at bottom",
    "labels": [
      {
        "structureId": "radial-styloid",
        "x": 0.4259,
        "y": 0.785,
        "radius": 0.012
      },
      {
        "structureId": "ulnar-styloid",
        "x": 0.5638,
        "y": 0.79,
        "radius": 0.012
      },
      {
        "structureId": "metacarpals",
        "x": 0.4979,
        "y": 0.5005,
        "radius": 0.016
      },
      {
        "structureId": "phalanges-hand",
        "x": 0.4979,
        "y": 0.309,
        "radius": 0.016
      },
      {
        "structureId": "trapezium",
        "x": 0.4394,
        "y": 0.6434,
        "radius": 0.016
      },
      {
        "structureId": "trapezoid",
        "x": 0.4814,
        "y": 0.614,
        "radius": 0.016
      },
      {
        "structureId": "capitate",
        "x": 0.5177,
        "y": 0.6312,
        "radius": 0.016
      },
      {
        "structureId": "hamate",
        "x": 0.5628,
        "y": 0.6258,
        "radius": 0.016
      },
      {
        "structureId": "hook-of-hamate",
        "x": 0.5738,
        "y": 0.6693,
        "radius": 0.012
      },
      {
        "structureId": "scaphoid",
        "x": 0.4534,
        "y": 0.7057,
        "radius": 0.016
      },
      {
        "structureId": "lunate",
        "x": 0.5052,
        "y": 0.6998,
        "radius": 0.016
      },
      {
        "structureId": "triquetrum",
        "x": 0.5408,
        "y": 0.697,
        "radius": 0.016
      },
      {
        "structureId": "pisiform",
        "x": 0.5545,
        "y": 0.73,
        "radius": 0.012
      }
    ]
  },
  {
    "id": "asset-skeletal-atlas-hip-bone",
    "key": "hip-bone",
    "replaces": null,
    "svgPath": "assets/images/anatomy/skeletal-atlas/skeletal-atlas-16-hip-bone.svg",
    "pngPath": "assets/images/anatomy/skeletal-atlas/skeletal-atlas-16-hip-bone.png",
    "title": [
      "Right hip bone: lateral (left) and medial (right) views",
      "Hueso coxal derecho: vistas lateral (izquierda) y medial (derecha)"
    ],
    "description": [
      "Right hip bone twice. Lateral view: anterior toward the viewer's right; ilium, ischium and pubis meet at the acetabulum, with the obturator foramen below. Medial view: anterior toward the viewer's left; the auricular surface of the ilium forms the sacroiliac joint.",
      "Hueso coxal derecho dos veces. Vista lateral: anterior hacia la derecha del observador; íleon, isquion y pubis confluyen en el acetábulo, con el foramen obturador debajo. Vista medial: anterior hacia la izquierda; la superficie auricular del íleon forma la articulación sacroilíaca."
    ],
    "orientation": "right hip bone; lateral panel anterior = viewer-right; medial panel anterior = viewer-left",
    "labels": [
      {
        "structureId": "ilium",
        "x": 0.2828,
        "y": 0.236,
        "radius": 0.016
      },
      {
        "structureId": "iliac-crest",
        "x": 0.2584,
        "y": 0.1667,
        "radius": 0.016
      },
      {
        "structureId": "asis",
        "x": 0.3779,
        "y": 0.21,
        "radius": 0.014
      },
      {
        "structureId": "ischium",
        "x": 0.2214,
        "y": 0.6223,
        "radius": 0.016
      },
      {
        "structureId": "pubis",
        "x": 0.371,
        "y": 0.686,
        "radius": 0.016
      },
      {
        "structureId": "ischial-tuberosity",
        "x": 0.1966,
        "y": 0.752,
        "radius": 0.014
      },
      {
        "structureId": "acetabulum",
        "x": 0.2966,
        "y": 0.54,
        "radius": 0.02
      },
      {
        "structureId": "obturator-foramen",
        "x": 0.299,
        "y": 0.6733,
        "radius": 0.014
      },
      {
        "structureId": "sacroiliac-joint",
        "x": 0.7724,
        "y": 0.33,
        "radius": 0.02
      }
    ]
  },
  {
    "id": "asset-skeletal-atlas-femur",
    "key": "femur",
    "replaces": null,
    "svgPath": "assets/images/anatomy/skeletal-atlas/skeletal-atlas-17-femur.svg",
    "pngPath": "assets/images/anatomy/skeletal-atlas/skeletal-atlas-17-femur.png",
    "title": [
      "Right femur: anterior (left) and posterior (right)",
      "Fémur derecho: anterior (izquierda) y posterior (derecha)"
    ],
    "description": [
      "Right femur twice. Anterior view: the head points medially (viewer's right). Posterior view: the head points to the viewer's left and the linea aspera runs as a ridge down the back of the shaft. Patella omitted.",
      "Fémur derecho dos veces. Vista anterior: la cabeza apunta medialmente (derecha del observador). Vista posterior: la cabeza apunta a la izquierda y la línea áspera recorre como una cresta la parte posterior de la diáfisis. Rótula omitida."
    ],
    "orientation": "right femur; anterior panel head = viewer-right; posterior panel head = viewer-left; patella omitted",
    "labels": [
      {
        "structureId": "femur",
        "x": 0.2862,
        "y": 0.305,
        "radius": 0.016
      },
      {
        "structureId": "femoral-neck",
        "x": 0.3069,
        "y": 0.229,
        "radius": 0.016
      },
      {
        "structureId": "femoral-head",
        "x": 0.3359,
        "y": 0.165,
        "radius": 0.016
      },
      {
        "structureId": "greater-trochanter",
        "x": 0.2331,
        "y": 0.212,
        "radius": 0.016
      },
      {
        "structureId": "femoral-condyles",
        "x": 0.2428,
        "y": 0.842,
        "radius": 0.02
      },
      {
        "structureId": "femoral-linea-aspera",
        "x": 0.73,
        "y": 0.5624,
        "radius": 0.014
      }
    ]
  },
  {
    "id": "asset-skeletal-atlas-leg-tibia-fibula",
    "key": "leg-tibia-fibula",
    "replaces": null,
    "svgPath": "assets/images/anatomy/skeletal-atlas/skeletal-atlas-18-leg-tibia-fibula.svg",
    "pngPath": "assets/images/anatomy/skeletal-atlas/skeletal-atlas-18-leg-tibia-fibula.png",
    "title": [
      "Right leg, anterior view, with tibial-plateau inset",
      "Pierna derecha, vista anterior, con recuadro de la meseta tibial"
    ],
    "description": [
      "Right tibia (medial, viewer's right) and fibula (lateral, viewer's left) from the front with the ankle mortise at the bottom. Inset: the tibial plateau from above (anterior at top) showing the intercondylar eminence between the two articular surfaces; patella omitted.",
      "Tibia derecha (medial, a la derecha del observador) y peroné (lateral, a la izquierda) vistos de frente, con la mortaja del tobillo abajo. Recuadro: la meseta tibial desde arriba (anterior arriba) con la eminencia intercondílea entre las dos superficies articulares; rótula omitida."
    ],
    "orientation": "right leg anterior view: fibula viewer-left, tibia viewer-right; inset superior view of plateau, anterior at top",
    "labels": [
      {
        "structureId": "fibula",
        "x": 0.2917,
        "y": 0.5207,
        "radius": 0.016
      },
      {
        "structureId": "tibia",
        "x": 0.3741,
        "y": 0.5317,
        "radius": 0.016
      },
      {
        "structureId": "tibial-tuberosity",
        "x": 0.3759,
        "y": 0.32,
        "radius": 0.014
      },
      {
        "structureId": "medial-malleolus",
        "x": 0.4121,
        "y": 0.87,
        "radius": 0.014
      },
      {
        "structureId": "lateral-malleolus",
        "x": 0.2897,
        "y": 0.9,
        "radius": 0.014
      },
      {
        "structureId": "ankle-mortise",
        "x": 0.3478,
        "y": 0.8913,
        "radius": 0.014
      },
      {
        "structureId": "tibial-plateau",
        "x": 0.6841,
        "y": 0.51,
        "radius": 0.02
      },
      {
        "structureId": "intercondylar-eminence",
        "x": 0.7701,
        "y": 0.5233,
        "radius": 0.014
      }
    ]
  },
  {
    "id": "asset-skeletal-atlas-foot-dorsal",
    "key": "foot-dorsal",
    "replaces": null,
    "svgPath": "assets/images/anatomy/skeletal-atlas/skeletal-atlas-19-foot-dorsal.svg",
    "pngPath": "assets/images/anatomy/skeletal-atlas/skeletal-atlas-19-foot-dorsal.png",
    "title": [
      "Right foot, dorsal view: tarsals, metatarsals, phalanges",
      "Pie derecho, vista dorsal: tarsos, metatarsianos y falanges"
    ],
    "description": [
      "Right foot from above, toes up, big toe (hallux) at the viewer's left. The talus sits above the calcaneus; navicular is medial, cuboid lateral, and the three cuneiforms lie under metatarsals 1-3. The big toe has 2 phalanges; the other toes have 3. \"Hallux\" is shown as the first-toe phalanges; it is not a separate structure.",
      "Pie derecho visto desde arriba, con los dedos hacia arriba y el dedo gordo (hallux) a la izquierda del observador. El astrágalo se apoya sobre el calcáneo; el navicular es medial, el cuboides lateral y las tres cuñas quedan bajo los metatarsianos 1-3. El dedo gordo tiene 2 falanges; los demás, 3. «Hallux» se muestra como las falanges del primer dedo; no es una estructura aparte."
    ],
    "orientation": "right dorsal view; hallux at viewer-left; heel at bottom",
    "labels": [
      {
        "structureId": "calcaneus",
        "x": 0.5345,
        "y": 0.8913,
        "radius": 0.016
      },
      {
        "structureId": "talus",
        "x": 0.4571,
        "y": 0.7357,
        "radius": 0.016
      },
      {
        "structureId": "navicular",
        "x": 0.4429,
        "y": 0.6146,
        "radius": 0.016
      },
      {
        "structureId": "cuboid",
        "x": 0.5572,
        "y": 0.6064,
        "radius": 0.016
      },
      {
        "structureId": "medial-cuneiform",
        "x": 0.4007,
        "y": 0.5438,
        "radius": 0.016
      },
      {
        "structureId": "intermediate-cuneiform",
        "x": 0.4441,
        "y": 0.5285,
        "radius": 0.016
      },
      {
        "structureId": "lateral-cuneiform",
        "x": 0.4872,
        "y": 0.531,
        "radius": 0.016
      },
      {
        "structureId": "metatarsals",
        "x": 0.4763,
        "y": 0.3833,
        "radius": 0.016
      },
      {
        "structureId": "phalanges-foot",
        "x": 0.4779,
        "y": 0.25,
        "radius": 0.016
      }
    ]
  },
  {
    "id": "asset-skeletal-atlas-synovial-joint",
    "key": "synovial-joint",
    "replaces": null,
    "svgPath": "assets/images/anatomy/skeletal-atlas/skeletal-atlas-20-synovial-joint.svg",
    "pngPath": "assets/images/anatomy/skeletal-atlas/skeletal-atlas-20-synovial-joint.png",
    "title": [
      "Generic synovial joint in section",
      "Articulación sinovial genérica en corte"
    ],
    "description": [
      "A diagrammatic synovial joint cut lengthwise, not tied to any one region. Cartilage-capped bone ends bound a joint cavity holding synovial fluid; the synovial membrane lines the fibrous capsule; an external ligament crosses the joint.",
      "Una articulación sinovial esquemática cortada a lo largo, sin relación con una región concreta. Los extremos óseos cubiertos de cartílago delimitan una cavidad articular con líquido sinovial; la membrana sinovial reviste la cápsula fibrosa; un ligamento externo cruza la articulación."
    ],
    "orientation": "schematic lengthwise section; proximal bone at top; no left-right meaning",
    "labels": [
      {
        "structureId": "synovial-joint",
        "x": 0.3179,
        "y": 0.5,
        "radius": 0.02
      },
      {
        "structureId": "fibrous-capsule",
        "x": 0.3759,
        "y": 0.4592,
        "radius": 0.014
      },
      {
        "structureId": "synovial-membrane",
        "x": 0.4103,
        "y": 0.4925,
        "radius": 0.012
      },
      {
        "structureId": "articular-cartilage",
        "x": 0.5,
        "y": 0.39,
        "radius": 0.014
      },
      {
        "structureId": "joint-cavity",
        "x": 0.5,
        "y": 0.5117,
        "radius": 0.016
      },
      {
        "structureId": "synovial-fluid",
        "x": 0.5,
        "y": 0.52,
        "radius": 0.012
      },
      {
        "structureId": "ligament",
        "x": 0.3897,
        "y": 0.3328,
        "radius": 0.014
      }
    ]
  },
  {
    "id": "asset-skeletal-atlas-shoulder-joint",
    "key": "shoulder-joint",
    "replaces": null,
    "svgPath": "assets/images/anatomy/skeletal-atlas/skeletal-atlas-21-shoulder-joint.svg",
    "pngPath": "assets/images/anatomy/skeletal-atlas/skeletal-atlas-21-shoulder-joint.png",
    "title": [
      "Right shoulder joint relationships, anterior view",
      "Relaciones de la articulación del hombro derecho, vista anterior"
    ],
    "description": [
      "Right shoulder from the front. The humerus is at the viewer's left; its head points medially (viewer's right) into the glenoid cavity of the scapula. Glenohumeral ligaments strengthen the front of the capsule; the acromioclavicular ligament joins clavicle and acromion above. Patient right is on the viewer's left.",
      "Hombro derecho visto de frente. El húmero queda a la izquierda del observador; su cabeza apunta medialmente (derecha del observador) hacia la cavidad glenoidea de la escápula. Los ligamentos glenohumerales refuerzan la parte anterior de la cápsula; el ligamento acromioclavicular une clavícula y acromion arriba. La derecha del paciente queda a la izquierda del observador."
    ],
    "orientation": "right shoulder anterior view; humerus viewer-left, scapula viewer-right",
    "labels": [
      {
        "structureId": "scapula",
        "x": 0.5803,
        "y": 0.6,
        "radius": 0.016
      },
      {
        "structureId": "greater-tubercle",
        "x": 0.331,
        "y": 0.44,
        "radius": 0.016
      },
      {
        "structureId": "humeral-head",
        "x": 0.3763,
        "y": 0.48,
        "radius": 0.016
      },
      {
        "structureId": "glenoid-cavity",
        "x": 0.4483,
        "y": 0.48,
        "radius": 0.016
      },
      {
        "structureId": "shoulder-joint",
        "x": 0.4262,
        "y": 0.48,
        "radius": 0.014
      },
      {
        "structureId": "glenohumeral-ligaments",
        "x": 0.4161,
        "y": 0.4183,
        "radius": 0.014
      },
      {
        "structureId": "acromion",
        "x": 0.4362,
        "y": 0.305,
        "radius": 0.016
      },
      {
        "structureId": "coracoid-process",
        "x": 0.4494,
        "y": 0.3673,
        "radius": 0.016
      },
      {
        "structureId": "clavicle",
        "x": 0.6655,
        "y": 0.254,
        "radius": 0.016
      },
      {
        "structureId": "acromioclavicular-ligament",
        "x": 0.3741,
        "y": 0.292,
        "radius": 0.014
      }
    ]
  },
  {
    "id": "asset-skeletal-atlas-knee-joint",
    "key": "knee-joint",
    "replaces": null,
    "svgPath": "assets/images/anatomy/skeletal-atlas/skeletal-atlas-22-knee-joint.svg",
    "pngPath": "assets/images/anatomy/skeletal-atlas/skeletal-atlas-22-knee-joint.png",
    "title": [
      "Right knee: anterior layer (left) and deep cruciates, patella omitted (right)",
      "Rodilla derecha: capa anterior (izquierda) y cruzados profundos, sin rótula (derecha)"
    ],
    "description": [
      "Right knee from the front, patient right at the viewer's left, so the fibular head and lateral collateral ligament are at the left and the medial collateral ligament at the right. Left panel: patella with the patellar ligament. Right panel: patella omitted to show the deep layer: the ACL runs from the lateral femoral condyle to the anterior tibial intercondylar area; the PCL runs from the posterior tibial intercondylar area to the medial femoral condyle, passing behind the ACL.",
      "Rodilla derecha vista de frente, con la derecha del paciente a la izquierda del observador, de modo que la cabeza del peroné y el ligamento colateral lateral quedan a la izquierda y el ligamento colateral medial a la derecha. Panel izquierdo: rótula con el ligamento rotuliano. Panel derecho: rótula omitida para mostrar la capa profunda: el LCA va del cóndilo femoral lateral al área intercondílea anterior de la tibia; el LCP va del área intercondílea posterior de la tibia al cóndilo femoral medial, pasando por detrás del LCA."
    ],
    "orientation": "right knee anterior view; lateral (fibula, LCL) at viewer-left; medial (MCL) at viewer-right; patella omitted in right panel",
    "labels": [
      {
        "structureId": "patella",
        "x": 0.2759,
        "y": 0.345,
        "radius": 0.02
      },
      {
        "structureId": "patellar-ligament",
        "x": 0.2763,
        "y": 0.5017,
        "radius": 0.014
      },
      {
        "structureId": "tibial-tuberosity",
        "x": 0.2772,
        "y": 0.64,
        "radius": 0.014
      },
      {
        "structureId": "lcl",
        "x": 0.1908,
        "y": 0.4483,
        "radius": 0.012
      },
      {
        "structureId": "mcl",
        "x": 0.3598,
        "y": 0.5,
        "radius": 0.014
      },
      {
        "structureId": "knee-joint",
        "x": 0.2759,
        "y": 0.48,
        "radius": 0.02
      },
      {
        "structureId": "femoral-condyles",
        "x": 0.6634,
        "y": 0.346,
        "radius": 0.02
      },
      {
        "structureId": "intercondylar-eminence",
        "x": 0.7241,
        "y": 0.493,
        "radius": 0.014
      },
      {
        "structureId": "pcl",
        "x": 0.7428,
        "y": 0.352,
        "radius": 0.012
      },
      {
        "structureId": "acl",
        "x": 0.7062,
        "y": 0.35,
        "radius": 0.012
      }
    ]
  }
] as SkeletalPlate[];
