import type { Lesson, Module, Question, SourceRecord, Structure } from './model';
import { OPENSTAX_SOURCE_ID } from './anatomy.ts';

export const SKELETAL_AXIAL_SOURCE_ID = 'source-openstax-ap-2013-skeletal-ch7';
export const SKELETAL_APPENDICULAR_SOURCE_ID = 'source-openstax-ap-2013-skeletal-ch8';
export const SKELETAL_SOURCE_ID = SKELETAL_AXIAL_SOURCE_ID;
export const JOINTS_SOURCE_ID = 'source-openstax-ap-2013-joints-ch9';
export const MUSCULAR_SOURCE_ID = 'source-openstax-ap-2013-muscle-ch11';
export const NERVOUS_SOURCE_ID = 'source-openstax-ap-2013-nervous-ch13';
export const NERVOUS_TISSUE_SOURCE_ID = 'source-openstax-ap-2013-nervous-ch12';
const sourceForStructure = (moduleId: string, category: string): string => {
  if (moduleId === 'skeletal-system') return /hand|carpal|tarsal|articular|radius|ulna|femur|tibia|fibula|pelvic|shoulder|humerus|forearm|foot|limb|rib landmarks/.test(category) ? SKELETAL_APPENDICULAR_SOURCE_ID : SKELETAL_AXIAL_SOURCE_ID;
  if (moduleId === 'nervous-system' && category === 'neural pathways') return NERVOUS_TISSUE_SOURCE_ID;
  return sourceForModule(moduleId);
};
const sourceForQuestion = (moduleId: string, structureId: string): string => moduleId === 'skeletal-system' && /carpal|foot|forearm|pelvis|leg|humer|radius|femur|rib/.test(structureId) ? SKELETAL_APPENDICULAR_SOURCE_ID : moduleId === 'nervous-system' && structureId === 'spinothalamic-tract' ? NERVOUS_TISSUE_SOURCE_ID : sourceForModule(moduleId);
const sourceForModule = (moduleId: string): string => ({
  'skeletal-system': SKELETAL_SOURCE_ID,
  'joints-ligaments': JOINTS_SOURCE_ID,
  'muscular-system': MUSCULAR_SOURCE_ID,
  'nervous-system': NERVOUS_SOURCE_ID,
}[moduleId] ?? OPENSTAX_SOURCE_ID);
export const systemsSources: SourceRecord[] = [
  { id:SKELETAL_AXIAL_SOURCE_ID, filename:'OpenStax Anatomy and Physiology (2013), Ch. 7 axial skeleton', hash:'openstax-ap-2013-ch7-axial', pageCount:null, title:'OpenStax 2013 · Axial Skeleton', courseLabAssociation:null, sourceType:'text', attributionLicenseStatus:'CC BY 4.0; attribution to OpenStax and contributors required', notes:'Chapter/section-level provenance for skull, vertebral column, and axial landmarks.', sourceUrl:'https://openstax.org/books/anatomy-and-physiology/pages/7-1-divisions-of-the-skeletal-system', licenseUrl:'https://creativecommons.org/licenses/by/4.0/', verificationStatus:'verified' },
  { id:SKELETAL_APPENDICULAR_SOURCE_ID, filename:'OpenStax Anatomy and Physiology (2013), Ch. 8 appendicular skeleton', hash:'openstax-ap-2013-ch8-appendicular', pageCount:null, title:'OpenStax 2013 · Appendicular Skeleton', courseLabAssociation:null, sourceType:'text', attributionLicenseStatus:'CC BY 4.0; attribution to OpenStax and contributors required', notes:'Chapter/section-level provenance for girdles, limbs, hands, feet, and articular landmarks.', sourceUrl:'https://openstax.org/books/anatomy-and-physiology/pages/8-1-the-pectoral-girdle', licenseUrl:'https://creativecommons.org/licenses/by/4.0/', verificationStatus:'verified' },
  { id:JOINTS_SOURCE_ID, filename:'OpenStax Anatomy and Physiology (2013), Ch. 9 joints', hash:'openstax-ap-2013-ch9-joints', pageCount:null, title:'OpenStax 2013 · Joints and Skeletal Movement', courseLabAssociation:null, sourceType:'text', attributionLicenseStatus:'CC BY 4.0; attribution to OpenStax and contributors required', notes:'Chapter/section-level provenance for joint classifications, synovial features, and movement.', sourceUrl:'https://openstax.org/books/anatomy-and-physiology/pages/9-1-classification-of-joints', licenseUrl:'https://creativecommons.org/licenses/by/4.0/', verificationStatus:'verified' },
  { id:MUSCULAR_SOURCE_ID, filename:'OpenStax Anatomy and Physiology (2013), Ch. 11 muscle interactions', hash:'openstax-ap-2013-ch11-muscle-interactions', pageCount:null, title:'OpenStax 2013 · Muscle Interactions', courseLabAssociation:null, sourceType:'text', attributionLicenseStatus:'CC BY 4.0; attribution to OpenStax and contributors required', notes:'Chapter/section-level provenance for regional muscle recognition, actions, and attachments.', sourceUrl:'https://openstax.org/books/anatomy-and-physiology/pages/11-1-interactions-of-skeletal-muscles-their-fascicle-arrangement-and-their-lever-systems', licenseUrl:'https://creativecommons.org/licenses/by/4.0/', verificationStatus:'verified' },
  { id:NERVOUS_TISSUE_SOURCE_ID, filename:'OpenStax Anatomy and Physiology (2013), Ch. 12 nervous tissue', hash:'openstax-ap-2013-ch12-nervous-tissue', pageCount:null, title:'OpenStax 2013 · Nervous Tissue', courseLabAssociation:null, sourceType:'text', attributionLicenseStatus:'CC BY 4.0; attribution to OpenStax and contributors required', notes:'Chapter/section-level provenance for introductory neural pathways and nervous tissue concepts.', sourceUrl:'https://openstax.org/books/anatomy-and-physiology/pages/12-1-basic-structure-and-function-of-the-nervous-system', licenseUrl:'https://creativecommons.org/licenses/by/4.0/', verificationStatus:'verified' },
  { id:NERVOUS_SOURCE_ID, filename:'OpenStax Anatomy and Physiology (2013), Ch. 13 nervous system', hash:'openstax-ap-2013-ch13-nervous-system', pageCount:null, title:'OpenStax 2013 · Anatomy of the Nervous System', courseLabAssociation:null, sourceType:'text', attributionLicenseStatus:'CC BY 4.0; attribution to OpenStax and contributors required', notes:'Chapter/section-level provenance for brain, spinal cord, cranial nerve, plexus, and peripheral nerve anatomy.', sourceUrl:'https://openstax.org/books/anatomy-and-physiology/pages/13-2-the-central-nervous-system', licenseUrl:'https://creativecommons.org/licenses/by/4.0/', verificationStatus:'verified' },
];
const makeStructures = (moduleId: string, rows: Array<[string, string, string, string[]]>): Structure[] => rows.map(([id, canonicalName, category, acceptedAliases]) => ({
  id, canonicalName, category, acceptedAliases, moduleId, sourceId: sourceForStructure(moduleId, category), sourcePage: null, examPriority: false, verificationStatus: 'verified',
}));
const sourceForLesson = (id: string): string => id.includes('joint') || id.includes('synovial') || id.includes('head-and-spine') || id.includes('upper-limb-joints') || id.includes('lower-limb-joints') ? JOINTS_SOURCE_ID : id.includes('muscle') || id.includes('axial') || id.includes('shoulder') || id.includes('arm-forearm') || id.includes('abdominal') || id.includes('hip-thigh') || id.includes('leg-and') ? MUSCULAR_SOURCE_ID : id.includes('neural-tracts') ? NERVOUS_TISSUE_SOURCE_ID : id.includes('brain') || id.includes('spinal') || id.includes('cranial-nerves') || id.includes('plexuses') || id.includes('ventricles') ? NERVOUS_SOURCE_ID : id.includes('cranial-fossae') || id.includes('regional-vertebrae') ? SKELETAL_AXIAL_SOURCE_ID : SKELETAL_APPENDICULAR_SOURCE_ID;
const makeLesson = (id: string, title: string, summary: string, structureIds: string[], recognitionCues: string[], landmarks: string[], relationships: string[], commonConfusions: string[], sourceId = sourceForLesson(id)): Lesson => ({
  id, title, summary, structureIds, recognitionCues, landmarks, relationships, commonConfusions, sourceIds: [sourceId],
});
const mc = (id: string, moduleId: string, structureId: string, prompt: string, answer: string | string[], options: string[], explanation: string, taskType: Question['taskType'] = 'multiple-choice'): Question => ({
  id, moduleId, structureIds: [structureId], taskType, prompt, answer, acceptedAliases: [], options, explanation, sourceId: sourceForQuestion(moduleId, structureId), sourcePage: null, examPriority: false, verificationStatus: 'verified',
});

const skeletalRows: Array<[string,string,string,string[]]> = [
  ['anterior-cranial-fossa','Anterior cranial fossa','skull fossae',[]],['middle-cranial-fossa','Middle cranial fossa','skull fossae',[]],['posterior-cranial-fossa','Posterior cranial fossa','skull fossae',[]],
  ['cribriform-plate','Cribriform plate','ethmoid landmarks',[]],['crista-galli','Crista galli','ethmoid landmarks',[]],['superior-orbital-fissure','Superior orbital fissure','skull foramina',[]],['inferior-orbital-fissure','Inferior orbital fissure','skull foramina',[]],
  ['foramen-ovale','Foramen ovale','skull foramina',[]],['foramen-rotundum','Foramen rotundum','skull foramina',[]],['foramen-spinosum','Foramen spinosum','skull foramina',[]],['carotid-canal','Carotid canal','skull foramina',[]],['hypoglossal-canal','Hypoglossal canal','skull foramina',[]],['stylomastoid-foramen','Stylomastoid foramen','skull foramina',[]],['incisive-foramen','Incisive foramen','skull foramina',[]],['greater-palatin-foramen','Greater palatine foramen','skull foramina',[]],
  ['uncinate-process','Uncinate process of ethmoid','ethmoid landmarks',[]],['pterygoid-process','Pterygoid process','sphenoid landmarks',[]],['clivus','Clivus','skull base',[]],['internal-occipital-crest','Internal occipital crest','occipital landmarks',[]],
  ['cervical-lordosis','Cervical lordosis','vertebral regions',[]],['thoracic-kyphosis','Thoracic kyphosis','vertebral regions',[]],['lumbar-lordosis','Lumbar lordosis','vertebral regions',[]],['uncinate-process-vertebra','Uncinate process of cervical vertebra','cervical landmarks',[]],['superior-costal-facet','Superior costal facet','thoracic landmarks',[]],['inferior-costal-facet','Inferior costal facet','thoracic landmarks',[]],['mammillary-process','Mammillary process','lumbar landmarks',[]],['accessory-process','Accessory process','lumbar landmarks',[]],
  ['scaphoid','Scaphoid','carpal bones',[]],['lunate','Lunate','carpal bones',[]],['triquetrum','Triquetrum','carpal bones',[]],['pisiform','Pisiform','carpal bones',[]],['trapezium','Trapezium','carpal bones',[]],['trapezoid','Trapezoid','carpal bones',[]],['capitate','Capitate','carpal bones',[]],['hamate','Hamate','carpal bones',['unciform']],['hook-of-hamate','Hook of hamate','carpal landmarks',[]],
  ['navicular','Navicular','tarsal bones',[]],['medial-cuneiform','Medial cuneiform','tarsal bones',[]],['intermediate-cuneiform','Intermediate cuneiform','tarsal bones',[]],['lateral-cuneiform','Lateral cuneiform','tarsal bones',[]],['cuboid','Cuboid','tarsal bones',[]],['ankle-mortise','Ankle mortise','articular landmarks',[]],['tibial-plateau','Tibial plateau','articular landmarks',[]],['intercondylar-eminence','Intercondylar eminence','articular landmarks',[]],['radial-tuberosity','Radial tuberosity','radius landmarks',[]],['ulnar-styloid','Ulnar styloid process','ulna landmarks',[]],['femoral-linea-aspera','Linea aspera','femur landmarks',[]],
];
export const skeletalExpansionStructures = makeStructures('skeletal-system', skeletalRows);
export const skeletalExpansionLessons: Lesson[] = [
  makeLesson('cranial-fossae-foramina','Cranial fossae and foramina','Cranial base depressions and openings organize passageways for vessels and nerves.', skeletalRows.slice(0,19).map((row) => row[0]), ['Fossae are named anterior, middle, and posterior from front to back.', 'The orbital fissures are openings at the orbit-cranial base transition.'], ['Cribriform plate forms the roof of the nasal cavity; the clivus slopes toward the foramen magnum.'], ['Foramina transmit structures; fossae are depressions that support or house neighboring anatomy.'], ['Do not treat every cranial opening as a suture or a sinus.']),
  makeLesson('regional-vertebrae','Regional vertebral features','Regional landmarks distinguish cervical, thoracic, and lumbar vertebrae beyond the basic body and processes.', skeletalRows.slice(19,27).map((row) => row[0]), ['Cervical, thoracic, and lumbar curves alternate lordosis and kyphosis.', 'Thoracic costal facets reflect rib articulation.'], ['Lumbar mammillary and accessory processes are posterior landmarks; cervical vertebrae have distinctive processes.'], ['Curves distribute load while vertebral facets guide regional motion.'], ['A vertebral curve is not a single bone; a costal facet is not the same as a transverse foramen.']),
  makeLesson('hand-wrist-bones','Hand and wrist bones','The eight carpals form two rows between radius/ulna and metacarpals.', [...skeletalRows.slice(27,36).map((row) => row[0]), 'radial-tuberosity','ulnar-styloid'], ['The scaphoid and lunate are proximal-row landmarks; capitate is the large central distal-row carpal.', 'The hamate has a palpable hook.'], ['Carpals articulate with metacarpals distally; the radius contributes to the wrist joint.'], ['Carpal arrangement supports mobility while distributing hand loads.'], ['Do not substitute carpal names for metacarpals or phalanges.']),
  makeLesson('foot-ankle-bones','Foot and ankle bones','Tarsals create a stable yet adaptable platform from leg to toes.', ['navicular','medial-cuneiform','intermediate-cuneiform','lateral-cuneiform','cuboid','ankle-mortise'], ['Navicular and three cuneiforms lie anterior to the talus; cuboid is lateral.', 'The ankle mortise receives the talus.'], ['The ankle mortise is formed by tibia and fibula around the talus.'], ['Tarsal geometry supports arches and transfers body weight.'], ['The ankle mortise is an articulation arrangement, not a separate bone.']),
  makeLesson('knee-articular-landmarks','Knee and articular landmarks','Articular surfaces and ridges help orient the knee and long bones.', ['tibial-plateau','intercondylar-eminence','femoral-linea-aspera'], ['The tibial plateau receives the femoral condyles; the intercondylar eminence lies between its surfaces.', 'The linea aspera is posterior on the femur.'], ['The knee surfaces transfer load and the linea aspera provides a posterior femoral orientation landmark.'], ['Articular landmarks identify a bone by its neighbor and position.'], ['The tibial plateau is not the femoral condyle.']),
];
export const skeletalExpansionQuestions: Question[] = [
  mc('q-skull-foramen-ovale','skeletal-system','foramen-ovale','Which opening is in the sphenoid and named for its oval shape?','Foramen ovale',['Foramen ovale','Foramen magnum','Carotid canal','Cribriform plate'],'Foramen ovale is an oval opening of the sphenoid.'),
  mc('q-skull-fossa-posterior','skeletal-system','posterior-cranial-fossa','Which cranial fossa supports the cerebellum?','Posterior cranial fossa',['Anterior cranial fossa','Middle cranial fossa','Posterior cranial fossa','Mandibular fossa'],'The posterior cranial fossa houses the cerebellum and brainstem.'),
  mc('q-vertebra-costal','skeletal-system','superior-costal-facet','Which regional vertebra landmark reflects rib articulation?','Superior costal facet',['Superior costal facet','Transverse foramen','Mammillary process','Uncinate process'],'Thoracic vertebrae bear costal facets for ribs.'),
  mc('q-carpal-central','skeletal-system','capitate','Which carpal is the large central bone of the distal row?','Capitate',['Scaphoid','Lunate','Capitate','Pisiform'],'The capitate occupies a central position in the distal carpal row.'),
  mc('q-carpal-hook','skeletal-system','hook-of-hamate','Which carpal landmark is a palpable hook?','Hook of hamate',['Hook of hamate','Radial tuberosity','Ulnar styloid','Tibial plateau'],'The hamate has a hook projecting toward the palm.'),
  mc('q-foot-mortise','skeletal-system','ankle-mortise','What receives the talus at the ankle?','Ankle mortise',['Ankle mortise','Tibial plateau','Glenoid cavity','Acetabulum'],'The tibia and fibula form the ankle mortise around the talus.'),
  mc('q-radial-tuberosity','skeletal-system','radial-tuberosity','Which radius landmark is an attachment region near its proximal shaft?','Radial tuberosity',['Radial tuberosity','Ulnar styloid','Hook of hamate','Linea aspera'],'The radial tuberosity is a proximal radius attachment landmark.'),
  mc('q-femur-linea-aspera','skeletal-system','femoral-linea-aspera','Which landmark runs along the posterior femoral shaft?','Linea aspera',['Linea aspera','Tibial plateau','Intercondylar eminence','Greater tubercle'],'The linea aspera is a posterior femoral shaft ridge.'),
];

const jointRows: Array<[string,string,string,string[]]> = [
  ['fibrous-joint','Fibrous joint','joint classification',[]],['suture-joint','Suture','fibrous joints',[]],['gomphosis','Gomphosis','fibrous joints',[]],['syndesmosis','Syndesmosis','fibrous joints',[]],
  ['cartilaginous-joint','Cartilaginous joint','joint classification',[]],['synchondrosis','Synchondrosis','cartilaginous joints',[]],['symphysis','Symphysis','cartilaginous joints',[]],
  ['synovial-joint','Synovial joint','joint classification',[]],['articular-cartilage','Articular cartilage','synovial features',[]],['joint-cavity','Joint cavity','synovial features',[]],['fibrous-capsule','Fibrous capsule','synovial features',[]],['synovial-membrane','Synovial membrane','synovial features',[]],['synovial-fluid','Synovial fluid','synovial features',[]],['ligament','Ligament','synovial features',[]],
  ['tmj','Temporomandibular joint','head and neck joints',['TMJ']],['shoulder-joint','Shoulder joint','upper limb joints',[]],['elbow-joint','Elbow joint','upper limb joints',[]],['proximal-radioulnar-joint','Proximal radioulnar joint','upper limb joints',[]],['distal-radioulnar-joint','Distal radioulnar joint','upper limb joints',[]],['wrist-joint','Wrist joint','upper limb joints',[]],
  ['hip-joint','Hip joint','lower limb joints',[]],['knee-joint','Knee joint','lower limb joints',[]],['ankle-joint','Ankle joint','lower limb joints',[]],['atlantoaxial-joint','Atlantoaxial joint','axial joints',[]],['intervertebral-joints','Intervertebral joints','axial joints',[]],
  ['acl','Anterior cruciate ligament','knee ligaments',['ACL']],['pcl','Posterior cruciate ligament','knee ligaments',['PCL']],['mcl','Medial collateral ligament','knee ligaments',['MCL']],['lcl','Lateral collateral ligament','knee ligaments',['LCL']],['deltoid-ligament','Deltoid ligament','ankle ligaments',[]],['acromioclavicular-ligament','Acromioclavicular ligament','shoulder ligaments',[]],['glenohumeral-ligaments','Glenohumeral ligaments','shoulder ligaments',[]],['annular-ligament','Annular ligament of radius','elbow ligaments',[]],['interosseous-membrane','Interosseous membrane','forearm relationships',[]],['patellar-ligament','Patellar ligament','knee ligaments',[]],['iliofemoral-ligament','Iliofemoral ligament','hip ligaments',[]],
];
export const jointsStructures = makeStructures('joints-ligaments', jointRows);
export const jointsLessons: Lesson[] = [
  makeLesson('joint-classification','Structural and functional classification','Joint classifications begin with connective tissue and continue with permitted movement.', jointRows.slice(0,8).map((row) => row[0]), ['Fibrous joints use dense connective tissue; cartilaginous joints use cartilage; synovial joints have a cavity.', 'Functional labels describe immovable, slightly movable, or freely movable behavior.'], ['Sutures, gomphoses, and syndesmoses are fibrous patterns; symphyses are cartilaginous.'], ['Structure predicts movement range and stability.'], ['Do not use “synovial” as a movement category alone.']),
  makeLesson('synovial-features','Synovial joint features','A capsule, cavity, fluid, cartilage, and supporting ligaments cooperate at synovial joints.', jointRows.slice(8,14).map((row) => row[0]), ['Articular cartilage covers bone ends; synovial membrane lines the inner capsule.', 'Synovial fluid reduces friction and helps nourish cartilage.'], ['The fibrous capsule reinforces the cavity; ligaments limit excessive translation.'], ['Accessory structures can improve congruence or distribute load.'], ['The synovial membrane is not the same as articular cartilage.']),
  makeLesson('head-and-spine-joints','Head and spine joints','The TMJ and upper cervical joints balance motion with protection.', ['tmj','atlantoaxial-joint','intervertebral-joints','fibrous-joint','suture-joint'], ['The TMJ combines hinge and gliding behavior; atlantoaxial rotation allows the head to turn.', 'Intervertebral joints combine discs and facet joints.'], ['The TMJ involves the mandible and temporal bone; atlas rotates around the dens of axis.'], ['Spinal joints distribute load while protecting the cord.'], ['The TMJ disc is not the mandible; atlantoaxial rotation is not atlanto-occipital nodding.']),
  makeLesson('upper-limb-joints','Upper-limb joints','Shoulder mobility and elbow/forearm orientation depend on distinct articulations.', ['shoulder-joint','elbow-joint','proximal-radioulnar-joint','distal-radioulnar-joint','wrist-joint','annular-ligament','interosseous-membrane','acromioclavicular-ligament'], ['The shoulder is shallow and mobile; the elbow is more constrained.', 'Radioulnar joints permit pronation and supination.'], ['The annular ligament holds the radial head against the ulna.'], ['Shoulder stability depends on capsule, labrum, and muscles; the interosseous membrane links radius and ulna.'], ['Radioulnar rotation is not the same as elbow flexion.']),
  makeLesson('lower-limb-joints','Lower-limb joints','Hip, knee, and ankle transmit body weight while preserving useful range of motion.', ['hip-joint','knee-joint','ankle-joint','acl','pcl','mcl','lcl','deltoid-ligament','patellar-ligament','iliofemoral-ligament'], ['The hip is deep and stable; the knee uses cruciate and collateral ligaments; the ankle mortise guides dorsiflexion and plantarflexion.'], ['ACL and PCL cross inside the knee; the deltoid ligament reinforces the medial ankle.'], ['Hip and knee align the lower limb for weight transfer.'], ['Collateral ligaments are not cruciate ligaments; the patellar ligament continues from quadriceps tendon.']),
  makeLesson('joint-injury-cues','Movement and injury cues','Relating a movement to the structure that restrains it makes joint study more useful.', ['acl','pcl','mcl','lcl','deltoid-ligament','glenohumeral-ligaments'], ['Ligaments resist excessive translation or rotation; dislocation risk rises with shallow articular geometry.', 'A joint description should name both motion and stabilizer.'], ['The shoulder trades stability for mobility; the knee relies heavily on ligamentous support.'], ['Joint surfaces, capsule, ligaments, and muscles work together.'], ['A ligament connects bone to bone; a tendon connects muscle to bone.']),
];
export const jointsModule: Module = { id:'joints-ligaments', title:'Joints & Ligaments', ordering:4, sourceIds:[OPENSTAX_SOURCE_ID], visible:true, published:true, contentStatus:'available', system:'joints', category:'Joint classification and movement', summary:'Classify joints and connect their structures to movement, stability, and injury cues.', coursePriority:false, lessons:jointsLessons };
export const jointsQuestions: Question[] = [
  mc('q-joint-fibrous','joints-ligaments','fibrous-joint','Which joint class is united by dense connective tissue?','Fibrous joint',['Fibrous joint','Cartilaginous joint','Synovial joint','Muscular junction'],'Fibrous joints are united by dense connective tissue.'),
  mc('q-joint-symphysis','joints-ligaments','symphysis','Which joint type uses fibrocartilage?','Symphysis',['Suture','Gomphosis','Symphysis','Synchondrosis'],'A symphysis contains a fibrocartilage pad or plate.'),
  mc('q-joint-fluid','joints-ligaments','synovial-fluid','What reduces friction inside a synovial joint?','Synovial fluid',['Synovial fluid','Bone marrow','Dense tendon','Periosteum'],'Synovial fluid lubricates the joint cavity.'),
  mc('q-joint-tmj','joints-ligaments','tmj','Which joint combines hinge and gliding movements?','Temporomandibular joint',['Temporomandibular joint','Wrist joint','Hip joint','Suture'],'The TMJ permits elevation/depression plus translation.'),
  mc('q-joint-shoulder','joints-ligaments','shoulder-joint','Which joint prioritizes mobility with a relatively shallow socket?','Shoulder joint',['Shoulder joint','Hip joint','Knee joint','Ankle joint'],'The glenohumeral joint is mobile but less inherently stable than the hip.'),
  mc('q-joint-pronation','joints-ligaments','proximal-radioulnar-joint','Which joint permits radius rotation during pronation and supination?','Proximal radioulnar joint',['Elbow joint','Proximal radioulnar joint','Wrist joint','Shoulder joint'],'The radioulnar joints permit forearm rotation.'),
  mc('q-joint-hip','joints-ligaments','hip-joint','Which joint receives the femoral head?','Hip joint',['Hip joint','Knee joint','Ankle joint','TMJ'],'The acetabulum receives the femoral head.'),
  { ...mc('q-joint-acl','joints-ligaments','acl','Which ligament limits anterior translation of the tibia?','Anterior cruciate ligament',['Anterior cruciate ligament','Posterior cruciate ligament','Medial collateral ligament','Lateral collateral ligament'],'The ACL resists anterior tibial translation.'), acceptedAliases:['ACL'] },
  { ...mc('q-joint-pcl','joints-ligaments','pcl','Which ligament limits posterior translation of the tibia?','Posterior cruciate ligament',['Posterior cruciate ligament','Anterior cruciate ligament','Medial collateral ligament','Lateral collateral ligament'],'The PCL resists posterior tibial translation.'), acceptedAliases:['PCL'] },
  { ...mc('q-joint-mcl','joints-ligaments','mcl','Which knee ligament is medial?','Medial collateral ligament',['Medial collateral ligament','Lateral collateral ligament','Anterior cruciate ligament','Posterior cruciate ligament'],'The MCL reinforces the medial knee.'), acceptedAliases:['MCL'] },
  mc('q-joint-ankle','joints-ligaments','ankle-joint','What bony arrangement receives the talus?','Ankle mortise',['Ankle mortise','Acetabulum','Glenoid cavity','TMJ'],'The tibia and fibula form the ankle mortise.'),
  mc('q-joint-ligament','joints-ligaments','ligament','What does a ligament connect?','Bone to bone',['Bone to bone','Muscle to bone','Nerve to muscle','Cartilage to skin'],'Ligaments connect bones and stabilize joints.'),
  mc('q-joint-capsule','joints-ligaments','fibrous-capsule','Which structure forms the outer layer of a synovial joint capsule?','Fibrous capsule',['Fibrous capsule','Synovial membrane','Articular cartilage','Synovial fluid'],'The fibrous capsule is the external capsule layer.'),
  mc('q-joint-deltoid','joints-ligaments','deltoid-ligament','Which ligament reinforces the medial ankle?','Deltoid ligament',['Deltoid ligament','LCL','ACL','Annular ligament'],'The deltoid ligament supports the medial ankle.'),
];

const muscleRows: Array<[string,string,string,string[]]> = [
  ['frontalis','Frontalis','facial expression',[]],['orbicularis-oculi','Orbicularis oculi','facial expression',[]],['orbicularis-oris','Orbicularis oris','facial expression',[]],['buccinator','Buccinator','facial expression',[]],['platysma','Platysma','neck muscles',[]],['sternocleidomastoid','Sternocleidomastoid','neck muscles',['SCM']],['scalenes','Scalene muscles','neck muscles',[]],
  ['trapezius','Trapezius','back muscles',[]],['latissimus-dorsi','Latissimus dorsi','back muscles',[]],['rhomboid-major','Rhomboid major','back muscles',[]],['rhomboid-minor','Rhomboid minor','back muscles',[]],['levator-scapulae','Levator scapulae','back muscles',[]],['erector-spinae','Erector spinae','back muscles',[]],['multifidus','Multifidus','back muscles',[]],
  ['pectoralis-major','Pectoralis major','thoracic muscles',[]],['pectoralis-minor','Pectoralis minor','thoracic muscles',[]],['serratus-anterior','Serratus anterior','thoracic muscles',[]],['intercostals','Intercostal muscles','thoracic muscles',[]],['diaphragm','Diaphragm','respiratory muscles',[]],
  ['deltoid','Deltoid','shoulder muscles',[]],['supraspinatus','Supraspinatus','rotator cuff',[]],['infraspinatus','Infraspinatus','rotator cuff',[]],['teres-minor','Teres minor','rotator cuff',[]],['subscapularis','Subscapularis','rotator cuff',[]],['teres-major','Teres major','shoulder muscles',[]],
  ['biceps-brachii','Biceps brachii','arm muscles',[]],['brachialis','Brachialis','arm muscles',[]],['coracobrachialis','Coracobrachialis','arm muscles',[]],['triceps-brachii','Triceps brachii','arm muscles',[]],['anconeus','Anconeus','arm muscles',[]],
  ['pronator-teres','Pronator teres','forearm muscles',[]],['supinator','Supinator','forearm muscles',[]],['flexor-carpi-radialis','Flexor carpi radialis','forearm muscles',[]],['extensor-carpi-radialis','Extensor carpi radialis','forearm muscles',[]],
  ['rectus-abdominis','Rectus abdominis','abdominal muscles',[]],['external-oblique','External oblique','abdominal muscles',[]],['internal-oblique','Internal oblique','abdominal muscles',[]],['transversus-abdominis','Transversus abdominis','abdominal muscles',[]],['quadratus-lumborum','Quadratus lumborum','abdominal muscles',[]],
  ['gluteus-maximus','Gluteus maximus','gluteal muscles',[]],['gluteus-medius','Gluteus medius','gluteal muscles',[]],['tensor-fasciae-latae','Tensor fasciae latae','gluteal muscles',[]],['iliopsoas','Iliopsoas','hip muscles',[]],['adductor-longus','Adductor longus','medial thigh',[]],['gracilis','Gracilis','medial thigh',[]],
  ['sartorius','Sartorius','anterior thigh',[]],['rectus-femoris','Rectus femoris','quadriceps',[]],['vastus-lateralis','Vastus lateralis','quadriceps',[]],['vastus-medialis','Vastus medialis','quadriceps',[]],['vastus-intermedius','Vastus intermedius','quadriceps',[]],['articularis-genus','Articularis genus','knee muscles',[]],
  ['biceps-femoris','Biceps femoris','hamstrings',[]],['semitendinosus','Semitendinosus','hamstrings',[]],['semimembranosus','Semimembranosus','hamstrings',[]],['tibialis-anterior','Tibialis anterior','leg muscles',[]],['fibularis-longus','Fibularis longus','leg muscles',[]],['gastrocnemius','Gastrocnemius','calf muscles',[]],['soleus','Soleus','calf muscles',[]],['popliteus','Popliteus','leg muscles',[]],
];
export const muscularStructures = makeStructures('muscular-system', muscleRows);
export const muscularLessons: Lesson[] = [
  makeLesson('muscle-orientation','Muscle orientation and naming','Position, fiber direction, and attachment terms make muscle names actionable.', muscleRows.slice(0,7).map((row) => row[0]), ['Names may describe location, shape, direction, or action.', 'Origin and insertion are positional teaching conventions, not a muscle’s only relationship.'], ['The sternocleidomastoid spans sternum/clavicle to mastoid region.'], ['Muscles create movement by pulling across joints.'], ['Do not treat a muscle name as its action without considering joint position.']),
  makeLesson('axial-muscles','Axial and respiratory muscles','Trunk and neck muscles support posture, breathing, and head movement.', muscleRows.slice(7,19).map((row) => row[0]), ['Trapezius and erector spinae support posture; diaphragm changes thoracic volume.', 'Intercostals lie between ribs.'], ['Serratus anterior acts on the scapula; pectorals connect upper limb to trunk.'], ['Axial muscles stabilize the trunk while appendicular muscles move limbs.'], ['The diaphragm is skeletal muscle with a primary respiratory role.']),
  makeLesson('shoulder-rotator-cuff','Shoulder and rotator cuff','The rotator cuff centers the humeral head while larger muscles move the arm.', muscleRows.slice(19,26).map((row) => row[0]), ['SITS identifies supraspinatus, infraspinatus, teres minor, and subscapularis.', 'Deltoid is a major arm abductor after initiation.'], ['Rotator cuff tendons blend with the shoulder capsule.'], ['Scapular position changes the leverage of shoulder muscles.'], ['Teres major is not part of the rotator cuff.']),
  makeLesson('arm-forearm','Arm and forearm actions','Elbow flexors, extensors, and forearm rotators act across distinct joints.', muscleRows.slice(26,34).map((row) => row[0]), ['Biceps assists elbow flexion and supination; triceps extends the elbow.', 'Pronator teres and supinator rotate the forearm.'], ['Brachialis crosses the elbow; wrist muscles cross the forearm into the hand.'], ['Action depends on the joint crossed and line of pull.'], ['Biceps is not the only elbow flexor; pronation is not wrist rotation.']),
  makeLesson('abdominal-wall','Abdominal wall','Layered abdominal muscles flex, rotate, compress, and stabilize the trunk.', muscleRows.slice(34,39).map((row) => row[0]), ['Rectus abdominis flexes the trunk; obliques rotate and laterally flex.', 'Transversus abdominis compresses the abdominal contents.'], ['Quadratus lumborum connects trunk and pelvis and contributes to lateral flexion.'], ['Abdominal pressure supports posture and forced expiration.'], ['Internal and external oblique fibers run in different directions.']),
  makeLesson('hip-thigh','Hip and thigh','Gluteal, adductor, quadriceps, and hamstring groups coordinate hip and knee motion.', muscleRows.slice(39,53).map((row) => row[0]), ['Gluteus maximus extends the hip; gluteus medius abducts and stabilizes the pelvis.', 'Quadriceps extend the knee; hamstrings flex the knee and extend the hip.'], ['Sartorius crosses hip and knee; iliopsoas is a powerful hip flexor.'], ['Balanced hip muscles stabilize the femoral head and pelvis.'], ['Rectus femoris crosses both hip and knee; vasti cross only the knee.']),
  makeLesson('leg-and-ankle','Leg and ankle','The leg compartments position the foot and control gait.', ['tibialis-anterior','fibularis-longus','gastrocnemius','soleus','popliteus'], ['Tibialis anterior dorsiflexes; gastrocnemius and soleus plantarflex.', 'Fibularis longus everts the foot.'], ['Gastrocnemius crosses knee and ankle; soleus crosses only the ankle.'], ['Calf muscles transfer force through the calcaneal tendon.'], ['Dorsiflexion and plantarflexion are ankle movements, not knee movements.']),
  makeLesson('muscle-actions','Action, attachment, and movement','A compact action map links muscle groups to the movements they produce.', muscleRows.map((row) => row[0]), ['Identify the joint, then ask whether the muscle shortens across it.', 'Opposing groups can be agonist and antagonist depending on the task.'], ['Attachments and lever arms influence force and range.'], ['Muscles act in coordinated groups rather than isolation.'], ['Origin/insertion terminology does not replace action analysis.']),
];
export const muscularModule: Module = { id:'muscular-system', title:'Muscular System', ordering:5, sourceIds:[OPENSTAX_SOURCE_ID], visible:true, published:true, contentStatus:'available', system:'muscular', category:'Regional muscles and actions', summary:'Learn major regional muscles through recognition cues, actions, and attachment relationships.', coursePriority:false, lessons:muscularLessons };
export const muscularQuestions: Question[] = [
  mc('q-muscle-diaphragm','muscular-system','diaphragm','Which muscle is the primary driver of quiet inspiration?','Diaphragm',['Diaphragm','Rectus abdominis','Trapezius','Soleus'],'Diaphragm contraction increases thoracic volume.'),
  mc('q-muscle-scm','muscular-system','sternocleidomastoid','Which muscle is named for sternum, clavicle, and mastoid attachments?','Sternocleidomastoid',['Sternocleidomastoid','Trapezius','Scalenes','Platysma'],'The name describes its major attachment regions.','typed-recall'),
  mc('q-muscle-cuff','muscular-system','supraspinatus','Which group is summarized by SITS?','Rotator cuff',['Rotator cuff','Quadriceps','Hamstrings','Abdominal wall'],'SITS refers to the four rotator cuff muscles.'),
  mc('q-muscle-deltoid','muscular-system','deltoid','Which muscle is a major arm abductor?','Deltoid',['Deltoid','Triceps brachii','Latissimus dorsi','Biceps brachii'],'The deltoid abducts the arm after initiation.'),
  mc('q-muscle-biceps','muscular-system','biceps-brachii','Which muscle assists forearm supination?','Biceps brachii',['Biceps brachii','Triceps brachii','Pronator teres','Soleus'],'Biceps brachii flexes the elbow and assists supination.'),
  mc('q-muscle-triceps','muscular-system','triceps-brachii','Which muscle extends the elbow?','Triceps brachii',['Triceps brachii','Biceps brachii','Brachialis','Supinator'],'Triceps brachii is the principal elbow extensor.'),
  mc('q-muscle-pronator','muscular-system','pronator-teres','Which muscle contributes to forearm pronation?','Pronator teres',['Pronator teres','Supinator','Biceps brachii','Deltoid'],'Pronator teres rotates the radius over the ulna.'),
  mc('q-muscle-rectus','muscular-system','rectus-abdominis','Which muscle flexes the trunk?','Rectus abdominis',['Rectus abdominis','Transversus abdominis','Gluteus medius','Erector spinae'],'Rectus abdominis is a trunk flexor.'),
  mc('q-muscle-gluteus','muscular-system','gluteus-maximus','Which muscle is a powerful hip extensor?','Gluteus maximus',['Gluteus maximus','Iliopsoas','Sartorius','Tibialis anterior'],'Gluteus maximus extends the hip.'),
  mc('q-muscle-medius','muscular-system','gluteus-medius','Which muscle abducts the hip and helps stabilize the pelvis?','Gluteus medius',['Gluteus medius','Adductor longus','Biceps femoris','Soleus'],'Gluteus medius abducts and stabilizes the pelvis.'),
  mc('q-muscle-quadriceps','muscular-system','rectus-femoris','Which group extends the knee?','Quadriceps',['Quadriceps','Hamstrings','Adductors','Rotator cuff'],'The quadriceps extend the knee.'),
  mc('q-muscle-hamstrings','muscular-system','biceps-femoris','Which group generally flexes the knee?','Hamstrings',['Hamstrings','Quadriceps','Gluteals','Calf muscles'],'Hamstrings flex the knee and extend the hip.'),
  mc('q-muscle-tibialis','muscular-system','tibialis-anterior','Which muscle dorsiflexes the ankle?','Tibialis anterior',['Tibialis anterior','Gastrocnemius','Soleus','Fibularis longus'],'Tibialis anterior dorsiflexes the ankle.'),
  mc('q-muscle-calf','muscular-system','gastrocnemius','Which muscle crosses both knee and ankle?','Gastrocnemius',['Gastrocnemius','Soleus','Tibialis anterior','Popliteus'],'Gastrocnemius crosses the knee and ankle.'),
  mc('q-muscle-soleus','muscular-system','soleus','Which calf muscle does not cross the knee?','Soleus',['Soleus','Gastrocnemius','Sartorius','Rectus femoris'],'Soleus acts across the ankle only.'),
  mc('q-muscle-origin','muscular-system','rectus-femoris','Which muscle crosses both hip and knee?','Rectus femoris',['Rectus femoris','Vastus medialis','Soleus','Brachialis'],'Rectus femoris is the biarticular quadriceps muscle.','muscle-origin-insertion'),
  mc('q-muscle-select','muscular-system','supraspinatus','Select the rotator cuff members.',['Supraspinatus','Infraspinatus','Teres minor','Subscapularis'],['Supraspinatus','Infraspinatus','Teres minor','Subscapularis'],'These four muscles form the rotator cuff.','select-all'),
  mc('q-muscle-order','muscular-system','transversus-abdominis','Order these abdominal wall layers from superficial to deep.',['External oblique','Internal oblique','Transversus abdominis'],['Transversus abdominis','External oblique','Internal oblique'],'The broad lateral abdominal layers proceed from external oblique to internal oblique to transversus abdominis.', 'ordered-sequence'),
  mc('q-muscle-action','muscular-system','fibularis-longus','Which action is associated with fibularis longus?','Eversion',['Eversion','Inversion','Elbow extension','Trunk flexion'],'Fibularis longus everts the foot.','muscle-action'),
  mc('q-muscle-function','muscular-system','serratus-anterior','Which muscle helps protract and upwardly rotate the scapula?','Serratus anterior',['Serratus anterior','Rhomboid major','Levator scapulae','Pectoralis minor'],'Serratus anterior moves the scapula along the thoracic wall.','function-relationship'),
];

const nervousRows: Array<[string,string,string,string[]]> = [
  ['cerebrum','Cerebrum','brain regions',[]],['frontal-lobe','Frontal lobe','cerebral lobes',[]],['parietal-lobe','Parietal lobe','cerebral lobes',[]],['temporal-lobe','Temporal lobe','cerebral lobes',[]],['occipital-lobe','Occipital lobe','cerebral lobes',[]],['insula','Insula','cerebral lobes',[]],['corpus-callosum','Corpus callosum','brain regions',[]],['thalamus','Thalamus','diencephalon',[]],['hypothalamus','Hypothalamus','diencephalon',[]],['epithalamus','Epithalamus','diencephalon',[]],['basal-nuclei','Basal nuclei','deep brain',[]],['caudate-nucleus','Caudate nucleus','basal nuclei',[]],['putamen','Putamen','basal nuclei',[]],['globus-pallidus','Globus pallidus','basal nuclei',[]],
  ['lateral-ventricle','Lateral ventricle','ventricles',[]],['third-ventricle','Third ventricle','ventricles',[]],['cerebral-aqueduct','Cerebral aqueduct','ventricles',[]],['fourth-ventricle','Fourth ventricle','ventricles',[]],['choroid-plexus','Choroid plexus','CSF structures',[]],['meninges','Meninges','protective structures',[]],['dura-mater','Dura mater','meninges',[]],['arachnoid-mater','Arachnoid mater','meninges',[]],['pia-mater','Pia mater','meninges',[]],['cerebrospinal-fluid','Cerebrospinal fluid','CSF',[]],
  ['midbrain','Midbrain','brainstem',[]],['pons','Pons','brainstem',[]],['medulla-oblongata','Medulla oblongata','brainstem',[]],['cerebellum','Cerebellum','hindbrain',[]],['arbor-vitae','Arbor vitae','cerebellum',[]],['spinal-cord','Spinal cord','spinal cord',[]],['central-canal','Central canal','spinal cord',[]],['dorsal-horn','Dorsal horn','spinal cord gray matter',[]],['ventral-horn','Ventral horn','spinal cord gray matter',[]],['dorsal-root','Dorsal root','spinal nerves',[]],['ventral-root','Ventral root','spinal nerves',[]],['dorsal-root-ganglion','Dorsal root ganglion','spinal nerves',[]],['dorsal-ramus','Dorsal ramus','spinal nerves',[]],['ventral-ramus','Ventral ramus','spinal nerves',[]],
  ['corticospinal-tract','Corticospinal tract','neural pathways',[]],['spinothalamic-tract','Spinothalamic tract','neural pathways',[]],['dorsal-column','Dorsal column','neural pathways',[]],['cranial-nerve-i','Cranial nerve I: olfactory','cranial nerves',['olfactory nerve']],['cranial-nerve-ii','Cranial nerve II: optic','cranial nerves',['optic nerve']],['cranial-nerve-iii','Cranial nerve III: oculomotor','cranial nerves',['oculomotor nerve']],['cranial-nerve-iv','Cranial nerve IV: trochlear','cranial nerves',['trochlear nerve']],['cranial-nerve-v','Cranial nerve V: trigeminal','cranial nerves',['trigeminal nerve']],['cranial-nerve-vi','Cranial nerve VI: abducens','cranial nerves',['abducens nerve']],['cranial-nerve-vii','Cranial nerve VII: facial','cranial nerves',['facial nerve']],['cranial-nerve-viii','Cranial nerve VIII: vestibulocochlear','cranial nerves',['vestibulocochlear nerve']],['cranial-nerve-ix','Cranial nerve IX: glossopharyngeal','cranial nerves',['glossopharyngeal nerve']],['cranial-nerve-x','Cranial nerve X: vagus','cranial nerves',['vagus nerve']],['cranial-nerve-xi','Cranial nerve XI: accessory','cranial nerves',['accessory nerve']],['cranial-nerve-xii','Cranial nerve XII: hypoglossal','cranial nerves',['hypoglossal nerve']],['cervical-plexus','Cervical plexus','nerve plexuses',[]],['brachial-plexus','Brachial plexus','nerve plexuses',[]],['lumbar-plexus','Lumbar plexus','nerve plexuses',[]],['sacral-plexus','Sacral plexus','nerve plexuses',[]],['phrenic-nerve','Phrenic nerve','peripheral nerves',[]],['median-nerve','Median nerve','peripheral nerves',[]],['ulnar-nerve','Ulnar nerve','peripheral nerves',[]],['radial-nerve','Radial nerve','peripheral nerves',[]],['sciatic-nerve','Sciatic nerve','peripheral nerves',[]],['femoral-nerve','Femoral nerve','peripheral nerves',[]],
];
export const nervousStructures = makeStructures('nervous-system', nervousRows);
export const nervousLessons: Lesson[] = [
  makeLesson('brain-lobes','Brain lobes and cortex','Cortical lobes provide a first map for sensory, motor, visual, and executive functions.', nervousRows.slice(0,7).map((row) => row[0]), ['Frontal is anterior, parietal superior/posterior, temporal lateral, and occipital posterior.', 'The insula lies deep to the lateral sulcus.'], ['Corpus callosum crosses between hemispheres.'], ['Cortical functions are distributed and interconnected.'], ['Do not confuse lobe location with a single isolated function.']),
  makeLesson('deep-brain','Diencephalon and basal nuclei','Deep structures relay, regulate, and coordinate information beneath the cortex.', nervousRows.slice(7,14).map((row) => row[0]), ['Thalamus relays; hypothalamus regulates homeostasis and endocrine links.', 'Basal nuclei help select and scale movement.'], ['Caudate, putamen, and globus pallidus form major basal nuclei components.'], ['Deep nuclei work with cortical and brainstem circuits.'], ['Basal nuclei are not the same as the cerebellum.']),
  makeLesson('ventricles-csf','Ventricles, meninges, and CSF','Fluid spaces and coverings protect the brain and provide a circulation route for CSF.', nervousRows.slice(14,24).map((row) => row[0]), ['Lateral ventricles connect toward the third ventricle through interventricular foramina.', 'Dura is outermost; pia closely follows the CNS surface.'], ['Choroid plexus produces CSF; the cerebral aqueduct connects third and fourth ventricles.'], ['CSF cushions and supports the CNS.'], ['A ventricle is a space, not a solid brain region.']),
  makeLesson('brainstem-cerebellum','Brainstem and cerebellum','The brainstem links brain and spinal cord; the cerebellum coordinates movement and balance.', ['midbrain','pons','medulla-oblongata','cerebellum','arbor-vitae'], ['Midbrain, pons, and medulla run superior to inferior.', 'Cerebellum lies posterior to the brainstem.'], ['Arbor vitae is internal cerebellar white matter.'], ['Brainstem pathways carry ascending and descending information.'], ['Pons is not the entire brainstem; cerebellum is not a cerebral lobe.']),
  makeLesson('spinal-cord','Spinal cord landmarks','Roots, horns, and rami organize the connection between cord and peripheral nerves.', ['spinal-cord','central-canal','dorsal-horn','ventral-horn','dorsal-root','ventral-root','dorsal-root-ganglion','dorsal-ramus','ventral-ramus'], ['Dorsal roots carry sensory input; ventral roots carry motor output.', 'Dorsal root ganglia contain sensory neuron cell bodies.'], ['Gray horns surround the central canal; rami branch after the spinal nerve forms.'], ['Spinal nerves connect segmental cord circuits to body regions.'], ['A root is proximal to the spinal nerve; a ramus is a branch after it forms.']),
  makeLesson('neural-tracts','Introductory neural pathways','Major tracts illustrate how information travels through the spinal cord and brain.', nervousRows.slice(38,41).map((row) => row[0]), ['Corticospinal pathways carry voluntary motor commands; spinothalamic pathways carry pain and temperature.', 'Dorsal columns carry discriminative touch and proprioceptive information.'], ['Tracts cross at characteristic levels, so side and modality matter.'], ['Pathways link peripheral receptors, spinal circuits, thalamus, and cortex.'], ['A tract is CNS; a nerve is peripheral.']),
  makeLesson('cranial-nerves','Cranial nerves I–XII','The twelve cranial nerves combine sensory, motor, and parasympathetic roles.', nervousRows.slice(41,53).map((row) => row[0]), ['I olfactory and II optic are special sensory; V is trigeminal; X is vagus.', 'Cranial nerve names and numbers are complementary recall systems.'], ['Facial expression uses VII; tongue motor control uses XII; eye movements involve III, IV, and VI.'], ['Cranial nerves connect brainstem or forebrain nuclei to head and selected viscera.'], ['Do not confuse optic (II) with oculomotor (III) or vestibulocochlear (VIII).']),
  makeLesson('plexuses-peripheral','Plexuses and peripheral nerves','Spinal rami combine in plexuses that distribute named nerves to the limbs and diaphragm.', nervousRows.slice(53).map((row) => row[0]), ['Cervical, brachial, lumbar, and sacral plexuses serve distinct regions.', 'The phrenic nerve is associated with the cervical plexus; sciatic with the sacral plexus.'], ['Median, ulnar, and radial nerves serve different upper-limb territories; femoral serves anterior thigh.'], ['Plexuses redistribute fibers from multiple spinal levels.'], ['A plexus is a network; a named peripheral nerve is a resulting branch.']),
];
export const nervousModule: Module = { id:'nervous-system', title:'Nervous System & Brain', ordering:6, sourceIds:[OPENSTAX_SOURCE_ID], visible:true, published:true, contentStatus:'available', system:'nervous', category:'Brain, spinal cord, and peripheral nerves', summary:'Build an introductory map of the brain, spinal cord, cranial nerves, plexuses, and major peripheral nerves.', coursePriority:false, lessons:nervousLessons };
export const nervousQuestions: Question[] = [
  mc('q-neuro-frontal','nervous-system','frontal-lobe','Which lobe is most anterior?','Frontal lobe',['Frontal lobe','Parietal lobe','Temporal lobe','Occipital lobe'],'The frontal lobe is anterior to the other cerebral lobes.'),
  mc('q-neuro-thalamus','nervous-system','thalamus','Which structure is a major relay toward the cortex?','Thalamus',['Thalamus','Cerebellum','Pons','Dura mater'],'The thalamus relays many sensory and motor signals.'),
  mc('q-neuro-hypothalamus','nervous-system','hypothalamus','Which structure links homeostasis with endocrine regulation?','Hypothalamus',['Hypothalamus','Occipital lobe','Corpus callosum','Putamen'],'The hypothalamus coordinates homeostasis and endocrine control.'),
  mc('q-neuro-ventricle','nervous-system','cerebral-aqueduct','What connects the third and fourth ventricles?','Cerebral aqueduct',['Cerebral aqueduct','Central canal','Corpus callosum','Choroid plexus'],'The cerebral aqueduct passes through the midbrain.'),
  mc('q-neuro-meninges','nervous-system','dura-mater','Which meninx is outermost?','Dura mater',['Dura mater','Arachnoid mater','Pia mater','Choroid plexus'],'Dura mater is the tough outer meninx.'),
  mc('q-neuro-csf','nervous-system','choroid-plexus','Which structure produces much of the CSF?','Choroid plexus',['Choroid plexus','Basal nuclei','Cerebellum','Dorsal horn'],'Choroid plexus produces CSF within ventricles.'),
  mc('q-neuro-brainstem','nervous-system','medulla-oblongata','Which brainstem region is most inferior?','Medulla oblongata',['Midbrain','Pons','Medulla oblongata','Cerebellum'],'The medulla is inferior to pons and midbrain.'),
  mc('q-neuro-root','nervous-system','dorsal-root','Which root carries sensory input toward the spinal cord?','Dorsal root',['Dorsal root','Ventral root','Dorsal ramus','Ventral ramus'],'Dorsal roots carry afferent sensory fibers.'),
  mc('q-neuro-ventral','nervous-system','ventral-root','Which root carries motor output away from the spinal cord?','Ventral root',['Ventral root','Dorsal root','Dorsal horn','Dorsal root ganglion'],'Ventral roots carry efferent motor fibers.'),
  mc('q-neuro-tract','nervous-system','spinothalamic-tract','Which tract is associated with pain and temperature?','Spinothalamic tract',['Spinothalamic tract','Corticospinal tract','Dorsal column','Corpus callosum'],'Spinothalamic pathways carry pain and temperature information.'),
  mc('q-neuro-cn1','nervous-system','cranial-nerve-i','Which cranial nerve carries olfactory information?','Cranial nerve I: olfactory',['Cranial nerve I: olfactory','Cranial nerve II: optic','Cranial nerve V: trigeminal','Cranial nerve X: vagus'],'CN I is the olfactory nerve.'),
  mc('q-neuro-cn2','nervous-system','cranial-nerve-ii','Which cranial nerve carries vision?','Cranial nerve II: optic',['Cranial nerve II: optic','Cranial nerve III: oculomotor','Cranial nerve VII: facial','Cranial nerve VIII: vestibulocochlear'],'CN II is the optic nerve.'),
  mc('q-neuro-cn5','nervous-system','cranial-nerve-v','Which cranial nerve provides major facial sensation?','Cranial nerve V: trigeminal',['Cranial nerve V: trigeminal','Cranial nerve VII: facial','Cranial nerve IX: glossopharyngeal','Cranial nerve XII: hypoglossal'],'CN V is the major sensory nerve of the face.'),
  mc('q-neuro-cn7','nervous-system','cranial-nerve-vii','Which cranial nerve controls many muscles of facial expression?','Cranial nerve VII: facial',['Cranial nerve VII: facial','Cranial nerve V: trigeminal','Cranial nerve XI: accessory','Cranial nerve XII: hypoglossal'],'CN VII supplies muscles of facial expression.'),
  mc('q-neuro-cn10','nervous-system','cranial-nerve-x','Which cranial nerve extends into thorax and abdomen?','Cranial nerve X: vagus',['Cranial nerve X: vagus','Cranial nerve IX: glossopharyngeal','Cranial nerve III: oculomotor','Cranial nerve VI: abducens'],'The vagus nerve has extensive thoracoabdominal distribution.'),
  mc('q-neuro-cn12','nervous-system','cranial-nerve-xii','Which cranial nerve controls tongue movement?','Cranial nerve XII: hypoglossal',['Cranial nerve XII: hypoglossal','Cranial nerve X: vagus','Cranial nerve VII: facial','Cranial nerve V: trigeminal'],'CN XII supplies tongue motor function.'),
  mc('q-neuro-plexus','nervous-system','brachial-plexus','Which plexus supplies much of the upper limb?','Brachial plexus',['Brachial plexus','Cervical plexus','Lumbar plexus','Sacral plexus'],'The brachial plexus distributes upper-limb fibers.'),
  mc('q-neuro-phrenic','nervous-system','phrenic-nerve','Which named nerve drives the diaphragm?','Phrenic nerve',['Phrenic nerve','Median nerve','Sciatic nerve','Radial nerve'],'The phrenic nerve supplies the diaphragm.'),
  mc('q-neuro-sciatic','nervous-system','sciatic-nerve','Which is the major nerve of the posterior lower limb?','Sciatic nerve',['Sciatic nerve','Femoral nerve','Ulnar nerve','Median nerve'],'The sciatic nerve supplies the posterior lower limb through major branches.'),
  mc('q-neuro-order','nervous-system','midbrain','Order the brainstem regions superior to inferior.',['Midbrain','Pons','Medulla oblongata'],['Pons','Medulla oblongata','Midbrain'],'The brainstem runs from midbrain to pons to medulla.','ordered-sequence'),
];