export default {
  'cell-membrane': 'The plasma membrane is the phospholipid boundary that encloses the cell and separates its cytoplasm from the surrounding fluid.',
  cytoplasm: 'Cytoplasm is the cell region between the plasma membrane and nucleus, containing cytosol and the organelles suspended in it.',
  'nucleus-cell': 'The nucleus is the membrane-enclosed compartment that contains most of a cell’s DNA.',
  'nucleolus-cell': 'The nucleolus is a dense region inside the nucleus where ribosomal subunits are assembled.',
  'chromatin-cell': 'Chromatin is DNA associated with proteins within the nucleus, where it forms the material of chromosomes.',
  'nuclear-envelope': 'The nuclear envelope is the double membrane surrounding the nucleus, with pores connecting it to the cytoplasm.',
  'ribosome-cell': 'A ribosome is a small RNA–protein complex found free in the cytoplasm or attached to rough endoplasmic reticulum.',
  'rough-er-cell': 'Rough endoplasmic reticulum is a membrane network bearing ribosomes on its cytoplasmic surface, often continuous with the nuclear envelope.',
  'smooth-er-cell': 'Smooth endoplasmic reticulum is a membrane network without surface-bound ribosomes, continuous with the cell’s endomembrane system.',
  'golgi-apparatus-cell': 'The Golgi apparatus is a stack of flattened membrane sacs that receives material from the endoplasmic reticulum and sorts it into vesicles.',
  'mitochondrion-cell': 'A mitochondrion is a double-membrane organelle with folded inner-membrane cristae, dispersed through the cytoplasm.',
  'lysosome-cell': 'A lysosome is a membrane-bound vesicle containing digestive enzymes within the cytoplasm.',
  'peroxisome-cell': 'A peroxisome is a small membrane-bound cytoplasmic organelle containing enzymes that break down fatty acids and harmful peroxides.',
  'centrosome-cell': 'The centrosome is the microtubule-organizing region near the nucleus, usually containing a pair of centrioles.',
  'microvillus-cell': 'A microvillus is a small actin-supported projection of the apical plasma membrane on an absorptive or lining cell.',
  'tight-junction-cell': 'A tight junction is a seal between neighboring epithelial cells near their apical surfaces that limits passage between them.',
  'desmosome-cell': 'A desmosome is a spot-like junction that fastens the intermediate filaments of neighboring cells together.',
  'gap-junction-cell': 'A gap junction is a channel-forming junction between adjacent cells that directly connects their cytoplasm.',
  'hemidesmosome-cell': 'A hemidesmosome anchors the basal surface of an epithelial cell to the underlying basement membrane.',
  'simple-squamous-epithelium': 'Simple squamous epithelium is one thin layer of flattened cells resting on a basement membrane.',
  'simple-cuboidal-epithelium': 'Simple cuboidal epithelium is one layer of roughly cube-shaped cells resting on a basement membrane.',
  'simple-columnar-epithelium': 'Simple columnar epithelium is one layer of taller-than-wide cells whose apical surfaces face a lumen or external space.',
  'pseudostratified-epithelium': 'Pseudostratified columnar epithelium is a single epithelial layer in which cells of different heights make nuclei appear stacked at different levels.',
  'stratified-squamous-keratinized': 'Keratinized stratified squamous epithelium has many layers with flattened, keratin-filled surface cells, as in the epidermis.',
  'stratified-squamous-nonkeratinized': 'Nonkeratinized stratified squamous epithelium has multiple layers with moist, living flattened cells at its exposed surface.',
  'stratified-cuboidal-epithelium': 'Stratified cuboidal epithelium consists of two or more layers with cube-shaped cells at the free surface.',
  'stratified-columnar-epithelium': 'Stratified columnar epithelium consists of multiple layers with column-shaped cells at the free surface.',
  'transitional-epithelium': 'Transitional epithelium is a multilayered lining whose surface cells change shape as the urinary organ beneath it stretches.',
  'basement-membrane-tissue': 'The basement membrane is a thin extracellular layer beneath an epithelium that separates it from underlying connective tissue.',
  'goblet-cell-tissue': 'A goblet cell is a mucus-secreting epithelial cell scattered among the lining cells of a mucous membrane.',
  'exocrine-gland-tissue': 'An exocrine gland is a secretory epithelial structure whose product reaches an epithelial surface through a duct.',
  'endocrine-gland-tissue': 'An endocrine gland is a ductless secretory structure whose cells lie near capillaries and release products into surrounding fluid.',
  'duct-gland-tissue': 'A glandular duct is the epithelial-lined passage that carries a product from an exocrine secretory unit to a surface.',
  'areolar-connective-tissue': 'Areolar connective tissue is a loose mesh of collagen and elastic fibers in abundant ground substance, often around vessels and organs.',
  'adipose-connective-tissue': 'Adipose tissue is connective tissue composed mainly of lipid-storing adipocytes grouped in lobules.',
  'reticular-connective-tissue': 'Reticular connective tissue is a fine branching fiber network that supports cells in structures such as lymph nodes and bone marrow.',
  'dense-regular-connective-tissue': 'Dense regular connective tissue contains parallel collagen bundles, as in tendons and many ligaments.',
  'dense-irregular-connective-tissue': 'Dense irregular connective tissue contains interwoven collagen bundles, as in the deeper dermis.',
  'elastic-connective-tissue': 'Elastic connective tissue contains abundant branching elastic fibers within an extracellular matrix, including in the walls of large arteries.',
  'hyaline-cartilage-tissue': 'Hyaline cartilage is a smooth-looking connective tissue in which chondrocytes sit in lacunae within a firm matrix.',
  'elastic-cartilage-tissue': 'Elastic cartilage contains chondrocytes in lacunae among dense elastic fibers, as in the external ear.',
  'fibrocartilage-tissue': 'Fibrocartilage contains chondrocytes in lacunae between thick collagen bundles, as in intervertebral discs.',
  'osteocyte-tissue': 'An osteocyte is a mature bone cell housed in a lacuna within the mineralized bone matrix.',
  'erythrocyte-tissue': 'An erythrocyte, or red blood cell, is a biconcave formed element suspended in the plasma of blood.',
  'leukocyte-tissue': 'A leukocyte, or white blood cell, is a nucleated blood cell that moves between blood and body tissues.',
  'platelet-tissue': 'A platelet is a small cell fragment circulating in blood, derived from a megakaryocyte in bone marrow.',
  'bone-tissue': 'Bone tissue is mineralized connective tissue with osteocytes in lacunae and a collagen-containing extracellular matrix.',
  'blood-tissue': 'Blood is a fluid connective tissue in which red cells, white cells, and platelets are suspended in plasma.',
  'skeletal-muscle-tissue': 'Skeletal muscle tissue is made of long, striated, multinucleate fibers arranged in bundles attached to the skeleton.',
  'cardiac-muscle-tissue': 'Cardiac muscle tissue is branching, striated muscle whose cells join at intercalated discs in the heart wall.',
  'smooth-muscle-tissue': 'Smooth muscle tissue consists of nonstriated spindle-shaped cells, commonly arranged in the walls of hollow organs and vessels.',
  'neuron-tissue': 'A neuron is a nervous-tissue cell with a cell body and processes, including an axon and usually dendrites.',
  'neuroglia-tissue': 'Neuroglia are the smaller supporting cells found among neurons in nervous tissue.',
  'collagen-fiber-tissue': 'A collagen fiber is a strong, rope-like extracellular fiber bundled in connective-tissue matrix.',
  'elastic-fiber-tissue': 'An elastic fiber is a branching extracellular fiber in connective tissue that can stretch and recoil.',
  'intercalated-disc-tissue': 'An intercalated disc is a specialized cell-to-cell junctional boundary between adjacent cardiac muscle cells.',
  'lacuna-tissue': 'A lacuna is a small space in the extracellular matrix that houses a cell, such as a chondrocyte or osteocyte.',
  'epidermis-skin': 'The epidermis is the outer, avascular keratinized stratified squamous epithelium of the skin.',
  'dermis-skin': 'The dermis is the connective-tissue layer beneath the epidermis that contains vessels, nerves, glands, and hair follicles.',
  'hypodermis-skin': 'The hypodermis is the loose connective and adipose layer beneath the dermis that anchors skin to deeper structures.',
  'stratum-basale': 'The stratum basale is the deepest epidermal layer, where cells attach to the basement membrane above the dermis.',
  'stratum-spinosum': 'The stratum spinosum is the epidermal layer immediately superficial to the stratum basale, with keratinocytes joined by desmosomes.',
  'stratum-granulosum': 'The stratum granulosum is the epidermal layer superficial to the stratum spinosum, containing flattened keratinocytes with prominent granules.',
  'stratum-lucidum': 'The stratum lucidum is a thin, clear epidermal layer between the granulosum and corneum, present in thick skin.',
  'stratum-corneum': 'The stratum corneum is the outermost epidermal layer, formed by flattened, dead, keratin-filled cells.',
  'keratinocyte-skin': 'A keratinocyte is the most abundant epidermal cell, found throughout the epidermal layers and filled with keratin as it matures.',
  'melanocyte-skin': 'A melanocyte is a pigment-producing cell in the stratum basale whose processes extend between nearby keratinocytes.',
  'merkel-cell-skin': 'A Merkel cell is a tactile epithelial cell in the stratum basale associated with a sensory nerve ending.',
  'langerhans-cell-skin': 'A Langerhans cell is a branching immune cell found among keratinocytes in the epidermis.',
  'papillary-layer-skin': 'The papillary layer is the superficial, loose connective-tissue part of the dermis directly beneath the epidermis.',
  'reticular-layer-skin': 'The reticular layer is the deeper, dense irregular connective-tissue part of the dermis beneath the papillary layer.',
  'dermal-papilla-skin': 'A dermal papilla is an upward projection of the papillary dermis that interlocks with the epidermis.',
  'collagen-skin': 'Dermal collagen fibers are thick protein bundles within the dermis that give skin tensile strength.',
  'elastic-fibers-skin': 'Dermal elastic fibers are branching fibers in the dermis that allow skin to stretch and recoil.',
  'cutaneous-blood-vessels-skin': 'Cutaneous blood vessels course through the dermis and hypodermis beneath the avascular epidermis.',
  'eccrine-sweat-gland': 'An eccrine sweat gland is a coiled tubular gland in the dermis whose duct opens directly onto the skin surface.',
  'apocrine-sweat-gland': 'An apocrine sweat gland is a large coiled gland in the dermis whose duct typically empties into a hair follicle.',
  'sebaceous-gland-skin': 'A sebaceous gland is an oil-producing gland in the dermis that usually opens into an adjacent hair follicle.',
  'ceruminous-gland-skin': 'A ceruminous gland is a modified sweat gland in the skin of the external acoustic meatus.',
  'sweat-pore-skin': 'A sweat pore is the opening at the skin surface where an eccrine sweat duct ends.',
  'sebaceous-duct-skin': 'A sebaceous duct is the short passage carrying a sebaceous gland’s secretion toward a hair follicle.',
  'hair-shaft-skin': 'The hair shaft is the visible portion of a keratinized hair that projects above the skin surface.',
  'hair-root-skin': 'The hair root is the portion of a hair below the skin surface, enclosed within its follicle.',
  'hair-follicle-skin': 'A hair follicle is an epidermal sheath extending into the dermis that surrounds the hair root.',
  'hair-bulb-skin': 'The hair bulb is the expanded base of a hair follicle, where the hair matrix surrounds the dermal papilla.',
  'dermal-papilla-hair': 'The hair dermal papilla is a connective-tissue projection into the base of the hair bulb.',
  'arrector-pili-skin': 'The arrector pili is a small smooth muscle connecting a hair follicle to the superficial dermis.',
  'nail-plate-skin': 'The nail plate is the hard keratin covering on the dorsal surface of the distal digit.',
  'nail-bed-skin': 'The nail bed is the skin beneath the nail plate, extending from the lunula region toward the fingertip.',
  'nail-root-skin': 'The nail root is the proximal part of the nail plate hidden beneath the proximal nail fold.',
  'nail-matrix-skin': 'The nail matrix is the epithelium beneath the proximal nail fold that produces the nail plate.',
  'tactile-corpuscle-skin': 'A tactile corpuscle is an encapsulated touch receptor in the superficial dermis, especially within dermal papillae.',
  'lamellated-corpuscle-skin': 'A lamellated corpuscle is a deep, onion-like sensory receptor found in the dermis and hypodermis.',
  'free-nerve-ending-skin': 'A free nerve ending is an unencapsulated sensory fiber that branches through the epidermis or dermis.',
  'hair-root-plexus-skin': 'A hair root plexus is a network of sensory nerve endings wrapped around a hair follicle.',
  'fibrous-tunic-eye': 'The fibrous tunic is the outer coat of the eyeball, formed by the sclera posteriorly and the cornea anteriorly.',
  'sclera-eye': 'The sclera is the opaque, tough posterior part of the fibrous coat surrounding most of the eyeball.',
  'cornea-eye': 'The cornea is the transparent anterior part of the fibrous coat, continuous with the sclera at the corneal margin.',
  'vascular-tunic-eye': 'The vascular tunic is the middle coat of the eyeball, consisting of the choroid, ciliary body, and iris.',
  'choroid-eye': 'The choroid is the vascular, pigmented layer between the sclera and retina over the posterior eyeball.',
  'ciliary-body-eye': 'The ciliary body is the ring of vascular tissue behind the iris that connects to the lens by suspensory ligaments.',
  'iris-eye': 'The iris is the colored ring of the vascular tunic anterior to the lens, surrounding the pupil.',
  'pupil-eye': 'The pupil is the central opening in the iris through which light enters the eye.',
  'anterior-chamber-eye': 'The anterior chamber is the aqueous-humor-filled space between the cornea and iris.',
  'posterior-chamber-eye': 'The posterior chamber is the small aqueous-humor-filled space between the iris and the lens and ciliary body.',
  'aqueous-humor-eye': 'Aqueous humor is the clear fluid filling the anterior and posterior chambers of the eye.',
  'vitreous-chamber-eye': 'The vitreous chamber is the large space behind the lens and in front of the retina.',
  'vitreous-humor-eye': 'Vitreous humor is the transparent gel filling the vitreous chamber behind the lens.',
  'lens-eye': 'The lens is a transparent, flexible structure behind the iris and pupil, suspended from the ciliary body.',
  'suspensory-ligaments-eye': 'The suspensory ligaments of the lens are zonular fibers that connect the lens capsule to the ciliary body.',
  'retina-eye': 'The retina is the light-sensitive neural layer lining the inner posterior wall of the eyeball.',
  'retinal-pigment-epithelium-eye': 'The retinal pigment epithelium is the pigmented outer retinal layer between the photoreceptors and choroid.',
  'optic-disc-eye': 'The optic disc is the retinal site where ganglion-cell axons leave the eye to form the optic nerve.',
  'fovea-centralis-eye': 'The fovea centralis is a small central pit in the macula lutea with the retina’s greatest concentration of cones.',
  'macula-lutea-eye': 'The macula lutea is the central region of the posterior retina that contains the fovea centralis.',
  'rods-eye': 'Rods are photoreceptor cells in the retina that are especially abundant outside the fovea.',
  'cones-eye': 'Cones are photoreceptor cells concentrated in the macula and most densely packed at the fovea centralis.',
  'bipolar-cells-eye': 'Retinal bipolar cells are interneurons positioned between photoreceptors and ganglion cells in the retina.',
  'ganglion-cells-eye': 'Retinal ganglion cells lie on the inner side of the retina, and their axons converge to form the optic nerve.',
  'eyelid-sense': 'An eyelid is a movable fold of skin and muscle that covers the anterior surface of the eyeball.',
  'conjunctiva-sense': 'The conjunctiva is a thin membrane lining the inner eyelids and reflecting onto the anterior sclera, but not the cornea.',
  'lacrimal-gland-sense': 'The lacrimal gland lies in the superolateral orbit and releases tears onto the eye surface.',
  'lacrimal-sac-sense': 'The lacrimal sac is the medial orbital reservoir that receives tears from the canaliculi and continues into the nasolacrimal duct.',
  'nasolacrimal-duct-sense': 'The nasolacrimal duct carries tears from the lacrimal sac into the inferior part of the nasal cavity.',
  'optic-nerve-eye': 'The optic nerve is cranial nerve II, formed by retinal ganglion-cell axons traveling from the eye toward the optic chiasm.',
  'medial-rectus-eye': 'The medial rectus is the extraocular muscle on the medial side of the eyeball, running from the orbit to the globe.',
  'lateral-rectus-eye': 'The lateral rectus is the extraocular muscle on the lateral side of the eyeball, running from the orbit to the globe.',
  'superior-rectus-eye': 'The superior rectus is an extraocular muscle that runs along the superior surface of the eyeball from the orbit.',
  'inferior-rectus-eye': 'The inferior rectus is an extraocular muscle that runs along the inferior surface of the eyeball from the orbit.',
  'superior-oblique-eye': 'The superior oblique passes through a pulley at the superomedial orbit before attaching to the superior posterior eyeball.',
  'inferior-oblique-eye': 'The inferior oblique runs from the anterior medial floor of the orbit to the inferior lateral surface of the eyeball.',
  'levator-palpebrae-eye': 'The levator palpebrae superioris extends from the superior orbit to the upper eyelid.',
  'auricle-ear': 'The auricle, or pinna, is the visible elastic-cartilage structure on the outside of the ear.',
  'external-acoustic-meatus-ear': 'The external acoustic meatus is the passage extending from the auricle through the temporal bone to the tympanic membrane.',
  'tympanic-membrane-ear': 'The tympanic membrane separates the external acoustic meatus from the middle-ear cavity.',
  'malleus-ear': 'The malleus is the first middle-ear ossicle, attached to the tympanic membrane and articulating with the incus.',
  'incus-ear': 'The incus is the middle-ear ossicle positioned between the malleus and stapes.',
  'stapes-ear': 'The stapes is the smallest middle-ear ossicle, whose footplate contacts the oval window.',
  'auditory-tube-ear': 'The auditory tube connects the middle-ear cavity to the nasopharynx.',
  'oval-window-ear': 'The oval window is the membrane-covered opening on the medial wall of the middle ear where the stapes footplate rests.',
  'round-window-ear': 'The round window is a membrane-covered opening on the medial wall of the middle ear, inferior to the oval window.',
  'cochlea-ear': 'The cochlea is the spiral-shaped part of the inner ear that contains the cochlear duct.',
  'vestibule-ear': 'The vestibule is the central chamber of the inner ear between the cochlea and semicircular canals.',
  'utricle-ear': 'The utricle is the larger membranous sac within the vestibule, connected to the semicircular ducts.',
  'saccule-ear': 'The saccule is the smaller membranous sac within the vestibule, adjacent to the cochlea.',
  'semicircular-canals-ear': 'The semicircular canals are three bony loops in different planes that enclose the semicircular ducts.',
  'semicircular-ducts-ear': 'The semicircular ducts are three membranous loops within the bony semicircular canals.',
  'cochlear-duct-ear': 'The cochlear duct is the membranous channel between the vestibular and tympanic ducts inside the cochlea.',
  'vestibular-duct-ear': 'The vestibular duct, or scala vestibuli, is the perilymph-filled upper chamber of the cochlea above the cochlear duct.',
  'tympanic-duct-ear': 'The tympanic duct, or scala tympani, is the perilymph-filled lower chamber of the cochlea beneath the cochlear duct.',
  'organ-of-corti-ear': 'The organ of Corti is the auditory sensory structure on the basilar membrane within the cochlear duct.',
  'hair-cells-ear': 'Inner-ear hair cells are sensory cells with hair bundles in the organ of Corti and vestibular sensory regions.',
  'vestibulocochlear-nerve-ear': 'The vestibulocochlear nerve, cranial nerve VIII, carries sensory information from the inner ear toward the brainstem.',
  'olfactory-epithelium-sense': 'The olfactory epithelium is specialized sensory epithelium in the roof of the nasal cavity.',
  'olfactory-receptor-sense': 'An olfactory receptor cell is a bipolar sensory neuron within the olfactory epithelium, with an axon directed toward the olfactory bulb.',
  'olfactory-bulb-sense': 'The olfactory bulb is neural tissue on the underside of the frontal lobe that receives axons from olfactory receptor cells.',
  'olfactory-nerve-sense': 'The olfactory nerve, cranial nerve I, consists of receptor-cell axons passing through the cribriform plate to the olfactory bulb.',
  'taste-bud-sense': 'A taste bud is a cluster of sensory epithelial cells in the lining of the tongue and other oral regions, opening at a taste pore.',
  'gustatory-receptor-sense': 'A gustatory receptor cell is a sensory epithelial cell within a taste bud, with microvilli projecting toward its taste pore.',
  'facial-nerve-taste': 'Facial nerve taste fibers, cranial nerve VII, carry taste signals mainly from the anterior two-thirds of the tongue.',
  'glossopharyngeal-nerve-taste': 'Glossopharyngeal nerve taste fibers, cranial nerve IX, carry taste signals mainly from the posterior third of the tongue.',
  'vagus-nerve-taste': 'Vagus nerve taste fibers, cranial nerve X, carry taste signals from the epiglottis and lower pharynx.',
  'optic-chiasm-sense': 'The optic chiasm is the midline crossing at the base of the brain where some optic nerve fibers cross.',
  'oculomotor-nerve-sense': 'The oculomotor nerve, cranial nerve III, enters the orbit to supply most extraocular muscles and the levator palpebrae superioris.',
  'trochlear-nerve-sense': 'The trochlear nerve, cranial nerve IV, enters the orbit to supply the superior oblique muscle.',
  'abducens-nerve-sense': 'The abducens nerve, cranial nerve VI, enters the orbit to supply the lateral rectus muscle.',
} as const;