export default {
  'endo-hypothalamus': 'The hypothalamus is a diencephalic region forming the floor of the third ventricle and linking the brain to the pituitary by neural and vascular routes.',
  'endo-pituitary': 'The pituitary gland lies in the sella turcica at the base of the brain and connects to the hypothalamus by the pituitary stalk.',
  'endo-anterior-pituitary': 'The anterior pituitary is the glandular front lobe of the pituitary, reached by hypothalamic hormones through portal blood.',
  'endo-posterior-pituitary': 'The posterior pituitary is the neural rear lobe of the pituitary, continuous with hypothalamic axons.',
  'endo-pars-intermedia': 'The pars intermedia is the thin region between the anterior and posterior pituitary lobes.',
  'endo-pituitary-stalk': 'The pituitary stalk is the narrow connection between the hypothalamus and pituitary gland.',
  'endo-pineal': 'The pineal gland is a small endocrine organ attached to the posterior roof of the diencephalon.',
  'endo-thyroid': 'The thyroid gland lies in the anterior neck, where its two lobes flank the upper trachea and join across the midline.',
  'endo-thyroid-lobe': 'A thyroid lobe is one of the paired lateral masses of the thyroid gland, lying on either side of the upper trachea.',
  'endo-thyroid-isthmus': 'The thyroid isthmus is the midline bridge connecting the thyroid lobes across the anterior trachea.',
  'endo-thyroid-follicle': 'A thyroid follicle is a spherical unit of follicular epithelial cells surrounding a central lumen filled with colloid.',
  'endo-thyroid-colloid': 'Thyroid colloid is the protein-rich material stored in the lumen at the center of each thyroid follicle.',
  'endo-follicular-cell': 'A thyroid follicular cell is an epithelial cell lining a thyroid follicle around its colloid-filled lumen.',
  'endo-parafollicular-cell': 'A parafollicular cell, or C cell, lies between thyroid follicles rather than forming their colloid-facing lining.',
  'endo-parathyroids': 'The parathyroid glands are small endocrine glands typically located on the posterior surface of the thyroid gland.',
  'endo-parathyroid-chief-cell': 'A parathyroid chief cell is the principal cell type within the parathyroid gland tissue.',
  'endo-thymus': 'The thymus is a lymphoid and endocrine organ in the anterior superior mediastinum, behind the sternum and above the heart.',
  'endo-adrenal': 'Each adrenal gland sits superior and medial to a kidney, with an outer cortex surrounding an inner medulla.',
  'endo-adrenal-cortex': 'The adrenal cortex is the gland’s outer layer, arranged in three zones around the central medulla.',
  'endo-adrenal-medulla': 'The adrenal medulla is the central region enclosed by the adrenal cortex and contains chromaffin cells.',
  'endo-zona-glomerulosa': 'The zona glomerulosa is the outermost adrenal cortical zone, immediately deep to the gland’s capsule.',
  'endo-zona-fasciculata': 'The zona fasciculata is the broad middle layer of the adrenal cortex, between the glomerulosa and reticularis.',
  'endo-zona-reticularis': 'The zona reticularis is the innermost adrenal cortical zone, bordering the medulla.',
  'endo-chromaffin-cell': 'A chromaffin cell is a secretory cell in the inner adrenal medulla, not in the outer cortical zones.',
  'endo-pancreas': 'The pancreas is a mixed gland behind the stomach, extending from the duodenum toward the spleen and containing endocrine islets among exocrine tissue.',
  'endo-pancreatic-islet': 'A pancreatic islet is a pale cluster of endocrine cells scattered among the darker exocrine acini of the pancreas.',
  'endo-alpha-cell': 'A pancreatic alpha cell is a glucagon-secreting endocrine cell within an islet of the pancreas.',
  'endo-beta-cell': 'A pancreatic beta cell is an insulin-secreting endocrine cell within an islet of the pancreas.',
  'endo-delta-cell': 'A pancreatic delta cell is a somatostatin-secreting endocrine cell within an islet of the pancreas.',
  'endo-ovary': 'An ovary is a paired female gonad lateral to the uterus, containing follicles and post-ovulatory structures in its cortex.',
  'endo-corpus-luteum': 'The corpus luteum is the temporary post-ovulatory structure formed from the ruptured ovarian follicle.',
  'endo-testis': 'A testis is a male gonad in the scrotum, composed of seminiferous tubules with hormone-producing interstitial tissue between them.',
  'endo-leydig-cell': 'A Leydig cell is an endocrine cell in the interstitial tissue between seminiferous tubules of the testis.',
  'endo-sertoli-cell': 'A Sertoli cell is a supporting cell within the seminiferous epithelium, extending among developing germ cells.',
  'endo-portal-system': 'The hypothalamic–hypophyseal portal system is a pair of connected capillary beds carrying blood from the hypothalamus to the anterior pituitary.',
  'endo-neurosecretory-cell': 'Hypothalamic neurosecretory cells are hormone-releasing neurons that act through portal blood on the anterior pituitary or project to the posterior pituitary.',
  'endo-endocrine-gland': 'An endocrine gland releases its secretions into surrounding tissue fluid and blood rather than through a duct to a surface.',
  'endo-exocrine-gland': 'An exocrine gland sends its secretion through a duct to an epithelial surface or organ lumen.',

  'cv-heart': 'The heart is a four-chambered muscular organ in the mediastinum, enclosed by the pericardium and connected to the pulmonary and systemic vessels.',
  'cv-apex': 'The apex is the inferior, left-pointing tip of the heart, formed mainly by the left ventricle.',
  'cv-base': 'The base is the broad superior and posterior aspect of the heart, opposite its inferior apex.',
  'cv-right-auricle': 'The right auricle is an ear-shaped muscular appendage projecting from the right atrium.',
  'cv-left-auricle': 'The left auricle is an ear-shaped muscular appendage projecting from the left atrium.',
  'cv-right-atrium': 'The right atrium is the heart’s upper right chamber, receiving the superior and inferior venae cavae and coronary sinus.',
  'cv-left-atrium': 'The left atrium is the upper left chamber, receiving pulmonary veins from the lungs.',
  'cv-right-ventricle': 'The right ventricle is the lower right chamber, separated from the left ventricle by the interventricular septum and opening into the pulmonary trunk.',
  'cv-left-ventricle': 'The left ventricle is the lower left chamber, separated from the right ventricle by the interventricular septum and opening into the aorta.',
  'cv-tricuspid': 'The tricuspid valve is the right atrioventricular valve between the right atrium and right ventricle.',
  'cv-mitral': 'The mitral, or bicuspid, valve is the left atrioventricular valve between the left atrium and left ventricle.',
  'cv-pulmonary-valve': 'The pulmonary semilunar valve guards the opening from the right ventricle into the pulmonary trunk.',
  'cv-aortic-valve': 'The aortic semilunar valve guards the opening from the left ventricle into the aorta.',
  'cv-interatrial-septum': 'The interatrial septum is the wall separating the right and left atria.',
  'cv-interventricular-septum': 'The interventricular septum is the thick wall separating the right and left ventricles.',
  'cv-chordae': 'Chordae tendineae are fibrous cords connecting atrioventricular valve cusps to papillary muscles in the ventricles.',
  'cv-papillary': 'Papillary muscles are projections from the ventricular wall that anchor the chordae tendineae of atrioventricular valves.',
  'cv-myocardium': 'The myocardium is the thick cardiac-muscle layer between the endocardium and epicardium in the heart wall.',
  'cv-endocardium': 'The endocardium is the smooth inner lining of the heart chambers and covers the surfaces of its valves.',
  'cv-epicardium': 'The epicardium is the outer surface of the heart wall and is the visceral layer of the serous pericardium.',
  'cv-fibrous-pericardium': 'The fibrous pericardium is the tough outer sac enclosing the heart and the roots of its great vessels.',
  'cv-serous-pericardium': 'The serous pericardium is the double-layered membrane around the heart, with parietal and heart-covering visceral layers.',
  'cv-pericardial-cavity': 'The pericardial cavity is the potential space between the parietal and visceral layers of serous pericardium.',
  'cv-coronary-sulcus': 'The coronary sulcus is the external groove encircling the heart between the atria and ventricles.',
  'cv-right-coronary': 'The right coronary artery arises from the aortic root and runs in the coronary sulcus on the right side of the heart.',
  'cv-left-coronary': 'The left coronary artery arises from the aortic root and divides into the anterior interventricular and circumflex arteries.',
  'cv-lad': 'The anterior interventricular artery, or LAD, descends in the anterior interventricular sulcus toward the apex.',
  'cv-circumflex': 'The circumflex artery is a branch of the left coronary artery that curves through the left portion of the coronary sulcus.',
  'cv-right-marginal': 'The right marginal artery follows the acute margin of the heart as a branch of the right coronary artery.',
  'cv-posterior-interventricular': 'The posterior interventricular artery runs in the posterior interventricular sulcus between the ventricles.',
  'cv-great-cardiac-vein': 'The great cardiac vein accompanies the anterior interventricular artery on the heart’s anterior surface and drains toward the coronary sinus.',
  'cv-middle-cardiac-vein': 'The middle cardiac vein accompanies the posterior interventricular artery in the posterior interventricular sulcus.',
  'cv-small-cardiac-vein': 'The small cardiac vein follows the right margin of the heart and drains into the coronary sinus.',
  'cv-coronary-sinus': 'The coronary sinus is the large venous channel on the posterior heart that collects cardiac veins and empties into the right atrium.',
  'cv-sa-node': 'The sinoatrial node is a small group of conducting cells near the opening of the superior vena cava into the right atrium.',
  'cv-av-node': 'The atrioventricular node lies low in the interatrial septum near the opening of the coronary sinus.',
  'cv-av-bundle': 'The atrioventricular bundle, or bundle of His, passes from the AV node into the interventricular septum.',
  'cv-purkinje': 'Purkinje fibers are conducting cells branching beneath the endocardium through the ventricular walls.',
  'cv-pulmonary-trunk': 'The pulmonary trunk leaves the right ventricle and divides into right and left pulmonary arteries.',
  'cv-pulmonary-veins': 'The pulmonary veins return blood from the lungs and enter the left atrium.',
  'cv-svc': 'The superior vena cava is the large vein returning blood from the upper body to the right atrium.',
  'cv-ivc': 'The inferior vena cava is the large vein returning blood from below the diaphragm to the right atrium.',
  'cv-ascending-aorta': 'The ascending aorta begins at the left ventricle and rises to continue as the aortic arch.',
  'cv-aortic-arch': 'The aortic arch curves from the ascending to descending aorta and gives rise to the brachiocephalic trunk, left common carotid, and left subclavian arteries.',
  'cv-descending-aorta': 'The descending aorta continues from the aortic arch through the thorax and abdomen.',
  'cv-brachiocephalic': 'The brachiocephalic trunk is the first branch of the aortic arch and divides into the right common carotid and right subclavian arteries.',
  'cv-left-common-carotid': 'The left common carotid artery rises directly from the aortic arch and ascends the left side of the neck.',
  'cv-left-subclavian': 'The left subclavian artery branches from the aortic arch and passes beneath the clavicle toward the left upper limb.',
  'cv-right-pulmonary-artery': 'The right pulmonary artery branches from the pulmonary trunk and carries blood to the right lung.',
  'cv-left-pulmonary-artery': 'The left pulmonary artery branches from the pulmonary trunk and carries blood to the left lung.',
  'cv-blood-plasma': 'Blood plasma is the liquid extracellular matrix in which the circulating formed elements are suspended.',
  'cv-blood-serum': 'Serum is the liquid remaining after blood clots, unlike plasma separated before clotting.',
  'cv-blood-formed-elements': 'Formed elements are the cellular components and cell fragments suspended in blood plasma: erythrocytes, leukocytes, and platelets.',
  'cv-blood-buffy-coat': 'The buffy coat is the thin layer of leukocytes and platelets between plasma and packed erythrocytes after blood is centrifuged.',
  'cv-blood-erythrocyte': 'A mature erythrocyte is an anucleate, biconcave blood cell whose thinner center appears pale in a stained smear.',
  'cv-blood-central-pallor': 'Central pallor is the lighter center of a mature erythrocyte in a smear, caused by the cell’s biconcave shape.',
  'cv-blood-platelet': 'A platelet is a tiny anucleate cytoplasmic fragment released into blood from a megakaryocyte in red marrow.',
  'cv-blood-megakaryocyte': 'A megakaryocyte is a very large nucleated cell in red bone marrow that sheds platelets into the circulation.',
  'cv-blood-leukocyte': 'A leukocyte is a nucleated white blood cell circulating among anucleate erythrocytes and platelet fragments.',
  'cv-blood-granulocyte': 'A granulocyte is a leukocyte with prominent stained cytoplasmic granules, including neutrophils, eosinophils, and basophils.',
  'cv-blood-agranulocyte': 'An agranulocyte is a leukocyte without prominent stain-visible granules, such as a lymphocyte or monocyte.',
  'cv-blood-neutrophil': 'A neutrophil is a granulocyte with a segmented nucleus and fine, pale-staining granules.',
  'cv-blood-eosinophil': 'An eosinophil is a granulocyte with a usually bilobed nucleus and conspicuous coarse orange-red granules.',
  'cv-blood-basophil': 'A basophil is a granulocyte with dense blue-purple granules that can partly obscure its nucleus.',
  'cv-blood-lymphocyte': 'A small lymphocyte is an agranulocyte with a large round nucleus and a narrow rim of cytoplasm.',
  'cv-blood-monocyte': 'A monocyte is a large agranulocyte with abundant cytoplasm and an indented or kidney-shaped nucleus.',
  'cv-blood-red-bone-marrow': 'Red bone marrow is hematopoietic tissue found mainly in axial bones and at the proximal ends of the humerus and femur in adults.',
  'cv-blood-hematopoiesis': 'Hematopoiesis is the production of blood cells, which occurs mainly in red bone marrow after birth.',
  'cv-blood-hematopoietic-stem-cell': 'A hematopoietic stem cell is a marrow precursor that can give rise to the blood-cell lineages.',
  'cv-blood-peripheral-blood-smear': 'A peripheral blood smear is a thin spread of circulating formed elements on a slide for microscopic examination.',

  'ves-artery': 'An artery is a blood vessel carrying blood away from the heart, regardless of its oxygen content.',
  'ves-arteriole': 'An arteriole is a small arterial branch that leads directly into a capillary bed.',
  'ves-capillary': 'A capillary is a microscopic vessel with a wall mainly one endothelial cell layer thick, linking arterioles to venules.',
  'ves-venule': 'A venule is a small vessel that receives blood from capillaries and joins larger veins.',
  'ves-vein': 'A vein is a vessel that returns blood toward the heart and generally has a thinner wall and wider lumen than a comparable artery.',
  'ves-intima': 'The tunica intima is the innermost vessel-wall layer, directly lining the lumen.',
  'ves-endothelium': 'The endothelium is the thin epithelial cell lining in direct contact with blood inside a vessel lumen.',
  'ves-media': 'The tunica media is the vessel-wall layer outside the intima, rich in smooth muscle and elastic tissue.',
  'ves-externa': 'The tunica externa, or adventitia, is the outer connective-tissue layer surrounding a vessel wall.',
  'ves-elastic': 'An elastic artery is a large artery with abundant elastic tissue in its wall, exemplified by the aorta.',
  'ves-muscular': 'A muscular artery has a prominent smooth-muscle tunica media and distributes blood to regional territories.',
  'ves-continuous': 'A continuous capillary has an uninterrupted endothelial lining and basement membrane with no fenestrations.',
  'ves-fenestrated': 'A fenestrated capillary has pores in its endothelial lining that permit greater exchange than a continuous capillary.',
  'ves-sinusoid': 'A sinusoid capillary has wide endothelial gaps and a discontinuous basement membrane, making it the most permeable capillary type.',
  'ves-rbc': 'An erythrocyte is a mature, anucleate biconcave red blood cell circulating among plasma, leukocytes, and platelets.',
  'ves-platelet': 'A platelet is a small cytoplasmic fragment circulating in blood, not a whole leukocyte or erythrocyte.',
  'ves-neutrophil': 'A neutrophil is a granular leukocyte identified in a blood smear by its segmented nucleus and fine pale granules.',
  'ves-aorta': 'The aorta is the body’s largest elastic artery, arising from the left ventricle and continuing through ascending, arch, and descending segments.',
  'ves-celiac-trunk': 'The celiac trunk branches from the abdominal aorta and supplies branches to the upper abdominal digestive organs.',
  'ves-renal-artery': 'A renal artery branches laterally from the abdominal aorta and enters a kidney at its hilum.',
  'ves-common-carotid': 'A common carotid artery ascends the neck before dividing into internal and external carotid arteries.',
  'ves-internal-carotid': 'The internal carotid artery is the common carotid branch that ascends into the skull to supply the brain and orbit.',
  'ves-external-carotid': 'The external carotid artery is the common carotid branch that supplies structures of the head and neck outside the cranial cavity.',
  'ves-subclavian': 'A subclavian artery passes beneath its clavicle and continues toward the upper limb as the axillary artery.',
  'ves-axillary': 'The axillary artery is the continuation of the subclavian artery through the armpit, becoming the brachial artery in the arm.',
  'ves-brachial': 'The brachial artery is the main artery of the upper arm, continuing from the axillary artery before dividing into radial and ulnar branches.',
  'ves-radial': 'The radial artery runs along the lateral, thumb-side of the forearm as a branch of the brachial artery.',
  'ves-ulnar': 'The ulnar artery runs along the medial, little-finger side of the forearm as a branch of the brachial artery.',
  'ves-femoral': 'The femoral artery is the major artery of the thigh, continuing from the external iliac artery below the inguinal ligament.',
  'ves-popliteal': 'The popliteal artery lies behind the knee as the continuation of the femoral artery before dividing into leg arteries.',
  'ves-anterior-tibial': 'The anterior tibial artery descends through the anterior compartment of the leg toward the dorsum of the foot.',
  'ves-posterior-tibial': 'The posterior tibial artery descends through the posterior leg and passes behind the medial ankle toward the foot.',
  'ves-internal-jugular': 'The internal jugular vein is a deep neck vein that drains the brain and joins the subclavian vein to form a brachiocephalic vein.',
  'ves-brachiocephalic-vein': 'A brachiocephalic vein is formed by the union of an internal jugular and subclavian vein and drains to the superior vena cava.',
  'ves-subclavian-vein': 'A subclavian vein returns blood from the upper limb and joins the internal jugular vein behind the clavicle.',
  'ves-axillary-vein': 'The axillary vein drains the upper limb through the armpit and continues as the subclavian vein.',
  'ves-jugular': 'A jugular vein is a vein in the neck that returns blood from the head toward the brachiocephalic veins.',
  'ves-cephalic': 'The cephalic vein is a superficial vein along the lateral side of the upper limb.',
  'ves-median-cubital': 'The median cubital vein is a superficial connector across the front of the elbow between the cephalic and basilic veins.',
  'ves-great-saphenous': 'The great saphenous vein is a long superficial vein ascending along the medial side of the foot, leg, and thigh.',
  'ves-hepatic-portal': 'The hepatic portal vein carries blood from digestive organs and the spleen into the liver before it returns to systemic veins.',
  'ves-splenic': 'The splenic vein drains the spleen and joins the portal venous route toward the liver.',
  'ves-mesenteric': 'The superior mesenteric vein drains much of the small intestine and joins the portal venous route to the liver.',
  'ves-hepatic-vein': 'The hepatic veins drain blood from the liver into the inferior vena cava.',
  'ves-sinusoids': 'Hepatic sinusoids are wide vascular channels between liver-cell plates that receive portal and arterial blood and drain toward central veins.',

  'lymph-fluid': 'Lymph is interstitial fluid collected inside lymphatic vessels on its way back to the venous circulation.',
  'lymph-capillary': 'A lymphatic capillary is a blind-ended, thin-walled vessel that begins in tissue spaces and collects interstitial fluid.',
  'lymph-collecting-vessel': 'A collecting lymphatic vessel receives lymph from capillaries and carries it toward lymph nodes and larger trunks.',
  'lymph-thoracic-duct': 'The thoracic duct begins at the cisterna chyli and returns lymph from most of the body to the left venous angle.',
  'lymph-right-duct': 'The right lymphatic duct drains the right upper quadrant and empties near the junction of the right internal jugular and subclavian veins.',
  'lymph-node': 'A lymph node is an encapsulated lymphoid organ along lymphatic vessels, with an outer cortex and inner medulla.',
  'lymph-cervical-nodes': 'Cervical lymph nodes are node groups in the neck that receive lymph from the head and neck.',
  'lymph-axillary-nodes': 'Axillary lymph nodes are node groups in the armpit that receive lymph from the upper limb and nearby regions.',
  'lymph-inguinal-nodes': 'Inguinal lymph nodes are node groups in the groin that receive lymph from the lower limb and nearby regions.',
  'lymph-afferent': 'Afferent lymphatic vessels enter a lymph node on its convex surface and deliver lymph to the subcapsular sinus.',
  'lymph-efferent': 'Efferent lymphatic vessels leave a lymph node at its indented hilum after lymph passes through the node.',
  'lymph-capsule': 'The lymph-node capsule is the outer connective-tissue covering that encloses the cortex and medulla.',
  'lymph-subcapsular-sinus': 'The subcapsular sinus is the lymph-filled space immediately beneath the lymph-node capsule.',
  'lymph-cortical-sinus': 'A cortical sinus is a lymphatic channel extending from the subcapsular sinus through the lymph-node cortex.',
  'lymph-cortex': 'The lymph-node cortex is the outer region beneath the capsule and contains lymphoid follicles.',
  'lymph-medulla': 'The lymph-node medulla is the deeper central region near the hilum and contains cords separated by sinuses.',
  'lymph-medullary-sinus': 'A medullary sinus is a lymphatic channel between medullary cords that carries lymph toward the node hilum.',
  'lymph-medullary-cord': 'A medullary cord is a strand of lymphoid tissue in the lymph-node medulla between medullary sinuses.',
  'lymph-hilum': 'The lymph-node hilum is the indented region where efferent lymphatic vessels leave and blood vessels enter or exit.',
  'lymph-spleen': 'The spleen is a blood-filtering lymphoid organ in the upper left abdomen, organized into white pulp and red pulp.',
  'lymph-white-pulp': 'White pulp is the lymphoid tissue of the spleen arranged around a central arteriole.',
  'lymph-marginal-zone': 'The splenic marginal zone is the border between the white pulp surrounding a central arteriole and the red pulp.',
  'lymph-central-arteriole': 'A central arteriole is the small artery embedded within a nodule of splenic white pulp.',
  'lymph-red-pulp': 'Red pulp is the blood-filled region of the spleen organized into splenic cords and vascular sinusoids.',
  'lymph-splenic-cords': 'Splenic cords are strands of tissue in the red pulp that lie between the splenic sinusoids.',
  'lymph-splenic-sinusoids': 'Splenic sinusoids are vascular channels in the red pulp between splenic cords.',
  'lymph-thymus': 'The thymus is a primary lymphoid organ in the anterior superior mediastinum, divided into lobules with a cortex and medulla.',
  'lymph-thymic-lobule': 'A thymic lobule is a subdivision of the thymus with a darker outer cortex surrounding a lighter medulla.',
  'lymph-thymic-cortex': 'The thymic cortex is the darker outer region of each thymic lobule, surrounding its medulla.',
  'lymph-thymic-medulla': 'The thymic medulla is the lighter central region of a thymic lobule and contains Hassall corpuscles.',
  'lymph-hassall': 'A Hassall corpuscle is a concentric structure found in the medulla of the thymus.',
  'lymph-palatine-tonsil': 'A palatine tonsil is a paired lymphoid mass on the lateral wall of the oropharynx.',
  'lymph-pharyngeal-tonsil': 'The pharyngeal tonsil, also called the adenoid, is lymphoid tissue in the roof of the nasopharynx.',
  'lymph-lingual-tonsil': 'Lingual tonsils are lymphoid nodules at the base of the tongue, behind the oral cavity.',
  'lymph-malt': 'Mucosa-associated lymphoid tissue, or MALT, is lymphoid tissue positioned beneath mucosal surfaces.',
  'lymph-peyers': 'Peyer patches are aggregated lymphoid nodules in the mucosa and submucosa of the ileum.',
  'lymph-lacteal': 'A lacteal is a lymphatic capillary in the core of an intestinal villus that collects absorbed dietary lipids.',
  'lymph-follicle': 'A lymphoid follicle is a rounded aggregate of lymphocytes in a lymphoid organ or mucosa.',
  'lymph-germinal-center': 'A germinal center is the lighter central region of an activated lymphoid follicle.',
  'lymph-cisterna': 'The cisterna chyli is an enlarged lymphatic sac in the abdomen that receives lumbar and intestinal trunks at the start of the thoracic duct.',
  'lymph-trunk': 'A lymphatic trunk is a large collecting vessel that receives lymph from regional vessels before it drains into a major duct.',
  'lymph-jugular-trunk': 'A jugular lymphatic trunk collects lymph from the head and neck and drains toward a lymphatic duct.',
  'lymph-subclavian-trunk': 'A subclavian lymphatic trunk collects lymph from an upper limb and drains near the root of the neck.',
  'lymph-intestinal-trunk': 'The intestinal lymphatic trunk collects lymph from abdominal digestive organs, including lipid-rich lymph from intestinal lacteals.',
  'lymph-lumbar-trunks': 'The paired lumbar lymphatic trunks collect lymph from the lower body and converge on the cisterna chyli.',
  'lymph-appendix': 'Appendix lymphoid tissue is lymphoid tissue in the wall of the vermiform appendix, associated with the intestinal mucosa.',
  'lymph-tonsil': 'A tonsil is a mucosa-associated lymphoid mass positioned around the entrance to the pharynx.',
} satisfies Record<string, string>;