/**
 * Quick definitions keyed only by existing verified structure IDs.
 * Orientation and organ-map wording follows the source-linked OpenStax
 * foundations lessons/questions; development wording follows §§28.1–28.2.
 * Cytology wording follows the verified BIOL 250 transcriptions (pp. 5–8, 11–12).
 */
export default {
  brain: 'The brain is the central nervous-system organ enclosed by the cranial cavity.',
  heart: 'The heart is a muscular cardiovascular organ in the thoracic mediastinum, between the pleural cavities.',
  lungs: 'The lungs are paired respiratory organs in the thorax, one in each pleural cavity beside the mediastinum.',
  liver: 'The liver is a digestive accessory organ located mostly in the patient’s right upper abdominal quadrant.',
  stomach: 'The stomach is a hollow digestive organ between the esophagus and small intestine, mainly in the left upper abdominal quadrant.',
  kidneys: 'The kidneys are paired urinary organs on the posterior abdominal wall, behind the parietal peritoneum.',
  pancreas: 'The pancreas is a gland behind the stomach that contributes to both digestion and the endocrine system.',
  'thyroid-gland': 'The thyroid gland is an endocrine organ in the anterior neck.',
  'pituitary-gland': 'The pituitary gland is an endocrine organ seated in the sella turcica at the base of the skull, beneath the hypothalamus.',
  'adrenal-glands': 'The adrenal glands are paired endocrine organs positioned superior to the kidneys.',
  spleen: 'The spleen is a lymphatic organ in the upper-left abdomen, lateral to the stomach.',
  uterus: 'The uterus is a muscular reproductive organ in the pelvis, between the urinary bladder and rectum.',

  'sagittal-plane': 'A sagittal plane divides the body into left and right portions, which need not be equal.',
  'coronal-plane': 'A coronal (frontal) plane divides the body into anterior and posterior portions.',
  'transverse-plane': 'A transverse (axial or horizontal) plane divides the body into superior and inferior portions.',
  'cranial-cavity': 'The cranial cavity is the space within the skull that contains the brain.',
  'vertebral-cavity': 'The vertebral cavity is the canal within the vertebral column that contains the spinal cord.',
  'thoracic-cavity': 'The thoracic cavity is the chest compartment superior to the diaphragm.',
  'abdominal-cavity': 'The abdominal cavity is the superior portion of the abdominopelvic cavity, below the diaphragm.',
  'pelvic-cavity': 'The pelvic cavity is the inferior portion of the abdominopelvic cavity, within the bony pelvis.',

  'anatomical-position': 'Anatomical position is the upright reference posture with the face forward, arms at the sides, and palms facing forward.',
  superior: 'Superior describes a structure closer to the head than another structure.',
  inferior: 'Inferior describes a structure farther toward the feet than another structure.',
  anterior: 'Anterior describes a position toward the front of the body.',
  posterior: 'Posterior describes a position toward the back of the body.',
  medial: 'Medial describes a position closer to the body’s midline.',
  lateral: 'Lateral describes a position farther from the body’s midline.',
  proximal: 'Proximal describes a position nearer a limb’s attachment to the trunk.',
  distal: 'Distal describes a position farther along a limb from its attachment to the trunk.',
  superficial: 'Superficial describes a position nearer the body surface.',
  deep: 'Deep describes a position farther from the body surface.',
  'midsagittal-plane': 'A midsagittal plane passes through the midline and divides the body into equal left and right halves.',
  'oblique-section': 'An oblique section is a cut made at an angle to the standard anatomical planes.',

  'cephalic-region': 'The cephalic region is the head region of the body.',
  'cervical-region': 'The cervical region is the neck, between the head and thorax.',
  'thoracic-region': 'The thoracic region is the chest portion of the trunk.',
  'abdominal-region': 'The abdominal region is the trunk area between the thorax and pelvis.',
  'pelvic-region': 'The pelvic region is the lower trunk area associated with the pelvis.',
  'brachial-region': 'The brachial region is the upper arm between the shoulder and elbow.',
  'antebrachial-region': 'The antebrachial region is the forearm between the elbow and wrist.',
  'carpal-region': 'The carpal region is the wrist between the forearm and hand.',
  'femoral-region': 'The femoral region is the thigh between the hip and knee.',
  'crural-region': 'The crural region is the leg between the knee and ankle.',
  'patellar-region': 'The patellar region is the anterior surface of the knee.',
  'popliteal-region': 'The popliteal region is the posterior surface of the knee.',
  'axillary-region': 'The axillary region is the armpit where the upper limb meets the thorax.',
  'inguinal-region': 'The inguinal region is the groin where the lower limb meets the trunk.',
  'umbilical-landmark': 'The umbilicus is the navel, a surface landmark near the center of the abdomen.',
  'sternal-landmark': 'The sternal region is the midline chest area over the sternum.',

  'dorsal-cavity': 'The dorsal body cavity is the posterior compartment formed by the cranial and vertebral cavities.',
  'ventral-cavity': 'The ventral body cavity is the anterior trunk compartment containing the thoracic and abdominopelvic cavities.',
  'abdominopelvic-cavity': 'The abdominopelvic cavity is the ventral compartment below the diaphragm, continuous through its abdominal and pelvic subdivisions.',
  'pleural-cavity': 'The pleural cavity is the thin potential space between the visceral and parietal pleura around a lung.',
  mediastinum: 'The mediastinum is the central thoracic compartment between the pleural cavities; the heart lies within it.',
  'visceral-pleura': 'The visceral pleura is the serous membrane layer directly covering a lung.',
  'parietal-pleura': 'The parietal pleura is the serous membrane layer lining the thoracic wall around a lung.',
  'visceral-pericardium': 'The visceral pericardium (epicardium) is the serous layer directly covering the heart.',
  'parietal-pericardium': 'The parietal pericardium is the outer serous layer lining the pericardial cavity around the heart.',
  'visceral-peritoneum': 'The visceral peritoneum is the serous membrane layer covering abdominal organs.',
  'parietal-peritoneum': 'The parietal peritoneum is the serous membrane layer lining the inner abdominopelvic wall.',
  'peritoneal-cavity': 'The peritoneal cavity is the thin potential space between the visceral and parietal peritoneum.',
  'retroperitoneal-region': 'The retroperitoneal region is posterior to the parietal peritoneum; the kidneys are located there.',

  'right-upper-quadrant': 'The right upper quadrant is the upper-right part of the abdominopelvic map from the patient’s perspective.',
  'left-upper-quadrant': 'The left upper quadrant is the upper-left part of the abdominopelvic map from the patient’s perspective.',
  'right-lower-quadrant': 'The right lower quadrant is the lower-right part of the abdominopelvic map from the patient’s perspective.',
  'left-lower-quadrant': 'The left lower quadrant is the lower-left part of the abdominopelvic map from the patient’s perspective.',
  'right-hypochondriac-region': 'The right hypochondriac region is the upper-right area of the nine-region abdominal map.',
  'epigastric-region': 'The epigastric region is the upper-center area of the nine-region abdominal map.',
  'left-hypochondriac-region': 'The left hypochondriac region is the upper-left area of the nine-region abdominal map.',
  'right-lumbar-region': 'The right lumbar region is the middle-right area of the nine-region abdominal map.',
  'umbilical-region': 'The umbilical region is the center area of the nine-region abdominal map, surrounding the umbilicus.',
  'left-lumbar-region': 'The left lumbar region is the middle-left area of the nine-region abdominal map.',
  'right-iliac-region': 'The right iliac region is the lower-right area of the nine-region abdominal map, also called the right inguinal region.',
  'hypogastric-region': 'The hypogastric region is the lower-center area of the nine-region abdominal map, below the umbilical region.',
  'left-iliac-region': 'The left iliac region is the lower-left area of the nine-region abdominal map, also called the left inguinal region.',
  'tissue-level': 'A tissue is a group of related cells organized to perform a shared role within the body.',
  'organ-level': 'An organ is a distinct body structure made of multiple tissue types working together.',
  'organ-system-level': 'An organ system is a group of organs that cooperate in related functions.',

  'dev-fertilization': 'Fertilization is the union of sperm and oocyte nuclei, usually in a uterine tube, that forms a zygote.',
  'dev-zygote': 'A zygote is the single cell formed by fertilization before its first cleavage divisions.',
  'dev-cleavage': 'Cleavage is the series of early cell divisions that increases blastomere number with little overall growth of the conceptus.',
  'dev-blastomere': 'A blastomere is one of the cells produced when the early conceptus undergoes cleavage.',
  'dev-morula': 'A morula is a compact, solid ball of blastomeres formed before a fluid-filled blastocyst develops.',
  'dev-blastocyst': 'A blastocyst is an early conceptus with a blastocoel, an inner cell mass, and an outer trophoblast.',
  'dev-blastocoel': 'The blastocoel is the fluid-filled cavity inside the blastocyst.',
  'dev-inner-cell-mass': 'The inner cell mass is the cluster of cells inside a blastocyst that gives rise to the embryo.',
  'dev-trophoblast': 'The trophoblast is the outer cell layer of the blastocyst that attaches to the endometrium and contributes to fetal placental tissues.',
  'dev-implantation': 'Implantation is the attachment and embedding of a blastocyst in the uterine endometrium through its trophoblast.',
  'dev-gastrulation': 'Gastrulation is the developmental process that organizes the embryo into ectoderm, mesoderm, and endoderm.',
  'dev-primitive-streak': 'The primitive streak is a linear region of the early embryonic disc through which cells move during gastrulation.',
  'dev-ectoderm': 'Ectoderm is the outer embryonic germ layer, positioned above mesoderm and endoderm in the early disc.',
  'dev-mesoderm': 'Mesoderm is the middle embryonic germ layer between ectoderm and endoderm.',
  'dev-endoderm': 'Endoderm is the inner embryonic germ layer that lines the primitive gut.',
  'dev-neurulation': 'Neurulation is the folding and closure of the ectodermal neural plate to form the neural tube.',
  'dev-neural-plate': 'The neural plate is a thickened region of dorsal embryonic ectoderm that folds to form the neural tube.',
  'dev-neural-tube': 'The neural tube is the closed tube formed from the neural plate, dorsal to the notochord and precursor to the brain and spinal cord.',
  'dev-notochord': 'The notochord is a midline mesodermal rod lying ventral to the neural tube in the early embryo.',
  'dev-somites': 'Somites are paired blocks of paraxial mesoderm positioned on either side of the neural tube.',
  'dev-embryonic-folding': 'Embryonic folding reshapes the flat disc into a more cylindrical body and encloses part of the yolk sac as the primitive gut.',
  'dev-primitive-gut': 'The primitive gut is the internal endoderm-lined tube formed as embryonic folding encloses part of the yolk sac.',
  'dev-amnion': 'The amnion is the extraembryonic membrane that surrounds the developing embryo.',
  'dev-chorion': 'The chorion is the outer extraembryonic membrane that contributes to the fetal side of the placenta.',
  'dev-chorionic-villi': 'Chorionic villi are projections of fetal chorion that meet maternal endometrial tissue at the placental interface.',
  'dev-placenta': 'The placenta is the maternal-fetal interface at the uterine wall, formed where chorionic villi meet endometrial tissue.',
  'dev-umbilical-cord': 'The umbilical cord connects the fetus to the placenta and contains two umbilical arteries and one umbilical vein.',

  interphase: 'Interphase is the part of the cell cycle between mitoses, comprising G1, S, and G2.',
  g1: 'G1 is the first growth phase of interphase, before DNA is replicated in S phase.',
  's-phase': 'S phase is the part of interphase when each chromosome’s DNA is replicated.',
  g2: 'G2 is the second growth phase of interphase, after DNA replication and before mitosis.',
  'sister-chromatids': 'Sister chromatids are the two identical copies of a replicated chromosome joined at its centromere.',
  centromere: 'The centromere is the chromosome region where its two sister chromatids remain joined.',
  mitosis: 'Mitosis is nuclear division that separates duplicated chromosomes through prophase, metaphase, anaphase, and telophase.',
  cytokinesis: 'Cytokinesis is division of the cytoplasm, distinct from the chromosome separation of mitosis.',
  prophase: 'Prophase is the first mitotic stage, when chromatin condenses into chromosomes and the spindle begins to form.',
  metaphase: 'Metaphase is the mitotic stage when chromosomes align at the metaphase plate near the cell center.',
  anaphase: 'Anaphase is the mitotic stage when sister chromatids separate and move toward opposite cell poles.',
  telophase: 'Telophase is the final mitotic stage, when nuclear envelopes reform around the separated chromosome sets.',
  'plasma-membrane': 'The plasma membrane is the cell’s phospholipid-bilayer boundary separating the interior from its surroundings.',
  mitochondrion: 'A mitochondrion is a cell organelle that supports cellular respiration and energy production.',
  'smooth-er': 'The smooth endoplasmic reticulum is an internal membrane network associated with lipid production, carbohydrate metabolism, and detoxification.',
  nucleus: 'The nucleus is the chromatin-containing compartment enclosed by the nuclear envelope.',
  'nuclear-envelope-cytology': 'The nuclear envelope is the membrane boundary around the nucleus, separating it from the surrounding cytoplasm.',
  nucleolus: 'The nucleolus is a region inside the nucleus associated with ribosomal-subunit assembly.',
  chromatin: 'Chromatin is the DNA-containing material inside the nucleus that condenses into visible chromosomes during prophase.',
  centrosome: 'The centrosome is a cytoplasmic region that organizes the spindle as its components separate during cell division.',
  cytosol: 'Cytosol is the fluid interior of the cell inside the plasma membrane and outside the nucleus.',
  'golgi-apparatus': 'The Golgi apparatus is a membrane-bound organelle in the cytoplasm that modifies and packages cell products.',
} as const;