/**
 * Quick definitions for the joints, muscular, and nervous-system structures
 * already present in the verified canonical catalog. The catalog remains the
 * source for names, aliases, modules, and categories; these keys are IDs only.
 */
export default {
  // Joints & ligaments — OpenStax Anatomy & Physiology, chapter 9.
  'fibrous-joint': 'A fibrous joint joins bones with dense connective tissue and has no joint cavity.',
  'suture-joint': 'A suture is a tight fibrous joint between adjacent bones of the skull.',
  gomphosis: 'A gomphosis is the fibrous joint anchoring a tooth root in its alveolar socket.',
  syndesmosis: 'A syndesmosis joins two bones by a ligament or interosseous membrane, as between the tibia and fibula.',
  'cartilaginous-joint': 'A cartilaginous joint joins bones with cartilage and has no joint cavity.',
  synchondrosis: 'A synchondrosis joins bones with hyaline cartilage, as at an epiphyseal plate or first rib.',
  symphysis: 'A symphysis joins bones at a fibrocartilage pad, as between vertebral bodies or the pubic bones.',
  'synovial-joint': 'A synovial joint has a fluid-containing cavity between cartilage-covered bone ends enclosed by a capsule.',
  'articular-cartilage': 'Articular cartilage is the smooth hyaline cartilage covering the ends of bones within a synovial joint.',
  'joint-cavity': 'The joint cavity is the narrow, fluid-containing space between the articular surfaces of a synovial joint.',
  'fibrous-capsule': 'The fibrous capsule is the tough outer layer enclosing a synovial joint cavity.',
  'synovial-membrane': 'The synovial membrane lines the inner surface of a joint capsule but does not cover the articular cartilage.',
  'synovial-fluid': 'Synovial fluid fills a joint cavity and lubricates the opposing articular surfaces.',
  ligament: 'A ligament is a band of dense connective tissue that connects bone to bone across a joint.',
  tmj: 'The temporomandibular joint connects the mandibular condyle to the temporal bone and contains an articular disc.',
  'shoulder-joint': 'The shoulder joint is the glenohumeral articulation of the humeral head with the shallow glenoid cavity of the scapula.',
  'elbow-joint': 'The elbow joint is the humeroulnar and humeroradial articulation between the distal humerus and proximal ulna and radius.',
  'proximal-radioulnar-joint': 'The proximal radioulnar joint surrounds the radial head with the radial notch of the ulna and permits forearm rotation.',
  'distal-radioulnar-joint': 'The distal radioulnar joint is where the distal radius rotates against the head of the ulna near the wrist.',
  'wrist-joint': 'The wrist joint links the distal radius with the proximal carpal row, especially the scaphoid and lunate.',
  'hip-joint': 'The hip joint is the deep articulation of the femoral head with the acetabulum of the pelvic bone.',
  'knee-joint': 'The knee joint brings the femoral condyles and patella into articulation with the tibial plateau.',
  'ankle-joint': 'The ankle joint is where the talus fits within the mortise formed by the distal tibia and fibula.',
  'atlantoaxial-joint': 'The atlantoaxial joint between C1 and C2 pivots around the dens of the axis.',
  'intervertebral-joints': 'Intervertebral joints link adjacent vertebrae through fibrocartilaginous discs between their bodies and facet joints between their articular processes.',
  acl: 'The anterior cruciate ligament crosses the knee from the anterior tibia to the femur and resists forward translation of the tibia.',
  pcl: 'The posterior cruciate ligament crosses the knee from the posterior tibia to the femur and resists backward translation of the tibia.',
  mcl: 'The medial collateral ligament reinforces the inner side of the knee, spanning the femur and tibia.',
  lcl: 'The lateral collateral ligament reinforces the outer side of the knee, spanning the femur and head of the fibula.',
  'deltoid-ligament': 'The deltoid ligament fans from the medial malleolus across the inner ankle to the tarsal bones.',
  'acromioclavicular-ligament': 'The acromioclavicular ligament spans the acromion and clavicle at the top of the shoulder.',
  'glenohumeral-ligaments': 'The glenohumeral ligaments are thickenings of the anterior shoulder-joint capsule between the glenoid region and humerus.',
  'annular-ligament': 'The annular ligament encircles the radial head and holds it against the ulna at the proximal radioulnar joint.',
  'interosseous-membrane': 'The interosseous membrane is a fibrous sheet connecting the shafts of the radius and ulna.',
  'patellar-ligament': 'The patellar ligament continues from the patella to the tibial tuberosity on the front of the knee.',
  'iliofemoral-ligament': 'The iliofemoral ligament reinforces the front of the hip capsule between the ilium and proximal femur.',

  // Muscular system — OpenStax Anatomy & Physiology, chapter 11 and its
  // verified regional muscle plates and lesson-linked attachments.
  frontalis: 'Frontalis is the anterior belly of the occipitofrontalis, lying over the frontal scalp.',
  'orbicularis-oculi': 'Orbicularis oculi is the circular muscle surrounding the orbit and eyelids.',
  'orbicularis-oris': 'Orbicularis oris encircles the opening of the mouth within the lips.',
  buccinator: 'Buccinator forms the muscular wall of the cheek, lateral to the oral cavity.',
  platysma: 'Platysma is a thin, superficial sheet extending from the upper chest across the front of the neck to the lower face.',
  'sternocleidomastoid': 'Sternocleidomastoid is the oblique neck muscle running from the sternum and clavicle to the mastoid process.',
  scalenes: 'The scalene muscles lie deep along the side of the neck, running from cervical vertebrae to the first two ribs.',
  trapezius: 'Trapezius is the broad superficial upper-back muscle spanning the neck and spine to the clavicle and scapula.',
  'latissimus-dorsi': 'Latissimus dorsi is a broad lower-back muscle whose fibers pass upward to the humerus.',
  'rhomboid-major': 'Rhomboid major runs from the upper thoracic spinous processes to the medial border of the scapula below its spine.',
  'rhomboid-minor': 'Rhomboid minor runs from the lower cervical and upper thoracic vertebrae to the medial scapular border at the level of the spine.',
  'levator-scapulae': 'Levator scapulae descends from the upper cervical transverse processes to the superior medial border of the scapula.',
  'erector-spinae': 'Erector spinae is a longitudinal muscle group running in columns on either side of the vertebral column.',
  multifidus: 'Multifidus is a deep back muscle group with short bundles spanning several vertebrae beside the spinous processes.',
  'pectoralis-major': 'Pectoralis major is the large superficial chest muscle running from the clavicle and sternum toward the humerus.',
  'pectoralis-minor': 'Pectoralis minor lies deep to pectoralis major and runs from the upper ribs to the coracoid process of the scapula.',
  'serratus-anterior': 'Serratus anterior lies on the lateral ribs and attaches to the anterior surface of the medial scapular border.',
  intercostals: 'Intercostal muscles occupy the spaces between adjacent ribs.',
  diaphragm: 'The diaphragm is the domed skeletal-muscle partition between the thoracic and abdominal cavities, inserting into a central tendon.',
  deltoid: 'Deltoid forms the shoulder cap from the clavicle and scapula to the deltoid tuberosity of the humerus.',
  supraspinatus: 'Supraspinatus runs from the supraspinous fossa of the scapula to the greater tubercle of the humerus as part of the rotator cuff.',
  infraspinatus: 'Infraspinatus runs from the infraspinous fossa of the scapula to the greater tubercle of the humerus as part of the rotator cuff.',
  'teres-minor': 'Teres minor runs along the lateral border of the scapula to the greater tubercle of the humerus as part of the rotator cuff.',
  subscapularis: 'Subscapularis covers the anterior surface of the scapula and attaches to the lesser tubercle of the humerus as part of the rotator cuff.',
  'teres-major': 'Teres major runs from the inferior scapula to the medial side of the humerus and is not part of the rotator cuff.',
  'biceps-brachii': 'Biceps brachii lies on the front of the upper arm, with two scapular heads joining at the radial tuberosity.',
  brachialis: 'Brachialis lies deep to biceps on the anterior arm and attaches the humerus to the ulna across the elbow.',
  coracobrachialis: 'Coracobrachialis runs from the coracoid process into the medial shaft of the humerus.',
  'triceps-brachii': 'Triceps brachii occupies the back of the upper arm and its three heads converge on the olecranon of the ulna.',
  anconeus: 'Anconeus is a small muscle at the posterolateral elbow, running from the lateral epicondyle to the ulna.',
  'pronator-teres': 'Pronator teres crosses the anterior forearm from the medial elbow to the lateral surface of the radius.',
  supinator: 'Supinator wraps around the proximal radius near the elbow on the deep lateral forearm.',
  'flexor-carpi-radialis': 'Flexor carpi radialis runs along the anterior forearm to the bases of the second and third metacarpals.',
  'extensor-carpi-radialis': 'Extensor carpi radialis runs along the lateral posterior forearm to the bases of the second and third metacarpals.',
  'rectus-abdominis': 'Rectus abdominis is the paired vertical muscle beside the midline, extending from the pubis to the costal cartilages and xiphoid process.',
  'external-oblique': 'External oblique is the superficial flat muscle of the lateral abdominal wall, with fibers running inferomedially.',
  'internal-oblique': 'Internal oblique lies deep to external oblique in the lateral abdominal wall, with fibers running superomedially.',
  'transversus-abdominis': 'Transversus abdominis is the deepest flat muscle of the lateral abdominal wall, with fibers running mainly horizontally.',
  'quadratus-lumborum': 'Quadratus lumborum lies in the posterior abdominal wall between the iliac crest, lumbar vertebrae, and twelfth rib.',
  'gluteus-maximus': 'Gluteus maximus is the large superficial buttock muscle extending from the posterior pelvis to the femur and iliotibial tract.',
  'gluteus-medius': 'Gluteus medius lies on the lateral ilium and attaches to the greater trochanter of the femur.',
  'tensor-fasciae-latae': 'Tensor fasciae latae lies at the anterolateral hip and continues into the iliotibial tract along the thigh.',
  iliopsoas: 'Iliopsoas combines psoas major and iliacus as they descend through the hip to the lesser trochanter of the femur.',
  'adductor-longus': 'Adductor longus is a superficial medial-thigh muscle running from the pubis to the linea aspera of the femur.',
  gracilis: 'Gracilis is a long, slender medial-thigh muscle that crosses the knee to attach to the medial proximal tibia.',
  sartorius: 'Sartorius runs obliquely across the anterior thigh from the anterior superior iliac spine to the medial proximal tibia.',
  'rectus-femoris': 'Rectus femoris is the superficial central quadriceps muscle crossing the hip and knee from the ilium to the patella.',
  'vastus-lateralis': 'Vastus lateralis occupies the outer anterior thigh and joins the quadriceps tendon at the patella.',
  'vastus-medialis': 'Vastus medialis occupies the inner anterior thigh and joins the quadriceps tendon at the patella.',
  'vastus-intermedius': 'Vastus intermedius lies deep to rectus femoris on the anterior femur and joins the quadriceps tendon at the patella.',
  'articularis-genus': 'Articularis genus is a small deep anterior-thigh muscle running from the distal femur to the knee-joint capsule.',
  'biceps-femoris': 'Biceps femoris lies on the posterolateral thigh and attaches distally to the head of the fibula.',
  semitendinosus: 'Semitendinosus is a medial hamstring running from the ischial tuberosity to the upper medial tibia.',
  semimembranosus: 'Semimembranosus is the deep medial hamstring running from the ischial tuberosity to the posterior medial tibia.',
  'tibialis-anterior': 'Tibialis anterior runs down the front of the leg from the tibia to the medial foot.',
  'fibularis-longus': 'Fibularis longus descends along the lateral leg and its tendon crosses under the foot to the first metatarsal and medial cuneiform.',
  gastrocnemius: 'Gastrocnemius is the superficial calf muscle with heads from the femur that join the calcaneal tendon.',
  soleus: 'Soleus lies deep to gastrocnemius, running from the tibia and fibula into the calcaneal tendon without crossing the knee.',
  popliteus: 'Popliteus crosses the back of the knee from the lateral femur to the posterior tibia.',
  'abductor-digiti-minimi-hand': 'Abductor digiti minimi lies along the little-finger side of the palm in the hypothenar eminence.',
  'abductor-pollicis-brevis': 'Abductor pollicis brevis is a superficial thenar muscle at the base of the thumb.',
  'flexor-pollicis-brevis': 'Flexor pollicis brevis lies in the thenar eminence and attaches to the proximal phalanx of the thumb.',
  'lumbricals-hand': 'The hand lumbricals run from the flexor digitorum profundus tendons to the extensor expansions of digits two through five.',
  'abductor-hallucis': 'Abductor hallucis runs along the medial border of the sole to the proximal phalanx of the great toe.',
  'flexor-digitorum-brevis-foot': 'Flexor digitorum brevis lies centrally in the sole and sends tendons to the middle phalanges of toes two through five.',
  'abductor-digiti-minimi-foot': 'Abductor digiti minimi runs along the lateral border of the sole to the fifth toe.',
  'extensor-digitorum-brevis-foot': 'Extensor digitorum brevis lies on the dorsum of the foot and sends tendons toward toes two through four.',
  'levator-ani': 'Levator ani is the broad pelvic-floor muscle group spanning the pubis and pelvic fascia to support pelvic organs.',
  pubococcygeus: 'Pubococcygeus is the medial part of levator ani, running from the pubis toward the coccyx and pelvic-floor midline.',
  iliococcygeus: 'Iliococcygeus is the posterolateral part of levator ani, spanning the tendinous arch and ischial spine to the coccyx.',
  'tibialis-posterior': 'Tibialis posterior is the deep posterior-leg muscle whose tendon passes behind the medial malleolus to the tarsal region.',
  masseter: 'Masseter is the thick chewing muscle lying over the mandibular ramus, from the zygomatic arch to the lateral mandible.',
  temporalis: 'Temporalis is the fan-shaped muscle over the temporal fossa that descends to the coronoid process of the mandible.',

  // Nervous system — OpenStax Anatomy & Physiology, chapters 12–13.
  cerebrum: 'The cerebrum is the large paired upper part of the brain, formed by two hemispheres surrounding deep nuclei.',
  'frontal-lobe': 'The frontal lobe occupies the anterior part of each cerebral hemisphere, in front of the parietal lobe.',
  'parietal-lobe': 'The parietal lobe occupies the superior and posterior cerebrum, behind the frontal and above the temporal lobe.',
  'temporal-lobe': 'The temporal lobe occupies the lateral, inferior cerebrum beneath the lateral sulcus.',
  'occipital-lobe': 'The occipital lobe forms the posterior pole of each cerebral hemisphere.',
  insula: 'The insula is a region of cerebral cortex buried deep within the lateral sulcus beneath surrounding lobes.',
  'corpus-callosum': 'The corpus callosum is a broad band of white matter crossing the midline to connect the cerebral hemispheres.',
  thalamus: 'The paired thalami lie on either side of the third ventricle, superior to the hypothalamus, within the diencephalon.',
  hypothalamus: 'The hypothalamus lies below the thalamus and forms the floor and lower walls of the third ventricle.',
  epithalamus: 'The epithalamus is the posterior-superior part of the diencephalon, bordering the roof of the third ventricle.',
  'basal-nuclei': 'The basal nuclei are groups of gray matter deep within the cerebral hemispheres, including the caudate nucleus, putamen, and globus pallidus.',
  'caudate-nucleus': 'The caudate nucleus is a C-shaped basal nucleus that follows the curve of the lateral ventricle.',
  putamen: 'The putamen is a basal nucleus positioned lateral to the globus pallidus and medial to the insular region.',
  'globus-pallidus': 'The globus pallidus is the medial portion of the lentiform nucleus, lying just medial to the putamen.',
  'lateral-ventricle': 'Each lateral ventricle is a C-shaped fluid space within a cerebral hemisphere.',
  'third-ventricle': 'The third ventricle is the midline fluid space between the thalami in the diencephalon.',
  'cerebral-aqueduct': 'The cerebral aqueduct is the narrow channel through the midbrain that connects the third and fourth ventricles.',
  'fourth-ventricle': 'The fourth ventricle lies between the pons and medulla anteriorly and the cerebellum posteriorly.',
  'choroid-plexus': 'Choroid plexus is vascular tissue within the brain ventricles that produces cerebrospinal fluid.',
  meninges: 'The meninges are the three connective-tissue membranes surrounding the brain and spinal cord.',
  'dura-mater': 'Dura mater is the tough outer meningeal layer surrounding the brain and spinal cord.',
  'arachnoid-mater': 'Arachnoid mater is the middle meningeal layer, deep to dura and separated from pia by the cerebrospinal-fluid-filled subarachnoid space.',
  'pia-mater': 'Pia mater is the delicate inner meningeal layer that closely follows the contours of the brain and spinal cord.',
  'cerebrospinal-fluid': 'Cerebrospinal fluid fills the brain ventricles and subarachnoid space around the brain and spinal cord.',
  midbrain: 'The midbrain is the superior part of the brainstem, between the diencephalon and pons and surrounding the cerebral aqueduct.',
  pons: 'The pons is the middle part of the brainstem, between the midbrain and medulla and anterior to the cerebellum.',
  'medulla-oblongata': 'The medulla oblongata is the inferior brainstem, continuous below with the spinal cord and above with the pons.',
  cerebellum: 'The cerebellum lies behind the brainstem in the posterior cranial fossa and has two hemispheres joined at the midline.',
  'arbor-vitae': 'Arbor vitae is the branching white matter visible within the cerebellum.',
  'spinal-cord': 'The spinal cord is the central nervous system tissue extending from the medulla through the vertebral canal.',
  'central-canal': 'The central canal is the small cerebrospinal-fluid-filled passage through the center of the spinal cord.',
  'dorsal-horn': 'The dorsal horn is the posterior gray-matter region of the spinal cord, where sensory input enters local circuits.',
  'ventral-horn': 'The ventral horn is the anterior gray-matter region of the spinal cord that contains somatic motor-neuron cell bodies.',
  'dorsal-root': 'The dorsal root carries sensory axons from a spinal nerve toward the spinal cord.',
  'ventral-root': 'The ventral root carries motor axons away from the spinal cord to join a spinal nerve.',
  'dorsal-root-ganglion': 'The dorsal root ganglion is the swelling on a dorsal root that contains sensory-neuron cell bodies.',
  'dorsal-ramus': 'The dorsal ramus is the posterior branch of a spinal nerve supplying the back.',
  'ventral-ramus': 'The ventral ramus is the larger anterior branch of a spinal nerve, supplying the front and sides of the trunk and forming limb plexuses.',
  'corticospinal-tract': 'The corticospinal tract is a descending central nervous system pathway from the cerebral cortex through the brainstem into the spinal cord.',
  'spinothalamic-tract': 'The spinothalamic tract is an ascending spinal-cord pathway carrying pain and temperature information toward the thalamus.',
  'dorsal-column': 'The dorsal column is the posterior white-matter pathway of the spinal cord carrying discriminative touch and proprioceptive information.',
  'cranial-nerve-i': 'The olfactory nerve (cranial nerve I) carries smell information from the nasal cavity to the forebrain.',
  'cranial-nerve-ii': 'The optic nerve (cranial nerve II) carries visual information from the retina toward the brain.',
  'cranial-nerve-iii': 'The oculomotor nerve (cranial nerve III) leaves the midbrain and supplies most extraocular muscles.',
  'cranial-nerve-iv': 'The trochlear nerve (cranial nerve IV) arises from the dorsal midbrain and supplies the superior oblique muscle of the eye.',
  'cranial-nerve-v': 'The trigeminal nerve (cranial nerve V) emerges from the pons and divides into three major branches serving the face.',
  'cranial-nerve-vi': 'The abducens nerve (cranial nerve VI) leaves the pontomedullary region and supplies the lateral rectus muscle of the eye.',
  'cranial-nerve-vii': 'The facial nerve (cranial nerve VII) exits the brainstem near the pons and supplies muscles of facial expression.',
  'cranial-nerve-viii': 'The vestibulocochlear nerve (cranial nerve VIII) connects the inner ear with the brainstem for hearing and balance.',
  'cranial-nerve-ix': 'The glossopharyngeal nerve (cranial nerve IX) exits the medulla to serve the posterior tongue and pharyngeal region.',
  'cranial-nerve-x': 'The vagus nerve (cranial nerve X) descends from the medulla through the neck into the thorax and abdomen.',
  'cranial-nerve-xi': 'The accessory nerve (cranial nerve XI) descends to the sternocleidomastoid and trapezius muscles.',
  'cranial-nerve-xii': 'The hypoglossal nerve (cranial nerve XII) leaves the medulla and supplies the muscles that move the tongue.',
  'cervical-plexus': 'The cervical plexus is a network formed by the anterior rami of spinal nerves C1–C4 in the neck.',
  'brachial-plexus': 'The brachial plexus is a network of anterior rami C5–T1 that passes from the neck toward the upper limb.',
  'lumbar-plexus': 'The lumbar plexus is a network formed mainly by anterior rami L1–L4 within the psoas major region.',
  'sacral-plexus': 'The sacral plexus lies on the posterior pelvic wall and distributes nerves to the buttock and lower limb.',
  'phrenic-nerve': 'The phrenic nerve descends from the cervical plexus across the anterior scalene muscle to the diaphragm.',
  'median-nerve': 'The median nerve descends from the brachial plexus through the arm and forearm and enters the hand through the carpal tunnel.',
  'ulnar-nerve': 'The ulnar nerve passes behind the medial epicondyle of the humerus before continuing down the medial forearm to the hand.',
  'radial-nerve': 'The radial nerve travels along the posterior arm near the radial groove and continues into the extensor side of the forearm.',
  'sciatic-nerve': 'The sciatic nerve exits the pelvis into the posterior thigh and divides into the major nerves of the leg.',
  'femoral-nerve': 'The femoral nerve passes from the lumbar plexus beneath the inguinal ligament into the anterior thigh.',
} as const;