/**
 * Source-backed quick definitions keyed only by canonical catalog structure ID.
 * Names, accepted aliases, module context, and provenance remain in the catalog.
 */
export default {
  'male-reproductive-testis': 'The testis is the male gonad housed in the scrotum.',
  'male-reproductive-tunica-albuginea': 'The tunica albuginea is the fibrous capsule of the testis, whose septa divide the organ into lobules.',
  'male-reproductive-tunica-vaginalis': 'The tunica vaginalis is the serous covering on the outer surface of the testis.',
  'male-reproductive-testicular-lobule': 'A testicular lobule is a compartment formed by septa from the tunica albuginea and contains seminiferous tubules.',
  'male-reproductive-testicular-mediastinum': 'The testicular mediastinum is the thickened region where seminiferous tubules converge toward the rete testis.',
  'male-reproductive-seminiferous-tubule': 'A seminiferous tubule is a coiled testicular tubule lined by developing germ cells.',
  'male-reproductive-sertoli-cell': 'A Sertoli cell is a supporting cell within the seminiferous epithelium.',
  'male-reproductive-leydig-cell': 'A Leydig cell lies in the interstitial tissue between seminiferous tubules.',
  'male-reproductive-rete-testis': 'The rete testis is a collecting network in the testicular mediastinum that receives fluid from seminiferous tubules.',
  'male-reproductive-efferent-ductule': 'An efferent ductule carries material from the rete testis into the head of the epididymis.',
  'male-reproductive-epididymis': 'The epididymis is a long coiled duct along the posterior testis, extending from head to tail.',
  'male-reproductive-head-of-epididymis': 'The head of the epididymis is its superior region, where efferent ductules enter.',
  'male-reproductive-body-of-epididymis': 'The body of the epididymis is the middle portion of the coiled duct along the posterior testis.',
  'male-reproductive-tail-of-epididymis': 'The tail of the epididymis is its inferior end and continues as the ductus deferens.',
  'male-reproductive-ductus-deferens': 'The ductus deferens is a muscular duct that continues from the epididymal tail toward the ejaculatory duct.',
  'male-reproductive-ampulla-of-ductus-deferens': 'The ampulla of the ductus deferens is its enlarged terminal portion near the junction with the seminal vesicle duct.',
  'male-reproductive-ejaculatory-duct': 'The ejaculatory duct is formed by the ductus deferens and seminal vesicle duct and passes through the prostate to the urethra.',
  'male-reproductive-urethra': 'The urethra is the passage from the bladder to the exterior and also carries reproductive fluid through the penis.',
  'male-reproductive-seminal-vesicle': 'A seminal vesicle is a gland posterior to the bladder whose duct joins the ductus deferens.',
  'male-reproductive-prostate-gland': 'The prostate gland lies inferior to the bladder and surrounds the prostatic urethra.',
  'male-reproductive-bulbourethral-gland': 'A bulbourethral gland lies inferior to the prostate beside the proximal urethra and opens into the urethral passage.',
  'male-reproductive-penis': 'The penis is the external organ containing the spongy urethra and erectile bodies.',
  'male-reproductive-root-of-penis': 'The root of the penis is its fixed proximal portion attached within the perineum.',
  'male-reproductive-body-of-penis': 'The body of the penis is its shaft between the fixed root and the distal glans.',
  'male-reproductive-glans-penis': 'The glans penis is the expanded distal end of the corpus spongiosum.',
  'male-reproductive-prepuce': 'The prepuce is a fold of skin that covers the glans penis.',
  'male-reproductive-scrotum': 'The scrotum is the external skin sac that contains the testes.',
  'male-reproductive-spermatic-cord': 'The spermatic cord is the bundled support extending between the abdominal wall and testis, carrying the ductus deferens and vessels.',
  'male-reproductive-dartos-muscle': 'Dartos is smooth muscle in the scrotal wall beneath its skin.',
  'male-reproductive-cremaster-muscle': 'The cremaster is skeletal muscle associated with the spermatic cord and testis.',
  'male-reproductive-bulbospongiosus-muscle': 'The bulbospongiosus overlies the bulb of the penis at its proximal root.',
  'male-reproductive-pampiniform-plexus': 'The pampiniform plexus is a venous network in the spermatic cord surrounding the testicular artery.',
  'male-reproductive-spermatogonium': 'A spermatogonium is an early germ cell at the basal side of the seminiferous epithelium.',
  'male-reproductive-primary-spermatocyte': 'A primary spermatocyte is a germ cell in the seminiferous epithelium that enters the first meiotic division.',
  'male-reproductive-secondary-spermatocyte': 'A secondary spermatocyte is the short-lived product of the first meiotic division, before the second division.',
  'male-reproductive-spermatid': 'A spermatid is the haploid germ-cell stage that differentiates into a spermatozoon near the seminiferous-tubule lumen.',
  'male-reproductive-spermatozoon': 'A spermatozoon is a mature male germ cell with a head and a motile flagellum.',
  'male-reproductive-acrosome': 'The acrosome is the cap over the spermatozoon head.',
  'male-reproductive-flagellum': 'The flagellum is the tail-like structure that propels a spermatozoon.',
  'male-reproductive-blood-testis-barrier': 'The blood-testis barrier is formed by tight junctions between Sertoli cells in the seminiferous epithelium.',
  'male-reproductive-interstitial-tissue': 'Interstitial tissue is the connective tissue between seminiferous tubules where Leydig cells are found.',
  'male-reproductive-corpus-cavernosum': 'A corpus cavernosum is one of the paired dorsal erectile bodies of the penis.',
  'male-reproductive-corpus-spongiosum': 'The corpus spongiosum is the erectile body that surrounds the spongy urethra and expands distally into the glans.',
  'male-reproductive-seminal-plasma': 'Seminal plasma is the fluid portion of semen contributed by the accessory glands.',
  'male-reproductive-prostatic-urethra': 'The prostatic urethra is the segment of urethra that passes through the prostate.',
  'male-reproductive-spongy-urethra': 'The spongy urethra is the urethral segment enclosed by the corpus spongiosum in the penis.',
  'male-reproductive-peritubular-myoid-cell': 'A peritubular myoid cell is a contractile cell surrounding a seminiferous tubule.',
  'female-reproductive-ovary': 'The ovary is the female gonad containing follicles, located lateral to the uterus.',
  'female-reproductive-ovarian-cortex': 'The ovarian cortex is the outer region of the ovary where follicles are concentrated.',
  'female-reproductive-ovarian-medulla': 'The ovarian medulla is the inner region of the ovary containing connective tissue and vessels.',
  'female-reproductive-ovarian-hilum': 'The ovarian hilum is the entry region for vessels at the medulla of the ovary.',
  'female-reproductive-ovarian-follicle': 'An ovarian follicle is an oocyte and its surrounding support cells within the ovarian cortex.',
  'female-reproductive-primordial-follicle': 'A primordial follicle is an early ovarian follicle with an oocyte surrounded by a single layer of flattened follicular cells.',
  'female-reproductive-primary-follicle': 'A primary follicle is an early growing ovarian follicle with cuboidal granulosa cells around its oocyte.',
  'female-reproductive-secondary-follicle': 'A secondary follicle is a developing ovarian follicle with multiple layers of granulosa cells around its oocyte.',
  'female-reproductive-antral-follicle': 'An antral follicle is an ovarian follicle containing a fluid-filled cavity called an antrum.',
  'female-reproductive-mature-follicle': 'A mature follicle is the large, fully developed ovarian follicle with a prominent antrum before ovulation.',
  'female-reproductive-corpus-luteum': 'The corpus luteum is the post-ovulatory ovarian structure formed from the ruptured follicle.',
  'female-reproductive-corpus-albicans': 'The corpus albicans is the fibrous remnant left when a corpus luteum regresses.',
  'female-reproductive-oocyte': 'An oocyte is a female germ cell contained within an ovarian follicle before it is released.',
  'female-reproductive-granulosa-cell': 'A granulosa cell is a follicular cell layer surrounding and supporting the oocyte.',
  'female-reproductive-theca-cell': 'A theca cell belongs to the outer supporting layers that surround the granulosa cells of an ovarian follicle.',
  'female-reproductive-uterine-tube': 'The uterine tube extends from the uterus toward the ovary and carries the oocyte toward the uterine cavity.',
  'female-reproductive-fimbriae': 'Fimbriae are fingerlike projections bordering the ovarian end of the uterine tube.',
  'female-reproductive-infundibulum': 'The infundibulum is the funnel-shaped ovarian end of the uterine tube, bordered by fimbriae.',
  'female-reproductive-ampulla-of-uterine-tube': 'The ampulla is the broad middle region of the uterine tube and a common site of fertilization.',
  'female-reproductive-isthmus-of-uterine-tube': 'The isthmus is the narrow medial portion of the uterine tube approaching the uterus.',
  'female-reproductive-uterus': 'The uterus is a hollow, muscular pelvic organ between the bladder and rectum, continuous inferiorly with the cervix.',
  'female-reproductive-fundus-of-uterus': 'The fundus is the dome-shaped uterine region superior to the openings of the uterine tubes.',
  'female-reproductive-body-of-uterus': 'The body is the main central portion of the uterus between the fundus and cervix.',
  'female-reproductive-cervix': 'The cervix is the narrow inferior part of the uterus that projects into the vagina.',
  'female-reproductive-cervical-canal': 'The cervical canal is the passage within the cervix connecting the uterine cavity to the vagina.',
  'female-reproductive-vagina': 'The vagina is the muscular canal extending from the cervix to the external genital vestibule.',
  'female-reproductive-endometrium': 'The endometrium is the mucosal lining on the inner surface of the uterus.',
  'female-reproductive-stratum-functionale': 'The stratum functionale is the superficial part of the endometrium that is shed during menstruation.',
  'female-reproductive-stratum-basale': 'The stratum basale is the deeper endometrial layer that remains and regenerates the stratum functionale.',
  'female-reproductive-myometrium': 'The myometrium is the thick smooth-muscle layer of the uterine wall between endometrium and perimetrium.',
  'female-reproductive-perimetrium': 'The perimetrium is the outer serosal covering of the uterus.',
  'female-reproductive-uterine-gland': 'A uterine gland is a tubular gland extending through the endometrial mucosa.',
  'female-reproductive-broad-ligament': 'The broad ligament is a double layer of peritoneum extending from the uterus along the sides of the reproductive organs.',
  'female-reproductive-suspensory-ligament-of-ovary': 'The suspensory ligament of the ovary connects the ovary to the lateral pelvic wall and carries ovarian vessels.',
  'female-reproductive-ovarian-ligament': 'The ovarian ligament connects the ovary to the uterus.',
  'female-reproductive-round-ligament': 'The round ligament extends from the uterus through the inguinal canal toward the labia majora.',
  'female-reproductive-mesovarium': 'The mesovarium is the part of the broad ligament that attaches to the ovary.',
  'female-reproductive-vaginal-fornix': 'A vaginal fornix is a recess of the upper vagina surrounding the portion of the cervix that projects into it.',
  'female-reproductive-external-os': 'The external os is the opening of the cervical canal into the vagina.',
  'female-reproductive-internal-os': 'The internal os is the opening of the cervical canal into the uterine cavity.',
  'female-reproductive-vulva': 'The vulva is the collective name for the external female genital structures surrounding the vestibule.',
  'female-reproductive-mons-pubis': 'The mons pubis is the rounded pad of tissue overlying the pubic symphysis.',
  'female-reproductive-labium-majus': 'A labium majus is one of the larger outer skin folds of the vulva.',
  'female-reproductive-labium-minus': 'A labium minus is one of the thinner inner folds bordering the vulvar vestibule.',
  'female-reproductive-clitoris': 'The clitoris is an erectile external genital organ at the anterior junction of the labia minora.',
  'female-reproductive-vestibule': 'The vestibule is the space between the labia minora that contains the urethral and vaginal openings.',
  'female-reproductive-greater-vestibular-gland': 'A greater vestibular gland lies beside the vaginal opening and releases its duct into the vestibule.',
  'female-reproductive-mammary-gland': 'The mammary gland is glandular tissue of the breast organized into lobes and lobules that drain toward the nipple.',
  'female-reproductive-nipple': 'The nipple is the raised projection of the breast where lactiferous ducts open.',
  'female-reproductive-areola': 'The areola is the pigmented area of skin surrounding the nipple.',
  'female-reproductive-mammary-lobule': 'A mammary lobule is a subdivision of mammary gland tissue containing secretory alveoli.',
  'female-reproductive-lactiferous-duct': 'A lactiferous duct carries fluid from mammary lobules toward the nipple.',
  'female-reproductive-lactiferous-sinus': 'A lactiferous sinus is the widened portion of a mammary duct near the nipple.',
  'female-reproductive-fallopian-epithelium': 'Fallopian epithelium is the ciliated lining of the uterine tube.',
  'female-reproductive-ciliated-columnar-cell': 'A ciliated columnar cell is a tall epithelial cell whose apical cilia line the uterine tube.',
  'female-reproductive-nonkeratinized-stratified-squamous-epithelium': 'Nonkeratinized stratified squamous epithelium is the moist, abrasion-resistant lining of the vagina.',
  'female-reproductive-follicular-fluid': 'Follicular fluid fills the antrum of a developing ovarian follicle.',
  'female-reproductive-corona-radiata': 'The corona radiata is the layer of granulosa cells that remains around the oocyte after ovulation.',
  'female-reproductive-zona-pellucida': 'The zona pellucida is the glycoprotein coat surrounding the oocyte.',
  'female-reproductive-theca-interna': 'The theca interna is the inner cellular layer of the ovarian follicle outside the granulosa cells.',
  'female-reproductive-theca-externa': 'The theca externa is the outer connective-tissue layer surrounding the ovarian follicle.',
  'female-reproductive-secretory-endometrium': 'Secretory endometrium is the post-ovulatory uterine lining with glands in a secretory phase.',
  'female-reproductive-proliferative-endometrium': 'Proliferative endometrium is the regenerating uterine lining that rebuilds after menstruation.',
  'female-reproductive-smooth-muscle-of-uterus': 'Smooth muscle of the uterus forms the myometrium in the uterine wall.',
  'female-reproductive-mammary-alveolus': 'A mammary alveolus is a small secretory sac within a mammary lobule that drains into a duct.',
} as const;