/**
 * Source-checked quick definitions keyed by canonical catalog structure ID.
 * Canonical names, accepted aliases, module and category remain in the catalog;
 * do not add term labels or alias records here.
 */
export default {
  // Respiratory System — OpenStax Anatomy & Physiology, chapter 22.
  'respiratory-system-nose': 'The nose is the external respiratory organ surrounding the openings into the nasal cavity.',
  'respiratory-system-nasal-cavity': 'The nasal cavity is the air passage behind the nostrils and above the oral cavity, divided into right and left sides by the septum.',
  'respiratory-system-nasal-septum': 'The nasal septum is the midline wall that separates the right and left nasal cavities.',
  'respiratory-system-nasal-vestibule': 'The nasal vestibule is the skin-lined entrance just inside each nostril.',
  'respiratory-system-nasal-concha': 'A nasal concha is a curved shelf projecting from the lateral wall of the nasal cavity.',
  'respiratory-system-choanae': 'The choanae are the paired posterior openings that connect the nasal cavities to the nasopharynx.',
  'respiratory-system-hard-palate': 'The hard palate is the bony anterior roof of the mouth that separates the oral and nasal cavities.',
  'respiratory-system-soft-palate': 'The soft palate is the movable muscular posterior roof of the mouth, behind the hard palate.',
  'respiratory-system-frontal-sinus': 'The frontal sinus is an air-filled cavity within the frontal bone above the nasal cavity.',
  'respiratory-system-maxillary-sinus': 'The maxillary sinus is an air-filled cavity within each maxilla, lateral to the nasal cavity.',
  'respiratory-system-ethmoidal-sinus': 'The ethmoidal sinuses are small air-filled spaces within the ethmoid bone between the nasal cavity and the orbits.',
  'respiratory-system-sphenoidal-sinus': 'The sphenoidal sinus is an air-filled cavity within the sphenoid bone posterior to the nasal cavity.',
  'respiratory-system-nasopharynx': 'The nasopharynx is the upper pharyngeal region behind the nasal cavity and above the soft palate.',
  'respiratory-system-oropharynx': 'The oropharynx is the pharyngeal region behind the oral cavity, extending from the soft palate toward the epiglottis.',
  'respiratory-system-laryngopharynx': 'The laryngopharynx is the inferior pharyngeal region behind the larynx that continues into the esophagus.',
  'respiratory-system-larynx': 'The larynx is the cartilaginous airway between the laryngopharynx and the trachea.',
  'respiratory-system-epiglottis': 'The epiglottis is an elastic cartilage at the entrance to the larynx that folds over the laryngeal inlet during swallowing.',
  'respiratory-system-laryngeal-inlet': 'The laryngeal inlet is the opening from the laryngopharynx into the larynx, bordered anteriorly by the epiglottis.',
  'respiratory-system-laryngeal-vestibule': 'The laryngeal vestibule is the upper part of the laryngeal cavity between its inlet and the vestibular folds.',
  'respiratory-system-glottis': 'The glottis is the laryngeal unit formed by the true vocal folds and the opening between them.',
  'respiratory-system-rima-glottidis': 'The rima glottidis is the opening between the right and left true vocal folds.',
  'respiratory-system-thyroid-cartilage': 'The thyroid cartilage is the large shield-shaped cartilage forming the anterior wall of the larynx.',
  'respiratory-system-cricoid-cartilage': 'The cricoid cartilage is the complete ring of cartilage at the inferior end of the larynx, just above the trachea.',
  'respiratory-system-arytenoid-cartilage': 'The paired arytenoid cartilages sit on the posterior cricoid and anchor the vocal folds.',
  'respiratory-system-vocal-folds': 'The vocal folds are the paired true folds within the larynx that border the rima glottidis.',
  'respiratory-system-vestibular-folds': 'The vestibular folds are the paired superior folds in the larynx, above the true vocal folds.',
  'respiratory-system-trachea': 'The trachea is the conducting airway descending from the larynx to its division into the main bronchi.',
  'respiratory-system-carina': 'The carina is the internal ridge at the point where the trachea divides into the right and left main bronchi.',
  'respiratory-system-trachealis-muscle': 'The trachealis is smooth muscle spanning the posterior gap in the tracheal cartilage rings.',
  'respiratory-system-right-main-bronchus': 'The right main bronchus is the first large airway branch from the trachea that enters the right lung.',
  'respiratory-system-left-main-bronchus': 'The left main bronchus is the first large airway branch from the trachea that enters the left lung.',
  'respiratory-system-lobar-bronchus': 'A lobar bronchus branches from a main bronchus and supplies one lobe of a lung.',
  'respiratory-system-segmental-bronchus': 'A segmental bronchus branches from a lobar bronchus and supplies a bronchopulmonary segment.',
  'respiratory-system-bronchiole': 'A bronchiole is a small conducting airway within the lungs whose wall lacks the cartilage plates found in bronchi.',
  'respiratory-system-terminal-bronchiole': 'A terminal bronchiole is the last conducting airway before the respiratory bronchioles begin.',
  'respiratory-system-right-lung': 'The right lung occupies the right thoracic cavity and is divided into superior, middle, and inferior lobes.',
  'respiratory-system-left-lung': 'The left lung occupies the left thoracic cavity and has superior and inferior lobes plus a cardiac notch.',
  'respiratory-system-superior-lobe': 'The superior lobe is the uppermost lobe of each lung, above its oblique fissure.',
  'respiratory-system-middle-lobe': 'The middle lobe is the right lung lobe between the horizontal and oblique fissures.',
  'respiratory-system-inferior-lobe': 'The inferior lobe is the lower lung lobe separated from the upper lobes by an oblique fissure.',
  'respiratory-system-cardiac-notch': 'The cardiac notch is the indentation in the anterior border of the left lung that accommodates the heart.',
  'respiratory-system-oblique-fissure': 'The oblique fissure is the slanted cleft that separates the inferior lobe from the upper lobe or lobes of a lung.',
  'respiratory-system-horizontal-fissure': 'The horizontal fissure is the cleft in the right lung that separates its superior and middle lobes.',
  'respiratory-system-hilum-of-lung': 'The hilum of a lung is the medial surface gateway through which structures of the lung root pass.',
  'respiratory-system-root-of-lung': 'The root of a lung is the bundle of bronchi, vessels, nerves, and lymphatics entering or leaving at its hilum.',
  'respiratory-system-visceral-pleura': 'The visceral pleura is the serous membrane that adheres directly to the surface of the lung.',
  'respiratory-system-parietal-pleura': 'The parietal pleura is the serous membrane lining the inner thoracic wall and diaphragm.',
  'respiratory-system-pleural-cavity': 'The pleural cavity is the potential space between the visceral and parietal pleura.',
  'respiratory-system-diaphragm': 'The diaphragm is the broad skeletal muscle forming the floor of the thoracic cavity and the boundary with the abdomen.',
  'respiratory-system-respiratory-bronchiole': 'A respiratory bronchiole is an airway with alveolar outpouchings that marks the transition from conducting passages to the respiratory zone.',
  'respiratory-system-alveolar-duct': 'An alveolar duct is a small passage lined by openings into alveoli that leads toward an alveolar sac.',
  'respiratory-system-alveolar-sac': 'An alveolar sac is a cluster of alveoli opening from the end of an alveolar duct.',
  'respiratory-system-alveolus': 'An alveolus is a small air-filled sac in the lung whose thin wall is closely associated with pulmonary capillaries.',
  'respiratory-system-alveolar-septum': 'An alveolar septum is the thin wall between neighboring alveoli that contains pulmonary capillaries.',
  'respiratory-system-type-i-pneumocyte': 'A type I pneumocyte is a thin squamous alveolar cell that forms most of the gas-exchange lining.',
  'respiratory-system-type-ii-pneumocyte': 'A type II pneumocyte is a cuboidal alveolar cell within the alveolar lining that produces surfactant.',
  'respiratory-system-alveolar-macrophage': 'An alveolar macrophage is an immune cell found within alveoli and other air spaces of the lungs.',
  'respiratory-system-respiratory-membrane': 'The respiratory membrane is the thin interface between alveolar air and blood in the adjacent pulmonary capillary.',
  'respiratory-system-pulmonary-capillary': 'A pulmonary capillary is a small blood vessel running through alveolar septa beside the air spaces.',
  'respiratory-system-ciliated-pseudostratified-epithelium': 'Ciliated pseudostratified epithelium is the airway lining, with cilia and goblet cells, characteristic of the trachea.',
  'respiratory-system-goblet-cell': 'A goblet cell is a mucus-secreting epithelial cell found among the ciliated cells lining conducting airways.',
  'respiratory-system-surfactant': 'Surfactant is the material secreted by type II pneumocytes that coats the alveolar surface.',
  'respiratory-system-smooth-muscle-of-airway': 'Airway smooth muscle is the muscle layer in airway walls, especially prominent around bronchioles.',
  'respiratory-system-elastic-fiber': 'An elastic fiber is connective-tissue material found in lung walls and alveolar septa that permits stretch and recoil.',

  // Digestive System — OpenStax Anatomy & Physiology, chapter 23.
  'digestive-system-mouth': 'The mouth is the oral cavity where the alimentary canal begins, bounded by the lips, cheeks, palate, and floor.',
  'digestive-system-tongue': 'The tongue is a mobile muscular organ on the floor of the oral cavity, inside the tooth arches.',
  'digestive-system-hard-palate': 'The hard palate is the bony anterior roof of the mouth that separates the oral and nasal cavities.',
  'digestive-system-soft-palate': 'The soft palate is the muscular posterior roof of the mouth, behind the hard palate.',
  'digestive-system-teeth': 'The teeth are mineralized structures anchored in the alveolar processes of the maxillae and mandible.',
  'digestive-system-parotid-gland': 'The parotid gland is a large salivary gland anterior and inferior to the ear, with a duct opening into the cheek.',
  'digestive-system-submandibular-gland': 'The submandibular gland lies beneath the mandible and drains by a duct into the floor of the mouth.',
  'digestive-system-sublingual-gland': 'The sublingual gland lies beneath the tongue in the floor of the oral cavity.',
  'digestive-system-sublingual-duct': 'A sublingual duct is a small salivary passage that opens into the floor of the mouth beside the tongue.',
  'digestive-system-pharynx': 'The pharynx is the muscular passage behind the nasal and oral cavities that continues inferiorly toward the larynx and esophagus.',
  'digestive-system-esophagus': 'The esophagus is the muscular tube carrying the alimentary passage from the pharynx through the thorax to the stomach.',
  'digestive-system-stomach': 'The stomach is the expanded alimentary-canal organ between the esophagus and duodenum, with cardia, fundus, body, and pyloric region.',
  'digestive-system-cardia': 'The cardia is the stomach region surrounding the entry from the esophagus.',
  'digestive-system-fundus': 'The fundus is the domed superior part of the stomach above and to the left of the esophageal entry.',
  'digestive-system-body-of-stomach': 'The body is the broad central region of the stomach between the fundus and pyloric region.',
  'digestive-system-pyloric-antrum': 'The pyloric antrum is the wider distal stomach region that narrows toward the pyloric canal.',
  'digestive-system-pylorus': 'The pylorus is the distal stomach region leading into the duodenum.',
  'digestive-system-pyloric-canal': 'The pyloric canal is the narrow distal stomach passage between the pyloric antrum and pyloric sphincter.',
  'digestive-system-pyloric-sphincter': 'The pyloric sphincter is the muscular outlet at the junction of the stomach and duodenum.',
  'digestive-system-rugae': 'Rugae are folds of the stomach’s mucosa and submucosa that flatten as the stomach expands.',
  'digestive-system-duodenum': 'The duodenum is the first, C-shaped segment of the small intestine, immediately beyond the pyloric sphincter.',
  'digestive-system-jejunum': 'The jejunum is the middle segment of the small intestine between the duodenum and ileum.',
  'digestive-system-ileum': 'The ileum is the distal segment of the small intestine that meets the cecum at the ileocecal valve.',
  'digestive-system-ileocecal-valve': 'The ileocecal valve marks the junction where the ileum opens into the cecum.',
  'digestive-system-villi': 'Villi are fingerlike projections of the small-intestinal mucosa that extend into the lumen.',
  'digestive-system-microvilli': 'Microvilli are microscopic projections from the apical surface of enterocytes that form the brush border.',
  'digestive-system-intestinal-crypt': 'An intestinal crypt is a tubular invagination of the small-intestinal mucosa between neighboring villi.',
  'digestive-system-brunner-gland': 'A Brunner gland is a mucus-secreting gland in the submucosa of the duodenum.',
  'digestive-system-enterocyte': 'An enterocyte is an absorptive epithelial cell lining the small intestine, with microvilli on its luminal surface.',
  'digestive-system-goblet-cell': 'A goblet cell is a mucus-secreting epithelial cell interspersed among cells of the intestinal lining.',
  'digestive-system-paneth-cell': 'A Paneth cell is a secretory cell located at the base of a small-intestinal crypt.',
  'digestive-system-cecum': 'The cecum is the pouch at the beginning of the large intestine that receives the ileum.',
  'digestive-system-appendix': 'The appendix is a narrow blind-ended tube projecting from the cecum.',
  'digestive-system-ascending-colon': 'The ascending colon is the large-intestinal segment running superiorly from the cecum along the right side of the abdomen.',
  'digestive-system-transverse-colon': 'The transverse colon crosses the abdomen between the ascending and descending colon.',
  'digestive-system-descending-colon': 'The descending colon runs inferiorly along the left side of the abdomen from the transverse colon.',
  'digestive-system-sigmoid-colon': 'The sigmoid colon is the S-shaped distal colon between the descending colon and rectum.',
  'digestive-system-rectum': 'The rectum is the terminal straight segment of the large intestine immediately superior to the anal canal.',
  'digestive-system-anal-canal': 'The anal canal is the short terminal passage between the rectum and anus.',
  'digestive-system-anus': 'The anus is the external opening at the end of the anal canal.',
  'digestive-system-haustra': 'Haustra are the pouchlike external segments of the colon formed by its shortened wall.',
  'digestive-system-taeniae-coli': 'The taeniae coli are three longitudinal bands of smooth muscle running along the colon.',
  'digestive-system-internal-anal-sphincter': 'The internal anal sphincter is the involuntary smooth-muscle ring around the upper anal canal.',
  'digestive-system-external-anal-sphincter': 'The external anal sphincter is the skeletal-muscle ring surrounding the anal canal.',
  'digestive-system-liver': 'The liver is a large gland in the upper right abdomen, inferior to the diaphragm and largely right of the stomach.',
  'digestive-system-right-lobe-of-liver': 'The right lobe is the larger anatomical lobe of the liver, lying mainly on the right side of the falciform ligament.',
  'digestive-system-left-lobe-of-liver': 'The left lobe is the anatomical lobe of the liver lying to the left of the falciform ligament.',
  'digestive-system-hepatic-artery': 'The hepatic artery is an arterial vessel entering the liver and accompanying portal-vein and bile-duct branches in portal triads.',
  'digestive-system-gallbladder': 'The gallbladder is a small sac on the inferior surface of the liver, connected to the bile ducts by the cystic duct.',
  'digestive-system-cystic-duct': 'The cystic duct connects the gallbladder to the common hepatic duct.',
  'digestive-system-common-hepatic-duct': 'The common hepatic duct drains bile from the liver and joins the cystic duct to form the common bile duct.',
  'digestive-system-common-bile-duct': 'The common bile duct is the passage formed by the common hepatic and cystic ducts that descends toward the duodenum.',
  'digestive-system-pancreas': 'The pancreas lies posterior to the stomach, with its head in the curve of the duodenum and its tail extending toward the spleen.',
  'digestive-system-head-of-pancreas': 'The head is the broad part of the pancreas nestled in the C-shaped curve of the duodenum.',
  'digestive-system-body-of-pancreas': 'The body is the central portion of the pancreas extending leftward from its head behind the stomach.',
  'digestive-system-tail-of-pancreas': 'The tail is the narrow left end of the pancreas extending toward the spleen.',
  'digestive-system-pancreatic-duct': 'The pancreatic duct runs through the pancreas and conveys its exocrine secretions toward the duodenum.',
  'digestive-system-hepatopancreatic-ampulla': 'The hepatopancreatic ampulla is the short expanded junction where the common bile and pancreatic ducts meet before the duodenum.',
  'digestive-system-major-duodenal-papilla': 'The major duodenal papilla is the mucosal projection into the descending duodenum where the hepatopancreatic ampulla opens.',
  'digestive-system-liver-lobule': 'A liver lobule is a microscopic hepatic unit organized around a central vein, with portal triads near its perimeter.',
  'digestive-system-central-vein': 'A central vein is the small vessel at the center of a liver lobule that receives blood from hepatic sinusoids.',
  'digestive-system-hepatic-sinusoid': 'A hepatic sinusoid is a vascular channel between plates of hepatocytes that carries blood toward a lobular central vein.',
  'digestive-system-portal-triad': 'A portal triad is a group at the periphery of a liver lobule containing branches of the hepatic portal vein and artery and a bile duct.',
  'digestive-system-pancreatic-acinus': 'A pancreatic acinus is a cluster of exocrine pancreatic cells arranged around a small duct lumen.',
  'digestive-system-pancreatic-islet': 'A pancreatic islet is a pale-staining cluster of endocrine cells scattered among the exocrine acini of the pancreas.',
  'digestive-system-mesentery': 'The mesentery is a double layer of peritoneum that connects the small intestine to the posterior abdominal wall and carries its vessels.',
  'digestive-system-greater-omentum': 'The greater omentum is a large peritoneal fold that hangs from the greater curvature of the stomach over the abdominal organs.',
  'digestive-system-lesser-omentum': 'The lesser omentum is a peritoneal fold connecting the liver with the lesser curvature of the stomach and proximal duodenum.',
  'digestive-system-mucosa': 'The mucosa is the innermost wall layer of the alimentary canal, facing the lumen and including its epithelium, lamina propria, and muscularis mucosae.',
  'digestive-system-lamina-propria': 'The lamina propria is the connective-tissue layer of the mucosa immediately beneath the alimentary-canal epithelium.',
  'digestive-system-muscularis-mucosae': 'The muscularis mucosae is a thin smooth-muscle layer at the outer edge of the alimentary-canal mucosa.',
  'digestive-system-submucosa': 'The submucosa is the connective-tissue wall layer just outside the mucosa and internal to the muscularis externa.',
  'digestive-system-muscularis-externa': 'The muscularis externa is the thick muscle layer outside the submucosa, generally organized into inner circular and outer longitudinal layers.',
  'digestive-system-serosa': 'The serosa is the outer visceral-peritoneal covering of an intraperitoneal portion of the alimentary canal.',
  'digestive-system-circular-muscle-layer': 'The circular muscle layer is the inner layer of the muscularis externa, arranged around the alimentary-canal lumen.',
  'digestive-system-longitudinal-muscle-layer': 'The longitudinal muscle layer is the outer layer of the muscularis externa, arranged along the length of the alimentary canal.',
  'digestive-system-gastric-pit': 'A gastric pit is an opening in the stomach mucosa that leads into underlying gastric glands.',
  'digestive-system-parietal-cell': 'A parietal cell is a glandular epithelial cell in the stomach mucosa that secretes hydrochloric acid.',
  'digestive-system-chief-cell': 'A chief cell is a glandular epithelial cell in the deeper portions of gastric glands that releases pepsinogen.',
  'digestive-system-hepatocyte': 'A hepatocyte is a liver epithelial cell arranged in plates beside hepatic sinusoids and bile canaliculi.',
  'digestive-system-hepatic-portal-vein': 'The hepatic portal vein carries venous blood from the digestive organs into the liver, where it branches toward the lobules.',

  // Urinary System — OpenStax Anatomy & Physiology, chapter 25.
  'urinary-system-kidney': 'A kidney is a retroperitoneal organ beside the vertebral column in the posterior upper abdomen.',
  'urinary-system-renal-capsule': 'The renal capsule is the fibrous covering directly surrounding the kidney.',
  'urinary-system-renal-cortex': 'The renal cortex is the outer region of the kidney, surrounding the medulla and containing renal corpuscles.',
  'urinary-system-renal-medulla': 'The renal medulla is the inner region of the kidney, organized into renal pyramids.',
  'urinary-system-renal-pyramid': 'A renal pyramid is a cone-shaped region of medulla whose tip points toward a minor calyx.',
  'urinary-system-renal-column': 'A renal column is an extension of cortical tissue between adjacent renal pyramids.',
  'urinary-system-renal-papilla': 'The renal papilla is the tip of a renal pyramid that projects into a minor calyx.',
  'urinary-system-minor-calyx': 'A minor calyx is a small cup that receives the renal papilla and funnels urine toward a major calyx.',
  'urinary-system-major-calyx': 'A major calyx is a collecting branch formed by the union of minor calyces and leading to the renal pelvis.',
  'urinary-system-renal-pelvis': 'The renal pelvis is the funnel-shaped collecting space inside the kidney that receives major calyces and continues as the ureter.',
  'urinary-system-renal-hilum': 'The renal hilum is the medial indentation of the kidney where vessels and the ureter pass into or out of the renal sinus.',
  'urinary-system-renal-sinus': 'The renal sinus is the internal space continuous with the hilum that contains the renal pelvis, calyces, vessels, and connective tissue.',
  'urinary-system-ureter': 'A ureter is a muscular tube that carries urine from the renal pelvis to the urinary bladder.',
  'urinary-system-urinary-bladder': 'The urinary bladder is a hollow muscular organ in the pelvic cavity that receives the ureters and empties into the urethra.',
  'urinary-system-trigone': 'The trigone is the smooth triangular region on the bladder floor between the two ureter openings and the urethral opening.',
  'urinary-system-detrusor-muscle': 'The detrusor is the smooth-muscle layer forming the wall of the urinary bladder.',
  'urinary-system-urethra': 'The urethra is the passage that carries urine from the urinary bladder to the exterior.',
  'urinary-system-internal-urethral-sphincter': 'The internal urethral sphincter is smooth muscle at the bladder outlet around the proximal urethra.',
  'urinary-system-external-urethral-sphincter': 'The external urethral sphincter is skeletal muscle around the urethra within the pelvic floor.',
  'urinary-system-nephron': 'A nephron is a kidney’s microscopic unit, consisting of a renal corpuscle and its associated tubule.',
  'urinary-system-renal-corpuscle': 'A renal corpuscle is the filtering portion of a nephron, formed by a glomerulus enclosed by a glomerular capsule.',
  'urinary-system-glomerulus': 'A glomerulus is a tuft of capillaries inside the glomerular capsule at the beginning of a nephron.',
  'urinary-system-glomerular-capsule': 'The glomerular capsule is the double-walled cup surrounding the glomerulus, with a capsular space facing its capillaries.',
  'urinary-system-proximal-convoluted-tubule': 'The proximal convoluted tubule is the first coiled segment of the nephron tubule, leaving the renal corpuscle in the cortex.',
  'urinary-system-nephron-loop': 'The nephron loop is the hairpin-shaped part of the tubule that descends into the medulla and returns toward the cortex.',
  'urinary-system-descending-limb': 'The descending limb is the nephron-loop segment that travels from the cortex toward the renal medulla.',
  'urinary-system-ascending-limb': 'The ascending limb is the nephron-loop segment that returns from the medulla toward the cortex.',
  'urinary-system-distal-convoluted-tubule': 'The distal convoluted tubule is the coiled nephron segment after the ascending limb and before the collecting duct.',
  'urinary-system-collecting-duct': 'A collecting duct is a straight kidney tubule that receives fluid from multiple nephrons and descends through the medulla.',
  'urinary-system-papillary-duct': 'A papillary duct is a terminal collecting passage that opens at a renal papilla into a minor calyx.',
  'urinary-system-juxtaglomerular-apparatus': 'The juxtaglomerular apparatus is the contact region where the distal tubule meets the arteriole at a renal corpuscle.',
  'urinary-system-macula-densa': 'The macula densa is a dense patch of distal-tubule cells next to the glomerulus at the juxtaglomerular apparatus.',
  'urinary-system-juxtaglomerular-cell': 'A juxtaglomerular cell is a modified smooth-muscle cell in the wall of the afferent arteriole beside the renal corpuscle.',
  'urinary-system-podocyte': 'A podocyte is a specialized cell of the glomerular capsule whose processes wrap around glomerular capillaries.',
  'urinary-system-filtration-membrane': 'The filtration membrane is the barrier between glomerular blood and capsular space, formed by capillary endothelium, basement membrane, and podocyte slit regions.',
  'urinary-system-peritubular-capillary': 'A peritubular capillary is a small blood vessel surrounding nephron tubules after branching from an efferent arteriole.',
  'urinary-system-vasa-recta': 'The vasa recta are straight capillaries extending into the medulla alongside nephron loops.',
  'urinary-system-afferent-arteriole': 'The afferent arteriole is the small artery that carries blood into a glomerular capillary tuft.',
  'urinary-system-efferent-arteriole': 'The efferent arteriole is the small artery that carries blood away from a glomerulus toward downstream capillaries.',
  'urinary-system-renal-artery': 'The renal artery branches from the abdominal aorta and enters the kidney through its hilum.',
  'urinary-system-renal-vein': 'The renal vein leaves the kidney through its hilum and drains into the inferior vena cava.',
  'urinary-system-segmental-artery': 'A segmental artery is a first-level branch of the renal artery supplying a segment of the kidney.',
  'urinary-system-interlobar-artery': 'An interlobar artery travels between renal pyramids through the renal columns.',
  'urinary-system-arcuate-artery': 'An arcuate artery arches along the base of a renal pyramid at the corticomedullary junction.',
  'urinary-system-cortical-radiate-artery': 'A cortical radiate artery branches from an arcuate artery and travels outward through the renal cortex.',
  'urinary-system-transitional-epithelium': 'Transitional epithelium, or urothelium, is the stretchable lining of the urinary collecting passages and bladder.',
  'urinary-system-principal-cell': 'A principal cell is an epithelial cell in the kidney’s collecting duct, interspersed with intercalated cells.',
  'urinary-system-intercalated-cell': 'An intercalated cell is a collecting-duct epithelial cell located among principal cells.',
  'urinary-system-cortical-radiate-vein': 'A cortical radiate vein drains blood from the renal cortex toward an arcuate vein.',
} as const;