const skeletalDefinitions: Record<string, string> = {
  'skull': 'The skull is the bony framework of the head, surrounding the brain and shaping the facial, orbital, nasal, and oral regions.',
  'frontal-bone': 'The frontal bone forms the forehead, the roof of the orbits, and part of the anterior cranial floor.',
  'parietal-bone': 'The paired parietal bones form much of the superior and lateral walls of the cranial vault.',
  'temporal-bone': 'Each temporal bone forms part of the lateral skull and cranial base around the ear region.',
  'occipital-bone': 'The occipital bone forms the posterior skull and cranial base around the foramen magnum.',
  'sphenoid-bone': 'The sphenoid is a central cranial-base bone that articulates with several other cranial bones and contributes to the orbits.',
  'ethmoid-bone': 'The ethmoid lies between the orbits and contributes to the nasal cavity, medial orbital walls, and anterior cranial floor.',
  'maxilla': 'Each maxilla forms part of the upper jaw, anterior hard palate, and margins of the nasal cavity and orbit.',
  'mandible': 'The mandible is the lower jaw; its condyles articulate with the temporal bones at the temporomandibular joints.',
  'zygomatic-bone': 'The zygomatic bone forms the prominence of the cheek and part of the lateral wall and floor of the orbit.',
  'nasal-bone': 'The paired nasal bones form the bony bridge at the superior part of the nose.',
  'lacrimal-bone': 'The small lacrimal bone lies in the medial wall of each orbit beside the nasal cavity.',
  'palatine-bone': 'Each palatine bone forms the posterior part of the hard palate and contributes to the nasal cavity and orbit.',
  'vomer': 'The vomer is a midline bone that forms the inferior portion of the nasal septum.',
  'inferior-nasal-concha': 'The inferior nasal concha is a separate curved bone projecting from the lateral wall of the nasal cavity.',
  'coronal-suture': 'The coronal suture joins the frontal bone to the parietal bones across the top of the skull.',
  'sagittal-suture': 'The sagittal suture joins the right and left parietal bones along the midline of the cranial vault.',
  'lambdoid-suture': 'The lambdoid suture joins the parietal bones to the occipital bone at the back of the skull.',
  'foramen-magnum': 'The foramen magnum is the large opening in the inferior occipital bone through which the brainstem continues as the spinal cord.',
  'optic-canal': 'The optic canal is an opening in the sphenoid bone that connects the cranial cavity with the orbit.',
  'jugular-foramen': 'The jugular foramen is an opening between the temporal and occipital bones at the cranial base.',
  'hyoid': 'The hyoid is a U-shaped bone in the anterior neck, suspended by soft tissues rather than articulating directly with another bone.',
  'atlas-c1': 'The atlas is the first cervical vertebra; its superior articular facets receive the occipital condyles, and it has no typical vertebral body.',
  'axis-c2': 'The axis is the second cervical vertebra, identified by its dens projecting superiorly into the atlas.',
  'cervical-vertebrae': 'The seven cervical vertebrae form the vertebral column in the neck, and their transverse foramina are a regional landmark.',
  'thoracic-vertebrae': 'The twelve thoracic vertebrae occupy the chest region and articulate with the ribs.',
  'lumbar-vertebrae': 'The five lumbar vertebrae form the lower-back region and have large bodies that support substantial trunk loads.',
  'sacrum': 'The sacrum is a fused triangular bone at the base of the vertebral column that articulates with both hip bones.',
  'coccyx': 'The coccyx is the small terminal part of the vertebral column, inferior to the sacrum.',
  'vertebral-foramen': 'The vertebral foramen is the opening within a vertebra; successive foramina form the vertebral canal.',
  'spinous-process': 'The spinous process projects posteriorly from a vertebra along the midline of the back.',
  'transverse-process': 'A transverse process projects laterally from each side of a vertebra.',
  'intervertebral-disc': 'An intervertebral disc is a fibrocartilaginous pad between adjacent vertebral bodies.',
  'sternum': 'The sternum is the midline bone of the anterior thoracic cage to which the upper ribs attach.',
  'manubrium': 'The manubrium is the superior part of the sternum, articulating with the clavicles and first ribs.',
  'body-of-sternum': 'The body is the long central part of the sternum, joined superiorly to the manubrium and inferiorly to the xiphoid process.',
  'xiphoid-process': 'The xiphoid process is the small inferior projection at the end of the sternum.',
  'true-ribs': 'Ribs 1–7 are true ribs because each attaches directly to the sternum through its own costal cartilage.',
  'false-ribs': 'Ribs 8–12 are false ribs because they do not attach directly to the sternum; ribs 11 and 12 are also floating ribs.',
  'floating-ribs': 'Ribs 11 and 12 are floating ribs because their anterior ends have no attachment to the sternum.',
  'clavicle': 'The clavicle is an anterior strut of the pectoral girdle, linking the sternum medially with the scapula at the acromion.',
  'scapula': 'The scapula is a flat, triangular bone on the posterior thorax whose glenoid cavity receives the head of the humerus.',
  'humerus': 'The humerus is the bone of the upper arm, articulating proximally with the scapula and distally with the radius and ulna.',
  'radius': 'The radius is the lateral forearm bone in anatomical position, on the thumb side, and broadens toward the wrist.',
  'ulna': 'The ulna is the medial forearm bone in anatomical position, on the little-finger side, and forms the prominent elbow hinge with the humerus.',
  'carpals': 'The eight carpal bones form the wrist between the forearm and the metacarpals.',
  'metacarpals': 'The five metacarpals form the bony framework of the palm between the carpals and finger phalanges.',
  'phalanges-hand': 'The phalanges of the hand are the bones of the fingers and thumb, distal to the metacarpals.',
  'pelvis': 'The pelvic girdle is formed by the hip bones, which join the sacrum and connect the lower limbs to the axial skeleton.',
  'ilium': 'The ilium is the broad, superior part of each hip bone and forms the upper margin of the pelvic girdle.',
  'ischium': 'The ischium is the posteroinferior part of each hip bone and includes the tuberosity that bears weight when sitting.',
  'pubis': 'The pubis is the anteroinferior part of each hip bone and meets its partner at the midline pubic symphysis.',
  'femur': 'The femur is the thigh bone; its head fits the acetabulum proximally and its distal condyles meet the tibia.',
  'patella': 'The patella is a sesamoid bone embedded in the quadriceps tendon at the anterior knee.',
  'tibia': 'The tibia is the medial, major weight-bearing bone of the leg, extending from the knee to the medial ankle.',
  'fibula': 'The fibula is the slender lateral bone of the leg, alongside the tibia, and forms the lateral ankle prominence.',
  'tarsals': 'The seven tarsal bones form the proximal skeleton of the foot, including the talus and calcaneus.',
  'talus': 'The talus is the superior tarsal bone that receives the tibia and fibula at the ankle and links the leg to the foot.',
  'calcaneus': 'The calcaneus is the heel bone, positioned inferior and posterior to the talus.',
  'metatarsals': 'The five metatarsals form the middle of the foot between the tarsals and toe phalanges.',
  'phalanges-foot': 'The phalanges of the foot are the toe bones; the hallux is the great toe and has two phalanges, while the other toes have three.',
  'acetabulum': 'The acetabulum is the deep socket formed by the ilium, ischium, and pubis that receives the head of the femur.',
  'glenoid-cavity': 'The glenoid cavity is the shallow lateral socket of the scapula that receives the head of the humerus.',
  'sacroiliac-joint': 'The sacroiliac joint is the articulation between the sacrum and the ilium of each hip bone.',
  'external-acoustic-meatus': 'The external acoustic meatus is the opening in the temporal bone that leads inward from the outer ear.',
  'internal-acoustic-meatus': 'The internal acoustic meatus is a canal in the petrous temporal bone on the inner surface of the cranial base.',
  'mastoid-process': 'The mastoid process is the palpable projection of the temporal bone posterior to the external acoustic meatus.',
  'styloid-process': 'The styloid process is a slender projection of the temporal bone inferior to the ear region.',
  'mandibular-condyle': 'The mandibular condyle is the posterior superior projection of the mandible that articulates with the temporal bone.',
  'mandibular-coronoid': 'The coronoid process of the mandible is its anterior superior projection, anterior to the mandibular condyle.',
  'mental-foramen': 'The mental foramen is an opening on the anterior body of the mandible, below the premolar region.',
  'supraorbital-foramen': 'The supraorbital foramen or notch is an opening in the frontal bone along the superior margin of the orbit.',
  'zygomatic-arch': 'The zygomatic arch is the lateral cheek arch formed by the temporal process of the zygomatic bone and the zygomatic process of the temporal bone.',
  'sella-turcica': 'The sella turcica is a saddle-shaped depression in the sphenoid bone that contains the hypophyseal fossa.',
  'occipital-condyles': 'The occipital condyles are paired projections beside the foramen magnum that articulate with the atlas.',
  'dens': 'The dens is the toothlike projection of the axis that extends into the atlas.',
  'vertebral-body': 'The vertebral body is the large anterior portion of a vertebra, positioned to bear weight.',
  'superior-articular-facet': 'A superior articular facet is the upward-facing joint surface on a vertebra that meets an inferior facet of the vertebra above.',
  'inferior-articular-facet': 'An inferior articular facet is the downward-facing joint surface on a vertebra that meets a superior facet of the vertebra below.',
  'transverse-foramen': 'A transverse foramen is an opening in the transverse process of a cervical vertebra.',
  'rib-head': 'The head of a rib is its posterior end, where it articulates with the bodies of thoracic vertebrae.',
  'rib-tubercle': 'The tubercle of a rib is a projection near its posterior end that articulates with a transverse process of a thoracic vertebra.',
  'costal-groove': 'The costal groove is a channel along the inferior internal border of a rib that shelters an intercostal neurovascular bundle.',
  'scapular-spine': 'The spine of the scapula is the prominent ridge on its posterior surface that continues laterally into the acromion.',
  'acromion': 'The acromion is the lateral extension of the scapular spine that articulates with the clavicle.',
  'coracoid-process': 'The coracoid process is an anterior projection of the scapula near the glenoid cavity.',
  'humeral-head': 'The head of the humerus is its rounded proximal end, which fits into the glenoid cavity of the scapula.',
  'greater-tubercle': 'The greater tubercle is the large lateral projection near the proximal end of the humerus.',
  'deltoid-tuberosity': 'The deltoid tuberosity is a roughened area on the lateral midshaft of the humerus.',
  'medial-epicondyle': 'The medial epicondyle is a projection on the medial side of the distal humerus.',
  'lateral-epicondyle': 'The lateral epicondyle is a projection on the lateral side of the distal humerus.',
  'capitulum': 'The capitulum is the rounded lateral articular surface at the distal end of the humerus that meets the head of the radius.',
  'trochlea': 'The trochlea is the spool-shaped medial articular surface at the distal end of the humerus that meets the ulna.',
  'radial-head': 'The head of the radius is its disc-shaped proximal end, articulating with the humerus and ulna at the elbow.',
  'radial-styloid': 'The radial styloid process is the pointed projection at the lateral, thumb-side end of the distal radius.',
  'olecranon': 'The olecranon is the large posterior projection at the proximal end of the ulna that forms the point of the elbow.',
  'trochlear-notch': 'The trochlear notch is the C-shaped proximal articular surface of the ulna that receives the humeral trochlea.',
  'iliac-crest': 'The iliac crest is the superior curved rim of the ilium and the palpable upper border of the hip bone.',
  'asis': 'The anterior superior iliac spine is the anterior projection at the superior end of the iliac crest.',
  'ischial-tuberosity': 'The ischial tuberosity is the large roughened projection on the posteroinferior ischium that bears weight when sitting.',
  'obturator-foramen': 'The obturator foramen is the large opening enclosed by the pubis and ischium of each hip bone.',
  'femoral-head': 'The head of the femur is its rounded proximal articular surface that fits into the acetabulum.',
  'femoral-neck': 'The femoral neck is the narrowed segment connecting the head of the femur to its shaft.',
  'greater-trochanter': 'The greater trochanter is the large lateral projection near the proximal end of the femur.',
  'femoral-condyles': 'The medial and lateral femoral condyles are rounded articular surfaces at the distal end of the femur that meet the tibia.',
  'tibial-tuberosity': 'The tibial tuberosity is the rough anterior projection on the proximal tibia, just below the knee.',
  'medial-malleolus': 'The medial malleolus is the distal projection of the tibia that forms the inner prominence of the ankle.',
  'lateral-malleolus': 'The lateral malleolus is the distal projection of the fibula that forms the outer prominence of the ankle.',
  'anterior-cranial-fossa': 'The anterior cranial fossa is the shallow anterior part of the cranial floor that supports the frontal lobes.',
  'middle-cranial-fossa': 'The middle cranial fossa is the central depression of the cranial floor, formed mainly by the sphenoid and temporal bones.',
  'posterior-cranial-fossa': 'The posterior cranial fossa is the deep posterior part of the cranial floor that contains the cerebellum and brainstem.',
  'cribriform-plate': 'The cribriform plate is the perforated horizontal part of the ethmoid that forms part of the roof of the nasal cavity.',
  'crista-galli': 'The crista galli is a midline projection of the ethmoid rising between the halves of the cribriform plate.',
  'superior-orbital-fissure': 'The superior orbital fissure is a gap in the sphenoid between its wings that connects the cranial cavity with the orbit.',
  'inferior-orbital-fissure': 'The inferior orbital fissure is a gap in the posterior floor and lateral wall of the orbit.',
  'foramen-ovale': 'The foramen ovale is an opening in the sphenoid bone on the middle cranial floor.',
  'foramen-rotundum': 'The foramen rotundum is an opening through the sphenoid bone in the middle cranial fossa.',
  'foramen-spinosum': 'The foramen spinosum is a small opening in the sphenoid bone, posterolateral to the foramen ovale.',
  'carotid-canal': 'The carotid canal is a passage through the petrous part of the temporal bone at the cranial base.',
  'hypoglossal-canal': 'The hypoglossal canal is an opening in the occipital bone near an occipital condyle.',
  'stylomastoid-foramen': 'The stylomastoid foramen is an opening in the temporal bone between the styloid and mastoid processes.',
  'incisive-foramen': 'The incisive foramen is an opening in the anterior hard palate, just behind the upper incisors.',
  'greater-palatin-foramen': 'The greater palatine foramen is an opening near the posterior lateral hard palate.',
  'uncinate-process': 'The uncinate process of the ethmoid is a thin, hook-shaped projection in the lateral wall of the nasal cavity.',
  'pterygoid-process': 'The pterygoid process projects inferiorly from the sphenoid and provides medial and lateral plates beside the nasal cavity.',
  'clivus': 'The clivus is the sloping midline part of the cranial base formed by the sphenoid and occipital bones, anterior to the foramen magnum.',
  'internal-occipital-crest': 'The internal occipital crest is a midline ridge on the inner occipital bone extending upward from the foramen magnum.',
  'cervical-lordosis': 'Cervical lordosis is the normal inward curve of the vertebral column in the neck.',
  'thoracic-kyphosis': 'Thoracic kyphosis is the normal outward curve of the vertebral column through the chest.',
  'lumbar-lordosis': 'Lumbar lordosis is the normal inward curve of the vertebral column in the lower back.',
  'uncinate-process-vertebra': 'The uncinate process of a cervical vertebra is a raised hook along the lateral edge of its superior end plate.',
  'superior-costal-facet': 'A superior costal facet on a thoracic vertebra is an articular surface for the head of a rib.',
  'inferior-costal-facet': 'An inferior costal facet on a thoracic vertebra is an articular surface for the head of a rib.',
  'mammillary-process': 'The mammillary process is a small posterior projection of a lumbar vertebra near its superior articular process.',
  'accessory-process': 'The accessory process is a small projection on a lumbar vertebra near the base of its transverse process.',
  'scaphoid': 'The scaphoid is a carpal bone in the proximal row on the thumb side of the wrist.',
  'lunate': 'The lunate is a centrally placed carpal bone in the proximal row, articulating with the radius.',
  'triquetrum': 'The triquetrum is a carpal bone in the proximal row on the little-finger side of the wrist.',
  'pisiform': 'The pisiform is a small sesamoid carpal bone on the palmar side of the triquetrum.',
  'trapezium': 'The trapezium is the distal-row carpal bone at the base of the thumb, articulating with the first metacarpal.',
  'trapezoid': 'The trapezoid is a distal-row carpal bone aligned with the base of the index-finger metacarpal.',
  'capitate': 'The capitate is the largest carpal bone, centrally located in the distal row and aligned with the third metacarpal.',
  'hamate': 'The hamate is a distal-row carpal bone on the little-finger side, distinguished by its palmar hook.',
  'hook-of-hamate': 'The hook of hamate is the palmar projection of the hamate on the ulnar side of the wrist.',
  'navicular': 'The navicular is a medial tarsal bone anterior to the talus and posterior to the cuneiforms.',
  'medial-cuneiform': 'The medial cuneiform is the medial bone of the distal tarsal row, between the navicular and first metatarsal.',
  'intermediate-cuneiform': 'The intermediate cuneiform is the central cuneiform, between the medial and lateral cuneiforms and behind the second metatarsal.',
  'lateral-cuneiform': 'The lateral cuneiform lies lateral to the intermediate cuneiform and proximal to the third metatarsal.',
  'cuboid': 'The cuboid is the lateral tarsal bone anterior to the calcaneus and proximal to the lateral metatarsals.',
  'ankle-mortise': 'The ankle mortise is the socket formed by the distal tibia and fibula around the talus.',
  'tibial-plateau': 'The tibial plateau is the superior surface of the proximal tibia, where its medial and lateral condyles meet the femur.',
  'intercondylar-eminence': 'The intercondylar eminence is the central ridge between the medial and lateral condyles of the tibia.',
  'radial-tuberosity': 'The radial tuberosity is a roughened medial projection on the proximal radius, below its head.',
  'ulnar-styloid': 'The ulnar styloid process is the pointed projection at the distal end of the ulna on the little-finger side of the wrist.',
  'femoral-linea-aspera': 'The linea aspera is a prominent longitudinal ridge along the posterior shaft of the femur.',
};

export default skeletalDefinitions;